docs/tempo/website/_index.md
docs/tempo/website/architecture/_index.md
docs/tempo/website/architecture/architecture.md
docs/tempo/website/architecture/consistent-hash-ring.md
docs/tempo/website/community/_index.md
docs/tempo/website/configuration/_index.md
docs/tempo/website/getting-started/_index.md
docs/tempo/website/guides/_index.md
docs/tempo/website/guides/loki-derived-fields.md

Make docs public, publish to https://grafana.com/docs/tempo/latest 🎉 🎉 
**Checklist**

Publish documentation to grafana.com

---

README.md

Small typo fix and updated to use the OSS page language.

Fixed typo, Used OSS page language

---

CHANGELOG.md
CONTRIBUTING.md
go.mod
go.sum
vendor/modules.txt

Follow up from #272. 
- Update vendor dependencies.
- Update instructions with new command to run (`make vendor-check`) before checking in files.
Fixes #NA
**Checklist**

Update vendor dependencies

---

README.md

See: https://github.com/cortexproject/cortex/#further-reading
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
**Checklist**

Add a further reading section

---

operations/tempo-mixin/tempo-operational.json

- Adds cluster/namespace selectors to queries in operational dashboard that were missing them

Added cluster/namespace selectors

---

docs/tempo/website/architecture/_index.md

**What this PR does**: Fixes a typo in the website
~Fixes #<issue number>~
**Checklist**

Fix typo in documentation

---

example/helm/readme.md
example/tk/readme.md

**What this PR does**: fixes markdown links from the `(title)[link]` format into `[link](title)` so as to be rendered correctly
cosmetic changes, thus, nothing to be added to the checklist
**Checklist**

fixed links in markdown

---

example/docker-compose/readme.md
example/helm/readme.md
example/tk/readme.md

Signed-off-by: Xiang Dai <long0dai@foxmail.com>
Fix typos.
**Checklist**

Docs: fix typos

---

operations/tempo-mixin/README.md
operations/tempo-mixin/alerts.jsonnet
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/mixin.libsonnet
operations/tempo-mixin/out/alerts.yaml
operations/tempo-mixin/out/rules.yaml
operations/tempo-mixin/rules.jsonnet
operations/tempo-mixin/rules.libsonnet
operations/tempo-mixin/runbook.md

Adds basic alerts, rules and runbook entries for Tempo
Fixes #240 
**Checklist**

Added runbook, basic alerts and rules

---

example/helm/readme.md
example/tk/readme.md
example/tk/tempo-microservices/spec.json
example/tk/tempo-single-binary/spec.json

- Adds new k3d commands (for >v3.0.0).
- Adds requirements to run the Helm examples locally.
- Changes apiServer in Tanka from `localhost` to `0.0.0.0`.
**Checklist**

Improve k3d examples

---

Makefile
cmd/tempo-query/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile

add support for multi arch build
split from https://github.com/grafana/tempo/pull/305
no fixes

Build: add support for multi arch build

---

CHANGELOG.md
RELEASES.MD

- Adds 0.3.0 to the changelog
- Documents release procedure

Added release procedure and cut 0.3.0 in the Changelog

---

.drone.yml

Install Git on the img before building.
Fixes #222
**Checklist**

[drone] Install Git on the img before building

---

CODEOWNERS

The docs PR #366 prevents @annanay25 and myself from approving docs PRs.  Readding us.

Add Annanay and Myself as docs codeowners

---

CONTRIBUTING.md
docs/README.md

Adds docs section to contributing guidelines, explains CI sync to grafana website & how to generate a preview locally.
cc @achatterjee-grafana 

Add docs section to contributing guidelines

---

CHANGELOG.md
RELEASES.MD

Cleanup some release instructions and cut 0.4.0 in CHANGELOG.
**Checklist**

Cleanup from 0.4.0 release

---

ADOPTERS.md

Signed-off-by: Richard Hartmann <richih@richih.org>

docs: Create ADOPTERS.md

---

CHANGELOG.md
docs/tempo/website/configuration/s3.md
tempodb/backend/s3/config.go
tempodb/backend/s3/s3.go

Removes the code that creates the S3 bucket.
Fixes #401
**Checklist**

Remove s3 bucket creation

---

CHANGELOG.md
tempodb/compaction_block_selector.go
tempodb/compaction_block_selector_test.go

Update changelog for https://github.com/grafana/tempo/pull/411

Compactor exclusion window

---

docs/tempo/website/Troubleshooting/_index.md
docs/tempo/website/_index.md
docs/tempo/website/community/_index.md
docs/tempo/website/troubleshooting/_index.md

Adds a troubleshooting section to the docs. Consists of a checklist of things to verify if facing issues while setting up Tempo.
Fixes #378 
**Checklist**

Add troubleshooting section to docs

---

tempodb/backend/s3/s3.go

Simple cleanup of s3 backend creation code.  Previously the logic was a little difficult to follow.  This is a simple rewrite in idiomatic go.

Cleanup of s3 backend New logic

---

operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/dashboards.libsonnet
operations/tempo-mixin/out/tempo-operational.json
operations/tempo-mixin/out/tempo-reads.json
operations/tempo-mixin/out/tempo-resources.json
operations/tempo-mixin/tempo-operational.json

Adds Query Frontend related dashboards
Fixes #na
**Checklist**

Add Query Frontend to dashboards

---

.gitignore
cmd/tempo/app/modules.go
modules/frontend/querysharding.go
operations/jsonnet/microservices/configmap.libsonnet
operations/jsonnet/microservices/frontend.libsonnet

Bunch of small things
-  Fix instrumentation & context propagation at the querier by using the right handler. `t.server.HTTP` is not wrapped by the middleware, but `t.server.HTTPServer.Handler` is. Thanks to @pstibrany for the pointers :)
- Fix status code returned by Query Frontend, by passing the downstream error through.
- Add a configmap for query frontend in jsonnet scripts
**Checklist**

Fix instrumentation at Querier

---

.goreleaser.yml
RELEASES.MD

Updates release procedure to skip the goreleaser changelog generation and use CHANGELOG instead.
`Add the github handles of contributors at the end of each entry` is a lot of manual work though 😕 
**Checklist**

Update release process instructions

---

Makefile

No longer default to experimental features, remove `--platform` flag from Makefile.
Fixes #NA
**Checklist**

Remove experimental docker flag from Makefile

---

operations/helm/tempo-microservices/templates/configmap-tempo-querier.yaml
operations/helm/tempo-microservices/templates/deployment-querier.yaml
operations/helm/tempo-microservices/templates/deployment-query-frontend.yaml
operations/helm/tempo-microservices/templates/service-querier.yaml
operations/helm/tempo-microservices/templates/service-query-frontend.yaml
operations/helm/tempo-microservices/values.yaml

Signed-off-by: swartz-k <9215868@gmail.com>
Adds Helm charts for the Query Frontend. Equivalent of #423
**Checklist**

Add helm charts for Query Frontend

---

CHANGELOG.md

Update changelog for v0.5.0

---

operations/jsonnet/microservices/vulture.libsonnet

While we drop the loki dependency from Vulture, parameterising the loki query would be nice to easy internal changes.
Fixes #na
**Checklist**

Parameterize vulture loki query

---

ADOPTERS.md

Signed-off-by: swartz-k <9215868@gmail.com>
Tempo is a great project and save a lot of our time.
We have made Tempo works on our platform. 
**Checklist**

Add Megvii to ADPOTERS

---

Makefile
modules/frontend/frontend.go
modules/frontend/querysharding.go
tempodb/encoding/v0/backend_block.go

- Default query parallelism at frontend to query shards …
- Add logfmt logging at query frontend for all requests …
- Re-add Backendblock.Find span removed during refactoring …
- Exclude vendor-fix from fmt command …
Fixes #na
**Checklist**

Minor updates to Query path

---

tempodb/backend/s3/s3.go

Delete S3 Bucket Exists logic to support more storage like AlibabaClous OSS
**Checklist**

Feat: s3 del bucket exists logic

---

operations/jsonnet/microservices/compactor.libsonnet

Adds a compactor service.  This would useful if one were to want to serve the `/compactor/ring` page for instance.

Added compactor service

---

modules/compactor/compactor.go
modules/frontend/frontend.go
modules/frontend/querysharding.go
modules/frontend/querysharding_test.go
modules/ingester/instance.go
modules/querier/http.go
pkg/util/http.go
pkg/util/trace.go
pkg/util/trace_test.go
tempodb/backend/gcs/gcs.go
tempodb/encoding/v0/backend_block.go

- This PR is a bugfix for #457, where we were incorrectly passing a json marshalled byte slice of traces to `combineTrace` which only accepts protobuf marshalled format.
- Changed signature of `combineTrace` to also return error, as it helps with bubbling it up as required
- Tests added accordingly
**Checklist**

Correct the translation of protobuf to json at query frontend

---

GOVERNANCE.md
MAINTAINERS.md

Vote: Make Marty Disibio a maintainer?

---

operations/helm/tempo-microservices/templates/service-query-frontend-discovery.yaml
operations/tempo-mixin/runbook.md

Some ops follow up for the Query frontend. Updating runbook and helm chart.
Helm chart update thanks to @betorvs -
https://grafana.slack.com/archives/C01D981PEE5/p1612187041042000?thread_ts=1612170214.037300&cid=C01D981PEE5
Fixes #na!
**Checklist**

[ops] - Update runbook, fix helm chart for query frontend

---

.goreleaser.yml

Fixes #335
Not sure how to test this. Push a tag onto my repo?
**Checklist**

Build tempo-query as part of goreleaser release process

---

docs/tempo/website/guides/_index.md
docs/tempo/website/guides/multitenancy.md
example/docker-compose/docker-compose.multitenant.yaml
example/docker-compose/docker-compose.otel.yaml
example/docker-compose/etc/otel-collector.yaml
example/docker-compose/example-data/datasources/datasource.yml

- Adds an example with the otel collector and multitenancy

OTEL Collector/Multitenant Example

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Make Dgzlopes Maintainer

---

operations/tempo-mixin/dashboards.libsonnet
operations/tempo-mixin/out/tempo-reads.json

Fixes the querier panel in mixins.
**Checklist**

Fix Querier panel in mixins

---

CHANGELOG.md

Updates the changelog for a rushed bugfix last week.
**Checklist**

changelog for wal replay

---

.goreleaser.yml

Fixes our goreleaser release process by adding an id to each build.
Fixes #na!
**Checklist**

Add unique id to each goreleaser build

---

docs/tempo/website/guides/_index.md
docs/tempo/website/guides/instrumentation.md
docs/tempo/website/guides/pushing-spans-with-http.md

- Adds links to recent blog posts about instrumenting applications
- Improve image alt text
@annanay25 image links on this page are broken, but reviewing the code it looks just like all of our other image links.  any ideas?
https://grafana.com/docs/tempo/latest/guides/pushing-spans-with-http/

Website: Added links to blog posts

---

docs/tempo/website/configuration/_index.md
docs/tempo/website/configuration/ingestion-limit.md
docs/tempo/website/configuration/override.md
docs/tempo/website/troubleshooting/_index.md

- Added new topic: "Override trace limit". 
- Updated topic "Troubleshooting" with a new section "Problem 4. Distributor is not accepting traces".
Issue: https://github.com/grafana/tempo/issues/395

Updated doc for issue 395

---

CHANGELOG.md
docs/tempo/website/monitoring/_index.md
operations/tempo-mixin/README.md

Cleanup Changelog from v0.6.0 release, add section for mixin in docs
Fixes #na!
**Checklist**

Cleanup Changelog from v0.6.0 release, add section for mixin in docs

---

modules/distributor/distributor.go

Adding internal_error for discarding spans.  Previously I had rejected this idea, but I have changed my mind.  With @mdisibio's upcoming work we will be able to 100% account for all dropped spans in Tempo and we should metric this for our tenants.

Add internal_error as reason for discarded spans

---

README.md
docs/tempo/website/guides/instrumentation.md

Adds resource links
Fixes #540 
**Checklist**

Added additional resource links

---

example/helm/microservices-extras.yaml
example/helm/readme.md

0.8.1 broke our helm example.  This PR updates instructions accordingly.
**Checklist**

Updated insructions to match the Tempo Helm Chart 0.8.1

---

tempodb/tempodb.go
tempodb/tempodb_test.go

Simplifies and tests the logic for whether or not to include a block in a search.

Cleaned up includeBlock logic

---

docs/tempo/website/guides/instrumentation.md

Add a new example!
**Checklist**

Add Python instrumentation example

---

example/readme.md

Add the TNS demo to the list of examples and cover the notable features including LogqlV2 and logfmt.
Fixes #234 #235
**Checklist**

Add TNS demo to list of examples

---

integration/e2e/e2e_test.go

otlp -> Jaeger gRPC
**Checklist**

Fix comments on e2e tests

---

cmd/tempo-vulture/main.go
operations/jsonnet/microservices/config.libsonnet
operations/jsonnet/microservices/vulture.libsonnet

- Adds org id to push
- Parameterizes vulture in jsonnet

Vulture Fixes

---

operations/jsonnet/microservices/frontend.libsonnet

Correct the query frontend port in microservices deployment

Fix query frontend service port

---

operations/tempo-mixin/runbook.md

This PR adds some steps and notes for how to address TempoCompactionsFailing.
n/a
**Checklist**

Add runbook for TempoCompactionsFailing

---

docs/tempo/website/configuration/querying.md

Accidentally left a "test" link in the docs. Removed.

Remove test link

---

cmd/tempo-vulture/main.go

Remove port requirement/check from Vulture

---

README.md

Adds a link to the community forum.
**Checklist**

Add community forum

---

tempodb/wal/block.go
tempodb/wal/block_test.go
tempodb/wal/replay_block.go

Fixes the method that generates wal names to work for v0 wals.

Fix v0 wal names

---

docs/tempo/website/troubleshooting/max-trace-limit-reached.md

Fixes a reference on the troubleshooting docs. Tried this locally with `make docs`.
**Checklist**

[docs] Fix Ingestion limits reference

---

docs/tempo/website/architecture/consistent-hash-ring.md

Add ring endpoints to docs

---

CONTRIBUTING.md
LICENSE
LICENSING.md
README.md
cmd/tempo-query/LICENSE_APACHE2
operations/LICENSE_APACHE2
pkg/tempopb/LICENSE_APACHE2

For a rationale as to why this was done, please see
* https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/
* https://grafana.com/blog/2021/04/20/qa-with-our-ceo-on-relicensing/
Signed-off-by: Richard Hartmann <richih@richih.org>
Signed-off-by: Joe Elliott <number101010@gmail.com>

Re-license to AGPLv3

---

.github/workflows/website.yml

Fixes website publish by reverting main => master.

Fix website publish

---

CHANGELOG.md

Resets the changelog for 0.7.0

0.7.0 release

---

CHANGELOG.md

Adds the missing changelog entry for #668

Wal Replay Changelog

---

RELEASES.MD
docs/tempo/website/configuration/_index.md
docs/tempo/website/configuration/azure.md
docs/tempo/website/configuration/compression.md
docs/tempo/website/configuration/manifest.md

I went through the docs and cleaned up some broken links / outdated sections. I'll start a code review to discuss the parts I'm less sure about.
**Checklist**
Not relevant, only the docs changed.

Docs cleanup

---

cmd/tempo-vulture/main.go

This PR improves logging of tempo-vulture with the intention to investigate sporadic 404s.
Changes:
- replace glog by zap
- add additional logging statements to distinguish different error paths
Example log after these changes:
```
2021-05-03T16:47:41.490+0200    INFO    tempo-vulture/main.go:84        sending trace   {"write_trace_id": "0f76bf113f57aa7b4acb6bfd29f97c20"}
2021-05-03T16:47:56.485+0200    INFO    tempo-vulture/main.go:84        sending trace   {"write_trace_id": "06739b5d43f529657602bebb64ab056a"}
2021-05-03T16:47:56.485+0200    INFO    tempo-vulture/main.go:227       querying Tempo  {"query_trace_id": "7602bebb64ab056a06739b5d43f52965", "tempo_query_url": "http://localhost:3100/api/traces/7602bebb64ab056a06739b5d43f52965"} …
```

Vulture: replace glog by zap, improve logging

---

cmd/tempo-vulture/main.go

Query requests from vulture can fail for multiple reasons, not only because Tempo returned a 404.  This PR introduces a new label `requestfailed` which will count the amount of errors that are not 404.
Additionally, I believe there was a mistake in how `error_total` is counted (`metricErrorTotal` in Go): if `queryTempoAndAnalyze` returns an error, this increments `error_total` but we should also still increase `trace_total`.
We currently do not do this and because of this `trace_total` will drop a bit when requests fail. This is misleading since we did attempt to query this trace.
Other dashboards calculate a percentage of "not found traces" using `trace_error_total / trace_total`:
```promql
sum(rate(tempo_vulture_trace_error_total{cluster="$cluster", …
```

Vulture: add metric label for requests that failed

---

cmd/tempo-vulture/main.go

Also log the seed used by the random generator when writing and reading traces. This is useful for debugging when traces were not found by vulture.

Vulture: log seed used to generate trace

---

integration/microservices/docker-compose.yaml
modules/ingester/ingester_test.go
modules/ingester/instance.go
pkg/tempopb/prealloc.go

- Fixes the prealloc issue in #696 instead of removing pool usage altogether?
**Checklist**

Prealloc fix

---

docs/tempo/website/configuration/manifest.md
modules/distributor/config.go
modules/distributor/distributor.go

Added the ability to turn on trace id logging in the distributors to help with debugging.
**Checklist**

Added trace id logging

---

modules/frontend/deduper.go
modules/frontend/deduper_test.go

Fix dedupe logic in query frontend to support zipkin

---

cmd/tempo/app/app.go

Add NotifyClientShutdown to methods with no auth

---

CHANGELOG.md

Corrects rollout instructions for the marshal reduction PR.

Fixed deploy instructions

---

.github/workflows/website.yml
docs/Makefile
docs/tempo/website/architecture/_index.md

https://github.com/grafana/tempo/pull/705 introduced a relref error in the website build.
This PR fixes the relref error, and also adds a test to the github action to prevent the website sync from occurring if there are any errors. It also adds a Makefile to preview the docs locally.

fix relref, add local docs preview/test, add website sync test

---

docs/tempo/website/architecture/architecture.md
docs/tempo/website/configuration/gcs.md
docs/tempo/website/configuration/s3.md
docs/tempo/website/operations/_index.md

Signed-off-by: Martin Disibio <mdisibio@gmail.com>
Fix the broken links on the operations main page, and s3/gcs config pages.
n/a
**Checklist**

Fix broken links after docs revamp

---

docs/tempo/website/operations/consistent_hash_ring.md

Improved consistent hash ring docs.

Improved Ring Docs

---

docs/tempo/website/configuration/gcs.md

Added required permission for GCS backend

---

example/docker-compose/readme.md
example/helm/readme.md
example/tk/readme.md
example/tk/tempo-microservices/main.jsonnet

Update / clean up the examples: remove stray mentions of tempo-query and verify they work.
Rendered preview: https://github.com/kvrhdn/tempo/tree/707-update-docs/example
Closes #707
**Checklist**

Clean up examples

---

CHANGELOG.md

Signed-off-by: Martin Disibio <mdisibio@gmail.com>
Release 1.0.0-rc.0
n/a
**Checklist**

release 1.0.0-rc.0

---

example/docker-compose/docker-compose.agent.yaml
example/docker-compose/docker-compose.otelcol.yaml
example/docker-compose/etc/agent.yaml
example/docker-compose/etc/otel-collector.multitenant.yaml
example/docker-compose/example-data/datasources/datasource.yml
example/docker-compose/readme.agent.md
example/docker-compose/readme.azure.md
example/docker-compose/readme.gcs.md
example/docker-compose/readme.grafana7.4.md
example/docker-compose/readme.local.md
example/docker-compose/readme.loki.md
example/docker-compose/readme.md
example/docker-compose/readme.multitenant.md
example/docker-compose/readme.otelcol.md
example/docker-compose/readme.s3.md

- Splits out all docker-compose examples into individual files. The original file was getting far too crowded
- Updates the root readme with links/descriptions to individual examples
- Added Grafana Agent, OTel Collector and GCS examples
Fixes #324

Split out and cleaned up examples

---

CHANGELOG.md

The change didn't make it in 0.7.0. Noticed this in a discussion with @sergeyshaykhullin. 

Fix changelog entry for #646.

---

docs/tempo/website/getting-started/_index.md

Fix a broken link introduced with #740.

Docs: Fix broken link to agent configuration

---

.drone/drone.yml

Adds additional triggers to allow us to run builds against feature branches using a tag matching `v*`

Add additional Drone build triggers

---

CHANGELOG.md
RELEASES.MD

- Updates changelog for 1.0.1
- Adds patch release instructions.

Patch release notes and v1.0.1 changelog

---

CHANGELOG.md
tempodb/backend/s3/instrumentation.go
tempodb/backend/s3/s3.go

Instrument AWS S3 requests with standard RED metrics

---

example/helm/readme.md

Forgot to update this line in #745

Fix outdated doc in Helm example

---

example/tk/tempo-microservices/main.jsonnet

Forgot this one in https://github.com/grafana/tempo/pull/785

refactor(example/tk): Remove kausal from the root element

---

docs/tempo/website/operations/monitoring.md

Document how to monitor Tempo. I've wasted some time figuring out why Tempo wasn't sending any traces so I hope to spare someone else the trouble 😓 
This is roughly inspired by https://github.com/grafana/tempo/blob/main/CONTRIBUTING.md#instrumentation
I had some difficulty finding a good balance between sharing useful information and repeating the basics common knowledge, feedback is welcome of course!
**Checklist**

docs: document Tempo instrumentation

---

cmd/tempo/app/app.go
cmd/tempo/app/modules.go

Export Server and ModuleManager fields on the `struct App`. This allow to add additional HTTP endpoint and modules through an external project.

 Export Server and ModuleManager fields of App

---

docs/tempo/website/configuration/_index.md
docs/tempo/website/operations/deployment.md
docs/tempo/website/troubleshooting/_index.md
docs/tempo/website/troubleshooting/agent.md
docs/tempo/website/troubleshooting/bad-blocks.md
docs/tempo/website/troubleshooting/max-trace-limit-reached.md
docs/tempo/website/troubleshooting/too-many-jobs-in-queue.md
docs/tempo/website/troubleshooting/unable-to-see-trace.md
operations/kube-manifests/ConfigMap-tempo-compactor.yaml
operations/kube-manifests/ConfigMap-tempo-distributor.yaml
operations/kube-manifests/ConfigMap-tempo-ingester.yaml
operations/kube-manifests/ConfigMap-tempo-querier.yaml
operations/kube-manifests/ConfigMap-tempo-query-frontend.yaml
operations/kube-manifests/Deployment-compactor.yaml
operations/kube-manifests/Deployment-distributor.yaml
operations/kube-manifests/Deployment-querier.yaml
operations/kube-manifests/Deployment-query-frontend.yaml
operations/kube-manifests/StatefulSet-ingester.yaml
operations/kube-manifests/StatefulSet-memcached.yaml
operations/kube-manifests/util/jsonnetfile.lock.json
operations/kube-manifests/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/k-compat.libsonnet
operations/kube-manifests/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-custom.libsonnet
operations/kube-manifests/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-noname.libsonnet
operations/kube-manifests/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-subtypes.libsonnet

Improve the docs a bit following some questions from the community. I've also updated operations/kube-manifests.

Improve docs: troubleshooting bad blocks, link OpenTelemetry receivers; update kube-manifests

---

modules/frontend/retry.go

Log status_code of failed requests in retry middleware

Log status_code of failed requests in retry middleware

---

tempodb/encoding/backend_block.go
tempodb/encoding/iterator_paged.go

Add blockID to iterator error msg to aid debugging

---

docs/tempo/website/configuration/_index.md

I noticed we didn't document `http_api_prefix`.

Docs: minor update configuration page

---

docs/tempo/website/troubleshooting/too-many-jobs-in-queue.md
example/docker-compose/azure/tempo-azure.yaml
example/docker-compose/gcs/tempo-gcs.yaml
example/docker-compose/local/tempo-local.yaml
example/docker-compose/s3/tempo-s3.yaml

[docs] Correct the comment on worker pool usage

---

CHANGELOG.md

Update changelog for v1.1.0-rc.0

---

docs/tempo/website/configuration/multitenancy.md
docs/tempo/website/configuration/querying.md
example/docker-compose/agent/docker-compose.yaml
example/docker-compose/azure/docker-compose.yaml
example/docker-compose/azure/readme.md
example/docker-compose/gcs/docker-compose.yaml
example/docker-compose/local/docker-compose.yaml
example/docker-compose/loki/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/otel-collector/docker-compose.yaml
example/docker-compose/s3/docker-compose.yaml

Update images used in the docker-compose examples. I quickly tested most of them to ensure they still ingest and are queryable.
Closes #870 
**Checklist**

Update docker-compose examples, tweak docs related to Grafana 7.4

---

docs/tempo/website/grafana-agent/automatic-logging.md

Improves automatic logging docs:
- Shows a stdout example which is easier to configure
- Corrects config for a logs_instance backend.
**Checklist**

Updated automatic logging docs

---

operations/tempo-mixin/tempo-operational.json

Add latency and qps panels for search to operational dashboard

---

cmd/tempo/app/app.go
cmd/tempo/app/modules.go

Signed-off-by: Christian Haudum <christian.haudum@gmail.com>
This PR exports the `memberlistKV` field on the `app.App` struct so it can be re-used in downstream projects to configure services that require memberlist configuration.
**Checklist**

Make memberlistKV field on app.App struct public

---

example/docker-compose/tempo-search/docker-compose.yaml
example/docker-compose/tempo-search/grafana-datasources.yaml
example/docker-compose/tempo-search/grafana.ini

Update the docker-compose search example:
- update the Grafana image to get the latests to get latest changes (i.e. https://github.com/grafana/grafana/pull/37765)
- set the `tempoSearch` feature flag in Grafana
- fix data source config
**Checklist**

Update Tempo search docker-compose example

---

CODEOWNERS

Karen Miller docs codeowner

---

docs/tempo/website/api_docs/_index.md

Update API reference table. Some sections were removed in https://github.com/grafana/tempo/pull/952/files#diff-7131c30555b99df76e0a16b739c65488cef1a9f128d8e82f69ca5808aab26a6a, we forgot to update the table.
**Checklist**

Docs: update API reference table

---

.drone/drone.yml
Makefile

Update the signature of drone.yml. Add a `make drone` target.
**Checklist**

Update signature drone.yml, add drone target to Makefile

---

docs/tempo/website/release-notes/v1-2.md

1.2 release notes

---

CHANGELOG.md

Tempo 1.2 Changelog

---

CHANGELOG.md
cmd/tempo-vulture/main.go

Allow visibility on the impact of search and query in isolation against the cache.
**Checklist**

Allow vulture query to be disabled

---

.github/workflows/website.yml
RELEASES.MD

Introduce latest/next versioning to tempo website documentation. This matches Grafana and Loki.  
n/a
**Checklist**

Update workflow and docs for new 'next' versioning

---

docs/tempo/website/grafana-agent/_index.md

Addresses https://github.com/grafana/technical-documentation/issues/51.

Docs: use better link to Grafana Agent configuration

---

CHANGELOG.md
operations/jsonnet/enterprise/main.libsonnet

Signed-off-by: Heds Simons <hedley.simons@grafana.com>
Fix the property name for the admin client configuration, changing it to `bucket_name` from the errorneous `bucket`.
N/A - PR without Issue.
**Checklist**

Ensure that the admin client jsonnet has correct S3 bucket property.

---

operations/jsonnet/microservices/config.libsonnet
operations/kube-manifests/ConfigMap-tempo-overrides.yaml

This PR restore the default overrides for tempo-overrides ConfigMap
Fixes #1148 
**Checklist**

Restore default overrides in tempo-overrides ConfigMap

---

CHANGELOG.md

update changelog for v1.2.1

---

.drone/drone.jsonnet
.drone/drone.yml

Fix CD pipeline by using correct image tags

---

.drone/drone.jsonnet
.drone/drone.yml

Correct vulture tags

---

tempodb/compactor.go

Checks block ownership for the shard when measuring outstanding blocks. Follow up from https://github.com/grafana/tempo/pull/1144.
**Checklist**

Check block ownership when measuring outstanding blocks

---

docs/Makefile

Updates the docs local preview commands.
**Checklist**

update docs preview commands

---

CHANGELOG.md

Oops missed changelog in #1197 
**Checklist**

Changelog for #1195

---

cmd/tempo-serverless/go.sum
go.mod
go.sum
vendor/github.com/pierrec/lz4/v4/README.md
vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go
vendor/github.com/pierrec/lz4/v4/internal/lz4block/blocks.go
vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_amd64.s
vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_arm.s
vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_arm64.s
vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_asm.go
vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_other.go
vendor/github.com/pierrec/lz4/v4/internal/lz4stream/block.go
vendor/github.com/pierrec/lz4/v4/internal/lz4stream/frame.go
vendor/github.com/pierrec/lz4/v4/internal/xxh32/xxh32zero_arm.s
vendor/github.com/pierrec/lz4/v4/lz4.go
vendor/github.com/pierrec/lz4/v4/options.go
vendor/github.com/pierrec/lz4/v4/reader.go
vendor/github.com/pierrec/lz4/v4/writer.go
vendor/modules.txt

Updates the lz4 dependency to the latest tag to catch fixes/performance improvements.
Fixes #1216 
**Checklist**

LZ4 Update

---

operations/jsonnet/microservices/configmap.libsonnet
operations/kube-manifests/ConfigMap-tempo-compactor.yaml
operations/kube-manifests/ConfigMap-tempo-distributor.yaml
operations/kube-manifests/ConfigMap-tempo-ingester.yaml
operations/kube-manifests/ConfigMap-tempo-querier.yaml
operations/kube-manifests/ConfigMap-tempo-query-frontend.yaml
operations/kube-manifests/Deployment-compactor.yaml
operations/kube-manifests/Deployment-distributor.yaml
operations/kube-manifests/Deployment-querier.yaml
operations/kube-manifests/Deployment-query-frontend.yaml
operations/kube-manifests/StatefulSet-ingester.yaml

Here we allow the configured bucket name to be used as the azure blob container name.
**Checklist**

Add azure bucket configuration to jsonnet microservices

---

.github/workflows/ci.yml

Update the `setup-pack` so we get a newer version of `pack`. The e2e workflow is failing right now.
**Checklist**

ci: update setup-pack

---

CHANGELOG.md
docs/tempo/website/release-notes/v1-3.md

Updates an incorrect PR number in the changelog.
The v1.3.0 bugs fixed section still needs to be specified and filled in.  Reviewers: what bug fixes should be listed in this v1.3.0 release notes?

Docs: draft release notes for v1.3

---

docs/tempo/website/getting-started/tempo-in-grafana.md
docs/tempo/website/operations/_index.md
docs/tempo/website/operations/backend_search.md

This documentation-only PR improves wording, and it corrects spelling, capitalization, formatting, and grammar.

Docs: revise Tempo search prose

---

CHANGELOG.md

Changelog Cleanup: v1.3

---

CHANGELOG.md
operations/jsonnet/single-binary/tempo.libsonnet

Removes unnecessary PersistentVolumeClaim
Fixes #1245 
**Checklist**

fix(tanka single-binary): remove unnecessary PersistentVolumeClaim

---

modules/compactor/compactor_ring.go
modules/compactor/config.go

As part of the migration away from cortex, here we copy what we need
to satisfy the compactor.

Copy `cortex/pkg/compactor` requirements into Tempo

---

modules/querier/config.go
modules/querier/querier.go
modules/querier/worker/frontend_processor.go
modules/querier/worker/processor_manager.go
modules/querier/worker/scheduler_processor.go
modules/querier/worker/worker.go

As part of the work to remove cortex as a dependency, here we copy what is needed to satisfy the querier.

Copy `cortex/pkg/querier/worker` package dependency into Tempo

---

LICENSING.md

It's a minuscle change and currently not needed, but it makes my life tracking changes across the various projects easier.

Add licensing boiler plate in case we ever need it

---

operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/yamls/alerts.yaml
pkg/tempopb/pool/pool_test.go

- Made latency and exclude list configurable
- Added `debug_pprof` to the exclude list

Tempo Mixin: TempoRequestLatency improvements

---

CHANGELOG.md

This update quantifies "considerably more resources" in the changelog for the v2 encoding rollout.

Changelog: Updated v2 encoding

---

docs/tempo/website/release-notes/v1-3.md

Update release notes for patch release: https://github.com/grafana/tempo/releases/tag/v1.3.1

Update release notes with 1.3.1 bug fixes

---

RELEASES.MD

* Move update docs section about patch releases down.
* Include step to add bug fixes to release notes.

Update the release guide for patch releases

---

docs/tempo/website/troubleshooting/_index.md
docs/tempo/website/troubleshooting/search-tag.md

Signed-off-by: Julien Leloup <jleloup@talend.com>
This PR adds a new troubleshooting case related to Tempo traces tag search failing to return values.
Does not fixes opened issues.
**Checklist**

Docs: add a new troubleshooting section for tag search issue

---

CHANGELOG.md

Small miss in cutting the 1.3.1 release.

Add 1.3.1 changelog entry

---

docs/tempo/website/copyright/_index.md

Removing copyright per https://raintank-corp.slack.com/archives/CH34H23HD/p1643999482151029
**Checklist**

Delete docs/tempo/website/copyright directory

---

RELEASES.MD

Remove patch version from release branch in release guide.

Remove patch version from release branch

---

.drone/drone.jsonnet
.drone/drone.yml
cmd/tempo-serverless/Makefile

Adds steps to build the Google Cloud Functions code package and push it to a GCS bucket.

GCP Drone Serverless 

---

.drone/drone.jsonnet
.drone/drone.yml

Adds a copy of code packages to a bucket for prod.

Tempo Serverless Drone: Added prod bucket

---

integration/util.go

Allow adding extra flags to the e2e test containers via an environment variable lookup. This is useful for downstream repositories that vendor the e2e tests and need to override certain values / add extra flags to configure the additional modules.
Fixes n/a
**Checklist**
- n/a Documentation added
- n/a `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Add environment variable to pass extra flags to the e2e test containers

---

example/docker-compose/s3/docker-compose.yaml
example/docker-compose/scalable-single-binary/docker-compose.yaml
integration/microservices/docker-compose.yaml

The latest minio images have moved the location of the minio binary.

Fixes minio path to reflect recent changes

---

CHANGELOG.md
cmd/tempo-serverless/handler.go

Improves error messages to clarify the location in the handler they are coming from. Will also help us differentiate between serverless platform and handler error messages.
**Checklist**

Tempo Serverless: Error clarity

---

cmd/tempo-serverless/readme.md

Just noticed this small typo 😅

Fix typo in tempo-serverless/README.md

---

cmd/tempo/app/modules.go
modules/ingester/ingester.go
modules/ingester/instance.go

Here we update some error strings to improve readability in determining from a single error string when one error stops and when another begins.  Also a correction to a docstring.

Update a few error messages and doc strings for readability

---

docs/tempo/website/operations/backend_search.md
docs/tempo/website/operations/serverless_aws.md
docs/tempo/website/operations/serverless_gcp.md

- Updates operational docs for backend seach
- Adds more recent config options
- Splits out GCP and AWS guides from main backend search article.

Backend search docs improvements

---

CHANGELOG.md
operations/jsonnet/single-binary/configmap.libsonnet

It enables retention with a default of 24h.
Fixes #1352 
**Checklist**

Enable retention in single-binary mode

---

example/helm/readme.md

Updated small typo fix
Fixes small typo
**Checklist**

Update Readme.md doc typo

---

docs/tempo/website/configuration/manifest.md

PR #1368 was missing the docs manifest update.  Here we include that update.
**Checklist**

Update docs manifest for #1368

---

docs/tempo/website/configuration/_index.md

Update the docs with some recent changes. Changes to dimensions were introduced in https://github.com/grafana/tempo/pull/1361 and https://github.com/grafana/tempo/pull/1366.
Related to #1303 
**Checklist**

metrics-generator: update docs

---

.drone/drone.jsonnet
.drone/drone.yml

Here we include changes to push the lambda artifacts to s3 as part of a serverless deployment.

Begin adding AWS serverless deployment to drone

---

.drone/drone.jsonnet
.drone/drone.yml

Here we include a region hardcode in attempt to help drone write the desired zip file to the correct bucket.

Update bucket region for serverless deployment

---

.drone/drone.jsonnet
.drone/drone.yml

Here we adjust the credential path for drone to access.

Adjust secret path for drone access

---

.drone/drone.jsonnet
.drone/drone.yml

Include the deployment steps necessary to deploy the zip artifact to the production bucket.

Include lambda zip file deployment in prod

---

.drone/drone.jsonnet
.drone/drone.yml

Here we include the necessary secrets that were relied upon in #1400.
Fixes #1400

Update drone configs for production lambda

---

docs/tempo/website/configuration/_index.md

Just a small tweak. This was suggested by Zach on a previous PR (https://github.com/grafana/tempo/pull/1386#discussion_r851287610) but I couldn't add it as the PR was set to auto-merge.

docs: address previous code review suggestion

---

CHANGELOG.md

- cuts the changelog for 1.4
- moves one changelog entry to the proper position

1.4 Changelog

---

docs/tempo/website/release-notes/_index.md
docs/tempo/website/release-notes/v1-4.md

Should have done this before cutting the release, but I forgot!

Tempo 1.4 release notes

---

cmd/tempo/app/modules.go

Removed double space in Log

---

operations/tempo-mixin/dashboards/tempo-operational.json
operations/tempo-mixin/yamls/tempo-operational.json

Here we update the panels on the Operational dashboard, which should be slightly more performant, and has some newer features we may want to use.
**Checklist**

Migrate all Operational dashboard panels

---

operations/jsonnet/enterprise/main.libsonnet

Updates the GET image in enterprise jsonnet.
@hedss Can you give a review? I'm honestly not sure how to test this correctly. Maybe we could pair up and we could look at it together.

Update GET to 1.3.0

---

.github/workflows/snyk.yml

What this PR does / why we need it:
This PR adds a short GH Action to generate and upload SBOM reports via Snyk.
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
FYSA @grafana/security-team

Snyk workflow add

---

.github/workflows/snyk.yml

Add error skipping for copy step. PRs are blocked due to Snyk workflow failing. Investigating GH/Snyk instability. 
**Checklist**

Add error skipping for copy step

---

operations/tempo-mixin/runbook.md

Improves the `TempoRequestLatency` runbook by adding some details about how to tune serverless.

Add serverless details to runbook

---

CHANGELOG.md
cmd/tempo/app/app.go
cmd/tempo/app/modules.go
integration/e2e/e2e_test.go
integration/e2e/metrics_generator_test.go
integration/e2e/serverless/serverless_test.go

Add metric to track which features are enabled in the configuration.
**Checklist**

Add metric to track feature enablement

---

CHANGELOG.md
docs/tempo/website/configuration/_index.md
pkg/cache/redis_client.go
pkg/cache/redis_client_test.go

Add SentinelPassword configuration for Redis

---

docs/tempo/website/server_side_metrics/service_graphs.md

* Add objects to sentences.
* Remove extraneous and incomplete phrase.

Docs: Perform a light edit

---

docs/tempo/website/configuration/_index.md

Reopening due to some bumpiness with the CLA assistant.
Previous PR here: https://github.com/grafana/tempo/pull/1496

Minor Docs Fix

---

.drone/drone.jsonnet
.drone/drone.yml
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
CONTRIBUTING.md
Makefile
cmd/tempo-serverless/Makefile
cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/lambda/Dockerfile
cmd/tempo-serverless/lambda/go.mod
go.mod

Update Go version of project from 1.17 -> 1.18

---

example/tk/lib/minio/minio.libsonnet

Here we expose the minio console port in the example jsonnet we provide for minio.
**Checklist**

Include console port in minio example

---

.github/dependabot.yml

Here we test out using dependabot to send automatic PRs for our dependency updates.
**Checklist**

Include initial dependabot config

---

example/docker-compose/gcs/readme.md

Fix the stack name in the README

Fix typo in readme

---

modules/generator/generator.go

Ensure we create the storage path that the generator relies on.
**Checklist**

Create generator storage path directory

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Due to my lack of involvement, I'm removing removing myself from the maintainer list.
Thank you all for all this time, and keep making Tempo **great**!
**Checklist**

Remove Daniel from maintainers

---

cmd/tempo/app/app.go
cmd/tempo/app/config.go

Here we move the app.Config to its own file.  This makes it slightly easier to find by name and matches many of the other packages of the project.
**Checklist**

Break app/config out to config.go

---

.github/workflows/milestoned_to_project.yml

Creating a GitHub workflow to automate adding milestoned issues to the Tempo project.

GitHub workflow for moving milestoned issues to projects

---

modules/querier/querier.go
tempodb/encoding/vparquet/block_search.go

- Correctly copy footer size into meta
- Tiny perf improvement

Parquet: Two quick fixes

---

tempodb/compactor.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/v2/compactor.go
tempodb/encoding/vparquet/compactor.go

Correctly pass iterator buffer config to compactor options

---

CHANGELOG.md

In preparation for 1.15 cleanup the changelog.
- Ordering fixed
- A few "features" moved to "enhancements"

Changelog Cleanup

---

docs/tempo/website/operations/_index.md
docs/tempo/website/troubleshooting/_index.md

Adds a link to the runbook file in the repository to the Deployment and operations page and the Troubleshooting page in the Tempo documentation. 
**Checklist**
- [ X ] Documentation added

Added link to runbook

---

docs/tempo/website/api_docs/_index.md
docs/tempo/website/configuration/_index.md

Fixes a broken link and corrects some formatting issues. 
Fixes #1641

[Doc] Fix broken api_doc link 

---

pkg/parquetquery/iters.go
tempodb/encoding/vparquet/block_search.go
tempodb/encoding/vparquet/block_search_test.go

Search has been broken since #1585. This PR undoes the damage and extends tests.
**Checklist**

Parquet: Fix search

---

cmd/tempo-query/Dockerfile

Bump jaeger-query image to 1.37.0

---

docs/tempo/website/api_docs/_index.md

Document how to make tag search longer available

---

CHANGELOG.md

Changelog Cleanup v1.5.0

---

cmd/tempo-query/tempo/plugin.go

Fix Jaeger query tag search

---

docs/tempo/website/configuration/_index.md
docs/tempo/website/configuration/azure.md
docs/tempo/website/configuration/compression.md
docs/tempo/website/configuration/gcs.md
docs/tempo/website/configuration/manifest.md
docs/tempo/website/configuration/multitenancy.md
docs/tempo/website/configuration/parquet.md
docs/tempo/website/configuration/polling.md
docs/tempo/website/configuration/querying.md
docs/tempo/website/configuration/s3.md

Provides basic Parquet documentation for the experimental release. We'll need additional documentation when this feature goes GA. 
Fixes #https://github.com/grafana/tempo-squad/issues/106
**Checklist**

[DOC] Updates for parquet draft doc

---

docs/tempo/website/release-notes/v1-5.md

Creates a set of draft release notes to be included in the Tempo documentation. All of the items from the release notes are included in this set for the doc site. 
Fixes #1636 
**Checklist**

[Doc] Draft release notes for 1.5

---

docs/tempo/website/configuration/parquet.md
docs/tempo/website/release-notes/v1-5.md

Corrects some incorrect links
**Checklist**

[Doc] Fixed links in release notes and Parquet docs

---

CHANGELOG.md

missed changelog in #1632, adding it now.

Add CHANGELOG entry for #1632

---

.github/workflows/website-versioned.yml

Fixes a typo in the website sync workflow.
n/a
**Checklist**

Fix release branch regex, needed a 'v'

---

docs/tempo/website/configuration/parquet.md

Changes wording from usage-reporting to storage on a link. 
**Checklist**

Fix link text for storage

---

docs/tempo/website/grafana-agent/span-metrics.md
docs/tempo/website/metrics-generator/app-performance-mgmt.md
docs/tempo/website/release-notes/v1-4.md

Fixes a broken image and two broken links
**Checklist**

[Docs] Fixed broken link and image for span metrics

---

pkg/parquetquery/iters.go

👋 This closes the pages once read.
See https://github.com/segmentio/parquet-go/pull/328
**Checklist**

Close pages in the column iterator

---

CHANGELOG.md
pkg/parquetquery/iters.go
pkg/parquetquery/predicate_test.go
tempodb/encoding/vparquet/block_findtracebyid.go
tempodb/encoding/vparquet/block_search.go

Correctly propagate errors from the iterator layer up through the querier. Previously these were swallowed.
I struggled to write tests for this. Any ideas welcome.
**Checklist**

Parquet: Querier error handling

---

operations/jsonnet/microservices/generator.libsonnet

Signed-off-by: irizzant <i.rizzante@gmail.com>
It adds the managements of variables expansion to the metrics generator Pod.
Fixes #1748
**Checklist**

fix(metrics generator): add variables expansion

---

tempodb/backend/azure/azure_helpers.go
tempodb/backend/azure/azure_helpers_test.go

Add a test to validate that we are building azure URLs correctly, added this while investigating https://github.com/grafana/tempo/issues/1728
Relates to https://github.com/grafana/tempo/issues/1728
**Checklist**

Add test for Azure GetContainerURL

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/segmentio/parquet-go/README.md
vendor/github.com/segmentio/parquet-go/buffer.go
vendor/github.com/segmentio/parquet-go/buffer_go18.go
vendor/github.com/segmentio/parquet-go/column.go
vendor/github.com/segmentio/parquet-go/column_buffer_go18.go
vendor/github.com/segmentio/parquet-go/config.go
vendor/github.com/segmentio/parquet-go/file.go
vendor/github.com/segmentio/parquet-go/internal/bytealg/bytealg_amd64.go
vendor/github.com/segmentio/parquet-go/internal/debug/debug.go
vendor/github.com/segmentio/parquet-go/internal/debug/finalizer_off.go
vendor/github.com/segmentio/parquet-go/internal/debug/finalizer_on.go
vendor/github.com/segmentio/parquet-go/merge.go
vendor/github.com/segmentio/parquet-go/null.go
vendor/github.com/segmentio/parquet-go/page.go
vendor/github.com/segmentio/parquet-go/page_values.go
vendor/github.com/segmentio/parquet-go/parquet.go
vendor/github.com/segmentio/parquet-go/row_group.go
vendor/github.com/segmentio/parquet-go/schema.go
vendor/github.com/segmentio/parquet-go/value_go18.go
vendor/github.com/segmentio/parquet-go/writer_go18.go
vendor/modules.txt

Catches a few updates to parquet go. In particular it brings in a memory improvement for ingesters and compactors.

Parquet Go Update

---

modules/overrides/list_to_map.go

Preallocate memory instead of enforcing an incremental growth. This will result in less work for the garbage collector.
Trivial fix.
**Checklist**
Trivial change.
Trivial change.
Trivial change.

tempo/modules/overrides: Preallocate memory

---

CONTRIBUTING.md
Makefile
operations/jsonnet/enterprise/main.libsonnet
operations/jsonnet/microservices/compactor.libsonnet

This PR adds `jsonnetfmt` Makefile target and formats existing files. This PR does NOT add any CI check for formatted files, although I think that would be a valuable check to have. If you agree, I can send it in separate PR.
**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Add jsonnetfmt make target and format existing files.

---

.github/workflows/ci.yml
Makefile
cmd/tempo/main.go
operations/jsonnet/microservices/compactor.libsonnet

This is a follow up to https://github.com/grafana/tempo/pull/1795. This PR adds CI checks for proper formatting of Jsonnet files. I've also added check for Go files formatting, as I haven't found it between the CI checks.
**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Add steps to CI pipeline to check if Go and Jsonnet code is properly formatted

---

modules/distributor/distributor.go

Improve distributor errors when pushing to metrics generator to help troubleshooting when pushing fails.
**Checklist**

Improve distributor errors when pushing to metrics generator

---

operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin-compiled/dashboards/tempo-reads.json
operations/tempo-mixin-compiled/dashboards/tempo-resources.json
operations/tempo-mixin-compiled/dashboards/tempo-rollout-progress.json
operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/dashboards/tempo-operational.json

We also ingest data through the internal gateway now.
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

[mixin] Also select cortex-gw-internal deployment

---

pkg/traceql/ast.go
pkg/traceql/ast_test.go

This PR implements `SpansetFilter.evalulate`.
Fixes n/a
**Checklist**

[TraceQL] Implement SpansetFilter

---

pkg/traceql/ast.go
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
pkg/traceql/ast_test.go

Implement `Pipeline.evaluate`.
**Checklist**

[TraceQL] Implement Pipeline.evaluate

---

docs/tempo/website/_index.md
docs/tempo/website/getting-started/_index.md
docs/tempo/website/getting-started/example-demo-app.md
docs/tempo/website/setup/_index.md

Removes the call to action for creating a Cloud account. This type of content will be automatically added. 
**Checklist**

Remove call to action for Cloud account

---

docs/tempo/website/metrics-generator/_index.md
docs/tempo/website/setup/tanka.md

Adds a link to the Grafana Cloud billing and usage doc for metrics-generator pages. 
**Checklist**

[Doc] Added link to billing and usage

---

cmd/tempo/app/modules.go
integration/e2e/config-scalable-single-binary.yaml

Here we update the default configuration for a compactor ring when in Scalable Single Binary mode.
Fixes #1613
**Checklist**

Set memberlist default on compactor ring in SSB target

---

modules/frontend/frontend.go
modules/frontend/handler.go

**What this PR does**: Adds status to query-frontend metric

Add status to query-frontend queries metric

---

docs/tempo/website/setup/tanka.md

Adds a configuration option for Tanka to reduce ingestor resource requirements.

[DOC] Add ingestors block to tanka doc

---

CONTRIBUTING.md

Add Compiling Jsonnnet section to CONTRIBUTING.md. 
This could help people who are new to jsonnet to compile basic changes.
**Checklist**

Add Compiling jsonnet section to CONTRIBUTING.md

---

docs/tempo/website/configuration/_index.md
docs/tempo/website/operations/generic_forwarding.md

This PR adds documentation for the Generic Forwarding feature introduced in https://github.com/grafana/tempo/pull/1775.
**Checklist**

Add Generic Forwarding documentation

---

docs/tempo/website/getting-started/_index.md
docs/tempo/website/getting-started/traces.md

Fixes two broken image links for the Get started content.

[DOC] Fix broken image links

---

README.md

Fixes a broken link
**Checklist**

chore: correct link to image in readme

---

docs/tempo/website/getting-started/_index.md

Fix broken image link in the get started page.

Fix broken image link

---

docs/tempo/website/metrics-generator/app-performance-mgmt.md

Fixes a broken image link on the APM dashboard page.

Fix broken APM image link

---

.github/workflows/website-next.yml
.github/workflows/website-versioned.yml

Update publishing workflows to use PATs with fine-grained access control

---

docs/tempo/website/setup/linux.md

This PR adds a brief paragraph to the Linux single binary set up page. This paragraph informs readers that they can also use the single binary in distributed mode. 
**Checklist**

Added note about distributed binaries

---

.github/workflows/website-versioned.yml
.github/workflows/website.yml

[release-v1.4] Update publishing workflows to use PATs with fine-grained access control

---

pkg/traceql/engine.go
pkg/traceql/expr.y
pkg/traceql/expr.y.go
pkg/traceql/parse_test.go
pkg/traceql/test_examples.yaml

Adds support for empty queries like `{}` and `{ }` directly into the parser
**Checklist**

Add support for {} to the parser

---

cmd/tempo-query/tempo/config.go
cmd/tempo-query/tempo/plugin.go

Related to https://github.com/jaegertracing/jaeger/pull/4151
**Checklist**

Make tenant header configurable

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/segmentio/parquet-go/Makefile
vendor/github.com/segmentio/parquet-go/column_buffer.go
vendor/github.com/segmentio/parquet-go/column_mapping.go
vendor/github.com/segmentio/parquet-go/column_path.go
vendor/github.com/segmentio/parquet-go/compare.go
vendor/github.com/segmentio/parquet-go/convert.go
vendor/github.com/segmentio/parquet-go/deprecated/int96.go
vendor/github.com/segmentio/parquet-go/errors.go
vendor/github.com/segmentio/parquet-go/file.go
vendor/github.com/segmentio/parquet-go/merge.go
vendor/github.com/segmentio/parquet-go/multi_row_group.go
vendor/github.com/segmentio/parquet-go/node.go
vendor/github.com/segmentio/parquet-go/null.go
vendor/github.com/segmentio/parquet-go/parquet.go
vendor/github.com/segmentio/parquet-go/reader.go
vendor/github.com/segmentio/parquet-go/row.go
vendor/github.com/segmentio/parquet-go/row_group.go
vendor/github.com/segmentio/parquet-go/scan.go
vendor/github.com/segmentio/parquet-go/schema.go
vendor/github.com/segmentio/parquet-go/type.go
vendor/github.com/segmentio/parquet-go/value.go
vendor/github.com/segmentio/parquet-go/writer.go
vendor/modules.txt

Upgrades parquet go to catch a regression on trace by id search. Async file mode was not being respected.

Upgrade parquet-go - async fix

---

CHANGELOG.md

Reordering and cleaning up the changelog for 2.0

Changelog Cleanup: 2.0

---

CHANGELOG.md

Fix a few typos in changelog
Fixes n/a
**Checklist**

Fix a few typos in changelog

---

docs/sources/setup/upgrade.md

Adds a page with information for upgrading Tempo. 
Fixes #1620 
**Checklist**

[DOCS] Upgrade Tempo doc

---

.goreleaser.yml

At some point this file was moved and it has broken CI.

Updated goreleaser path

---

docs/sources/setup/upgrade.md

Adds resource changes and note about potential issue with 1.5 blocks.

Tempo 2.0: Upgrade Notes

---

docs/sources/release-notes/v2-0.md

Correct table formatting in the release notes. 
**Checklist**

[DOCS] Fix table format in release notes

---

CHANGELOG.md
cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/segmentio/parquet-go/row.go
vendor/github.com/segmentio/parquet-go/row_builder.go
vendor/github.com/segmentio/parquet-go/transform.go
vendor/modules.txt

Backport of https://github.com/grafana/tempo/pull/2055

Update parquet-go (#2055)

---

docs/sources/release-notes/v2-0.md

Fixes a broken link in the release notes for 2.0

[DOC] Fix broken link in release notes

---

.github/workflows/ci.yml
.github/workflows/website-next.yml
.github/workflows/website-versioned.yml

See successful run in https://github.com/grafana/tempo/actions/runs/4063424051/jobs/6995648338

Ensure technical documentation builds on PRs and before publishing to the website

---

CHANGELOG.md
operations/tempo-mixin-compiled/dashboards/tempo-tenants.json
operations/tempo-mixin/dashboards/tempo-tenants.libsonnet

Apply rate() to bytes/s panel in tenant's dashboard
Fixes #2077
**Checklist**

Apply rate() to bytes/s panel in tenant's dashboard

---

docs/sources/traceql/_index.md

Update docs to specify that the intrinsics listed in the table is an exhaustive list of the intrinsics available today.

Clarify the specific intrinsic fields that currently exist

---

CHANGELOG.md
docs/sources/configuration/_index.md
docs/sources/configuration/manifest.md
modules/storage/config.go
tempodb/backend/s3/config.go
tempodb/backend/s3/s3.go

allow session token in static config

---

CHANGELOG.md
tempodb/encoding/vparquet/combiner.go
tempodb/encoding/vparquet/combiner_test.go

Parquet: Fix Combiner (#2095)

---

CHANGELOG.md
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/main.go
cmd/tempo-serverless/lambda/main_test.go

Unescape query strings in lambda (#2120)

---

CHANGELOG.md
RELEASES.MD

- 2.0.1 changelog
- release notes improvements

2.0.1 changelog

---

docs/sources/tempo/traceql/_index.md

Removes Marty's name from the link to the TraceQL blog post. 
**Checklist**

[DOC] Update link for TraceQL blog post

---

cmd/tempo/app/modules.go

**What this PR does**: This fixes a problem in GET where Tokengen is used. The problem was that Tokengen also spins up the server, which has internal server as a dependency. Since internal server was added as a service to wait for, the server service for Tokengen was never allowed to properly stop.  
**Checklist**

include internal server

---

docs/sources/helm-charts/tempo-distributed/_index.md
docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
docs/sources/helm-charts/tempo-distributed/release-notes/_index.md

Adds the initial draft of the Tempo Helm chart documentation for tempo-distributed. We can expand on this doc in subsequent iterations.  
I've followed the content structure from the Mimir repo: https://github.com/grafana/mimir/tree/main/docs/sources/helm-charts/mimir-distributed 
The release-notes/_index.md file is set to draft: true so it will not appear in the documentation. I've included this file for whenever we have versioned release notes. 
Questions for review: 
* Are there additional sections that we need? 
Fixes #1628 
Related: https://github.com/grafana/tempo/pull/2124 
**Checklist**

[DOC] tempo-distributed helm chart doc

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Make small corrections to code fencing in the helm doc for tempo-distributed
**Checklist**

Update yaml indent and code fences for getting started with helm

---

docs/sources/tempo/release-notes/v2-0.md

Update the release notes to include bug fixes and enhancements for 2.0.1.
**Checklist**

[DOC] Add 2.01 to release notes

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

GET doc with Helm
Fixes https://github.com/grafana/enterprise-traces/issues/403
**Checklist**

[DOC] Add GET helm doc

---

CHANGELOG.md

Include an additional option as removed in the changelog.
**Checklist**

Include additional option as removed in changelog

---

.github/workflows/website-next.yml
docs/sources/helm-charts/tempo-distributed/_index.md
docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
docs/sources/helm-charts/tempo-distributed/release-notes/_index.md

Publish "next" Helm chart documentation for tempo-distributed

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Fixes some minor errors in the Helm chart doc formatting. 
**Checklist**

[DOC] Fix helm doc errors

---

CHANGELOG.md

**What this PR does**: correct the changelog with a better description of the PR
**Checklist**

Update changelog with a better description

---

docs/sources/tempo/getting-started/example-demo-app.md
docs/sources/tempo/operations/deployment.md
docs/sources/tempo/setup/_index.md

Add links to the new Tempo and GET Helm chart doc to the Set up documentation. 
**Checklist**

[DOC] Add links to Helm doc

---

CONTRIBUTING.md

Updates the contributing.md file with information about the documentation directories, publication branches, and general doc info. 
**Checklist**

Updated guidelines for writing

---

pkg/traceql/ast_execute.go

Obvious improvement pointed out by @mdisibio for #2254 .

Prealloc map for performance

---

modules/compactor/compactor.go
tempodb/compactor.go
tempodb/compactor_test.go
tempodb/retention.go
tempodb/retention_test.go
tempodb/tempodb.go
tempodb/tempodb_search_test.go
tempodb/tempodb_test.go

* Update tempodb.Compactor interface to include a context
* Update implementations of tempodb.Compactor to pass a context when available
* Handle context.Done() to break the compaction cycle
* Small format and docstring changes
**Checklist**

Update compactor to handle context

---

docs/sources/tempo/traceql/_index.md

TraceQL docs: add guidance for regex authoring indicating that it's Golang regular expression and suggesting online regex testing sites like https://regex101.com/
**Checklist**

[Documentation - TraceQL] Add guidance for regex authoring

---

docs/sources/tempo/grafana-agent/_index.md

Fixed the blog link to one that works, previous link was a 404
**Checklist**

Fixed for blog url 404

---

docs/sources/tempo/setup/helm-chart.md

Fixes a link formatting error. 
**Checklist**

Fix link issue in Helm chart doc

---

docs/sources/tempo/getting-started/docker-example.md
docs/sources/tempo/getting-started/example-demo-app.md
docs/sources/tempo/setup/_index.md

Links to the Intro To MLT sandbox repository which includes a running Tempo instance.
N/A
**Checklist**

docs: Add extra examples to the getting started guides.

---

docs/sources/tempo/traceql/_index.md

Adds a simple example of regex for TraceQL.

add a regex example

---

docs/sources/tempo/configuration/parquet.md
docs/sources/tempo/operations/schema.md

This PR fixes three broken links that were causing some of the doc publishing scripts to fail.

[DOC] Fix broken links

---

docs/sources/tempo/configuration/_index.md

Noticed these were missing from the docs
**Checklist**

Docs: document metrics_generator_forwarder_workers and _queue_size

---

CHANGELOG.md
docs/sources/tempo/release-notes/v2-1.md

Fixes an incorrect link in the changelog and release notes for 2.1.
**Checklist**

[DOC] Fixed link in changelog for 2.1

---

CHANGELOG.md
cmd/tempo-vulture/main.go

**What this PR does**: add simply traceql query to vulture 
Fixes #2009 
**Checklist**

Add traceql search in vulture

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Proposal to make @electron0zero a maintainer. An approving review is a vote in favor.
[Tempo Work](https://github.com/grafana/tempo/pulls?q=is%3Apr+author%3Aelectron0zero+is%3Aclosed)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+reviewed-by%3Aelectron0zero+is%3Aclosed)
@grafana/tempo

Maintainer - @electron0zero

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Proposal to make @ie-pham a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/ie-pham)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aie-pham)
@grafana/tempo

Maintainer - @ie-pham

---

modules/frontend/frontend.go
modules/frontend/search_progress.go
modules/frontend/search_progress_test.go
modules/frontend/search_streaming.go
modules/frontend/search_streaming_test.go
modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go

Bring https://github.com/grafana/tempo/pull/2454 to `r95`

[r95] Fix Search - Cross pollination (#2454)

---

docs/sources/tempo/traceql/_index.md

Keeping the information on the page consistent with the currently supported aggregates: https://grafana.com/docs/tempo/latest/traceql/#aggregators
Keeping the information on the page consistent with the currently supported aggregates: https://grafana.com/docs/tempo/latest/traceql/#aggregators
-
**Checklist**

Docs: Update supported traceql aggregates

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Fixes the Tempo version number in the Helm chart documentation. 
**Checklist**

[DOC] Update Tempo version

---

.github/workflows/sbom-report.yml

Quick PR to add SBOM report generation on release. We (Security Engineering) have this running in grafana/grafana and grafana/loki. We are planning to expand this to all our OSS Projects.
**Checklist**

Automated SBOM Report Generation

---

docs/sources/tempo/configuration/_index.md

Update instructions on enabling env variable parsing in config file
Updated the `-config.expand-env` option instructions, which now include the full option with value (`-config.expand-env=true`), instead of only specifying the option name. This will also unify the instructions on enabling env. variables in config with [Loki configuration](https://grafana.com/docs/loki/latest/configuration/), where the full option with value is specified.
- 
**Checklist**

Update "use-environment-variables-in-the-configuration" section

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/sidecar-proxy.md

Adds @mdisibio sidecar proxies doc. 
**Checklist**

[DOC] Doc for sidecar proxies

---

docs/sources/tempo/configuration/_index.md

Updates the docs for the metrics generator configuration
Fixes #2508
**Checklist**

Updated documentation for metrics_ingestion_time_range_slack

---

.github/workflows/ci.yml
Makefile
operations/jsonnet/microservices/Makefile
operations/jsonnet/microservices/Readme.md
operations/jsonnet/microservices/test/environments/default/main.jsonnet
operations/jsonnet/microservices/test/environments/default/spec.json
operations/jsonnet/microservices/test/jsonnetfile.json
operations/jsonnet/microservices/test/jsonnetfile.lock.json
operations/jsonnet/microservices/test/lib/k.libsonnet
operations/jsonnet/microservices/test/main.libsonnet
operations/jsonnet/microservices/test/test1.jsonnet

Here I propose that we create the necessary structure to start unit testing out jsonnet microservices code.  No useful tests are included here, but would allow potential changes to be tested against in future PR.s
* Creates a jsonnet test environment based on our example
* Compiles the jsonnet environment output into a file
* Compiles the environment with tanka to verify
* Executes the first jsonnet test to verify that the output matches the compilation.
**Checklist**

Begin unit testing jsonnet microservices

---

.drone/drone.jsonnet
.drone/drone.yml

100 weeks of DronCI later, we need to bump the matcher for weekly branches. Here is for a 100 more 🥂

Run DronCI for weekly branches with >r99

---

docs/sources/tempo/operations/schema.md

Fixes a broken link in the schema doc for Parquet. 
**Checklist**

[DOC] Fix broken link in schema

---

cmd/tempo-query/Dockerfile

Bump jaeger-query to 1.46.0

---

docs/sources/tempo/release-notes/v2-1.md

Wrong url for upgrade docs

---

docs/sources/tempo/getting-started/_index.md
docs/sources/tempo/getting-started/docker-example.md
docs/sources/tempo/operations/best-practices.md

Fixes a broken image in the best practices doc and corrects minor formatting errors. 
**Checklist**

[DOC] Fix missing image and formatting

---

docs/sources/tempo/setup/_index.md
docs/sources/tempo/setup/deployment.md
docs/sources/tempo/setup/operator/_index.md
docs/sources/tempo/setup/operator/quickstart.md

Moves some content from https://tempo-operator.netlify.app/ into the upstream docs
Follow up tasks:
**Checklist**

Migrate operator docs to Grafana

---

docs/sources/tempo/traceql/_index.md

Renames the TraceQL page to Query with TraceQL in prep for mounting this content in Cloud Traces documentation. 
**Checklist**

[DOC] Update page title for TraceQL

---

CHANGELOG.md
docs/sources/tempo/traceql/_index.md
pkg/traceql/ast.go
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
pkg/traceql/ast_test.go
pkg/traceql/ast_validate.go
pkg/traceql/enum_attributes.go
pkg/traceql/storage.go
pkg/traceql/test_examples.yaml
pkg/traceqlmetrics/mocks.go
tempodb/encoding/vparquet/block_traceql.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet2/block_traceql_test.go
tempodb/tempodb_search_test.go

Backport #2625 to r103

---

docs/sources/tempo/operations/best-practices.md
docs/sources/tempo/operations/troubleshooting/_index.md
docs/sources/tempo/traces.md

Add content written by @Mkrummz to best-practices.md and traces.md. Also, fixes a missing alias for Troubleshooting section. 
**Checklist**

[DOC] Add best practices; fix alias

---

cmd/tempo-query/Dockerfile

Bump jaeger-query image to 1.47.0

---

tempodb/encoding/vparquet3/block_traceql.go

Apply https://github.com/grafana/tempo/pull/2660 to `vParquet3`
Fixes #2674 
**Checklist**

Apply structural operator bugfix to vparquet3

---

docs/sources/tempo/configuration/grafana-agent/automatic-logging.md

We want folks to use TraceQL, and so here we update some older docs to mention it.
**Checklist**

[docs] update automatic-logging to include mention of TraceQL

---

docs/sources/tempo/setup/operator/api-docs.md

Operator api docs

---

docs/sources/tempo/setup/operator/_index.md

Fix comminity heading

---

docs/sources/tempo/setup/operator/monitor.md

Follow up after https://github.com/grafana/tempo/pull/2596
Migrates https://tempo-operator.netlify.app/docs/observability_tracing.md/ to the grafana docs
**Checklist**
- [ x] Documentation added

Add operator minitor docs

---

docs/sources/tempo/setup/operator/object-storage.md

Follow up after https://github.com/grafana/tempo/pull/2596 
The PR migrates content from https://tempo-operator.netlify.app/docs/object_storage.md/ to Grafana docs
**Checklist**
- [x ] Documentation added

Add operator object storage docs

---

docs/sources/tempo/api_docs/metrics-summary.md

Adds metrics summary API doc (copied from Cloud Traces content)
**Checklist**

[DOC] Add metrics summary doc

---

docs/sources/tempo/setup/upgrade.md

Adds a missing `%` to an admonition shortcode. 
**Checklist**

Fix missing character on upgrade.md

---

docs/sources/tempo/traceql/architecture.md

We already have some structural querying, so made more specific to say parent and ancestor.
**Checklist**

Specify that parent and ancestor structural queries are coming 

---

docs/sources/tempo/traceql/_index.md

Future work relref fix
**Checklist**

Fix relref to future work to make it more specific

---

CHANGELOG.md

Prepares the changelog for 2.2.1

2.2.1 changelog

---

docs/sources/tempo/release-notes/v2-2.md

Updates the 2.2 release notes with the bug fixes for 2.2.1
Fixes #2811 
**Checklist**

[DOC] 2.2.1 release notes draft

---

docs/sources/tempo/configuration/parquet.md

Fixes a link in the Parquet docs. 
**Checklist**

[DOC] Fix Parquet doc link

---

docs/sources/tempo/configuration/azure.md

Adds a sample file configuration for Azure Storage
**Checklist**

Add yaml file sample for Azure Storage

---

docs/sources/tempo/traceql/_index.md

Replace `“` with `"`, as in the rest of the updated file.

Fix quotes

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/operations/architecture.md
docs/sources/tempo/troubleshooting/max-trace-limit-reached.md

Adds information about the live trace and how it's controlled in the configuration > ingester section. 
Based on https://github.com/grafana/tempo/discussions/2380
**Checklist**

[DOC] Add live trace info

---

cmd/tempo-cli/cmd-analyse-block.go

Support analysing vParquet3 blocks

---

docs/sources/tempo/configuration/_index.md

Fix typo in docs

---

CHANGELOG.md

Updates the changelog for 2.2.2 and fixes the date on 2.2.1.

Changelog 2.2.2

---

docs/sources/tempo/release-notes/v2-2.md

Creates 2.2.2 release notes
**Checklist**

[DOC] Add 2.2.2 to release notes

---

docs/sources/tempo/configuration/grafana-agent/service-graphs.md
docs/sources/tempo/metrics-generator/service_graphs/enable-service-graphs.md

Corrects links and aliases for the service graph documentation. 
**Checklist**

[DOC] Fix links in service graph docs

---

tempodb/encoding/vparquet2/copy.go
tempodb/encoding/vparquet3/copy.go

Backport #2890 to r112
**Checklist**

[backport r112] Fix flush index error handling (#2890)

---

docs/variables.mk

The pinned version is no longer needed and is missing features.
**Checklist**

Use latest docs-base image

---

docs/sources/tempo/setup/operator/_index.md

Add managed upgrades to operator feature list
**Checklist**

[DOC] Add managed upgrades to operator feature list

---

CHANGELOG.md

Cleaned up the changelog for 2.2.3

2.2.3 Changelog

---

docs/sources/tempo/release-notes/v2-2.md

Adds release notes for 2.2.3. 
**Checklist**

Add release notes for 2.2.3

---

modules/generator/generator.go

Resolves a very minor typo in modules/generator/generator.go
N/A
**Checklist**

Fix typo in modules/generator/generator.go error message

---

docs/sources/tempo/api_docs/pushing-spans-with-http.md
docs/sources/tempo/getting-started/docker-example.md

Updates the Pushing spans with HTTP example doc to include more examples, use a Docker example, and remove Zipkin. 
Fixes #1695 #2522 
**Checklist**

[DOC] Update Pushing spans HTTP doc

---

docs/Makefile
docs/README.md
docs/docs.mk
docs/make-docs
docs/tempo/website/api_docs/_index.md
docs/tempo/website/configuration/_index.md
docs/tempo/website/troubleshooting/unable-to-see-trace.md
docs/variables.mk

Fixes two broken links in Tempo docs for v1.2. This is part of an effort to remove all broken links from all documentation. 
Part of: https://github.com/grafana/technical-documentation/issues/811

[DOC] Fix broken links in doc for Tempo v1.2

---

example/docker-compose/agent/docker-compose.yaml
example/docker-compose/azure/docker-compose.yaml
example/docker-compose/cross-cluster/docker-compose.yaml
example/docker-compose/debug/docker-compose.yaml
example/docker-compose/distributed/docker-compose.yaml
example/docker-compose/gcs/docker-compose.yaml
example/docker-compose/local/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/otel-collector/docker-compose.yaml
example/docker-compose/s3/docker-compose.yaml
example/docker-compose/scalable-single-binary/docker-compose.yaml

Moves the Grafana version from the last major release to current major release.
N/A
**Checklist**

Move local Docker Compose Grafana version to 10.1.1.

---

cmd/tempo-query/Dockerfile

Bump jaeger-query docker image to 1.50

---

CODEOWNERS

Grants ownership of docs to https://github.com/jdbaldry for maintenance of tooling and other things.
**Checklist**

Grant jbaldry ownership of docs

---

CHANGELOG.md
docs/make-docs
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go
modules/overrides/userconfigurable/client/limits.go
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin/dashboards/tempo-operational.json

Update weekly release r118 with latest changes from main, mainly to include https://github.com/grafana/tempo/pull/3012
**Checklist**

Update r118 with latest changes from main

---

.drone/drone.yml

Update the drone signature for a recent drone change.
**Checklist**

Update drone signature

---

cmd/tempo/app/config.go

Fix internal server loglevel nil

---

CHANGELOG.md

Updates the changelog for 2.3 rc.0

Tempo: 2.3 rc.0 changelog

---

modules/generator/registry/registry.go

Limits the warning message `tenant=<id> msg="reached max active series" active_series=<x> max_active_series=<y>` to once per second per tenant.  Otherwise during spikes of high volume it can approach 10K+ lines/second.
Fixes n/a
**Checklist**

Reduce max active series warning log rate

---

CHANGELOG.md

Adds a changelog entry for 2.2.4 and patches up some minor issues with the 2.3 changelog.

2.2.4 Changelog

---

docs/sources/tempo/setup/set-up-test-app.md

**What this PR does**: It's just a fix for a typo
None
**Checklist**

fix typo in doc

---

docs/sources/tempo/setup/operator/multitenancy.md

Document multi-tenancy with operator

---

CHANGELOG.md

Marks v2.3 in the changelog and adjusts 2 entries.

v2.3 Changelog!

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
modules/frontend/handler.go
modules/frontend/transport/roundtripper.go
vendor/github.com/grafana/dskit/concurrency/worker.go
vendor/github.com/grafana/dskit/httpgrpc/httpgrpc.go
vendor/github.com/grafana/dskit/httpgrpc/server/server.go
vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
vendor/github.com/grafana/dskit/ring/batch.go
vendor/modules.txt

vendors in some dskit changes that altered import paths of a few httpgrpc utils
**Checklist**

vendor dskit: update httpgrpc utils import paths

---

docs/sources/tempo/configuration/azure.md
docs/sources/tempo/configuration/s3.md
docs/sources/tempo/release-notes/v2-3.md

Updates the S3 configuration doc to address missign ListObjects
Fixes #2489
**Checklist**

[DOC] DRAFT Update the S3 config doc to add ListObjects

---

CHANGELOG.md

Updates the changelog for release 2.3.1.

Changelog - Release 2.3.1

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/operations/tempo_cli.md
docs/sources/tempo/traceql/_index.md

Added links to the TraceQL streaming content and updated some of the TraceQL information for the query editor. 
FYI @electron0zero 
**Checklist**

Update streaming doc

---

docs/sources/tempo/getting-started/instrumentation.md

docs: fix typo

---

CHANGELOG.md
tempodb/blocklist/poller.go

Without this change the error condition does not properly decrement the waitgroup and blocks indefinitely.
**Checklist**

Fix poller waitgroup handling

---

integration/poller/poller_test.go

Downstream repos (i.e. Grafana Enterprise Traces) is very unhappy with this lint error.  Fixing it.... There may be more.
**Checklist**

Fix lint errors that are affecting downstream repos

---

docs/sources/tempo/setup/helm-chart.md

Moves the Helm doc link on the Helm set up page to make it easier to find. 
**Checklist**

[DOC] Move link for helm documentation

---

docs/sources/tempo/getting-started/docker-example.md

docs: Update docker-example.md

---

CHANGELOG.md
cmd/tempo-cli/Dockerfile
cmd/tempo-serverless/cloud-run/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile
cmd/tempo/Dockerfile_debug

Here we update the alpine image version to 3.19.
**Checklist**

Update Alpine image to 3.19

---

cmd/tempo/app/app.go
cmd/tempo/app/modules.go
cmd/tempo/app/server_service.go

Two changes to allow enterprise vendoring to work:
- Expose the server
- Expose a way to enable http2

Fix Enterprise Vendoring

---

.github/workflows/ci.yml
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/schema_test.go

**What this PR does**: Add new schema for links and updated both links and events to use the generic Attribute struct. 
**Checklist**

links and events schema changes [wip]

---

tempodb/encoding/vparquet3/block_findtracebyid.go

Improves cpu and mem usage of vParquet3 FindTraceByID.   We found that vParquet3 encoding was using more resources than vParquet2 and vParquet.  This change greatly improves the situation but doesn't offer a good explanation of why since vParquet3 and vParquet2 FindTraceByID were nearly identical.    Updating to GenericReader provides the bulk of improvements, but saw a couple other bookkeeping things to address.
```
│  before.txt   │              after.txt              │
│    sec/op     │   sec/op     vs base                │
FindTraceByID/VPARQUET_INDEX=0-12   11.329m ± 28%   5.010m ± 1%  -55.78% (p=0.000 n=10)
│  before.txt   │              after.txt               │
│     B/op      │     B/op      vs base                │
FindTraceByID/VPARQUET_INDEX=0-12 …
```

vParquet3 use more efficient GenericReader

---

tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet3/schema.go

Add attributes to the instrumentation scope. This PR just changes the schema. The attributes are not actually written as the current proto does not support attributes on instrumentation scope level.
Fixes grafana/tempo-squad#367
**Checklist**

Add attributes to instrumentation scope

---

.github/workflows/doc-validator.yml

https://github.com/grafana/technical-documentation/releases/tag/doc-validator%2Fv4.0.0

Update to `doc-validator` 4.0.0

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/querying.md
docs/sources/tempo/getting-started/_index.md
docs/sources/tempo/getting-started/tempo-in-grafana.md
docs/sources/tempo/traces.md

Adds new videos to the Tempo docs for what are traces, traces vs los vs metrics, and intro to distributed tracing. 
**Checklist**

[DOC] Add videos to docs

---

docs/sources/tempo/setup/set-up-test-app.md

Backports https://github.com/grafana/tempo/pull/3228,  Set up a test app 
**Checklist**

[DOC][Release 2.3] Backport 3228 to release v2.3

---

docs/sources/tempo/traces.md

Incorporates Jen Villa's comments from the Grafana Cloud Traces [version of this content](https://github.com/grafana/website/pull/17547).
**Checklist**

[DOC] Update traces versus metrics and logs

---

operations/tempo-mixin/README.md

Add instructions on how to use the mixins.
Related: https://github.com/grafana/tempo-squad/issues/344
**Checklist**

[DOC] Update README.md

---

pkg/parquetquery/iters.go

**What this PR does**: Commenting out seekwithipage until https://github.com/ie-pham/tempo/pull/new/boolfix is merged in parquet-go since this function relies on the Slice() function. 
**Checklist**

Comment out seekwithinpage until bug is fixed

---

docs/sources/tempo/operations/prometheus_datasource.md

Fixes a missing screenshot in operations/prometheus_datasource.md.
FYI @zalegrala 
**Checklist**

[DOC] Fix missing metrics vis screenshot

---

CODEOWNERS

I don't want to confuse contributors or other maintainers either by:
1. ignoring PRs because they are not my core responsibility
1. approving PRs that the project maintainers would prefer I didn't
I've taken the opportunity to add a comment header to the CODEOWNER file to explain how to use the file. The same conventions are used in the grafana/grafana and grafana/website repository and probably more.

Update my code ownership to better reflect my responsibilities to the repo

---

docs/sources/tempo/setup/linux.md

Reported by a reader via an email to docs@grafana.com

Fix typo in configuration comment

---

docs/sources/tempo/operations/cross_tenant_query.md
docs/sources/tempo/operations/multitenancy.md

Fixes minor issues in the multi-tenancy and cross-tenant docs. 
**Checklist**

[DOC] Fix minor errors in multi-tenancy doc

---

modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go
modules/querier/worker/frontend_processor.go

Here we aim to improve the context handling on the search path in the case of cancellation and timeouts.
Related #2680
**Checklist**

Improve frontend search context handling

---

modules/ingester/flush.go

This PR fixes flush during shutdown. Previously the flush code hit an asynchronous goroutine resulting in abandoning the flush op. 
Fixes #3298 
**Checklist**

Fix flush during shutdown

---

CHANGELOG.md

Cleans up and cuts the changelog for 2.4.0-rc.0

Tempo 2.4.0-rc.0 Changelog

---

pkg/cache/memcached.go

Traces for `query_range` at scale are unusable due to their size.  Quite literally -- even a small query over 30 minutes cannot be read to due exceeding our largest max_bytes_per_trace.    This PR simply deletes the two `Memcached.GetMulti` spans created for every cache read and take up 90% of the trace.  (example:  105K spans out of 119K)
Would like to hear feedback if they are valuable enough to keep in other cases.  It would be possible to conditionally create the spans for different API requests or cache roles, or convert them to span events.  For `query_range` they must be removed though.
Fixes n/a
**Checklist**

WIP: Remove memcached spans

---

docs/sources/tempo/release-notes/v2-4.md
docs/sources/tempo/setup/upgrade.md

Release notes and upgrade guide for Tempo 2.4
FYI @09jvilla and @joe-elliott 
Fixes #3402 
**Checklist**

[DOC] Release notes for 2.4

---

docs/sources/tempo/operations/user-configurable-overrides.md

Noticed some small issues with the user-configurable overrides docs.
**Checklist**

Small fixes user-configurable overrides docs

---

docs/sources/tempo/setup/operator/monolithic.md

Document Tempo Operator Monolithic mode
**Checklist**

[DOC] Document Tempo Operator Monolithic mode

---

CHANGELOG.md

2.4.1 changelog

---

docs/design-proposals/2023-11 TraceQL Metrics.md

Adds design proposal for TraceQL language additions for metrics. The rendered version can be viewed at: https://github.com/mdisibio/tempo/blob/traceql-metrics-design-proposal/docs/design-proposals/2023-11%20TraceQL%20Metrics.md
Fixes n/a
**Checklist**

TraceQL Metrics design proposal

---

modules/frontend/slos.go

we noticed our production cluster that current buckets are not sufficient. so add more buckets for better observability. 
**Checklist**

Increase buckets in queryThroughput histogram

---

docs/sources/tempo/setup/set-up-test-app.md

Updates documentation on how to generate traces
Fixes #3481
**Checklist**

Outdated documentation setting up a test app

---

docs/sources/tempo/_index.md
docs/sources/tempo/api_docs/_index.md

Creates a landing page for Tempo documentation. 
Fixes #3539 
**Checklist**

[DOC] Tempo landing page for docs

---

docs/sources/tempo/configuration/polling.md
docs/sources/tempo/operations/backend_search.md
docs/sources/tempo/operations/caching.md
docs/sources/tempo/operations/monitor/_index.md
docs/sources/tempo/operations/monitor/polling.md
docs/sources/tempo/operations/monitor/set-up-monitoring.md
docs/sources/tempo/operations/monitoring.md

Updates the monitoring Tempo documentation with instructions on how to use the mixins. 
Remaining
Fixes #https://github.com/grafana/tempo-squad/issues/344
**Checklist**

[DOC] Update monitoring doc

---

.drone/drone.jsonnet
.drone/drone.yml
Makefile

Add platform var to `build-ci-tools` drone step

Add platform var to build-ci-tools drone step

---

build/tools.mk

Now that we have an upstream image built from CI, switch to using it.
https://hub.docker.com/r/grafana/tempo-ci-tools/tags
**Checklist**

Use upstream tools image

---

docs/sources/tempo/_index.md

Reported in https://raintank-corp.slack.com/archives/C5PG2JK8W/p1713243017471489
I didn't find any other instances when I grep'd for it.

Replace ß with s

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/parquet-go/parquet-go/CONTRIBUTING.md
vendor/github.com/parquet-go/parquet-go/README.md
vendor/github.com/parquet-go/parquet-go/buffer_pool.go
vendor/github.com/parquet-go/parquet-go/column.go
vendor/github.com/parquet-go/parquet-go/compress/zstd/zstd.go
vendor/github.com/parquet-go/parquet-go/schema.go
vendor/github.com/parquet-go/parquet-go/writer.go
vendor/modules.txt

Update the parquet-go dependency to the latest commit [962b3c5827c3](https://github.com/parquet-go/parquet-go/commit/962b3c5827c3c0de1f2be9fd8079823de00f076b)
**Checklist**

Update parquet-go to latest commit in main

---

docs/sources/tempo/operations/backend_search.md

Major overhaul of the Tune search performance doc. Content updates from @electron0zero. 
Fixes #3237
**Checklist**

[DOC] Revised Tune search performance doc

---

docs/sources/tempo/traceql/_index.md

Remove incorrect query

---

docs/sources/tempo/_index.md
docs/sources/tempo/configuration/grafana-agent/_index.md
docs/sources/tempo/setup/operator/monolithic.md

Fixes two broken links and some linter errors. 
**Checklist**

[DOC] Fix broken links and linter errors

---

CHANGELOG.md

Move the changelog entry for the 2.4.2 release.
**Checklist**

Update changelog for v2.4.2 release

---

docs/sources/tempo/release-notes/v2-4.md

Adds release notes for Tempo 2.4.2
Fixes https://github.com/grafana/tempo/issues/3677
**Checklist**

[DOC] Add 2.4.2 release notes

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
docs/sources/tempo/setup/linux.md
example/docker-compose/cross-cluster/tempo-distributed-a.yaml
example/docker-compose/cross-cluster/tempo-distributed-b.yaml
example/docker-compose/distributed/tempo-distributed.yaml
example/docker-compose/multi-tenant/tempo.yaml
example/docker-compose/scalable-single-binary/tempo-scalable-single-binary.yaml
example/docker-compose/shared/tempo.yaml
integration/e2e/backend/backend.go
integration/e2e/config-limits-partial-success.yaml
modules/frontend/search_sharder_test.go
tempodb/backend/azure/azure_test.go

Fixed multiple typos within the project

Fixed multiple typos

---

CHANGELOG.md

Cleans up the changelog for v2.5.0-rc.0

Changelog cleanup - v2.5.0-rc.0

---

docs/sources/tempo/operations/caching.md
docs/sources/tempo/release-notes/v2-4.md
docs/sources/tempo/setup/upgrade.md

Verifies the information on the [Improve caching performance documentation page](https://grafana.com/docs/tempo/latest/operations/caching/). 
Minor updates to address some linting errors. 
Fixes #3597 
**Checklist**

[DOC] Updates for caching doc and linting fixes

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/parquet.md

Mention vParquet4 in the config docs
Fixes grafana/tempo-squad#385
**Checklist**

Document how to enable vParquet4 in the config section

---

CHANGELOG.md

Cutting an rc1 with 2 more PRs

Tempo 2.5.0-rc1 changelog

---

build/tools.mk
operations/jsonnet-compiled/StatefulSet-memcached.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/config.libsonnet

Update the memcached and exporter image versions.
**Checklist**

Update jsonnet memcached image version

---

CHANGELOG.md

**What this PR does**: Update changelog to reflect v.2.5.0
**Checklist**

update changelog for v2.5.0

---

docs/sources/tempo/metrics-generator/span_metrics.md

Fixes what appears to be a copy-pasta error.
N/A
**Checklist**

Fixed copy-pasta error?

---

docs/sources/tempo/release-notes/v2-5.md

Adds the links the 2.5 blog post and video to the release notes. 
**Checklist**

[DOC] Add links to blog post for 2.5

---

docs/sources/tempo/traceql/_index.md
modules/ingester/instance_search_test.go
pkg/search/util.go
pkg/traceql/enum_attributes.go

**What this PR does**: Add event name intrinsics to search tags, update documentation
**Checklist**

Event intrinsics tag

---

tempodb/encoding/vparquet4/block_traceql.go

Tiny aesthetical fix in the docstring of the fetch() function
Fixes my OCDlike issues :)
**Checklist**

Fix tiny format glitches in fetch() docstring

---

cmd/tempo/app/config.go
tempodb/config.go

DOCS fix-typos

---

modules/frontend/search_sharder_test.go

Fixes tests broken in main by this PR: https://github.com/grafana/tempo/pull/3901

Tempo: Fix tests

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/grafana/dskit/crypto/tls/tls.go
vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
vendor/modules.txt

Include the certificate loading fix from https://github.com/grafana/dskit/pull/552 
Related [grafana/dskit/552](https://github.com/grafana/dskit/pull/552)
**Checklist**

Update dskit for TLS certificate loading issue

---

docs/sources/tempo/shared/best-practices-traces.md

Fixes a broken link in the shared doc for best practices. 
**Checklist**

[DOC] Fix broken link in tracing best practices

---

CHANGELOG.md
docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/operations/user-configurable-overrides.md

- Fix some broken links related with config overrides
**Checklist**

doc: broken links in config overrides

---

docs/sources/tempo/operations/consistent_hash_ring.md

[DOC]: add queriers to the list of users of the metrics-generator ring

---

docs/sources/tempo/configuration/grafana-alloy/_index.md

Fixed link that returns 404 Error on https://grafana.com/docs/tempo/latest/configuration/grafana-alloy/.
None.
**Checklist**

doc: fix "Allow configuration syntax" link in _index.md

---

docs/sources/tempo/setup/operator/_index.md

Clarify and update supported Kubernetes versions of the Tempo Operator
-
**Checklist**

[DOC] operator: clarify and update supported Kubernetes versions of the Tempo Operator

---

CHANGELOG.md

Forgot to add a changelog entry
**Checklist**

Add support for native histograms to CHANGELOG.md

---

docs/sources/tempo/traceql/metrics-queries.md

Adds doc for the compare function for TraceQL metrics. 
Reference: PR #3695 
**Checklist**

[DOC] Add doc for compare function for metrics doc

---

docs/sources/tempo/api_docs/pushing-spans-with-http.md

Since Traces V2 is out there, we can use it in the documentation
**Checklist**
- [X ] Documentation added

[Doc] Update retrieve traces  doc to use Traces V2

---

.github/workflows/doc-validator.yml

Things like `./`, `./path/to/URL/`, `../path/to/other/URL/`.
https://github.com/grafana/technical-documentation/releases/tag/doc-validator%2Fv5.2.0
**Checklist**

Use doc-validator image that supports relative path URLs

---

CHANGELOG.md

Cleans up the changelog in preparation for releasing Tempo v2.6.

2.6 Changelog Prep

---

docs/sources/tempo/getting-started/example-demo-app.md
docs/sources/tempo/operations/monitor/_index.md
docs/sources/tempo/operations/monitor/set-up-monitoring.md
docs/sources/tempo/setup/set-up-test-app.md
docs/sources/tempo/troubleshooting/_index.md
docs/sources/tempo/troubleshooting/agent.md
docs/sources/tempo/troubleshooting/unable-to-see-trace.md

Updates procedures, examples, and content to use Grafana Alloy, in the Monitor Tempo, Troubleshoot Tempo, and Set up a test app documentation. 
Fixes https://github.com/grafana/tempo/issues/4025
**Checklist**

[DOC] Convert monitor, troubleshoot, set up test app to Alloy

---

docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/traceql/_index.md

Adds the blog post link and fixes a 2.5 reference in the first sentence. 
**Checklist**

Add blog post links to rel notes

---

.github/workflows/backport.yml
.github/workflows/ci.yml
.github/workflows/dependabot_serverless_gomod.yml
.github/workflows/doc-validator.yml
.github/workflows/metrics-collector.yml
.github/workflows/milestoned_to_project.yml

update app token

---

.drone/drone.yml
.github/workflows/ci.yml

**What this PR does**: remove requiring token for vendor-check
**Checklist**

Remove requiring github token for vendor-check

---

.drone/drone.yml

Fix variable names in drone

---

.drone/drone.yml

Typo in drone.yml

---

.drone/drone.jsonnet
.drone/drone.yml

Drone Signature 

---

.drone/drone.jsonnet
.drone/drone.yml

drone typo dashes not underscores

---

.drone/drone.jsonnet
.drone/drone.yml

Drone configs changes

---

.github/workflows/backport.yml
.github/workflows/dependabot_serverless_gomod.yml
.github/workflows/doc-validator.yml

remove app-id logic from forked repo CI actions

---

.github/workflows/backport.yml
.github/workflows/doc-validator.yml
docs/sources/tempo/api_docs/metrics-summary.md

Doc validator token

---

CHANGELOG.md
tempodb/tempodb.go

Change the log level for log in the tempoDB after searching for a trace from INFO to DEBUG
Fixes #4105 
**Checklist**

fix(logs): change log level of log of Find method in tempodb

---

CHANGELOG.md

Backport 44d38686b54e951ba06f8885238684502a215bba from #4187

[release-v2.6] Changelog v2.6.1

---

docs/sources/tempo/release-notes/v2-6.md

Adds the 2.6.1 changelog to the 2.6 release notes. 
**Checklist**

[DOC] Add 2.6.1 to release notes

---

.drone/drone.jsonnet
.drone/drone.yml

Fix the release process by uploading the binaries to GitHub
#4194 
**Checklist**

fix: create a GitHub token for the release process

---

.drone/drone.jsonnet
.drone/drone.yml

Use gcr secret for pulling image during the release process

drone: use gcr secret for pulling image

---

.drone/drone.jsonnet
.drone/drone.yml

Backport 551bd0d9571f38cad85e8405760e7346b6a2c2a4 from #4195
---
Fix the release process by uploading the binaries to GitHub
#4194 
**Checklist**

[release-v2.6] fix: create a GitHub token for the release process

---

docs/sources/tempo/setup/upgrade.md

Adds the breaking change from 2.6.1 to the Upgrade page. 
**Checklist**

[DOC] Add 2.6.1 breaking change to Upgrade page

---

.github/workflows/drone-signature-check.yml

Add a GitHub workflow that checks the signature of drone config file when the config file changes. The workflow will fail if the current signature does not match the expected one.

[EngHub] Add "Drone Signature Check" workflow

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Update CODEOWNERS, GOVERNANCE and MAINTAINERS to reflect new username and name.
**Checklist**

Update name and username Yuna

---

modules/generator/registry/counter.go
modules/generator/registry/gauge.go

Here we continue pre-allocating the labels for the registry to reduce memory allocations. This is a follow-on to https://github.com/grafana/tempo/pull/4232, https://github.com/grafana/tempo/pull/4244 and https://github.com/grafana/tempo/pull/4261.
**Checklist**

Further reduce Labes() calls in the metrics registry

---

docs/sources/tempo/api_docs/metrics-summary.md

Adds additional details to the metrics-summary.md page from [this comment](https://github.com/grafana/tempo/pull/4193#issuecomment-2462441907).
**Checklist**

[DOC] Add clarification for metrics summary and traceQL metrics

---

modules/frontend/metrics_query_range_sharder.go

The previous PR #4325 introduced a bug where queries at your max time range would incorrectly fail.  This is because the request alignment behavior changed, and it could align it to max+1 more step interval.   This isn't the responsibility of the caller to account for, so this swaps the order of validation and alignment in the frontend.  Reviewing this code again, I think is the correct approach all along.  Checking things after alignment only works if the time range is perfectly divisible by step, so that the time range doesn't increase after alignment.  Currently it doesn't have to be.
**Checklist**

Fix incorrect query error when querying at max metrics time range

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Adds a Configure TLS section to the Helm chart doc. 
Part of #4326 
**Checklist**

[DOC] Add TLS info to Helm chart doc

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go

Adds more unit tests to the block-builder module, including the failure modes: failed commits, failed flushes and receiving old records.

Add more failure modes to the block-builder

---

docs/sources/tempo/traceql/_index.md

Fix minor typo in TraceQL docs

Fix minor typo in TraceQL docs

---

operations/jsonnet-compiled/StatefulSet-memcached.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/config.libsonnet

Here we keep use the latest memcached version as default in jsonnet.
**Checklist**

Bump default memcached version

---

tempodb/blocklist/poller_test.go

Add some benchmarks for later use.
**Checklist**

Improve poller benchmarks for later use

---

modules/blockbuilder/partition_writer.go

Correctly pass start/end time when appending a trace
**Checklist**

[rhythm] Correctly pass start/end time when appending a trace

---

docs/sources/tempo/configuration/grafana-alloy/tail-based-sampling.md

Add additional information about tail-based sampling. 
**Checklist**

[DOC] Add tail-based sampling doc

---

cmd/tempo/app/modules.go

Small internal change to how the memberlist config is handled. This makes it possible to add additional codecs downstream.
**Checklist**

Init memberlist codecs: append to preconfigured codecs if any

---

.github/workflows/add-to-docs-project.yml
.github/workflows/backport.yml
.github/workflows/ci.yml
.github/workflows/dependabot_serverless_gomod.yml
.github/workflows/doc-validator.yml
.github/workflows/metrics-collector.yml
.github/workflows/milestoned_to_project.yml
.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml
.github/workflows/sbom-report.yml
.github/workflows/stale.yml
.github/workflows/update-make-docs.yml

Until now we were using ubuntu-latest, which will automatically start using ubuntu 24.04 soon. With this we make it explicit and controlled.
**Checklist**

Update Github Actions to Ubuntu 24.04

---

.github/workflows/docker-ci-tools.yml
build/tools.mk

Update tools image in the Makefile to prove that the new build workflow works.
**Checklist**

Update tools image in the Makefile

---

.drone/drone.jsonnet
.drone/drone.yml

drone: remove serverless pipeline

---

CHANGELOG.md
cmd/tempo-cli/Dockerfile
cmd/tempo-query/Dockerfile
cmd/tempo-serverless/cloud-run/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile
cmd/tempo/Dockerfile_debug

Resolves [CVE-2024-9143](https://nvd.nist.gov/vuln/detail/CVE-2024-9143)
```
grafana/tempo:latest (alpine 3.20.3)
Total: 2 (UNKNOWN: 0, LOW: 2, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
┌────────────┬───────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                           │
├────────────┼───────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2024-9143 │ LOW      │ fixed  │ 3.3.2-r0          │ 3.3.2-r1      │ openssl: Low-level invalid GF(2^m) parameters lead to OOB │
│ …
```

Bump alpine base image to 3.21

---

docs/sources/tempo/metrics-generator/_index.md
docs/sources/tempo/metrics-generator/multitenancy.md

Adds documentation for multitenancy support in the metrics-generator
Fixes https://github.com/grafana/tempo-squad/issues/365
**Checklist**

Add docs for multitenancy support in the metrics-generator

---

CHANGELOG.md

Cuts the changelog for v2.7.0-rc.0

Changelog v2.7.0-rc.0

---

.github/workflows/docker.yml

fix trailing space that made the docker command fail
**Checklist**

Fix trailing space in workflow command

---

.github/workflows/docker.yml

Add docker manifest creation in the workflow

---

.github/workflows/release.yml

Fix release workflow conditional so it doesn't run on PR

---

docs/sources/tempo/setup/upgrade.md

Remove an extra period in the 2.7 heading. 
**Checklist**

[DOC] Fix typo in Upgrade doc

---

modules/blockbuilder/blockbuilder.go

If a partial error is received, it's passed as part of the response. So, that needs to be checked as well.

[rhythm] Handle commit partial errors

---

operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/dashboards/tempo-writes.libsonnet

Fixes the writes dash to render correctly when using an Envoy sidecar.

Ops: Fix envoy writes dash

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md

Adds more documentation for the gRPC compression change to increase the change's visibility. 
Fixes #4606 
**Checklist**

[DOC] Update gRPC compression documentation

---

modules/distributor/distributor.go

* Wrap the Prometheus registry so native Kafka metrics are prefixed with `tempo_distributor_`
* Add partition label to `tempo_distributor_kafka_write_bytes_total`

[rhythm] Improve distributor kafka metrics

---

docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md

Add an example of search with arrays to the TraceQL doc. 
**Checklist**

[DOC] Updated TraceQL doc with an example for arrays

---

CHANGELOG.md
build/tools.mk
go.mod
modules/frontend/queue/queue_test.go
pkg/api/http.go

Continues https://github.com/grafana/tempo/pull/4685
1. Update go to v1.24.0
2. Use new version on linter image that supports go1.24
3. Minor fixes for go update
**Checklist**

Update go to v1.24.0

---

operations/tempo-mixin/runbook.md

Remove outdated info from the runbook

---

example/nomad/tempo-distributed/config.yml
example/nomad/tempo-distributed/tempo.hcl
example/nomad/tempo-monolith/tempo.hcl

- This PR bumps nomad examples to tempo image v2.7.1
**Checklist**

Nomad example bump version to 2.7.1

---

modules/distributor/distributor.go

Adds shuffle sharding to writes to Kafka. It reusese the `ingestion` override used for writing to ingesters.

[rhythm] Add shuffle sharding

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go

Backport #4744 to r189
**Checklist**

Backport #4744 to r189

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/frontend/traceid_handlers.go

update changelog entry, docs and add log `request_throughput` and  `inspected_bytes`
follow up on https://github.com/grafana/tempo/pull/4668.
**Checklist**

Log inspected bytes for trace by id results

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Proposal to make @carles-grafana a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/carles-grafana)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Acarles-grafana)
@grafana/tempo

Carles Garcia proposed as Tempo maintainer

---

modules/frontend/traceid_handlers.go

Log inspected bytes for trace by id V2 results

---

CHANGELOG.md
build/tools.mk
go.mod

chore: upgrade go version to 1.24.1

---

README.md
docs/sources/tempo/traceql/_index.md

Replaces Explore Traces with Traces Drilldown in the docs
**Checklist**

Update Explore Traces to Traces Drilldown in docs

---

CHANGELOG.md

Fix old changelog entry

---

README.md
docs/sources/tempo/api_docs/pushing-spans-with-http.md
docs/sources/tempo/configuration/grafana-agent/_index.md
docs/sources/tempo/configuration/grafana-agent/automatic-logging.md
docs/sources/tempo/configuration/grafana-agent/service-graphs.md
docs/sources/tempo/configuration/grafana-agent/tail-based-sampling.md
docs/sources/tempo/configuration/grafana-alloy/_index.md
docs/sources/tempo/configuration/grafana-alloy/automatic-logging.md
docs/sources/tempo/configuration/grafana-alloy/service-graphs.md
docs/sources/tempo/configuration/grafana-alloy/tail-sampling/_index.md
docs/sources/tempo/configuration/grafana-alloy/tail-sampling/enable-tail-sampling.md
docs/sources/tempo/configuration/network/tls.md
docs/sources/tempo/getting-started/_index.md
docs/sources/tempo/getting-started/docker-example.md
docs/sources/tempo/getting-started/example-demo-app.md
docs/sources/tempo/introduction/_index.md
docs/sources/tempo/release-notes/v2-4.md
docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/setup/operator/multitenancy.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md
docs/sources/tempo/traceql/architecture.md

Fixes broken links in Tempo docs. 
Fixes https://github.com/grafana/tempo/issues/4826
**Checklist**

[DOC] Fix broken links in Tempo doc

---

pkg/ingest/writer_client.go

We support both propagators in Tempo https://github.com/grafana/tempo/blob/main/cmd/tempo/main.go#L261

[rhythm] Add baggage propagator to ingest pkg

---

example/docker-compose/alloy/docker-compose.yaml
example/docker-compose/alloy/readme.md
example/docker-compose/cross-cluster/docker-compose.yaml
example/docker-compose/debug/docker-compose.yaml
example/docker-compose/distributed/docker-compose.yaml
example/docker-compose/ingest-storage/docker-compose.yaml
example/docker-compose/local/docker-compose.yaml
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/otel-collector/docker-compose.yaml
example/docker-compose/scalable-single-binary/docker-compose.yaml
example/helm/microservices-extras.yaml
example/helm/single-binary-extras.yaml
example/tk/lib/synthetic-load-generator/main.libsonnet

Update images for grafana and xk6-client-tracing in examples
**Checklist**

Update example images

---

README.md

Fix link title typo in README

---

CHANGELOG.md

Updates the changelog for 2.7.2

Changelog 2.7.2

---

docs/sources/tempo/release-notes/v2-7.md

Creates release notes for 2.7.2.
**Checklist**

[DOC] Create release notes for 2.7.2

---

operations/jsonnet-compiled/ConfigMap-tempo-backend-scheduler.yaml
operations/jsonnet-compiled/ConfigMap-tempo-backend-worker.yaml
operations/jsonnet-compiled/Service-backend-scheduler.yaml
operations/jsonnet-compiled/Service-backend-worker.yaml
operations/jsonnet-compiled/StatefulSet-backend-scheduler.yaml
operations/jsonnet-compiled/StatefulSet-backend-worker.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json

Jsonnet introduced in https://github.com/grafana/tempo/pull/4770.
**Checklist**

Generate compiled jsonnet of backend worker and scheduler

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

**What this PR does**: Update documentation for helm once this [helm PR](https://github.com/grafana/helm-charts/pull/3563) is merged. 
**Checklist**

Update helm documentation for overrides

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go

Updates query range error message to be simpler / more human readable.
Follow up from https://github.com/grafana/grafana/pull/102809
Fixes https://github.com/grafana/traces-drilldown/issues/378
**Checklist**

Update query range error message

---

integration/e2e/limits_test.go

It fixes a flaky test by checking that eventually we hit the limit
**Checklist**

fix: check that eventually it returns an error when the trace is flushed

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go

Adds tracing to the block-builder
**Checklist**

[rhythm] Add tracing to block-builder

---

operations/tempo-mixin-compiled/dashboards/tempo-block-builder.json
operations/tempo-mixin/dashboards.libsonnet
operations/tempo-mixin/dashboards/dashboard-utils.libsonnet
operations/tempo-mixin/dashboards/tempo-block-builder.libsonnet

It adds a new dashboard for Tempo blockbuilder
**Checklist**

chore: add tempo block-builder dashboard to tempo-mixin

---

CHANGELOG.md
modules/frontend/handler.go

chore: query-frontend logs add msg

---

cmd/tempo-vulture/main_test.go

Fixes flaky test by increasing ticker time
**Checklist**

Vulture: fix flaky test

---

modules/querier/querier_query_range.go

noticed this duplicate code while working on https://github.com/grafana/tempo/pull/4646, so sending this standalone PR to cleanup this code.
no change log entry as this is an internal cleanup, just made it's own PR to keep https://github.com/grafana/tempo/pull/4646 clean.
**Checklist**

metrics: cleanup duplicate code in QueryRange endpoint

---

modules/distributor/distributor.go

Updated the distributor to properly handle errors when writing to Kafka. Now returns the error instead of just logging it.
**Checklist**

[rhythm] Handle Kafka producer error in distributor

---

CHANGELOG.md
integration/e2e/api/query_plugin_test.go

It fixes flaky tests in `query_plugin_test.go`
**Checklist**

chore: fix flaky tests in query_plugin

---

.github/workflows/backport.yml
.github/workflows/metrics-collector.yml
.github/workflows/milestoned_to_project.yml

Trying to fix failures in backport workflow, I am not 100% sure why it fails so trying to update the workflow and see if that fixes it.
my current suspect is the failures are due to templating issue, so formatting the template variables correctly
**Checklist**

github: update and pin create-github-app-token in backport action

---

.github/workflows/backport.yml

workflow started breaking after upgrade, so let's see if downgrade to v1.12.0 fixes it? 🤞🏼 
**Checklist**

github: downgrade actions/create-github-app-token to v1.12.0

---

modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/tenant_store_test.go
modules/frontend/search_sharder_test.go
tempodb/tempodb.go

Fix race condition in WaitGroup, add function for tests to synchronously poll the blocklist.
**Checklist**

[Rhythm] Attempt to fix flakey block builder tests

---

cmd/tempo-cli/cmd-rewrite-blocks.go

Here we make an adjustment to the drop-traces CLI command to improve the discovery process for which blocks need to be rewritten.  Previously, we would open each block for each trace ID passed and specifically request to drop those trace IDs from the block.  However, I beleive it is enough to find any block ID which has any of the trace IDs and rewrite them all.  Since we know we will be opening each of the matching blocks, we can just skip each traced passed, regardless of if we know it to be present in the block or not.
**Checklist**

[tempo-cli] Improve discovery speed when dropping multiple traces

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
modules/frontend/config.go

setting the default max series to 0 to disable limiting

---

docs/sources/tempo/configuration/manifest.md
modules/backendscheduler/backendscheduler.go
modules/backendscheduler/config.go
modules/backendscheduler/provider/compaction.go
modules/backendscheduler/work/job.go
modules/backendscheduler/work/job_test.go

Tighten up the compaction loops to avoid dead spots

---

integration/e2e/api/config-query-range-max-series-disabled-querier.yaml
integration/e2e/api/config-query-range-max-series-disabled.yaml
integration/e2e/api/query_range_test.go
modules/querier/querier_query_range.go

[bugfix] fix bug when max size is set to zero

---

CHANGELOG.md
modules/overrides/config_legacy.go
modules/overrides/config_test.go

This PR contains two changes:
1) Correctly handles conversion of ingestion_artificial_delay field between config formats
2) Fixes other conversion issues and adds comprehensive conversion tests
**Checklist**

Fix artificial delay override

---

docs/sources/tempo/shared/tempo-in-grafana.md

Changes one occurance of Explore apps to Drilldown apps
Related to https://github.com/grafana/traces-drilldown/issues/270
**Checklist**

Change Explore Traces to Traces Drilldown

---

cmd/tempo-cli/cmd-rewrite-blocks.go

Fix the log formatting for the go-kit logger.
**Checklist**

[tempo-cli] Fix rewrite-traces logger

---

CHANGELOG.md
operations/tempo-mixin-compiled/dashboards/tempo-resources.json
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/dashboards/tempo-resources.libsonnet

It adds a Memcached panel to the resources dashboard
**Checklist**

feat: add memcached to the resources dashboard

---

.github/workflows/backport.yml
.github/workflows/ci.yml
.github/workflows/docker-ci-tools.yml
.github/workflows/docker.yml
.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml
.github/workflows/release.yml
.github/workflows/sbom-report.yml
.github/workflows/update-make-docs.yml

- pin actions workflows
- removes use of `pull_request_target` with `pull_request`
PS: this breaks backport workflow, will be fixed in follow up PR
**Checklist**

tempo: follow github actions security best practices

---

.github/workflows/release.yml
.github/workflows/stale.yml

[chore] remove high level zizmor risks

---

.github/workflows/backport.yml
.github/workflows/docker.yml
.github/workflows/metrics-collector.yml
.github/workflows/milestoned_to_project.yml

[chore] get github app secrets from vault

---

.github/workflows/docker.yml
.github/workflows/release.yml

[chore] update get vaults secrets version

---

docs/sources/tempo/getting-started/instrumentation.md

Fix a broken link in the instrumentation doc. 
Fixes https://github.com/grafana/tempo/issues/5024
**Checklist**

Fix broken link to OTel go examples

---

CHANGELOG.md
go.mod
tools/Dockerfile
tools/go.mod

Fixes #[5040](https://github.com/grafana/tempo/issues/5040)
**Checklist**

Update tools to use go version 1.24.2

---

modules/generator/instance.go
modules/generator/processor/hostinfo/processor.go

Enables host info processor
See #4698

enable host info metrics generator processor

---

example/docker-compose/alloy/docker-compose.yaml
example/docker-compose/alloy/readme.md
example/docker-compose/local/docker-compose.yaml
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml

examples: update grafana and memcached images

---

CHANGELOG.md

Reorder/cleanup the changelog to prepare for 2.8.0-rc.0

Tempo 2.8-rc.0 changelog

---

.github/workflows/docker.yml
.github/workflows/release.yml

Cherry picks: https://github.com/grafana/tempo/commit/dfc430c16bdb3000f6728355a14b62b7325871a8

Tempo 2.8: Cherry Pick CI Fix

---

.github/workflows/release.yml

Missed a --force param

---

.github/workflows/release.yml

The release process needs to be able to post new releases. Adding permissions.

Fix token perms

---

.github/workflows/backport.yml
.github/workflows/metrics-collector.yml

more permission fixes for github actions workflows.
**Checklist**

ci: fix metrics-collector and backport workflows

---

modules/backendscheduler/cache.go

This will allow some debug about why flushes failed.
**Checklist**

[backendscheduler] log failed flush errors

---

docs/sources/tempo/configuration/grafana-agent/tail-based-sampling.md
docs/sources/tempo/release-notes/v2-8.md
docs/sources/tempo/setup/command-line-flags.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md

Fix broken links introduced in the 2.8 update. 
Fixes https://github.com/grafana/tempo/issues/5263
**Checklist**

[DOC] Fix links for 2.8 release

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/anonymous-usage-reporting.md
docs/sources/tempo/configuration/usage-tracker.md
docs/sources/tempo/release-notes/v1-5.md

Backport #5265 anonymous usage reporting doc to 2.8 release
Fixes #<issue number
**Checklist**

[release-v2.8][DOC]  Backport doc 5265 anonymous usage

---

tools/Dockerfile
tools/go.mod

This is the first PR (out of 2) to update Go to 1.24.4
The changelog update will be part of the second PR
Fixes the following CVEs
* CVE-2025-22874 (high)
* CVE-2025-4673 (medium)
* CVE-2025-0913 (medium)
**Checklist**

Update go to 1.24.4 (Part 1, tools)

---

operations/tempo-mixin-compiled/dashboards/tempo-backendwork.json
operations/tempo-mixin/dashboards/tempo-backendwork.json

Updates the tempo-mixin for the backend dashbaord:
* include request/latency panels
* fix several queries to include $cluster
**Checklist**

[tempo-mixin] Update backendwork dashboard

---

.github/workflows/ci.yml
Makefile
integration/backendscheduler/backendscheduler_test.go
integration/backendscheduler/config.yaml
modules/backendscheduler/backendscheduler_test.go

Here we include some integration tests for the `backend-scheduler` component, and put them into CI.  These tests check the metric state of the scheduler, based on the work in the system at various points of operation against a set of expectations.
**Checklist**

Backend scheduler tests

---

operations/jsonnet-compiled/StatefulSet-memcached.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/memcached/memcached.libsonnet

Another change to the memchached jsonnet means we need to update here for CI to pass in other unrelated PRs.
**Checklist**

[tempo-mixin] run make jsonnet

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Proposal to make @ruslan-mikhailov a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/ruslan-mikhailov)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aruslan-mikhailov)
@grafana/tempo

Ruslan Mikhailov maintainer

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/grafana-alloy/tail-sampling/_index.md
docs/sources/tempo/configuration/grafana-alloy/tail-sampling/enable-tail-sampling.md
docs/sources/tempo/configuration/grafana-alloy/tail-sampling/policies-strategies.md
docs/sources/tempo/setup/linux.md
docs/sources/tempo/troubleshooting/out-of-memory-errors.md

Backports these PRs to v2.8: 
#5213 
#5345 
#5367 
#5294 
**Checklist**
* Apply suggestions from code review

[release-v2.8][DOC] Backport doc PRs 5213, 5345, 5367, 5294 (incl. tail sampling) 

---

integration/backendscheduler/backendscheduler_test.go

The backend-scheduler integration tests have been throwing false positives in CI.  Here we broaden our expectations while still confirming the integrity of the system.
**Checklist**

Update backend-scheduler integration tests to allow for more variance

---

modules/backendscheduler/backendscheduler.go

**What this PR does**: ignore blocks with nocompact flag in backend scheduler
Fixes https://github.com/grafana/tempo/pull/5390#discussion_r2228928185
**Checklist**

[Rhythm] Scheduler: ignore blocks with nocompact flag

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
integration/e2e/api/query_range_test.go
modules/frontend/config.go
modules/frontend/metrics_query_range_handler.go
operations/jsonnet-compiled/util/jsonnetfile.lock.json

It checks if step is too small and generates too many time series
**Checklist**

Step validation

---

docs/sources/tempo/configuration/_index.md

Documents the value of TTL under memcached section of cache
Fixes #5175
**Checklist**

[docs]: document usage of ttl in memchaed config under cache section

---

example/docker-compose/alloy/readme.md

Replaces Agent with Alloy in the title for the Alloy docker compose readme.md
**Checklist**

Update Agent to Alloy in example readme

---

tools/Dockerfile
tools/go.mod

It upgrades tempo tools to go 1.25.0
**Checklist**

chore: upgrade tempo tools

---

pkg/parquetquery/pool_test.go

To avoid data leakage
**Checklist**

tempo: add test to ensure ResultPool is cleaned properly

---

modules/backendscheduler/work/job.go

As a follow up to #5379, we replace `sync.RWMutex` with `sync.Mutex` on `Job`.
**Checklist**

Switch job from sync.RWMutex to sync.Mutex

---

tempodb/encoding/vparquet5/block_traceql.go
tempodb/encoding/vparquet5/block_traceql_pool_test.go

To ensure data is cleaned and not leaked.
**Checklist**

tempo: add tests for vparquet pools

---

docs/sources/tempo/troubleshooting/querying/too-many-requests-error.md

It adds a new page to document an error querying traces 
**Checklist**

docs: add documentation about how to solve too many requests error
