grafana/tempo

docs/tempo/website/getting-started/_index.md
Small nit: the `grafana/agent` repo's project name should be "Grafana Cloud Agent."
=> Change "Grafana Agent" to "Grafana Cloud Agent"

.github/workflows/metrics-collector.yml
This adds a metric collector github action that sends metrics to a grafana cloud graphite instance: 
We use it for Grafana for this dashboard:
https://play.grafana.org/d/aw0AkS5Gz/grafana-issue-triage?orgId=1 
This just adds the basic metrics like stars, forks, open issue count etc. 
You can then add custom github queries to get a trending for how different issue counts change with time (like open PRs, bugs issues with no label).
https://github.com/grafana/grafana/blob/master/.github/metrics-collector.json 
The code for this action is here:
https://github.com/grafana/grafana-github-actions 
Can see that the GH_BOT_ACCESS_TOKEN secret is already added to this repo, will add another one for the GRAFANA_MISC_STATS_API_KEY
=> Stats: Adding GitHub action to collect GitHub repo & issue stats

operations/tempo-mixin/README.md, operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/tempo-operational.json
The Tempo Operational dashboard is a big dumb overly complex dashboard that I love.
This dashboard requires Loki for annotations and promtail for the bad words.  It's quite possible it just doesn't work in your environment without a fair amount of tweaking.
I am PRing it to this repo for 2 reasons:
1) It provides a stack of metrics for other operators to consider monitoring while running Tempo.
2) We want it in our internal infrastructure and we vendor the tempo-mixin to do this.
=> Add Tempo Operational dashboard

.github/workflows/ci.yml
Disables vendor check.  It is currently failing all PRs with the following diffs:
go.mod
```
-	google.golang.org/genproto v0.0.0-20201022181438-0ff5f38871d5 // indirect
+	google.golang.org/genproto v0.0.0-20201026171402-d4b8fe4fd877 // indirect
```
go.sum
```
-google.golang.org/genproto v0.0.0-20201022181438-0ff5f38871d5 h1:YejJbGvoWsTXHab4OKNrzk27Dr7s4lPLnewbHue1+gM=
-google.golang.org/genproto v0.0.0-20201022181438-0ff5f38871d5/go.mod h1:FWY/as6DDZQgahTzZj3fqbO1CbirC29ZNUFHwi0/+no=
+google.golang.org/genproto v0.0.0-20201026171402-d4b8fe4fd877 h1:d4k3uIU763E31Rk4UZPA47oOoBymMsDImV3U4mGhX9E=
+google.golang.org/genproto v0.0.0-20201026171402-d4b8fe4fd877/go.mod h1:FWY/as6DDZQgahTzZj3fqbO1CbirC29ZNUFHwi0/+no=
```
cc @annanay25 please look into why this is failing …
=> Disable Vendor Check

docs/README.md
This PR adds a small readme on the docs folder. Explains link behavior. I used the same structure as [Loki](https://github.com/grafana/loki/blob/master/docs/README.md).
=> Add README to docs folder

CHANGELOG.md, cmd/tempo/app/app.go, cmd/tempo/main.go
Warns the user if the configuration looks strange.
Fixes #244
**Checklist**
=> Add warnings for suspect configurations

cmd/tempo-cli/main.go
Adds local backend support to tempo-cli. After following up with the discussions made #236 and #281 I thought it would be nice to have the local backend support so it would be easier to fiddle around.
Example:
```
bin/tempo-cli -backend=local -bucket=<absolute-path or relative path>/example-data/tempo \
-tenant-id=single-tenant -block-id e0ff6495-6d13-4c0e-a704-938384a9dcac
```
It uses the bucket option as the path to the local backend.
=> add local backend to cli

CHANGELOG.md, cmd/tempo-vulture/main.go, pkg/util/errors.go, pkg/util/query.go
This PR adds some things:
- Return a `not found error` in case we don't find the traceID.
- Increase Prometheus not found metric on tempo-vulture.
I'm not a Go expert, but this approach seemed "reasonable" :smile:
Fixes #286
**Checklist**
=>  Increase Prometheus not found metric on tempo-vulture

CHANGELOG.md, modules/storage/config.go
Support setting s3 credentials with command line flags by adding the flags `storage.trace.s3.access_key` and `storage.trace.s3.secret_key`.
Fixes #308
=> command line flags for s3 credentials

operations/helm/tempo-microservices/templates/deployment-querier.yaml, operations/helm/tempo-single-binary/templates/statefulset.yaml, operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/single-binary/tempo.libsonnet, operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/out/tempo-reads.json
- Exposes port 16687 to allow scraping of Jaeger-Query metrics
- Adds Jaeger Query metrics to the Tempo Reads dashboard
Fixes #None
**Checklist**
=> Expose jaeger metrics

CHANGELOG.md, cmd/tempo/app/app.go, docs/tempo/website/configuration/_index.md, integration/e2e/config-all-in-one.yaml, integration/e2e/config-microservices.yaml, modules/ingester/config.go, modules/storage/config.go, operations/helm/tempo-microservices/templates/configmap-tempo-compactor.yaml, operations/helm/tempo-microservices/templates/configmap-tempo-querier.yaml, operations/helm/tempo-microservices/templates/configmap-tempo.yaml, operations/jsonnet/microservices/configmap.libsonnet, tempodb/compactor.go, tempodb/compactor_bookmark_test.go, tempodb/compactor_test.go, tempodb/config.go, tempodb/tempodb.go, tempodb/tempodb_test.go
Renames maintenance cycle to blocklist poll as proposed on https://github.com/grafana/tempo/pull/195#discussion_r498038769
- s/MaintenanceCycle/BlocklistPoll/
- s/maintenance_cycle/blocklist_poll/
- s/DefaultMaintenanceCycle/DefaultBlocklistPoll/
Fixes #198
**Checklist**
=> Rename maintenance cycle to blocklist poll

cmd/tempo/app/app.go
- Cleans up some verbiage for the config warnings
- Removes a mysterious 3
**Checklist**
=> Config warning cleanup

.github/workflows/ci.yml, Makefile, vendor/github.com/open-telemetry/opentelemetry-proto/gen/go/collector/metrics/v1/metrics_service.pb.gw.go, vendor/github.com/open-telemetry/opentelemetry-proto/gen/go/collector/trace/v1/trace_service.pb.gw.go
`vendor-check` in the CI was failing every time a dependency needed an upgrade (frequently!). This was because we didn't have a version lock in, and hence vendor check had been disabled meanwhile.
This PR uses the `otel/build-protobuf:0.1.0` image to generate protos. CI workflow has been updated to reuse the check.
Fixes NA
**Checklist**
=> Use docker image to generate opentelemetry proto files 

CHANGELOG.md, tempodb/tempodb.go, tempodb/tempodb_test.go
People are seeing this in the beta, so I felt like we should just fix it.  I don't see a reason to distinguish between asking for a tenant that does not exist and asking for a trace that does not exist so just returned nil if the tenant was not found.
Fixes #94 
**Checklist**
=> Return 404 on unknown tenant

example/docker-compose/docker-compose.loki.yaml, example/docker-compose/docker-compose.s3.minio.yaml, example/docker-compose/docker-compose.yaml
Tempo query crashes when it starts before Tempo. I added a `depends` condition to the docker-compose examples.
**Checklist**
=> Add depends to docker-compose examples

CHANGELOG.md, cmd/tempo/app/app.go, docs/tempo/website/configuration/_index.md, example/docker-compose/etc/tempo-s3-minio.yaml, modules/compactor/config.go, tempodb/compactor.go, tempodb/config.go, tempodb/wal/compactor_block.go
Changes the compactor to flush partial blocks to the backend based on buffered data size instead of trace count. The default is 30MB.   This ensures that at least 5MB of data can be buffered for the S3 parts, and should work well without tuning across most cases, no matter if traces are large or small.   Exposed as configuration option flush_size_bytes.  The default value allows for a maximum block size of 300GB (10,000 parts maximum).
Fixes #306 
**Checklist**
=> #306 - Compactor flush to backend based on buffer size

CHANGELOG.md, tempodb/tempodb.go, tempodb/tempodb_test.go
If a tenant disappears blocks are pruned from the in-memory blocklist.
Fixes #285
**Checklist**
=> Prune in-memory blocks from missing tenants

docs/tempo/website/getting-started/_index.md
In the getting started guide the docker command used "$(PWD)" to get the
working directory. That works in macOS (zsh), but doesn't work in bash
for example.
Examples on the docker site uses $(pwd), so this changes to lower case.
E.g. https://docs.docker.com/storage/volumes/#backup-a-container
Updates examples in documentation to work in bash.
N/A
**Checklist**
=> docs: fix examples in getting-started documentation

CHANGELOG.md, modules/ingester/instance.go
This PR adds a `per tenant bytes counter` metric. I went with the distributor approach!
The metric is increased when we cut the complete traces.
Fixes #223
**Checklist**
=> Add per tenant bytes counter

.drone.yml
Adds the targetarch build arg so our drone builds will work again.  This was broken in #311 when multi arch support was added.
=> Added build arg so drone will build

.gitignore, CHANGELOG.md, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/tempodb.go, tempodb/tempodb_test.go
The compactor can log frequent errors like the following:  `msg="unable to find meta during compaction.  trying again on this block list"`. The root cause seems to be that when a block is compacted, it is updated in the storage backend, but not in the in-memory blocklist until the next polling cycle.  This causes the stale entry to be considered for compaction on subsequent runs, causing the errors for several minutes (based on default timings). 
This PR updates the compactor to immediately update the in-memory blocklist to be aware of changes it makes:  add the new blocks created during compaction, move the old ones to the compacted section.  The changes are temporary and get overwritten during the next poll cycle, but are still helpful to cut down on the noise, …
=> Address frequent errors logged by compactor regarding meta not found

tempodb/retention.go, tempodb/retention_test.go, tempodb/tempodb.go, tempodb/tempodb_test.go
Introduce sharding by block ID in the retention logic so that compactors don't work on the same blocks.  We could also shard by tenantID (meaning 1 compactor would perform all retention for the tenant), but at the risk of less evenly distributed work.  
This PR also moves retention to a separate file.
Fixes #330
**Checklist**
=> Shard retention to eliminate contention

CHANGELOG.md, tempodb/backend/diskcache/disk_cache.go, tempodb/wal/wal.go
This PR changes `path.Join` to `filepath.Join` in:
- tempodb/backend/diskcache/disk_cache.go
- tempodb/wal/wal.go
Fixes #136
**Checklist**
=> From path.Join to filepath.Join

CHANGELOG.md, go.mod, operations/tempo-mixin/tempo-operational.json, tempodb/compactor.go, tempodb/compactor_test.go, vendor/modules.txt
Adds a new metric counter (compaction_objects_combined_total) for when traces are combined during compaction (parts of trace split across blocks).  This metric will help investigation into #216 
n/a
**Checklist**
=> Add new compactor_objects_combined metric and test

CHANGELOG.md, modules/distributor/receiver/shim.go
Removes the `panic()` in ReportFatalError().  This is causing distributors to panic on rollout with a simple "http: Server Closed" message.  Obviously it is intentional that the http server is closed and panic'ing at this point would be silly. 
Fixes #342 
**Checklist**
=> Remove panic in ReportFatalError

.github/workflows/ci.yml, tempodb/compaction_block_selector_test.go
Include tests on the hash string returned by timeWindowBlockSelector. This is to improve test coverage before making changes in this area.
n/a
**Checklist**
=> Include hash string in block selector tests

operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/single-binary/tempo.libsonnet, operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/out/tempo-resources.json
Minor improvements to tempo operational tools
- add resources panel for tempo distributor
- disable tracing on the tempo-query container using `JAEGER_DISABLED=true`
**Checklist**
=> [ops] Fix resources dashboard, disable tempo-query tracing by default

CHANGELOG.md, tempodb/compaction_block_selector.go, tempodb/compaction_block_selector_test.go, tempodb/compactor.go, tempodb/compactor_test.go
Enhance TimeWindowBlockSelector to allow choosing more than 2 blocks in the active window to compact at a time, controllable by parameters.   Hard-coded default values are min=2 (same behavior as before) and max=8.   Blocks outside the active window are compacted using the minimum block count always (same behavior as before).  The min/max parameters are not exposed as configuration values but could be if it makes sense.
Existing tests were updated to specify max=2 to preserve prior behavior as needed.  New test was added for choosing more than 2 blocks.
n/a
**Checklist**
=> Compact more than 2 blocks at a time

CHANGELOG.md, go.mod, go.sum, vendor/github.com/weaveworks/common/middleware/http_tracing.go, vendor/github.com/weaveworks/common/middleware/instrument.go, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
- Updates weaveworks common to get exemplar support.
**Checklist**
=> Updated Weaveworks/common to catch exemplars

cmd/tempo-query/main.go, cmd/tempo-query/tempo/plugin.go, go.mod, modules/querier/querier.go, tempodb/tempodb.go, vendor/modules.txt
Further improvements on query path observability.
- Added tracing to the GRPC plugin.  For some reason context does not propagate from jaeger-query to the plugin, but this additional span still gives us insight into what's happening in the plugin
- Fixed the bytes/query histogram.  It was always capping out.
- Removed the block.Find span.  Agreed with @annanay25 it made the trace harder to read.
**Checklist**
=> Query Path Observability Improvements

CHANGELOG.md, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go
Adds a config option/flag to use signature version 2 in the S3 backend. This will switch from the default V4 auth to a V2, which might be necessary for some object storage implementations.
Fixes #<issue number
**Checklist**
=> feat: add option to S3 backend for V2 signatures

CHANGELOG.md, modules/ingester/flush.go, modules/ingester/ingester.go, modules/ingester/instance.go, pkg/flushqueues/exclusivequeues.go, pkg/flushqueues/exclusivequeues_test.go, pkg/flushqueues/flushqueues.go, pkg/util/test/metrics.go, tempodb/compactor_test.go
Occassionally ingesters fail to flush due to a double queuing (#217) issue discovered by @calvernaz.  This PR looks to fix that by:
- Creating a shim in front of the priority queues `ExclusiveQueues` that prevents multiple items from being queued with the same key
- Adjusting the `flushLoop()` to either call `.Requeue()` or `.ClearKey()` after flush has failed or succeeded
- Consolidated helper methods to extract prometheus metric values to `./pkg/util/test`
- Actually wait for flush queues to clear in `stopping()` eep!
Fixes #217 
**Checklist**
=> Fix Ingesters Occassionally Double Flushing

CODEOWNERS
Adds @achatterjee-grafana as a docs owner which will help her to contribute and review PRs to the docs folder and its subdirs.
=> Add Jita as docs owner

pkg/util/trace.go, pkg/util/trace_test.go
Use bytes.Equal instead of fnv hash to compare inputs in CombineTraces.  Benchmarks show a modest improvement when inputs differ (5-10%), and an extremely large improvement when inputs are identical.
Before:
```
BenchmarkCombineTraces-12             	   13642	     98505 ns/op
BenchmarkCombineTracesIdentical-12    	  184737	      6696 ns/op
```
After
```
BenchmarkCombineTraces-12             	   14634	     91460 ns/op
BenchmarkCombineTracesIdentical-12    	16753951	        76.9 ns/op
```
n/a
**Checklist**
=> Use bytes.Equal instead of hash in CombineTraces

operations/tempo-mixin/tempo-operational.json, tempodb/compactor.go, tempodb/compactor_test.go
Add "level" label to tempodb_compaction_objects_combined_total. Update operational dashboard to match.
n/a
**Checklist**
=> Add level label to tempodb_compaction_objects_combined_total metric

CHANGELOG.md, tempodb/backend/s3/s3.go
Fix S3 backend logs "unsupported value type" 
Fixes #381 
**Checklist**
=> Fix value type

pkg/util/trace.go, pkg/util/trace_test.go
Small optimization to CombineTraceProtos method to reuse hash instead of allocating a new one inside TokenForTraceID. This eliminates ~3 allocations per span.  Benchmarks were added to show effects for trace sizes between 1 and 100K spans.  Increment was also moved out of the loops.
Benchmarks before:
```
$ go test -bench . -benchmem -cpu=1
goos: darwin
goarch: amd64
pkg: github.com/grafana/tempo/pkg/util
BenchmarkCombineTraces                      13558	     98462 ns/op	   79911 B/op	    1724 allocs/op
BenchmarkCombineTracesIdentical          17060538	        79.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkCombineTraceProtos/1            10671867	       119 ns/op	      12 B/op	       3 allocs/op
BenchmarkCombineTraceProtos/10             596056	      2123 …
```
=> Reuse hash in CombineTraceProtos to reduce memory allocations

modules/ingester/instance.go, modules/ingester/instance_test.go
Small optimization to ingester instance.getOrCreateTrace method to reuse hash instead of allocating a new one inside TokenForTraceID. This eliminates 1 allocation per Push.   Basic benchmarks were added:
Before:
```
$ go test -bench . -benchmem
goos: darwin
goarch: amd64
pkg: github.com/grafana/tempo/modules/ingester
BenchmarkInstancePush-12                 	 1817228	       650 ns/op	     197 B/op	       4 allocs/op
BenchmarkInstancePushExistingTrace-12    	 7747898	       152 ns/op	      47 B/op	       1 allocs/op
BenchmarkInstanceFindTraceByID-12        	   90445	     12661 ns/op	   11035 B/op	     209 allocs/op
PASS
ok  	github.com/grafana/tempo/modules/ingester	3.801s
```
After:
```
$ go test -bench . -benchmem       
goos: darwin
goarch: amd64
pkg: …
```
=> Reuse hash in instance.Push to reduce memory allocations

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/out/alerts.yaml, operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/runbook.md
Adds alerts for failed flushes and compactions to the tempo-mixin.
Also regenerated dashboards and alerts.  Dashboards were behind for ?? reasons.
Fixes #Nada
**Checklist**
=> Added failing flushes and compaction alerts

tempodb/wal/complete_block.go
A performance improvement I noticed while reviewing the ingester query path.  A complete block should always have a valid bloom filter so we should test it before bothering to read the index/object file.
=> Test bloom filter before finding in a complete block

tempodb/compaction_block_selector.go, tempodb/compaction_block_selector_test.go
Excludes blocks in the last active time window from compaction. This prevents errors from ownership conflicts where two compactors process the same block at the same time, which can occur at the boundary from active to inactive sharding schemes. 
**Example**: compactor A starts a compaction on data 23:59 ago, and 2 minutes later compactor B starts a compaction on data 24:01 ago.   The same blocks can be chosen by both, and compactor B will experience errors marking the blocks as compacted at the end of compaction.   Additionally the data in the shared blocks will be duplicated into the new blocks.
n/a
**Checklist**
=> Exclude blocks in last active window from compaction

operations/helm/tempo-microservices/templates/configmap-tempo.yaml, operations/jsonnet/microservices/configmap.libsonnet
Our helm and jsonnet deployments configure the ingesters to unnecessarily poll the blocklist.  This is a small cost, but it's unnecessary so let's eliminate it!
**Checklist**
=> Disable polling ingesters

docs/tempo/website/architecture/architecture.md, docs/tempo/website/getting-started/_index.md, docs/tempo/website/getting-started/example-demo-app.md
Previously the markdown links were merging the relative url with the url
of the current page, rather than the base url of the parent folder. E.g.
we were linking to architecture/architecture/consistent-hash-ring instead
of architecture/consistent-hash-ring).
Used relrefs for fixing links instead of modifying the markdown link, as
relrefs will throw errors if the page doesn't exist.
Minor documentation update for broken links and a whitespace. 
Tested with `make docs` and checking the updated links worked locally. Also ran `make docs-test`.
~Fixes #<issue number>~
**Checklist**
~- [ ] Tests updated~
~- [ ] Documentation added~
~- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, …
=> Fix doc links and add space

CHANGELOG.md, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/tempodb.go, tempodb/tempodb_test.go
Changes compactor to iterate through one tenant each cycle, instead of choosing randomly.
Fixes #420 
**Checklist**
=> Iterate through tenants for compaction instead of choosing randomly

CHANGELOG.md, modules/ingester/config.go
Increases the complete block timeout default to be 1 minute greater than the default poll cycle.  This will prevent race conditions where a complete block is removed from an ingester but the querier has not yet repolled the backend blocks.
**Checklist**
=> Increase complete block timeout

tempodb/backend/azure/azure.go, tempodb/backend/azure/compactor.go
Corrects build https://github.com/grafana/tempo/pull/432/checks?check_run_id=1619853512
```
Running [/home/runner/golangci-lint-1.32.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1037: failed prerequisites: [(inspect@github.com/grafana/tempo/tempodb/backend/azure, isgenerated@github.com/grafana/tempo/tempodb/backend/azure): analysis skipped: errors in package: [/home/runner/work/tempo/tempo/tempodb/backend/azure/azure.go:51:67: BlockMeta not declared by package encoding /home/runner/work/tempo/tempo/tempodb/backend/azure/azure.go:76:107: BlockMeta not declared by package encoding /home/runner/work/tempo/tempo/tempodb/backend/azure/azure.go:110:105: BlockMeta not declared by …
```
=> Correct imports

cmd/tempo/app/app.go
Follow up of #400. Skips authentication for internal grpc call `/frontend.Frontend/Process` used between the query worker and frontend, as this is a common call used for all users.
Fixes #NA
**Checklist**
=> Exclude auth for internal grpc calls b/n worker and frontend

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/out/alerts.yaml
Makes the compations and flushes failed per hour to be configurable thresholds instead of the hardcoded value.
Fixes #
**Checklist**
=> Made compactions and flushes failed configurable

operations/tempo-mixin/tempo-operational.json
Fix ingester push latency metric on tempo operational dashboard, that was broken with introduction of new PushBytes method.
Fixes n/a
Related to #430 
**Checklist**
=> Fix ingester push latency metric on operational dashboard

modules/distributor/distributor.go
About 25% of traces are falling into the +Inf bucket for the tempo_distributor_traces_per_batch metric.  This PR doubles the number of buckets, increasing the ceiling from 12 to 27.  It's kind of a guess as to most appropriate buckets, but this is a step in that direction.
n/a
**Checklist**
=> Add more buckets to tempo_distributor_traces_per_batch metric

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet
**What this PR does**: This PR ignores some routes when checking for `TempoRequestLatency` alert. Specifically query-frontend route is designed to be called as long-running request, so we should ignore it.
**Checklist**
- [NA] Tests updated
- [NA] Documentation added
=> Ignore metrics and query-frontend call for latency alert.

modules/distributor/distributor.go
This is a continuation of #439 to increase the bucket range even further, up to 1024.  Testing in internal environment was showing +Inf bucket still receiving a significant amount of traffic and local testing with the synthetic-load-generator was able to produce batches with 300+ traces, which far exceeds the current limit.   
n/a
**Checklist**
=> Increase distributor_traces_per_batch buckets

example/docker-compose/docker-compose.s3.minio.yaml
While experimenting with the local minio example I noticed that Tempo was regularly refusing to start b/c the minio backend was not ready.  First, I attempted to use `depends_on`, but even this was not sufficient to prevent Tempo from failing on startup. 
I am not happy with this fix, but I'm unable to find a better way.
=> Delay tempo start to make sure that minio is running

cmd/tempo-cli/cmd-list-blocks.go, tempodb/backend/azure/azure.go, tempodb/backend/backend.go, tempodb/backend/gcs/gcs.go, tempodb/backend/local/local.go, tempodb/backend/local/local_test.go, tempodb/backend/memcached/cache.go, tempodb/backend/memcached/cache_test.go, tempodb/backend/redis/cache.go, tempodb/backend/redis/cache_test.go, tempodb/backend/s3/compactor.go, tempodb/backend/s3/s3.go, tempodb/backend/util/test.go, tempodb/backend/util/util.go, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/encoding/backend_block.go, tempodb/encoding/backend_block_test.go, tempodb/encoding/block.go, tempodb/encoding/compactor_block.go, tempodb/encoding/compactor_block_test.go, tempodb/encoding/complete_block.go, tempodb/encoding/iterator_backend.go, tempodb/tempodb.go
This started as a smaller PR that has gotten fairly intense.  List of changes
- Refactor of backend.Reader and Writer interfaces to be agnostic to the underlying data layout
- Changes to all backends to match the new interfaces
- Removal of index functionality in the cli (not worth further complication of the BackendBlock interface)
- Minor refactor/simplification of CompactorBlock methods
- Changed s3 backend's ClearBlock method to not be reliant on knowledge of individual objects
- Added BackendBlock interface and used it in tempodb Find method
This is close to being done, but still requires some additional testing.
Fixes #
**Checklist**
=> Additional Backend Refactoring : Versioned Blocks

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/out/alerts.yaml, operations/tempo-mixin/runbook.md
The distributor alert in the mixin does not actually indicate any kind of degraded functionality in Tempo, but rather that something perhaps should be investigated.  Unlike previously thought unhealthy distributors does _not_ impact global rate limiting.
**Checklist**
=> Downgraded the distributor alert to warning

CHANGELOG.md, modules/distributor/distributor.go
Adds `tempo_distributor_bytes_received_total` per tenant.  This metric contains the uncompressed proto bytes received per tenant as a counter.  Previously I had been concerned about the performance impact of this addition, but after @mdisibio 's work in #430 I think this will be fine.
Fixes #410
**Checklist**
=> Added bytes ingested metric per tenant

CHANGELOG.md, modules/ingester/instance.go, modules/ingester/instance_test.go
Ingesters currently show unreasonably high p99's on read and write.  This is likely due to slow appends to the headblock.   Note that under the hood it is [inserting into a slice](https://github.com/grafana/tempo/blob/a7961951f136e323ada598b26f0ff38f34da2174/tempodb/encoding/appender.go#L30).
This PR reduces the time that we lock the active traces map by simply adding them to a linked list.  Then we drop the active traces lock and only lock the blocks while we are adding them to the append block.
**Checklist**
=> Fix Ingester Stutter

CHANGELOG.md, modules/ingester/instance.go
Reduces the locking range on the block mutex during an active traces flush.  This significantly improves Ingester query latency:
I was surprised to not immediately see similar improvement at the query frontend.  However, I did find that the impact of querier scaling is now much more apparent with the ingester fix:
First annotation is the new ingester being deployed.  Second annotation is scaling the queriers to 10.
**Checklist**
=> Fix Ingester Query Latency Spikes

operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/memcached.libsonnet
Made the number of memcached replicas configurable in the tempo-microservices jsonnet.   Was previously hardcoded to 3.
**Checklist**
=> Made memcached replica count configurable

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/runbook.md, tempodb/backend/gcs/gcs.go, tempodb/tempodb.go
- Adds alert and runbook for failure to poll blocklist
- No longer considers it an error if a block does not have a meta or compacted block meta (this was artificially raising failure to poll blocklist)
**Checklist**
=> Add alert for failed polling of the blocklist

tempodb/encoding/complete_block.go
Write the block meta last.  This will prevent components from attempting to access a block that does not yet exist.
=> Write block meta last to prevent bad blocks

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/troubleshooting/_index.md, example/docker-compose/etc/tempo-azure.yaml, example/docker-compose/etc/tempo-gcs-fake.yaml, example/docker-compose/etc/tempo-local.yaml, example/docker-compose/etc/tempo-s3-minio.yaml, integration/bench/config.yaml, integration/e2e/config-all-in-one-azurite.yaml, integration/e2e/config-all-in-one.yaml, integration/e2e/config-microservices.yaml, modules/ingester/config.go, modules/ingester/flush.go, modules/ingester/instance.go, modules/ingester/instance_test.go, tempodb/encoding/common/types.go, tempodb/encoding/v0/appender.go, tempodb/encoding/v0/appender_buffered.go, tempodb/wal/append_block.go
Adds config value and logic to cut ingester headblock based on size.  Default is 1GB.  
Fixes #474 
**Checklist**
=> Add support to cut an active block based on total bytes

docs/tempo/website/guides/pushing-spans-with-http.md
the documentation for how to push traces from the cli, doesnt work this PR fixes this. I also updated the documented link to the jaeger ui to directly go to the trace created in the is example
=> Fixing broken docker run and clarifying direct trace url

operations/tempo-mixin/tempo-operational.json
A few tempo operational dashboard tweaks:
1. goroutines panel use {{pod}} instead of {{job}}.  Job is a constant value like "ingester". Pod is what we want "ingester-nn"
2. Working set panel ignore container=POD, which yields not useful metrics like memory = 3MB.
n/a
**Checklist**
=> A few dashboard tweaks

.github/workflows/bench.yml, .github/workflows/ci.yml
If a PR only changes the contents of the `docs/` folder, there is no need to run the `benchmark` and the `ci` workflows.
I tried it on a private repo, and looks like it's working! Hopefully here will work too.
My tests:
- Change file inside `docs/` -> Workflow skiped.
- Change file outside `docs/` -> Workflow run.
- Change file inside `docs/` and file outside `docs/` -> Workflow run.
This was discussed with @annanay25 on Slack.
**Checklist**
=> Skip workflow runs if the change only affects the docs folder

CHANGELOG.md, docs/tempo/website/configuration/s3.md, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go
Re-add s3 region and add forcepathstyle config options.   Digging deeper, the cortex s3 client does not support multipart uploads which is critical to tempo, therefore it is not the right fit at this time, and stayed with the minio client.
Fixes #431 
**Checklist**
=> Add s3 options region and forcepathstyle

operations/jsonnet/microservices/configmap.libsonnet
The jsonnet for compactors sets the per_tenant_override_file, but doesn't mount the configmap, so it was always pointing to a non-existent file.  Now that compactors read the overrides, they fail since it doesn't exist.   This PR updates the jsonnet to mount it as expected.
n/a
**Checklist**
=> Also mount overrides.yaml for the compactor now that it reads them

operations/tempo-mixin/alerts.libsonnet
Improve 1h alerts by making them multi window queries.  This will allow for the alert to both trigger on the broader pattern as seen over an hour and quickly drop off if bad things stop happening.
=> Add multi window alerts to all 1 hour alerts

CHANGELOG.md, example/docker-compose/etc/tempo-azure.yaml, example/docker-compose/etc/tempo-gcs-fake.yaml, example/docker-compose/etc/tempo-local.yaml, example/docker-compose/etc/tempo-s3-minio.yaml, modules/ingester/ingester_test.go, modules/ingester/instance_test.go, modules/querier/querier_test.go, modules/storage/config.go, tempodb/compactor_bookmark_test.go, tempodb/compactor_test.go, tempodb/encoding/compactor_block.go, tempodb/encoding/compactor_block_test.go, tempodb/encoding/complete_block.go, tempodb/encoding/complete_block_test.go, tempodb/encoding/config.go, tempodb/encoding/v0/appender_buffered.go, tempodb/encoding/v1/appender_buffered.go, tempodb/retention_test.go, tempodb/tempodb_test.go, tempodb/wal/wal_test.go
Changed configuration option `index_downsample` to `index_downsample_bytes`.  Defaulted to 2MB.  Downsampling by bytes instead of traces will give us more consistent and predictable amounts of data to pull from the backend when doing `ReadRange` from blocks.  This will help prevent large traces from creating extremely large pages.
Note that this value is before compression.  2MB with ztsd should result in roughly 300KB pages in our backend.  If you are using no compression or a different compression format it is advised to adjust this accordingly.
**Checklist**
=> Index Downsample Bytes

integration/e2e/config-limits.yaml, integration/e2e/e2e_test.go, integration/e2e/limits_test.go, modules/distributor/distributor.go, modules/ingester/instance.go, modules/ingester/trace.go, modules/overrides/limits.go
`tempo_discarded_spans_total` is meant to be a metric to inform tenants as to why they may be getting refused spans.  Previously it only covered the most basic rate limiting case.   This PR looks to extend that to include all limit based reasons that a span might be refused.
There is unfortunately no 100% correct way to metric this.  For instance, in the provided solution we are only including spans from the one trace that was rejected however the distributor will refuse the entire batch.  
We could try to metric this in the distributor which would make the metric more authentic.  It would be gross to try to get the rejection reason.  Substring matching?  It is also true that if a batch is rejected in the ingester it has already probably succeeded on other traces. …
=> Increment discarded spans metric for all limit reasons

CHANGELOG.md, docs/tempo/website/troubleshooting/_index.md, operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/tempo-operational.json, tempodb/compactor.go
Prompted by the metric: `tempo_receiver_accepted_spans` but that comes from OTel so not touching that. Found these two are missing _total so added it.
=> Make sure counters have _total suffix

modules/ingester/ingester.go
Replays the wal before entering the ring.  This will prevent ingesters from being overwhelmed while replaying the wal.
**Checklist**
=> Replay WAL first

CHANGELOG.md, cmd/tempo/app/app.go, modules/ingester/client/client.go
Switches the default compression for ingester_client from gzip to snappy. This is primarily used for distributor->ingester traffic, but also for querier->ingester.   
Internal testing shows that snappy outperforms gzip:
* 53% reduction in distributor cpu
* 12% reduction in ingester cpu
* 10% reduction in Push latency
* Minor improvements to mem usage (working set)
n/a
**Checklist**
=> Switch default ingester_client grpc compression from gzip to snappy

operations/tempo-mixin/runbook.md
Updates runbook entries for unhealthy compactor/distributor with a set of steps to forget the unhealthy ring entries.
**Checklist**
=> Unhealthy compactor/ingester runbook updates

cmd/tempo/app/app.go, operations/jsonnet/microservices/common.libsonnet, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/microservices/tempo.libsonnet
Update /ready handler for more detailed check for query-frontend: only return ready when at least 1 querier has connected (this is duplicated from cortex).    Add readiness probes to all jsonnet/microservices containers.
n/a
**Checklist**
=> Readiness probe updates

CHANGELOG.md, cmd/tempo-cli/cmd-list-block.go, docs/tempo/website/cli/_index.md
The tempo-cli `list block --check-dupes` option was broken for compressed blocks because it did not properly set the encoding.  This PR fixes that but also changes the option to `--scan` and adds some help things:  min/max object size, and ability to exit early and print current stats with CRTL+C.  These things were useful during a recent investigation.
The output looks like this:
```
$ ./tempo-cli -c ~/tempo.gcs.yaml list block ............ --scan
ID            :  700f39bb-219a-4bfd-a7c4-24df06cd6db7
Version       :  v1
Total Objects :  273967
Data Size     :  427 MB
Encoding      :  zstd
Level         :  0
Window        :  448220
Start         :  2021-02-17 20:34:00.405224842 +0000 UTC
End           :  2021-02-17 20:38:59.463662752 +0000 UTC
Duration      :  4m59s …
```
=> Fix tempo-cli list block encoding and add some helpful things

example/docker-compose/docker-compose.azure.azurite.yaml, example/docker-compose/docker-compose.gcs.fake.yaml, example/docker-compose/docker-compose.loki.yaml, example/docker-compose/docker-compose.multitenant.yaml, example/docker-compose/docker-compose.s3.minio.yaml, example/docker-compose/docker-compose.yaml, integration/microservices/docker-compose.yaml
Bumps Grafana from `7.3.0-beta1` to `7.4.2`.
Bumps Loki from `1.6.1` to `2.1.0`.
**Checklist**
=> Bump Grafana and Loki versions

.goreleaser.yml
Fixes this error in the goreleaser release process - 
```
⨯ release failed after 13.59s error=failed to add /home/runner/work/tempo/tempo/dist/tempo-query_linux_amd64/tempo -> tempo to the archive: file tempo already exists in the archive
```
CI run ID: https://github.com/grafana/tempo/runs/1927489321
Fixes #na!
**Checklist**
=> Add binary name in goreleaser config to avoid overwrite

operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/single-binary/tempo.libsonnet
- Removes overrides from the calculation of the config_hash so we can deploy these w/o rolling parts of Tempo
- Adds pod anti-affinity to ingesters
**Checklist**
=> Jsonnet Improvements

CHANGELOG.md, tempodb/backend/s3/s3.go
This commit ensure that the same object prefix string is used to query and strip
an object when listing all the objects in a bucket.
Some S3 implementations (in this case Dell ECS) cannot be relied upon to return
the correct `res.Prefix`. Dell ECS will return it URLencoded, e.g. "traceID%2F"
instead of "traceID/".
I am able to test this on ECS, but I do not have access to other blob storage, so help with testing additional storage backend would be appreciated.
Fixes #558 
**Checklist**
=> Fix object prefix not being stripped for Dell ECS

CHANGELOG.md, tempodb/backend/s3/s3.go
This PR fixes `tempodb/backend/s3/Blocks()` to fetch the complete list of blocks in case the `ListObjects()` result is truncated. 
**Checklist**
=> fixed listing blocks for backend/s3

CHANGELOG.md, modules/ingester/instance.go, tempodb/encoding/complete_block.go, tempodb/encoding/complete_block_test.go, tempodb/wal/append_block.go
This PR addresses a few instances where Append/CompleteBlock file handles would be left open and rely on GC to cleanup. The split of the deletion of WAL (AppendBlock) from creation of CompleteBlock also helps to ensure that AppendBlock.Clear is called, closing all handles.
Fixes #569
**Checklist**
=> Close gaps where append/completeblock file handles would rely on GC to close

docs/tempo/website/getting-started/_index.md
The `curl` command downloads the sample configuration to tempo.yaml, but the docker container is looking for `tempo-local.yaml`
Fixes the filename of the config file in the "Getting Started" guide.
**Checklist**
=> Fixed the filename in getting started

integration/bench/stress_test_write_path.js
- Increases the number of VUs on the bench stress test.
- Adds sleep to the `writePath` scenario.
Fixes https://github.com/grafana/tempo/pull/580/checks?check_run_id=2068246653
**Checklist**
=> Fix bench flaky test

CHANGELOG.md, cmd/tempo-cli/cmd-list-blocks.go, cmd/tempo-cli/cmd-list-compactionsummary.go, cmd/tempo-cli/main.go, cmd/tempo-cli/shared.go
This PR adds a new `list compaction-summary` command to tempo-cli that displays stats grouped by compaction level.  I think this will be helpful for understanding and tuning compaction performance.  The output looks like this:
```
Stats by compaction level:
+-----+-------------+--------------------------------+----------------------------+----------------------------+----------------+---------------+
| LVL |   BLOCKS    |             TOTAL              |       SMALLEST BLOCK       |       LARGEST BLOCK        |    EARLIEST    |    LATEST     |
+-----+-------------+--------------------------------+----------------------------+----------------------------+----------------+---------------+
|   0 | 358 (8 %)   | 105,846,286 objects (165 GB)   | 269,834 objects (432 MB) …
```
=> Add new list compaction-summary command to tempo-cli

docs/tempo/website/configuration/ingestion-limit.md, modules/overrides/overrides.go, modules/overrides/overrides_test.go
Adds the ability set a wildcard override in our override file.  This will allow us to feel comfortable that defaults are coming from within the file and that the override file is loaded.
=> Add wildcard tenant

modules/ingester/instance.go
An ingester can panic on startup if it executes a .Find() during wal replay b/c we are not locking the correct lock on `PushBytes()`
=> Lock the correct lock on wal replay

modules/ingester/instance_test.go
Adds `PushBytes()` to the `TestInstanceDoesNotRace()` test.  This should have been part of the previous PR, but it was Saturday and I didn't think about it.
Also confirmed that reverting the previous fix causes this test to fail.
**Checklist**
=> Added PushBytes to the race test

tempodb/encoding/base/object.go
Everytime we've seen this error it has been on wal replay due to a corrupt wal.  The following guard code is a fine bandaid that will allow the ingester to start, but the bigger fix is #418 
Fixes #597 
**Checklist**
=> Handle ingester panic with corrupt buffers

docs/tempo/website/_index.md, docs/tempo/website/monitoring/_index.md
Documents steps to scale the persistent volumes for ingesters (a process we recently had to do).   I think the location makes sense under monitoring... perhaps it would be useful to turn it into a monitoring and operations section.  Also fix missing link on main page.
n/a
**Checklist**
=> Document steps to scale persistent volume claims for ingesters

modules/distributor/distributor.go, modules/distributor/receiver/shim.go, operations/jsonnet/microservices/distributor.libsonnet
A handful of fixes to reduce the dropped spans during rollout.
- Adds a 30 second sleep before shutting down the OTel receiver and after the pod readiness probe is down.
- Adjusts the rollout
- Only roll one 1 distributor at a time
- Wait 1 minute after issuing SIGTERM to force kill the pod
Before changes we were dropping 100k+ spans in ops.  On the latest rollout with all changes this was reduced to ~100.
Fixes #530
**Checklist**
=> Improve distributor rollouts

CHANGELOG.md, modules/ingester/flush.go, modules/ingester/ingester.go, modules/ingester/instance.go, modules/ingester/instance_test.go, pkg/flushqueues/exclusivequeues.go, pkg/flushqueues/exclusivequeues_test.go, pkg/flushqueues/priority_queue.go, pkg/flushqueues/priority_queue_test.go, tempodb/encoding/complete_block.go, tempodb/wal/append_block.go, tempodb/wal/replay_block.go
This PR improves some stability, error handling, and logging for various things:
Main changes:
* Introduce exponential backoff for flushing blocks to backend (s3/gcs/etc), with a max backoff of 120s.  Flushes are attempted forever
* Introduce exponential backoff for converting wal->complete blocks. We have seen this error due to a corrupted wal file when the disk was full.  Backoff is from 30s->60s with 3 attempts, yielding around 120 seconds of retry time, after which the wal file is permanently deleted and data is (probably) lost.
* Fix regression where the WAL file was deleted as soon as the complete block was created, instead of only after a successful flush to the backend. This was broken unintentionally in the previous round of flush changes.
* Introduce …
=> Several fixes and improvements to block flushing, wal replay, file deletion, and logging

modules/compactor/compactor.go, modules/frontend/querysharding.go, modules/frontend/querysharding_test.go, modules/ingester/instance.go, modules/querier/querier_test.go, pkg/util/trace.go, pkg/util/trace_test.go, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/tempodb.go
This PR is a follow up to #606 that updates the object_combined metric to only increment when combination actually took place.  
n/a
**Checklist**
=> Update objects_combined metric to only increment if combination actually took place

cmd/tempo/app/modules.go
Previously we were postfixing the memberlist name with a guid to force uniqueness on restarts. This functionality, however, has been added to memberlist directly so let's remove this confusing bit of code.
https://github.com/grafana/tempo/blob/master/vendor/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/memberlist_client.go#L131
=> Memberlist: removed unncessary postfix

modules/ingester/trace.go
Previously if a span was refused due to "trace too large" it would not update the last append time. This would make the very large trace flush and then begin accepting even more spans for the same already enormous trace.
=> Update lastAppend on a trace even if spans refused

CHANGELOG.md, cmd/tempo-cli/cmd-list-index.go, cmd/tempo-cli/cmd-view-index.go, cmd/tempo-cli/main.go, tempodb/encoding/backend_block.go
This PR adds two new commands that may be helpful for analysis:
`list index` Displays count/smallest/largest index entries for the block
Example: 
```
$ ./tempo-cli -c ~/tempo.gcs.yaml list index 1 eb9097da-ce9b-4c79-a95e-2544e47eb600
Index entries: 85565
Min record: ID:000000000000000000f98dff14b6d9d8 Start:376637542 Length:88266
Max record: ID:00000000000000003ac4feb1e33cb8be Start:8797836709 Length:16873958
```
`view index` Dumps index entries to stdout with pauses for enter key
Example:
```
$ ./tempo-cli -c ~/tempo.gcs.yaml view index 1 8007402d-e2bf-4867-885b-56667d1a21bb
.
.
.
Index entry:      27694     ID: 0000000000000000091531809b380fca     Start: 3681618906     Length:     131629
Index entry:      27695     ID: 000000000000000009154701495d4bcc     Start: …
```
=> Add two new commands to dump and summarize a block index

operations/tempo-mixin/tempo-operational.json
Some operational dashboard panels did not match on the cluster or namespace variable, so the data would be misleading for any environments with multiple clusters sharing the same namespace.  This PR adds those filters to all relevant panels.  it's probably not necessary to match on both namespace and job, but it seemed good for consistency.
n/a
**Checklist**
=> Ensure all operational dashboard panels follow cluster/namespace variables

.drone/drone.yml
tempo-query depends on [jaeger-query](https://hub.docker.com/r/jaegertracing/jaeger-query) which does not have arm64 support. Unless we build the entire jaeger-query image ourselves we can not provide arm64 support for tempo-query.
This should be fine since the latest Grafana and Tempo images no longer require tempo-query and it will be phased out as people upgrade.
"Fixes" #594 
**Checklist**
=> Remove arm64 builds for tempo-query

CHANGELOG.md, modules/ingester/config.go
Adds a new flag `ingester.lifecycler.ID` allow manual override of ingester ring ID. This can be required for one-off cases like migrations or debugging.
Fixes #na!
**Checklist**
=> Add a new flag to allow manual override of ingester ring ID

tempodb/tempodb.go
Based on previous values the max the histogram covered was `8s` which we were capping constantly. Changed to have each bucket cover a full minute and give us vision up to 5 minutes.
=> Updated blocklist histogram

CHANGELOG.md, docs/tempo/website/configuration/_index.md, modules/storage/config.go, tempodb/backend/cache/cache.go, tempodb/backend/cache/cache_test.go, tempodb/backend/cache/memcached/memcached.go, tempodb/backend/cache/redis/redis.go, tempodb/config.go, tempodb/tempodb.go
- Add support for Cortex Background Cache.
- Refactor our code to use the Cortex Cache interface.
Fixes #528
**Checklist**
=> Add support for Cortex Background Cache

pkg/io/read.go, tempodb/encoding/common/types.go, tempodb/encoding/finder_paged.go, tempodb/encoding/iterator_paged.go, tempodb/encoding/iterator_record.go, tempodb/encoding/iterator_recordless.go, tempodb/encoding/streaming_block_test.go, tempodb/encoding/v0/data_reader.go, tempodb/encoding/v0/data_reader_test.go, tempodb/encoding/v1/data_reader.go, tempodb/encoding/v1/data_reader_test.go, tempodb/encoding/v2/data_reader.go, tempodb/encoding/v2/page.go, tempodb/encoding/v2/page_test.go, tempodb/encoding/versioned_test.go, tempodb/wal/wal_test.go
Performance improvements on wal and backend block iterating.
- Added `ReadAllWithEstimate` and `ReadAllWithBuffer` to allow for more efficient 
- Added a reusable buffer parameter to the `DataReader.Read()` method for use in iteration
- Restored some lost tests/benchmarks on Complete/Streaming blocks
=> Wal improvements

modules/frontend/frontend.go, modules/frontend/querysharding.go, modules/frontend/querysharding_test.go
Add information about tenant and the size of response for better discoverability in query frontend.
Fixes #649
**Checklist**
=> Add tenant and request size info to query frontend log

CHANGELOG.md, modules/overrides/limits.go
Add json struct tags to `limits` struct. To be consistent with [cortex](https://github.com/cortexproject/cortex/blob/master/pkg/util/validation/limits.go#L34) and [loki](https://github.com/grafana/loki/blob/main/pkg/validation/limits.go#L22)
Fixes NA
**Checklist**
=> Add json struct tags to Limits

tempodb/encoding/finder_paged.go, tempodb/encoding/iterator_deduping.go, tempodb/encoding/iterator_deduping_test.go, tempodb/encoding/iterator_record.go, tempodb/encoding/v0/object.go, tempodb/wal/wal_test.go
When working on the versioned WAL I noticed that the iterators inconsistently returned io.EOF. The deduping and standard iterator just returned all `nil` when complete. This is kind of a scary change, but important that all iterators behave the same.
**Checklist**
=> Make all Iterators return io.EOF

cmd/tempo-query/tempo/plugin.go, pkg/util/http_test.go
Two AGPL licensed strings were referenced from an APACHE2 licensed folder. This PR copies the strings into the folder to prevent licensing issues and sets up a test to make sure they don't drift.
Fixes #663
=> Tempo query license cleanup

docs/tempo/website/guides/pushing-spans-with-http.md
Fixes pushing spans with http documentation given the recent configurable http prefix change.
Fixes #670 
**Checklist**
=> Fixed docs for http prefix

pkg/io/read.go, tempodb/encoding/streaming_block_test.go, tempodb/encoding/v1/data_reader.go
PProf is showing that ~20% of ingester allocations during a CompleteBlock operation occur in `v1.dataReader => tempo_io.ReadAllWithEstimate`. This change adds a reusable buffer slice to the `v1.dataReader` to reduce allocations.
Also moved the +1 bytes into `ReadAllWithEstimate()`
=> Compression buffer

CHANGELOG.md, cmd/tempo/app/app.go, cmd/tempo/app/modules.go, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, docs/tempo/website/guides/multitenancy.md, docs/tempo/website/guides/pushing-spans-with-http.md, example/docker-compose/docker-compose.loki.yaml, example/docker-compose/docker-compose.multitenant.yaml, example/docker-compose/etc/tempo-azure.yaml, example/docker-compose/etc/tempo-gcs-fake.yaml, example/docker-compose/etc/tempo-local.yaml, example/docker-compose/etc/tempo-s3-minio.yaml, example/tk/tempo-microservices/main.jsonnet, integration/bench/config.yaml, integration/e2e/config-all-in-one-azurite.yaml, integration/e2e/config-all-in-one.yaml, integration/e2e/config-limits.yaml, integration/e2e/config-microservices.yaml, integration/microservices/tempo.yaml, modules/distributor/distributor.go, modules/distributor/receiver/shim.go, operations/jsonnet/single-binary/configmap.libsonnet
This PR renames `auth.enabled` to `multitenancy.enabled` and changes its default value to false.
Fixes #639
**Checklist**
=> Rename auth.enabled to multitenancy.enabled

tempodb/encoding/v1/data_reader.go
Expand buffer to its capacity before appending more slices to make up for the difference to the length of compressed pages to read. Otherwise we're first filling already allocated elements before actually expanding the buffer.
None
**Checklist**
=> Expand buffer to its capacity before appending more slices

.goreleaser.yml
Signed-off-by: Martin Disibio <mdisibio@gmail.com>
`make release`/goreleaser was setting the wrong ldflags (-X) leading to `tempo -version` printing empty values.  Docker images were ok because they are built using `make exe` and set here: https://github.com/grafana/tempo/blob/main/Makefile#L26
Fixes #669 
**Checklist**
=> Fix ldflags set by goreleaser

CHANGELOG.md, docs/tempo/website/configuration/manifest.md, modules/distributor/config.go, modules/distributor/distributor.go
Adds the ability to not extend writes to other ingesters when it sees an inactive ingester. This is useful during rollouts to prevent amplifying traces across all ingesters.
**Checklist**
=> Added option to disable extended writes

cmd/tempo/main.go, modules/ingester/instance.go, modules/ingester/instance_test.go
- Adds a cli parameter `mutex-profile-fraction` allowing us to dynamically enable mutex profiling
- Moves max traces check before grabbing the traces mutex and uses an atomic.Int32. This will relieve pressure on the traces mutex and allow more effective load shedding.
=> Enable mutex profiling. Fix load shedding.

docs/tempo/website/configuration/s3.md
Adds "s3:PutObjectTagging" and "s3:GetObjectTagging" to the list of required permissions for s3. If an object has tags s3 copy will fail (which we use to move meta.json -> meta.compacted.json) in the compactors.
https://medium.com/collaborne-engineering/s3-copyobject-access-denied-5f7a6fe0393e
=> Update required s3 permissions

cmd/tempo-vulture/main.go, go.mod, go.sum, vendor/github.com/jsternberg/zap-logfmt/encoder.go, vendor/modules.txt
Change logging format of tempo-vulture from json to logfmt to be more consistent with the other applications.
Before:
```
2021-05-03T16:47:41.490+0200    INFO    tempo-vulture/main.go:84        sending trace   {"write_trace_id": "0f76bf113f57aa7b4acb6bfd29f97c20"}
2021-05-03T16:47:56.485+0200    INFO    tempo-vulture/main.go:84        sending trace   {"write_trace_id": "06739b5d43f529657602bebb64ab056a"}
2021-05-03T16:47:56.485+0200    INFO    tempo-vulture/main.go:227       querying Tempo  {"query_trace_id": "7602bebb64ab056a06739b5d43f52965", "tempo_query_url": "http://localhost:3100/api/traces/7602bebb64ab056a06739b5d43f52965"}
2021-05-03T16:48:11.489+0200    INFO    tempo-vulture/main.go:84        sending trace   {"write_trace_id": …
```
=> Vulture: use logfmt logging, update zap-logfmt to v1.2.0

CHANGELOG.md, pkg/util/trace.go, pkg/util/trace_test.go
Uses span.Kind to differentiate between zipkin client/server spans in combine.
Related to #682 and #687 
**Checklist**
=> Support for Zipkin: CombineTraces

cmd/tempo-vulture/main.go
Fixes segmentation fault if `queryTempoAndAnalyse` returns nil, err. Introduced by the previous PR #689 🙈 
The log _Tempo Vulture starting_ accidentally got removed in a previous PR.
=> Vulture: fix segmentation fault that occurs if queryTempoAndAnalyse returns nil, err

CHANGELOG.md, cmd/tempo/app/app.go, operations/kube-manifests/Namespace-tracing.yaml
Fix Query Frontend GRPC settings to fix the noisy error message 
```
caller=frontend_processor.go:59 msg="error processing requests" address=127.0.0.1:9095 err="rpc error: code = Unavailable desc = transport is closing"
```
Thanks to @pstibrany for digging into this in Cortex - https://github.com/cortexproject/cortex/issues/3606#issuecomment-745179803
Fixes #493 
**Checklist**
=> Fix Query Frontend grpc settings to avoid noisy error log

operations/tempo-mixin/out/tempo-operational.json, operations/tempo-mixin/tempo-operational.json
_PR description updated 17 May_
Update the vulture section in the Tempo Operational dashboard.
Before:
After:
Changes:
- display both a time series graph and an average bar gauge
- splitting in errors is now dynamic, so if we add a new error label it will automatically appear in the dashboard
=> Update tempo operational dashboard: add vulture requestfailed panel

operations/jsonnet/microservices/config.libsonnet
The port number is already added by vulture itself. Specifying the port again in the Jsonnet config leads to a double entry and causes the following error message:
```
T=2021-05-27T13:49:10.966Z L=ERROR M="error pushing batch to Tempo" org_id= write_trace_id=65d82e9fe247036e0a9086c9f4a8eebb seed=1622123340 error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address distributor:14250:14250: too many colons in address\""
```
The port is already added here:
https://github.com/grafana/tempo/blob/85bdea314ac7100948d3069021ff410f5d153917/cmd/tempo-vulture/main.go#L157-L158
Alternative solution is to not add the port in the Go code and leave it in the Jsonnet config, but this will have more impact downstream. …
=> Jsonnet: fix tempoPushUrl of vulture

example/docker-compose/docker-compose.s3.minio.yaml, example/tk/lib/minio/minio.libsonnet, integration/microservices/docker-compose.yaml
The older version of minio does not work on Apple M1.
FYI, Minio has quietly changed their license to AGPL a month ago, but this shouldn't impact us.
https://github.com/minio/minio/commit/069432566fcfac1f1053677cc925ddafd750730a
=> Bump version of minio

CHANGELOG.md, cmd/tempo/app/modules.go, integration/e2e/e2e_test.go
Adds a new endpoint `/api/echo` that always returns with 200  and a body `echo`.
Closes #624
**Checklist**
=> Add HTTP endpoint /api/echo to query-frontend

example/docker-compose/docker-compose.yaml
Expose the OpenTelemetry ports in the default `docker-compose.yaml` file. OpenTelemetry is one if the most commonly used frameworks to work with traces and a lot of tools use OTLP so I think it would make sense to expose the OTLP ports similar to Jaeger and Zipkin by default.
No issues
**Checklist**
=> Add OTLP port to docker-compose example

modules/querier/config.go, modules/querier/querier.go
Cortex was setting these defaults using flags, we did not port them over correctly when we added these configs to our querier.
=> Fix 500s on query frontend rollout

README.md
tempo-query is no longer required if you're using Grafana 7.5.x and forward. Removing references to it on the main readme will reduce confusion.
=> Removed reference to tempo-query

operations/tempo-mixin/runbook.md
The job queue is no longer used for polling. Removed incorrect line suggesting changing a job queue setting to help with polling.
=> Playbook: Removed incorrect info

example/tk/lib/grafana/main.libsonnet, example/tk/readme.md, example/tk/tempo-microservices/main.jsonnet, example/tk/tempo-single-binary/main.jsonnet
**What this PR does**
- Replace Jaeger UI in example by Grafana
- Reduce replicas of memcached to 1, with 3 replicas the cluster will often run out of CPU (on my machine at least)
Follow up from #720
=> Add Grafana to Tanka examples

CODEOWNERS, GOVERNANCE.md, MAINTAINERS.md
Proposal to make Mario Rodriguez @mapno a maintainer. An approving review is a vote in favor.
- [Agent Work](https://github.com/grafana/agent/pulls?q=is%3Apr+author%3Amapno+is%3Aclosed)
- [Tempo Work](https://github.com/grafana/tempo/pulls?q=is%3Apr+author%3Amapno+is%3Aclosed)
- [Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+reviewed-by%3Amapno+is%3Aclosed)
Additionally Mario has participated in the public slack and community forums helping people get started with and operate Tempo.
=> Make Mario Rodriguez a maintainer

RELEASES.MD
Updates the release process.
- Adds a step to cut docs for the newly minted version.
- Adds a step to update the helm-charts with the new version.  
- Removes requirement to check the config manifest. I think we should just require this being updated as part of PRs. Really this should just be updated with CI.
- Removes requirement to find github handles for all PRs. Let's just require them as part of the changelog submission.
=> Updated Release Process

cmd/tempo-cli/cmd-list-block.go, cmd/tempo-cli/cmd-list-blocks.go, cmd/tempo-cli/cmd-list-compactionsummary.go, cmd/tempo-cli/shared.go, docs/tempo/website/operations/tempo_cli.md
The tempo-cli list block --scan command was broken when new meta fields were added such as DataEncoding, and IndexPageSizeBytes. This cleans up the meta handling so that it is less brittle.  Also updates documentation for recently added commands.
n/a
**Checklist**
=> Cleanup tempo-cli block meta handling and docs

CHANGELOG.md, tempodb/backend/azure/azure.go
Fix an issue with the append method on the Azure backend. The AppendBlock on the azure SDK only works when the block is created as an [append blocks](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.appendblobclient.appendblock?view=azure-dotnet).
**Checklist**
=> fix(azure): append method on azure backend

example/helm/microservices-extras.yaml, example/helm/microservices-grafana-values.yaml, example/helm/readme.md, example/helm/single-binary-extras.yaml, example/helm/single-binary-grafana-values.yaml, example/tk/readme.md
Replace Jaeger UI with Grafana in the Helm examples. This makes them consistent with the docker-compose and tanka examples.
=> Use Grafana in helm examples

cmd/tempo-query/tempo/plugin.go, modules/frontend/deduper.go, modules/frontend/frontend.go, modules/frontend/querysharding.go, modules/frontend/querysharding_test.go, tempodb/backend/readerat.go
Update usage of `ioutil.ReadAll` to `io.ReadAll` since the former was marked as deprecated in Go v1.16. From discussion on Slack with @mdisibio I gather that `ReadAllWithEstimate` is typically the preferred way now, however looking at the places where that function is used, there's usually a way to estimate the size of the buffer beforehand. The remaining uses of `ioutil.ReadAll` on the other hand are used to read the `Response` from an HTTP request; while it's entirely possible that the response has a `Content-Length` header, it's also not a guarantee.
_none_
**Checklist**
- [ N/A ] Tests updated
- [ N/A ] Documentation added
=> replace ioutil.ReadAll with io.ReadAll

.drone/drone.yml
The drone build of tempo-query is broken: https://drone.grafana.net/grafana/tempo/402/1/3
Relevant step:
```
1.15.3-alpine: Pulling from library/golang
Digest: sha256:df0119b970c8e5e9f0f5c40f6b55edddf616bab2b911927ebc3b361c469ea29c
Status: Downloaded newer image for golang:1.15.3-alpine
+ apk add make git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.41.0-r0)
(2/6) Installing libcurl (7.77.0-r0)
(3/6) Installing expat (2.2.9-r1)
(4/6) Installing pcre2 (10.35-r0)
(5/6) Installing git (2.26.3-r0)
(6/6) Installing make (4.3-r0)
Executing busybox-1.31.1-r19.trigger
OK: 22 MiB in 21 packages
+ COMPONENT=tempo-query make exe …
```
=> Update build image of tempo-query - fixes Drone build

docs/tempo/website/api_docs/_index.md
Clarify docs after a bit of confusion in the community Slack.
=> Docs: distributor ring is only available with global override strategy

CHANGELOG.md, integration/microservices/docker-compose.yaml, tempodb/encoding/v2/page.go, tempodb/encoding/v2/page_test.go
Adds guard code against a negative page length. This issue appears to occur when an ingester undergoes an unexpected shutdown. Details in issue.
Fixes #752 
**Checklist**
=> Guard against negative dataLength while reading a page

operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/memcached.libsonnet
This makes overriding the connection limit more consistent with other configurations. Before you had to override connection limit at `$.memcached.connection_limit`, now you can use `$._config.memcached.connection_limit`
=> jsonnet: add connection_limit to $._config.memcached - increase default to 4096

CHANGELOG.md, operations/tempo-mixin/tempo-operational.json
Add container name to Memory and CPU metrics. They are reported per cgroup, so pods with more than one container have several lines. This change allows them to be distinguished.
Also filter out 'pause' container - these metrics are typically very low because the "pause" container is a piece of Kubernetes internals that sits and does nothing. Filtering them out of the display aids readability.
Note in some Kubernetes installations the pause container is labled "POD", which was previously filtered out from the dashboard in #496. See containerd/cri#922 for background on the name.
None
**Checklist**
=> Tweak CPU and memory display on operational dashboard

docs/tempo/website/configuration/_index.md
The otlp grpc receiver uses port 55680 not 5680.
=> Fix otlp receiver port in documentation

CHANGELOG.md, tempodb/backend/azure/azure_helpers.go, tempodb/backend/azure/instrumentation.go
Initial draft PR to add instrumentation to Azure.
Fixes #[759](https://github.com/grafana/tempo/issues/759)
**Checklist**
=> Add initial instrumentation to Azure

operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/configmap.libsonnet
Updates the jsonnet library:
- bump image of memcached to `1.6.9-alpine`
- decrease the memcached timeout to `200ms`
From running Tempo at Grafana Labs we see latencies are well below 200ms. The P999 latency will occasionally peak above 200ms.
In this image, spikes are caused by deployments of memcached.
=> Jsonnet: update memcached image and timeout setting

CHANGELOG.md, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/kube-manifests/ConfigMap-tempo-distributor.yaml, operations/kube-manifests/ConfigMap-tempo-ingester.yaml, operations/kube-manifests/ConfigMap-tempo-querier.yaml, operations/kube-manifests/ConfigMap-tempo-query-frontend.yaml, operations/kube-manifests/Deployment-compactor.yaml, operations/kube-manifests/Deployment-distributor.yaml, operations/kube-manifests/Deployment-querier.yaml, operations/kube-manifests/Deployment-query-frontend.yaml, operations/kube-manifests/StatefulSet-ingester.yaml, operations/kube-manifests/StatefulSet-memcached.yaml
Split the `tempo` configmap into `tempo-distributor` and `tempo-ingester`. This will allow both services to be updated independently (changing the config of the ingesters should not impact the distributor and vice versa).
I've also added `config_hash` annotation to both so they get replaced when the config changes.
Fixes #742 
**Checklist**
=> Jsonnet: use dedicated configmaps for distributors and ingesters

operations/jsonnet/microservices/configmap.libsonnet
Converting `null` or `{}` to YAML both result in `null`. But null in Jsonnnet can trip someone up that expects the value to be there. For instance when extending tempo_config they might do something like this:
```
tempo_config+:: {
distributor+: {
// ...
}
}
```
Using +: is generally preferred because it doesn't overwrite previous values, but would not work if tempo_config.distributor is null.
=> Jsonnet: replace null with {}

CHANGELOG.md, modules/ingester/flush.go
Add a histogram for size paralleling `tempo_ingester_flush_duration_seconds`.
This improves the observability of the ingester write path.
**Checklist**
=> Add histogram for flush size in bytes

operations/jsonnet/microservices/configmap.libsonnet
By not appending new config, the jsonnet library might overwrite custom user configuration. We should favour appending whenever extending an already existing object (in this case $.tempo_config).
=> Jsonnet: always use append (+:) when extending config

operations/jsonnet/single-binary/config.libsonnet, operations/jsonnet/single-binary/configmap.libsonnet, operations/jsonnet/single-binary/tempo.libsonnet
**What this PR does**: Remove the assumption that kausal is always available in the root element, instead we declare it explicitly, because it is an implementation detail that is leaking to the consumers of the libraries.
N/A
**Checklist**
=> refactor(jsonnet/single-binary): Remove kausal from the root element

operations/jsonnet/microservices/common.libsonnet, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/jsonnet/microservices/memcached.libsonnet, operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/microservices/tempo.libsonnet, operations/jsonnet/microservices/vulture.libsonnet
**What this PR does**: Remove the assumption that kausal is always available in the root element, instead we declare it explicitly, because it is an implementation detail that is leaking to the consumers of the libraries.
N/A
**Checklist**
=> refactor(jsonnet/microservices): Remove kausal from the root element

example/tk/lib/grafana/main.libsonnet, example/tk/lib/minio/minio.libsonnet, example/tk/lib/synthetic-load-generator/main.libsonnet, example/tk/tempo-microservices/main.jsonnet, example/tk/tempo-single-binary/main.jsonnet
Pretty much the same thing as #781 and #782 but for the tanka examples instead.
> Remove the assumption that kausal is always available in the root element, instead we declare it explicitly, because it is an implementation detail that is leaking to the consumers of the libraries.
**Checklist**
=> refactor(example/tk): Remove kausal from the root element

tempodb/backend/util/test.go, tempodb/blocklist/poller.go, tempodb/blocklist/poller_test.go, tempodb/tempodb.go, tempodb/tempodb_test.go
Refactors blocklist polling code by moving it into its own package and adding tests. This is in preparation for adding a bucket index.
=> Refactor Blocklist Polling

CHANGELOG.md, operations/jsonnet/microservices/common.libsonnet, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/jsonnet/microservices/querier.libsonnet
Move all Kubernetes resource settings into `$._config`, this way users only need to override `$._config` and don't need to know about the internals (`tempo_compactor_container` etc.).
Fixes https://github.com/grafana/tempo/issues/701: resource settings were not applied correctly due to import ordering.
**Checklist**
=> Move resource requests and limits into $._config

docs/tempo/website/api_docs/_index.md
- Adds details about return value of the querier endpoint
- Changed heading for `/api/echo` to better reflect what it does. (don't want to get mixed up with k8s /readiness handlers)
=> Improved query docs

CHANGELOG.md, cmd/tempo/main.go, docs/tempo/website/configuration/_index.md, go.mod, go.sum, vendor/github.com/drone/envsubst/.drone.yml, vendor/github.com/drone/envsubst/.gitignore, vendor/github.com/drone/envsubst/LICENSE, vendor/github.com/drone/envsubst/eval.go, vendor/github.com/drone/envsubst/funcs.go, vendor/github.com/drone/envsubst/go.mod, vendor/github.com/drone/envsubst/go.sum, vendor/github.com/drone/envsubst/parse/node.go, vendor/github.com/drone/envsubst/parse/parse.go, vendor/github.com/drone/envsubst/parse/scan.go, vendor/github.com/drone/envsubst/path/match.go, vendor/github.com/drone/envsubst/readme.md, vendor/github.com/drone/envsubst/template.go, vendor/modules.txt
Setting default value to false to keep backward compatibility
Signed-off-by: Ashmita Bohara <ashmita.bohara152@gmail.com>
Fixes https://github.com/grafana/tempo/issues/788
**Checklist**
=> Add flag for environment vars substitution in config file

docs/tempo/website/getting-started/_index.md
Fixed 4 typos in the documentation of `OpenTelemetry`, my editor has also apparently cleared out some space characters at the end of some lines. 
None, just noticed it.
**Checklist**
- [N/A] Tests updated
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Fix OpenTelemetry typos on the Getting Started docs page.

tempodb/encoding/v2/page.go, tempodb/encoding/v2/page_test.go
Adds guard code to catch corrupt blocks and return an error instead of panic'ing.
=> Additional Guard code while parsing the header

operations/tempo-mixin/tempo-operational.json, operations/tempo-mixin/yamls/tempo-operational.json
Helps track the total length in the backend in multi tenant environments -
=> Make the blocklist panel stacked

docs/tempo/website/getting-started/_index.md, docs/tempo/website/grafana-agent/_index.md, docs/tempo/website/grafana-agent/automatic-logging.md, docs/tempo/website/grafana-agent/tail-based-sampling.md
Agent docs have been restructured moving the tempo config into a separate file. This PR updates all references.
=> Docs: update links to agent configuration

CHANGELOG.md, modules/ingester/flush.go
Create a new span for each flush, log the trace ID, and any error that comes back.
Passing a context in to `handleFlush()` seems more natural than having it assume it is only called in background context.
**Checklist**
=> Emit traces for ingester flush operations

CHANGELOG.md, docs/tempo/website/configuration/_index.md, modules/frontend/config.go, modules/frontend/deduper.go, modules/frontend/frontend.go, modules/frontend/querysharding.go, modules/frontend/retry.go, modules/frontend/retry_test.go
Requests from the query-frontend to the querier might fail when a querier is starting or stopping. Simply retrying this request usually solves this.
This PR adds a retry middleware which will relaunch requests (up to 5 times by default) if the request failed (http 500 or error).
Related to #761 
**Checklist**
=> Add retry middleware in query-frontend

tools/image-tag
Remove -o pipefail from image-tag script
It is a bash-ism so not supported in some environments
Script doesn't have any pipelines where we could get a failure protected by pipefail
Fixes #815 
**Checklist**
- NA `CHANGELOG.md` updated - this is not a user-visible change
=> Remove -o pipefail from image-tag script

.errcheck-exclude.txt, .golangci.yml, cmd/tempo-cli/cmd-list-block.go, modules/distributor/receiver/shim.go
Attempt to tweak golangci-lint and its linters to avoid CI failing on unrelated issues (as happened in https://github.com/grafana/tempo/pull/808).
=> Clean up CI linting

example/docker-compose/s3/docker-compose.yaml, example/docker-compose/s3/readme.md, example/tk/lib/minio/minio.libsonnet, integration/microservices/docker-compose.yaml
Minio is aggressive about removing old tags.  The `RELEASE.2021-05-26T00-22-46Z` tag no longer exists in dockerhub. I normally hate using latest, but I think we should here so we don't have to constantly update this.
Also added `restart: on-failure` for when Tempo starts faster than minio.
=> Swapped to latest minio

operations/tempo-mixin/tempo-operational.json, operations/tempo-mixin/yamls/tempo-operational.json
This change simplifies navigating between Tempo dashboards:
- the `tempo` tag adds it to the dropdown
- the link adds the same dropdown to Tempo Operational
=> Add Tempo tag and link to operational dashboard

.drone/drone.yml, CHANGELOG.md, tools/image-tag
This PR lays the groundwork to adopt an internal weekly release cycle. This simply adds an additional trigger to CI so it can build and push artifacts on `r?` and `r??` branches, which are later consumed by our internal automation.
=> Prepare CI for our internal release train

operations/tempo-mixin/tempo-operational.json, operations/tempo-mixin/yamls/tempo-operational.json
Operations removed a legacy cluster. The old name shouldn't be used anymore. Therefore we also renamed the data source.
=> rename legacy datasource

operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/frontend.libsonnet
Avoid repeating the server port across our jsonnet. This allows you to use a different port by changing just one setting.
=> Jsonnet: prefer $._config.port over hardcoding the server port

.github/workflows/bench.yml, .github/workflows/ci.yml
Noticed this when creating https://github.com/grafana/tempo/pull/832: CI and benchmarks run even though some of these folders don't contain code impacting Tempo or its tests. Waiting until CI is green is thus unnecessary and might give a false sense of safety.
=> Don't run CI and benchmarks when non-code folders change

operations/jsonnet/microservices/config.libsonnet
**What this PR does**: Fixes a runtime error in the jsonnet library introduced in https://github.com/grafana/tempo/pull/832
```
$ tk diff environments/tempo/<a-tempo-environment>
Error: evaluating jsonnet: RUNTIME ERROR:
<path-to-vendored-library>/microservices/config.libsonnet:90:51-52 Not a unary operator: %
```
=> fix(jsonnet): % is not an unary operator

modules/frontend/frontend.go
If the query-frontend uses a GRPC stream to communicate with the querier, HTTP error responses are wrapped in the returned error. When logging the response status code, we should try to extract a HTTP response from this grpc error as well.
Closes #845
**Checklist**
=> query-frontend: attempt to log response status code from grpc error

pkg/io/read.go, tempodb/backend/azure/azure.go, tempodb/backend/azure/azure_test.go, tempodb/backend/backend.go, tempodb/backend/cache/cache.go, tempodb/backend/cache/cache_test.go, tempodb/backend/gcs/gcs.go, tempodb/backend/gcs/gcs_test.go, tempodb/backend/local/local.go, tempodb/backend/local/local_test.go, tempodb/backend/mocks.go, tempodb/backend/raw.go, tempodb/backend/raw_test.go, tempodb/backend/readerat.go, tempodb/backend/s3/s3.go, tempodb/backend/s3/s3_test.go, tempodb/encoding/backend_block.go, tempodb/encoding/block.go, tempodb/wal/local_block.go
This PR adds a new `shouldCache` parameter to the Backend interface on the Read/Write functions.
Pros:
- Cleaner interface, follow up of #804 
- Ability to cache based on some custom parameters. Will be useful in #805 
Cons:
- Lots of `ioutil.NopCloser(bytes.NewReader(buffer))` usage while translating byte slices <> io.ReadCloser 
_Note: I'm still working on tests and CI, opened the PR for early review of the general direction._
Fixes #na!
**Checklist**
=> Add shouldCache param to backend interface read/write methods

docs/tempo/website/grafana-agent/tail-based-sampling.md
Updates docs to reflect changes in https://github.com/grafana/agent/pull/765
=> Update Agent docs for lb

CHANGELOG.md, pkg/util/http.go, pkg/util/http_test.go
Without this change, invalid characters received from the user input causes a bad error message to the user.  Here we check that all of the characters that are to be decoded are valid hex characters and improve the error to the user in the event the trace ID submitted has invalid characters.
Fixes #846
**Checklist**
=> Allow only valid trace ID characters when decoding

docs/tempo/website/configuration/_index.md, modules/frontend/config.go, modules/frontend/frontend.go, modules/frontend/retry.go, modules/frontend/retry_test.go
Improves the retry middleware in query-frontend:
- when err is a grpc error, extract http response and check status code (fixes #844)
- lower default retry to 2
- add a prometheus metric `query_frontend_retries`
- don't log errors (avoids #843)
Closes #844
Closes #843
Supersedes #849
Closes #824
**Checklist**
=> query-frontend/retry: properly handle grpc errors; lower default max_retries

.drone/drone.yml, cmd/tempo-query/Dockerfile
`jaegertracing/jaeger-query` is a multi-arch images since `1.24.0` https://hub.docker.com/r/jaegertracing/jaeger-query/tags?page=1&ordering=last_updated
so we could bump the latest version and enable multi-arch image builds of `tempo-query`
Enable multi-arch images of tempo-query
**Checklist**
=> Bump jaegertracing/jaeger-query to 1.25.0 and enable multi-arch image builds of tempo-query

CHANGELOG.md, cmd/tempo/app/app.go, docs/tempo/website/api_docs/_index.md
Add `/services` which prints a plaintext list of all the services in the service map with their status and optional failure case.
```
$ curl  localhost:3201/services
memberlist-kv: Running
querier: Running
ring: Running
server: Running
store: Running
```
Cortex has a similar endpoint which returns HTML, but I decided to keep this simple and plaintext.
https://github.com/cortexproject/cortex/blob/master/pkg/cortex/status.go
**Checklist**
=> Add /services endpoint

CODEOWNERS, GOVERNANCE.md, MAINTAINERS.md
Proposal to make @kvrhdn a maintainer. An approving review is a vote in favor.
- [Agent Work](https://github.com/grafana/agent/pulls?q=is%3Apr+author%3Akvrhdn+is%3Aclosed)
- [Tempo Work](https://github.com/grafana/tempo/pulls?q=is%3Apr+author%3Akvrhdn+is%3Aclosed)
- [Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+reviewed-by%3Akvrhdn+is%3Aclosed)
Additionally Koenraad has participated in the public slack and community forums as well as contributed to the OpenTelemetry project.
=> Make Koenraad Verheyden a maintainer

CHANGELOG.md, example/docker-compose/gcs/docker-compose.yaml
Without this change, the fake GCS server does not start properly due to
incorrect port specification.  Here we make the necessary update to ensure that
the fake server is started.
Fixes #869
**Checklist**
=> Update port spec for GCS docker-compose example

CHANGELOG.md, cmd/tempo-cli/cmd-query-blocks.go, cmd/tempo-cli/main.go, docs/tempo/website/operations/tempo_cli.md, pkg/util/http.go, pkg/util/http_test.go
Adds the ability to query the backend blocks directly and dump all info found for a trace id. This also changes the existing query option to better distinguish it in the cli.
`./tempo-cli query` => `./tempo-cli query api` or `./tempo-cli query blocks`
The command outputs each block found, its contents and the combined trace.
**Checklist**
=> Added query blocks cli command

CHANGELOG.md, example/docker-compose/distributed/docker-compose.yaml, example/docker-compose/distributed/grafana-datasources.yaml, example/docker-compose/distributed/prometheus.yaml, example/docker-compose/distributed/readme.md, example/docker-compose/distributed/tempo-distributed.yaml, example/docker-compose/s3/readme.md
Without this change, there is not an example of how a user might proceed with
local testing and development using docker-compose.  Here we copy the local
docker-compose example and extend it to include the distributed configuration
pieces necessary to get a functional example.
Fixes #746
**Checklist**
=> Include distributed docker-compose example

tempodb/backend/raw.go
Fixes an issue where `Blocks()` fails on GCS when there is a tenant index present with error message `failed to poll blocklist. using previously polled lists" err="failed to parse : invalid UUID length: 0`.  This fix is a bandaid. A more correct fix requires #880 to be resolved.
=> Fix Blocks() on GCS

CHANGELOG.md, operations/tempo-mixin/runbook.md
Now that the unforgettable ring member issue is finally cleared:
- Remove references in runbooks
- Add a changelog entry
**Checklist**
=> Unforgettable ring member cleanup

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/runbook.md
Clarifies the `TempoFlushesFailing` alert and renames it to `TempoIngesterFlushesFailing`.
- The original description mentions failed compactions, but this alert can only be triggered by ingesters. It uses the `tempo_ingester_failed_flushes_total` metric that is created in `modules/ingester/flush.go`
- The section about the compactor creating orphaned blocks seems useful, maybe we should move it to another alert?
=> Rename and clarify TempoFlushesFailing -> TempoIngesterFlushesFailing

cmd/tempo/app/app.go, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md
The latest Cortex upgrade started correctly applying Memberlist LAN defaults. This caused a spike in resource usage by memberlist ring propagation. This PR looks to choose some sensible defaults that balances resource usage against ring propagation speed. With the proposed defaults in a 125 node memberlist cluster and a ring heartbeat of 5s:
CPU Usage: .04
Bandwidth (tx + rx): 346 KBs
Average heartbeat age: 15s
**Checklist**
=> Revisit Memberlist defaults

CHANGELOG.md, modules/ingester/trace.go
Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>
This PR adds trace id to `trace too large message`
Fixes #884 
**Checklist**
=> adds traceid to trace too large message

CHANGELOG.md, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/ingester.libsonnet
Add support to tempo workloads to read `overrides` values from single configmap in microservice mode.
Fixes #875
**Checklist**
=> Use single configmap for overrides

example/docker-compose/loki/docker-compose.yaml
Migrates examples from the deprecated loki API: `/api/prom/push` -> `/loki/api/v1/push`
- https://grafana.com/docs/loki/latest/api/#post-apiprompush
=> Migrate from deprecated api

CHANGELOG.md, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/ingester.libsonnet
It edit tempo microservices jsonnet and makes the `overrides_config` block name consistent with Loki and Cortex
1. Loki - https://github.com/grafana/loki/blob/main/production/ksonnet/loki/overrides.libsonnet#L21
2. Cortex - https://github.com/grafana/cortex-jsonnet/blob/main/cortex/config.libsonnet#L469
Fixes #NA
**Checklist**
=> Make overrides configmap block name consistent

docs/tempo/website/configuration/polling.md, docs/tempo/website/operations/polling.md, operations/jsonnet/microservices/configmap.libsonnet, operations/tempo-mixin/runbook.md
A small batch of doc/runbook improvements that are important before we cut 1.1:
- Remove incorrect information about 404ing if ingesters scale too quickly
- Update polling docs to discuss dangers of compactor polling cycle being > querier polling cycle.
- Correct jsonnet to not set compactor polling cycle to > querier polling cycle.
**Checklist**
=> Doc improvements

cmd/tempo-cli/cmd-query-blocks.go
Changes marshaller from `encoding/json` to `gogo/protobuf/jsonpb` in CLI's block query command. This formats the output to use the camelCase, using json tags inside protobuf, rather than the actual json tags (see [here](https://github.com/grafana/tempo/blob/main/pkg/tempopb/trace/v1/trace.pb.go#L191) for an example)
Fixes #910
**Checklist**
=> Use camelCase format for cli block query output

CHANGELOG.md, modules/querier/querier.go, tempodb/tempodb.go
Add additional information to trace searches to aid in debugging.
Fixes #907
**Checklist**
=> Include additional detail when searching for traces

CHANGELOG.md, modules/storage/config.go
Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>
This PR renames` --storage.trace.maintenance-cycle` to` --storage.trace.blocklist_poll`
Fixes #862 
**Checklist**
=> renames CLI flag from --storage.trace.maintenance-cycle to --storage.trace.blocklist_poll

tempodb/search/pipeline.go, tempodb/search/pipeline_test.go
Search duration filtering had incorrect results when trying to filter durations above ~4s. This was due to inadvertently storing nanos in uint32. This fixes to use uint64.
Fixes some of #932 
**Checklist**
=> Fix 32/64-bit issue in search duration filtering

example/helm/microservices-grafana-values.yaml, example/helm/readme.md, example/helm/single-binary-grafana-values.yaml
When testing the latest 1.1 helm packages I found that the ports are configured incorrectly in our helm examples. Fixed.
Also removed the line about using a custom image b/c the helm charts pull specific stable versions and do not use `:latest`.
**Checklist**
=> Fixed helm examples

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/rules.libsonnet
Similiar to https://github.com/grafana/cortex-jsonnet/pull/319 in cortex, Replaces hard-coded usage of [namespace, job] or [namespace, cluster] in alerts and recording rules to support different configurations of cluster and job unique identifier labels.
I generated the existing alerts/rules in `yamls/` folder and the only differences I see are recent changes to `yamls/alerts.yml` that haven't been synced
N/A
**Checklist**
~- [ ] Tests updated~
~- [ ] Documentation added~
=> add configurable 'job_selectors' and 'cluster_selectors'

CHANGELOG.md, modules/ingester/ingester.go, modules/ingester/ingester_test.go, modules/ingester/instance.go, pkg/flushqueues/exclusivequeues.go
This PR fixes #937 by deleting locally complete blocks during wal replay, and another race condition on ingester startup.  Here is a description of the situation and why this should fix it.
1. An ingester may restart or crash while completing the wal file. It can happen after creating the new local block, but before deleting the wal file.
2. On restart the ingester replays wal, and rediscovers local blocks.  Both exist it ends up with 2 queue entries instead of 1.  It will both recomplete the wal and reflush the local block.  These occur independently and there are no consistency checks while processing the queue entry.
3. This is a race condition in multiple ways. 
a. The wal complete is in progress, writing over top of `data` when it is flushed to the backend. The …
=> Delete completed local blocks when replaying wal

CHANGELOG.md, modules/overrides/overrides.go, vendor/github.com/grafana/dskit/runtimeconfig/manager.go, vendor/modules.txt
Make tempo use runtimeconfig from `dskit` instead of `cortex` (similar to Loki)
Fixes # NA
**Checklist**
=> Make tempo use runtimeconfig from `dskit` instead of `cortex`

CHANGELOG.md, cmd/tempo/app/modules.go, modules/overrides/limits.go, modules/overrides/overrides.go
Adds a runtime config handler at `/runtime_config`
Fixes #893
**Checklist**
=> Add runtime config handler

operations/tempo-mixin/yamls/alerts.yaml, operations/tempo-mixin/yamls/tempo-operational.json
Regenerate tempo-mixin yamls by running the commands from the README.
I noticed #930 only updated the file in `tempo-mixin/` and not in `tempo-mixin/yamls/`
Apparently this also happened in #887 and #834
**Checklist**
=> tempo-mixin: regenerate yamls/

.github/workflows/ci.yml, Makefile, operations/tempo-mixin/Makefile, operations/tempo-mixin/README.md, operations/tempo-mixin/dashboards.libsonnet
- Adds a Makefile to simplify generating the tempo-mixin yamls.
- Link this Makefile to the root-level Makefile so you can do `make tempo-mixin`.
- Verify tempo-mixin has been updated in CI.
Should avoid issues like #956
**Checklist**
=> tempo-mixin: add Makefile and CI check

CHANGELOG.md, cmd/tempo/app/app.go, cmd/tempo/app/modules.go, docs/tempo/website/api_docs/_index.md, modules/overrides/overrides.go
Here we move a few status endpoints onto the `/status` endpoint.  Optionally, users can pass a few query parameters that will reduce the amount of output.
Fixes #949
**Checklist**
=> Consolidate status information onto /status endpoint

operations/jsonnet/microservices/vulture.libsonnet, operations/kube-manifests/Deployment-vulture.yaml
Remove incorrect CLI flag when using vulture in jsonnet or kube-manifest.
**Checklist**
=> Drop incorrect vulture flag from operations manifests

CHANGELOG.md, pkg/tempofb/SearchBlockHeader_util.go, pkg/tempofb/SearchPage_util.go, pkg/tempofb/searchdata_util.go, pkg/tempofb/types.go, tempodb/search/backend_search_block.go, tempodb/search/pipeline.go, tempodb/search/pipeline_test.go, tempodb/search/streaming_search_block.go, tempodb/search/streaming_search_block_test.go
Maintains a search blocker header for wal blocks like #943 did for completed blocks. This helps eliminate blocks from the search faster for non-existent or sparse values.
The wal requires a mutable header, so some refactoring was done to better fit the search pipeline and the various trace/page/block structs together, i.e. the pipeline can now match directly against a SearchBlockHeaderMutable.
Fixes some of #932 
**Checklist**
=> Add search block headers for wal blocks

CHANGELOG.md, modules/querier/config.go, modules/querier/http.go
Split up `querier.query_timeout` for trace lookup and search queries. Search queries are usually slower than trace lookup queries, splitting them up allows operators to configure them separately.
Part of #932
**Checklist**
=> Split up QueryTimeout for trace and search queries

CHANGELOG.md, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/memcached.libsonnet
Add `memcached.memory_limit` to the `$._config` structure. This will make it easier to increase this as necessary. Since we already expose `connection_limit`, having `memory_limit` seems useful as well.
Default was already 1024
https://github.com/grafana/jsonnet-libs/blob/bc9b685050691a78ee414cd8f789857de0eabe8d/memcached/memcached.libsonnet#L24
**Checklist**
=> Jsonnet: add $._config.memcached.memory_limit

modules/distributor/search_data.go, modules/distributor/search_data_test.go, tempodb/search/util.go
This PR removes capturing of `root.<xyz>` search attributes.  This reduces the size of the search data by ~30%, and seems worth it as in practice these attributes were not very useful to search on.  `root.name` and `root.service.name` are still captured because they are used for display.    
Fixes part of #932 
**Checklist**
=> Search no root attrs

cmd/tempo-cli/main.go, cmd/tempo/main.go, integration/e2e/e2e_test.go, integration/util.go, modules/frontend/deduper.go, modules/frontend/frontend.go, modules/frontend/frontend_test.go, modules/frontend/querysharding.go, modules/frontend/querysharding_test.go, modules/ingester/ingester_test.go, modules/ingester/instance_search_test.go, modules/ingester/instance_test.go, modules/overrides/overrides_test.go, modules/querier/querier_test.go, tempodb/backend/azure/azure.go, tempodb/backend/cache/cache.go, tempodb/backend/cache/cache_test.go, tempodb/backend/gcs/gcs.go, tempodb/backend/local/compactor.go, tempodb/backend/local/local.go, tempodb/backend/local/local_test.go, tempodb/backend/mocks.go, tempodb/backend/s3/s3.go, tempodb/compactor_test.go, tempodb/encoding/streaming_block_test.go, tempodb/retention_test.go, tempodb/tempodb_test.go, tempodb/wal/wal.go, tempodb/wal/wal_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since tempo has upgraded to Go 1.17 (#953), this PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages. This change is transparent to end users.
N/A
**Checklist**
- ~~[ ] Tests updated~~
- ~~[ ] Documentation added~~
- ~~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~
=> refactor: move from io/ioutil to io and os package

cmd/tempo-vulture/main.go, cmd/tempo-vulture/main_test.go, integration/e2e/config-all-in-one-azurite.yaml, integration/e2e/config-all-in-one-gcs.yaml, integration/e2e/config-all-in-one-s3.yaml, integration/e2e/config-microservices.yaml, integration/e2e/e2e_test.go, pkg/util/client.go, pkg/util/errors.go, pkg/util/trace_info.go, pkg/util/trace_info_test.go
Extend the `microservices` e2e test to include search functionality.
Fixes #925
**Checklist**
=> Include simple e2e test to test searching

CHANGELOG.md, cmd/tempo/app/app.go, example/docker-compose/distributed/docker-compose.yaml
Nil check overrides module in /status endpoint
Querier and query-frontend do not run the overrides module. The status handler now checks in that module is being run and skips it in case it isn't.
It also modifies the distributed docker-compose to run minio with `minio` command, instead of executing the binary.
**Checklist**
=> Nil check overrides module in /status endpoint

cmd/tempo/app/modules.go, go.mod, modules/frontend/deduper.go, modules/frontend/frontend.go, modules/frontend/handler.go, modules/frontend/middleware.go, modules/frontend/querysharding.go, modules/frontend/querysharding_test.go, modules/frontend/retry.go, modules/frontend/retry_test.go, modules/querier/http.go
Frontend cleanup in preparation for additional work. More can be done here, but I think this is a good start. Improvements include.
- Rewritten query sharder that more efficiently combines and does so in parallel with incoming requests. We will save ms!
- More detailed comments
- Removal of frontend.Handler which was the exact same as http.Roundtripper
- Reduction of 3 methods of middleware merging to a mere 2. Begone tripperware!
- Dropped dependency on Cortex queryrange package
- Moved request/response logging up to our http.Handler to catch both trace by id and search queries (and all future queries)
- Moved query shards config test into NewMiddleware
- Added "op" label to `query_frontend_queries_total` metric
- Mused about whether our routing should be handled …
=> Frontend Refactor

docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/polling.md
This PR improves the docs associated with blocklist_poll_stale_tenant_index.
https://github.com/grafana/tempo/pull/1005 was merged in without a
doc review.
=> Docs: correct grammar/spelling/formatting of PR 1005

example/docker-compose/agent/docker-compose.yaml, example/docker-compose/azure/docker-compose.yaml, example/docker-compose/distributed/docker-compose.yaml, example/docker-compose/gcs/docker-compose.yaml, example/docker-compose/local/docker-compose.yaml, example/docker-compose/loki/docker-compose.yaml, example/docker-compose/otel-collector-multitenant/docker-compose.yaml, example/docker-compose/otel-collector/docker-compose.yaml, example/docker-compose/s3/docker-compose.yaml
* update examples to patch for https://grafana.com/blog/2021/10/05/grafana-7.5.11-and-8.1.6-released-with-critical-security-fix/
=> Update examples to use grafana:8.1.6

.drone/drone.yml, Makefile
Drone CI has been failing during the docker-arm image-tag step. Log from the Drone runner:
```
latest: Pulling from alpine/git
Digest: sha256:f73275dbb1a12e4322778e8d1cc7bda1656a849fb4b0e6b7fb935e8cf06c5cee
Status: Downloaded newer image for alpine/git:latest
+ apk --update --no-cache add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/2) Installing readline (8.1.0-r0)
(2/2) Installing bash (5.1.4-r0)
Executing bash-5.1.4-r0.post-install
Executing busybox-1.33.1-r3.trigger
1 error; 27 MiB in 34 packages
```
You can reproduce this by running alpine/git locally on a ARM machine:
```
$ docker run -it --entrypoint=/bin/sh alpine/git
/git # apk …
```
=> drone: run apk fix when using alpine/git on ARM

CHANGELOG.md, modules/distributor/search_data.go, modules/querier/querier.go, tempodb/search/pipeline.go, tempodb/search/pipeline_test.go, tempodb/search/util.go
This PR adds support for searching on span status.   Raw span status in OTLP is an integer, and this is recorded as the new tag `status.code=<int>` (this matches the way Grafana already displays this data).   This can be searched directly, or via the following more user-friendly methods:
1.  `status.code=unset|ok|error` - The search pipeline will rewrite the text versions into a lookup for the corresponding integer. The tag name/value lookup apis will return these user-friendly texts and not the integers.
2. `error=true|false` - A new virtual "error" tag can be searched that is rewritten into a lookup on status.code integer. Similarly, the tag name/value lookup apis will return this tag and the two values.
Fixes part of #932 …
=> Support error and status.code searches

operations/tempo-mixin/dashboard-utils.libsonnet, operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/yamls/tempo-reads.json, operations/tempo-mixin/yamls/tempo-writes.json
- Updates the Tempo / Reads dashboard to include search endpoints
- Latency graphs group by route, status/qps graphs group all together (mimics Loki)
- Forks underlying latency_panel function to allow grouping by additional fields
Fixes #924 
**Checklist**
=> Update read dash to include relevant tempo endpoints

CHANGELOG.md, operations/jsonnet/enterprise/.gitignore, operations/jsonnet/enterprise/Makefile, operations/jsonnet/enterprise/jsonnetfile.json, operations/jsonnet/enterprise/jsonnetfile.lock.json, operations/jsonnet/enterprise/main.libsonnet, operations/jsonnet/enterprise/test/eval.jsonnet, operations/jsonnet/enterprise/test/jsonnetfile.json, operations/jsonnet/enterprise/test/jsonnetfile.lock.json
This PR adds a [jsonnet](https://jsonnet.org/) library for [Grafana Enterprise Traces](https://grafana.com/products/enterprise/traces/).
Closes https://github.com/grafana/backend-enterprise/issues/2593
**Checklist**
=> Add jsonnet lib for Grafana Enterprise Traces

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/yamls/alerts.yaml
Tweak the expression of `TempoNoTenantIndexBuilders` so it only fires if there a no tenant index builders _and_ the blocklist is not empty.
In a Tempo cluster that has not received any data yet, there will also not be any tenant index builders.
=> Only fire TempoNoTenantIndexBuilders if blocklist is not empty

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/yamls/alerts.yaml
Adds a configurable namespace label to cortex metrics used for alerts. This can be useful if you're running tempo and cortex in the same cluster.
**Checklist**
=> Add filtering by namespace in non-tempo alerts

CHANGELOG.md, Makefile, cmd/tempo/app/http.go, cmd/tempo/app/modules.go, integration/e2e/compression_test.go, integration/e2e/config-all-in-one-local.yaml, pkg/util/client.go, vendor/github.com/klauspost/compress/gzhttp/LICENSE, vendor/github.com/klauspost/compress/gzhttp/README.md, vendor/github.com/klauspost/compress/gzhttp/gzip.go, vendor/github.com/klauspost/compress/gzhttp/transport.go, vendor/github.com/klauspost/compress/gzhttp/writer/gzkp/gzkp.go, vendor/github.com/klauspost/compress/gzhttp/writer/interface.go, vendor/modules.txt
=> Add gzip middleware to frontend HTTP endpoints

CHANGELOG.md, modules/overrides/limits.go
Signed-off-by: Maarten De Wispelaere <maarten@bitprocessor.be>
The defaults for `MaxBytesPerTrace` and `MaxSearchBytesPerTrace` are broken.
Fixes: https://github.com/grafana/tempo/issues/1110
**Checklist**
=> Fix MaxBytesPerTrace/MaxSearchBytesPerTrace defaults

operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/yamls/tempo-reads.json
PR https://github.com/grafana/tempo/pull/1095 accidentally changed the routes used by the Tempo / Reads dashboard. It hardcoded a `tempo_` prefix. If an HTTP prefix is configured in the jsonnet, this will already be appended by setting `$._config.http_api_prefix`.
=> tempo-mixin: fix routes in Tempo / Reads dashboard

CHANGELOG.md, tempodb/compactor.go, tempodb/encoding/iterator_multiblock.go, tempodb/encoding/iterator_multiblock_test.go
This PR patches over https://github.com/grafana/tempo/issues/1107 by logging a warning and continuing instead of failing with an error. Research concludes that somehow empty traces are being written to blocks.  The compactor bookmarks have already been unintentionally skipping empties in _most_ cases, but there are a few edge cases that are not skipped and led to this error.  Therefore skipping all seems ok.  We have not yet determined how the empty traces originate, or what changed between 1.1 and 1.2, but this fix should alleviate 1.2 troubles for the users encountering this bug.  
Fixes #1107 
**Checklist**
=> V1.2 compaction error fix

.golangci.yml, pkg/model/encoding.go, tempodb/backend/raw.go, tempodb/backend/tenantindex.go, tempodb/search/pipeline.go, tempodb/wal/replay.go
Here we make the necessary updates to address the deprecations warning.  Replace `golint` with `revive` and remove `interfacer` due to non-maintenance and limited functionality.  Also sort.
=> Update golangci linters for deprecation warnings

modules/querier/querier_search.go, modules/querier/querier_search_test.go
If a `tags` parameter is found the code now uses that as a "flag" to no longer parse tags the old way.
=> Improve Tag Parsing on Search

CHANGELOG.md, modules/compactor/compactor.go, modules/querier/querier_test.go, pkg/model/combine.go, pkg/model/combine_test.go, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/encoding/common/types.go, tempodb/encoding/finder_paged.go, tempodb/encoding/iterator_deduping.go, tempodb/encoding/iterator_deduping_test.go, tempodb/encoding/iterator_multiblock.go, tempodb/search/data_combiner.go, tempodb/search/streaming_search_block.go, tempodb/wal/wal_test.go
- Improves combine efficiency when combining more than 2 objects with the same id by only marshalling to/from proto once
- Adds an error return from the ObjectCombiner.Combine() method and bubbles it up. (replaces #1111)
**Checklist**
=> Improve Combine Efficiency

CHANGELOG.md, cmd/tempo/app/modules.go, docs/tempo/website/configuration/_index.md, modules/overrides/limits.go, modules/overrides/overrides.go
=> Include metrics for configured limit overrides

operations/tempo-mixin/Makefile, operations/tempo-mixin/dashboard-utils.libsonnet, operations/tempo-mixin/jsonnetfile.lock.json, operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/grafana-builder/grafana.libsonnet, operations/tempo-mixin/yamls/tempo-reads.json, operations/tempo-mixin/yamls/tempo-resources.json, operations/tempo-mixin/yamls/tempo-writes.json
~~This is a temporary patch until https://github.com/grafana/jsonnet-libs/pull/703 is merged.~~ Update the grafana-builder jsonnet library to include https://github.com/grafana/jsonnet-libs/pull/703
More details can be found in that issue as well.
> This dropdown is populated with the namespaces a Tempo cluster is running in. The current behaviour (with allValue: '.+') is confusing, because selecting All in the dropdown ends up querying all namespaces.
The previous behaviour (with allValue: null) only queries the namespaces that are returned by the query.
>
> The reason we got confused is that in our dashboard you can select a cluster and if you know there is only 1 Tempo namespace in that cluster you kind of expect to only see data from that namespace. But with …
=> tempo-mixin: clear allValue so selecting All namespaces only queries Tempo namespaces

CHANGELOG.md, tempodb/blocklist/poller.go
There is a bug where the tenant index age will not be updated correctly for the tenant index writer. To reproduce:
- Scale to a bunch of compactors
- Allow a poll cycle to complete.
- Scale to 1 compactor. This compactor is now the tenant index writer for all tenants and so it will no longer update `tempodb_blocklist_tenant_index_age_seconds` for any tenants. All of the tenants it had previously been polling (and not writing) will now grow stale.
- Watch the metrics for all tenants show stale even though it's not true.
To fix just force roll the compactors and they should reset their metrics correctly.
**Checklist**
=> Bugfix: Tenant index writer does not update age

.github/workflows/ci.yml, operations/kube-manifests/ConfigMap-tempo-compactor.yaml, operations/kube-manifests/ConfigMap-tempo-distributor.yaml, operations/kube-manifests/ConfigMap-tempo-ingester.yaml, operations/kube-manifests/ConfigMap-tempo-querier.yaml, operations/kube-manifests/ConfigMap-tempo-query-frontend.yaml, operations/kube-manifests/Deployment-compactor.yaml, operations/kube-manifests/Deployment-distributor.yaml, operations/kube-manifests/Deployment-querier.yaml, operations/kube-manifests/Deployment-query-frontend.yaml, operations/kube-manifests/StatefulSet-ingester.yaml, operations/kube-manifests/util/jsonnetfile.lock.json
CI has been failing since Tanka has released v0.19: https://github.com/grafana/tanka/blob/main/CHANGELOG.md#0190-2021-11-22
This pins the version to 0.19 and updates the kube-manifests.
=> Pin version of tanka used in CI, update kube-manifests

CHANGELOG.md, tempodb/compactor.go
Adds new metric to measure compaction load. It counts the number of blocks that are yet to be compacted before the next maintenance cycle. It's higher, the greater the compaction load is.
**Checklist**
=> Compaction load metric

CHANGELOG.md, operations/tempo-mixin/dashboards.libsonnet, operations/tempo-mixin/tempo-operational.json, operations/tempo-mixin/yamls/tempo-operational.json, operations/tempo-mixin/yamls/tempo-reads.json, operations/tempo-mixin/yamls/tempo-writes.json
* Update examples and operations to use the newer backend-agnostic metric name.
**Checklist**
=> Update mixin to use new backend metric

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, docs/tempo/website/configuration/polling.md, modules/compactor/config.go, modules/storage/config.go, tempodb/compactor.go, tempodb/config.go
- Moves the max_compaction_cycle parameter to the appropriate config block
- Renames it to be more descriptive `max_time_per_tenant`
**Checklist**
=> Fix location of max compaction parameter

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/azure.md, modules/storage/config.go, tempodb/backend/azure/azure_helpers.go, tempodb/backend/azure/azure_test.go
Allow default values for Azure storage to be pulled from the environment.
Update examples and operations to use the newer backend-agnostic metric name.
**Checklist**
=> Allow environment variables for Azure storage credentials

CHANGELOG.md, example/docker-compose/otel-collector-multitenant/otel-collector.multitenant.yaml, example/docker-compose/otel-collector/otel-collector.yaml
#1142 Changed the default OTLP/GRPC port. This PR updates examples to work and notes it as a breaking in the changelog.
**Checklist**
=> Update examples to use the new port

CODEOWNERS, GOVERNANCE.md, MAINTAINERS.md
Proposal to make @zalegrala a maintainer. An approving review is a vote in favor. He has been particularly active in improving our automated testing but has also made contributions to Tempo proper.
- [Tempo Work](https://github.com/grafana/tempo/pulls?q=is%3Apr+author%3Azalegrala+is%3Aclosed)
- [Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+reviewed-by%3Azalegrala+is%3Aclosed)
Additionally Zach has participated in the public slack and has attended the community calls.
=> Make Zach Leslie maintainer

CHANGELOG.md, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/querier.libsonnet, operations/kube-manifests/Deployment-distributor.yaml, operations/kube-manifests/Deployment-querier.yaml, operations/kube-manifests/Deployment-query-frontend.yaml, operations/kube-manifests/util/jsonnetfile.lock.json
Increase max surge for all components except ingesters and compactor. This should speed up rollouts by a factor of 3 without increasing risks.
=> jsonnet: set rollingUpdate.maxSurge to 3 for distributor, frontend and queriers

integration/e2e/config-all-in-one-local.yaml, integration/e2e/config-limits.yaml, integration/e2e/config-microservices.yaml, integration/e2e/config-scalable-single-binary.yaml, integration/e2e/e2e_test.go
Two changes:
- One was to increase the `max_search_bytes_per_trace` to account for large vulture traces (actually a lot of search tags added in any given trace)
- Increase `trace_idle_period` in TestMicroservices. It was set to `100ms` and vulture was emitting multiple batches (taking longer than 100ms for each send I guess) and this was counted as multiple traces at the ingester -> taking the ingester traces created metric to 2 instead of the expected value of 1 which we were waiting on
=> Increase limits for integration tests to account for large vulture traces

CHANGELOG.md, modules/ingester/instance.go, modules/ingester/instance_test.go, pkg/util/test/metrics.go
Adds metric for ingester live traces per tenant.  It is updated each sweep interval.
Fixes #1120 
**Checklist**
=> Metric live traces

CHANGELOG.md, pkg/api/http.go
Export the `URLParamTraceID` constant in the `api` package as this constant was already exported in the `util` package prior to version 1.2.
**Checklist**
- ~[ ] Tests updated~
- ~[ ] Documentation added~
=> export trace id constant in api package

modules/ingester/instance.go
Log the tenant ID that is being rate limited by live traces.
=> Log the tenant ID in the live traces exceeded error

modules/distributor/distributor.go, modules/distributor/receiver/shim.go
Ensure the trace context is propagated to all ingesters and add a couple of spans.
Result:
=> instrumentation: fix trace context propagation distributor -> ingester

docs/tempo/website/api_docs/_index.md
Reviewers: https://github.com/grafana/tempo/pull/1045 got merged in without a Doc team reviewer.  This PR corrects a few documentation items from PR 1045.  When reviewing this PR, please pay close attention to the paragraph that begins "Displays the configuration currently applied to Tempo (in YAML format)..." I moved this paragraph to the portion of the section that describes /status/config, which is where it was placed before PR 1045; plus, the paragraph seems to me to describe /status/config, and not /runtime_config.  Let me know in a review if I have incorrectly moved the paragraph.
=> Docs: revise GET /status/config and /runtime_config descriptions

tempodb/encoding/v2/page.go, tempodb/encoding/v2/page_test.go
Detects incomplete pages during unmarshalling and raises an error.   Previously it would have silently returned the partially read buffer.  This is primarily for None encoding, as the other compression encodings would have caught it already during decompression.
Fixes #1195 
**Checklist**
=> Detect incomplete page read and return error

CHANGELOG.md, modules/ingester/instance.go, modules/ingester/instance_test.go, modules/ingester/trace.go
This PR updates the ingester to keep track of traces that exceeded max size and reject further writes to them, even after they are flushed to disk. The list of traces is reset when cutting the head block. 
Fixes part of #1133 
**Checklist**
=> Ingester prevent writes to large traces even after flushing

docs/tempo/website/release-notes/v1-2.md
This backports the addition of the v1.2.1 release notes to the published v1.2.1 docs. (They were only in the "next" version.)
=> Docs: Add v1.2.1 release note items (#1125)

docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, integration/e2e/config-serverless.yaml, modules/querier/config.go, modules/querier/querier.go
- Changes the `search_external_endpoint` setting to `search_external_endpoints` and takes a list of strings.
- Randomly choose one of the endpoints in the list
- Adds a per external endpoint duration metric.
Ticks a box on #1175 
**Checklist**
=> Backend Search: Add the ability to use a pool of external endpoints

CHANGELOG.md, cmd/tempo-cli/cmd-query-search.go, integration/e2e/e2e_test.go, integration/e2e/serverless_test.go, pkg/util/client.go
Backend search is triggered by passing the `start` and `end` parameters to the `/api/search` endpoint. This PR adds some cli options to do exactly that. Also straightens out some type wrangling with the `client.SearchWithRange` function. 
Ticks a box on #1175 
**Checklist**
=> Backend Search: Added cli option to query a range

pkg/model/matches.go, pkg/model/matches_test.go
Adds support for tag types besides strings. Does not attempt more esoteric types such as array or kvlist.
Checks a box on #1175
**Checklist**
=> Backend Search: Added support for bool, double and int tags

docs/design-proposals/README.md
Add a new directory `design-proposals` in which we can capture future design proposals. I've also added a README suggesting an initial process. This is just an initial suggestion that we can improve incrementally as we gain experience with this process.
=> Add design-proposals directory

integration/e2e/receivers_test.go
Fix e2e tests broken by https://github.com/grafana/tempo/pull/1215
n/a
**Checklist**
=> Fix e2e tests

modules/frontend/searchsharding.go, pkg/api/http.go, pkg/api/http_test.go
- Prioritizes the ingester search over backend. Currently the ingester search (which may return very quickly) can get stuck behind 1000s of backend searches.
- Fixed an issue where min/max duration and limits were being set for the queriers even though they were not set in the initial query.
=> Backend Search: Two fixes

CHANGELOG.md, Makefile
It update goreleaser install method from [deprecated](https://github.com/goreleaser/godownloader/issues/207) goreleaser/godowlowader to [go install](https://goreleaser.com/install/#go-install).
goreleaser is mainly used in the release CI job, in which we previously [set up go](https://github.com/grafana/tempo/blob/main/.github/workflows/release.yml#L10).
**Checklist**
=> Update goreleaser install method

docs/tempo/website/release-notes/v1-3.md
We're not listing any of the bugs fixed for v1.3.0, so remove the subsection from the release notes.
=> Docs: remove unneeded v1.3.0 bug fix release notes subsection

pkg/model/matches_test.go, pkg/model/trace/matches.go, tempodb/search/pipeline.go, tempodb/search/util.go
The previous PR (#1234) incorrectly tested for all conditions to be true on a single span which would make backend search behave differently then ingester search. This PR
- correctly tests to make sure query conditions are true across the entire trace
- adds support for `name`, `status.code` and `error` tags
- removes an errant .zip file from the repo
Respect to @annanay25 for his earlier suggestion. My approach of asserting conditions per span was wrong from the start! Using a map to track conditions across the entire trace was the correct approach.
=> Tempo Backend Search: Actual Fixes

.drone/drone.jsonnet, .drone/drone.yml
arm64 builds are failing because the `alpine/git` container has apk errors. When Drone tries to execute any apk command, the command says there are errors and fails which causes the whole pipeline to fail.
```
latest: Pulling from alpine/git
Digest: sha256:d4740deff7f05d2d48771ff66d9d9c26dfb76f0db0aa833b1ea0ee346fa1e48f
Status: Downloaded newer image for alpine/git:latest
+ apk fix
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/1) [APK unavailable, skipped] Reinstalling ca-certificates (20191127-r5)
1 error; 25 MiB in 32 packages
```
There are more details in this issue upstream: https://github.com/alpine-docker/git/issues/35
Previously …
=> drone: pin alpine/git image to avoid apk errors on arm64

.drone/drone.jsonnet, .drone/drone.yml
(cherry picked from commit be6476d9a1d171055f284c434f3432615258ca1c)
Cherry pick #1242 onto r28, this is needed to build a Docker image for this branch.
=> Cherry-pick: drone: pin alpine/git image to avoid APK errors on arm64

docs/tempo/website/getting-started/tempo-in-grafana.md, docs/tempo/website/release-notes/v1-3.md
Add this in the release notes and in the feature documentation.
=> Docs: Reword to note Grafana does not yet have tempoBackendSearch toggle

CHANGELOG.md, operations/jsonnet/enterprise/main.libsonnet
The jsonnet for GET creates a job to generate the token from a GET license (`tokengen`). This job should be created once when installing GET and the job can not be modified afterwards. To make this easier to manage, this PR adds a config option `run_tokengen_job` which is disabled by default and can be set to explicitly create the tokengen job.
_How it works:_
The first time a GET cluster is created the user should set:
```jsonnet
_config+:: {
run_tokengen_job: true,
},
```
During `tk apply`, tanka will create the tokengen job (just like before). After the job has run, the user should remove this line and the tokengen job will not be modified anymore by tanka.
**Checklist**
=> Enterprise jsonnet: add config to create tokengen job explicitly

CHANGELOG.md, cmd/tempo-serverless/go.mod, cmd/tempo-serverless/go.sum, go.mod, go.sum, integration/e2e/config-microservices.tmpl.yaml, integration/e2e/e2e_test.go, pkg/gogocodec/gogocodec.go, vendor/go.etcd.io/etcd/api/v3/version/version.go, vendor/modules.txt
Registers etcd's server proto in gogoproto codec
Fixes #1213 
**Checklist**
=> Gogoproto coded etcd

docs/tempo/website/configuration/_index.md
The polling link is broken in this doc. Removing!
=> Docs: Remove TOC entry that links to nothing

Makefile, cmd/tempo-serverless/Makefile
Break vendor-check into a new command update-mod, which is responsible
for keeping tempo's and tempo serverless' go.mod and tempo vendor file tidy.
=> Makefile: add update-mod to tidy go.mod's

operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/yamls/alerts.yaml
Introduce a `for: 5m` statement in the TempoComapctiosnFailing alert in order to reduce its sensitivity.
Fixes #1270
**Checklist**
=> Add a for statement for TempoCompactionsFailing alert

.github/workflows/ci.yml
In order to require CI checks to pass for PRs to be merge-able, those checks need to be *always* run.  Even if the changes do not require them (i.e. `docs/**`, `example/**` and `tools/**` paths).
This PR comments out the ignore of said paths, so CI is always run.
=> Require for CI checks to always pass

.github/workflows/ci.yml
The vendor-check job is getting rate-limited when downloading protoc.
Example: https://github.com/grafana/tempo/runs/5233640313?check_suite_focus=true
The documentation says to use GITHUB_TOKEN to authenticate requests: https://github.com/arduino/setup-protoc#usage
Permissions this token has by default seem limited: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
**Checklist**
=> ci: use GITHUB_TOKEN in setup-protoc to avoid rate-limtiing

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/runbook.md, operations/tempo-mixin/yamls/alerts.yaml
Adds new alerts to the tempo-mixin.
- `TempoProvisioningTooManyWrites`: measures number of writes to ingesters stays below a defined target (30MB/s per ingester).
- `TempoCompactorsTooManyOutstandingBlocks`: measures that the number of blocks pending to be compacted does not go above a target.
- `TempoBadOverrides`: monitors failed override reloads.
**Checklist**
=> Add new alerts to the tempo-mixin

CHANGELOG.md, example/docker-compose/agent/agent.yaml, example/docker-compose/agent/docker-compose.yaml, example/docker-compose/local/docker-compose.yaml, example/docker-compose/otel-collector-multitenant/docker-compose.yaml, example/docker-compose/otel-collector/docker-compose.yaml, example/docker-compose/otel-collector/readme.md, operations/kube-manifests/ConfigMap-tempo-distributor.yaml, operations/kube-manifests/Deployment-distributor.yaml, operations/kube-manifests/util/example/main.jsonnet
OTLP listening port was changed from 55680/55681 to 4317/4318, updated in Tempo in https://github.com/grafana/tempo/pull/1142. This PR cleans all references (docker-compose examples mainly) from the legacy ports and uses the new ones.
Fixes #1293
**Checklist**
=> Update examples and configs OTLP ports

CHANGELOG.md, cmd/tempo-vulture/main.go
- Updates the vult to search for tags over the entire range using the `tempo-retention-duration` parameter.
- Drops the `tempo-search-retention-duration` parameter.
**Checklist**
=> Update the vult to use backend search

CHANGELOG.md, docs/tempo/website/getting-started/tempo-in-grafana.md, docs/tempo/website/release-notes/v1-3.md
- Updates the changelog for the 1.3.2 release
- Updates the release notes with the 1.3.2 bug fix
- Adds the Grafana version for backend search capabilities.
=> Update changelog for v1.3.2

modules/ingester/ingester_test.go, modules/ingester/instance_search_test.go, modules/ingester/instance_test.go, tempodb/backend/local/local_test.go, tempodb/compactor_test.go, tempodb/encoding/streaming_block_test.go, tempodb/retention_test.go, tempodb/tempodb_test.go, tempodb/wal/wal_test.go
A testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
**Checklist**
=> test: use `T.TempDir` to create temporary test directory

modules/generator/remotewrite/appendable.go, modules/generator/remotewrite/appendable_test.go, modules/generator/remotewrite/appender.go, modules/generator/remotewrite/appender_test.go
Make sending exemplars configurable by respecting the send_exemplars field on the remote write config.
Linked to https://github.com/grafana/tempo/issues/1303
**Checklist**
=> metrics-generator: respect remote_write.client.send_exemplars

modules/generator/instance.go, modules/generator/processor/registry.go, modules/generator/processor/registry_test.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/processor/spanmetrics/spanmetrics_test.go
Add a metric `tempo_metrics_generator_active_series` that exposes the amount of active series managed by this instance (and per tenant). From tests this matches exactly with what Prometheus reports in its status pages ✨ 
Linked to https://github.com/grafana/tempo/issues/1303
**Checklist**
=> metrics-generator: expose active_series metric

CHANGELOG.md, docs/tempo/website/configuration/_index.md, go.mod, modules/querier/config.go, modules/querier/querier.go, modules/querier/querier_test.go, modules/querier/worker/worker.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/semaphore/semaphore.go, vendor/modules.txt
- Adds a configuration option to allow the queriers to perform a configurable number of searches locally before reaching out to the external endpoints
- Adds docs for `max_concurrent_queries`
Ticks a box on #1175 
**Checklist**
=> Tempo Serverless: Queriers Prefer Self

operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/dashboards/tempo-operational.json, operations/tempo-mixin/dashboards/tempo-resources.libsonnet, operations/tempo-mixin/yamls/tempo-operational.json, operations/tempo-mixin/yamls/tempo-resources.json
Tweak `Tempo / Resources` to add a row for the metrics-generator.
Tweak `Tempo / Operational` to add `metrics-generator` and `query-frontend` to the component dropdown.
I've also adjusted the query powering the `namespace` dropdown. `label_values(tempo_build_info, namespace)` is also used in the other dashboards.
Related to #1303 
**Checklist**
=> tempo-mixin: add metrics-generator to Tempo / Resources and Operational

modules/generator/processor/servicegraphs/config.go
We accidentally copied `mapstructure` struct tags from the agent code, this don't work when reading from a yaml file 😅 
**Checklist**
=> metrics-generator: use yaml struct tags instead of mapstructure

CHANGELOG.md, example/docker-compose/distributed/tempo-distributed.yaml, integration/e2e/config-scalable-single-binary.yaml, modules/ingester/ingester.go, modules/ingester/instance.go, modules/ingester/trace.go, modules/ingester/trace_test.go, pkg/model/segment_decoder.go, pkg/model/segment_decoder_test.go, pkg/model/v1/segment_decoder.go, pkg/model/v2/segment_decoder.go, tempodb/backend/block_meta.go, tempodb/backend/block_meta_test.go, tempodb/compactor_test.go, tempodb/encoding/streaming_block.go, tempodb/tempodb_test.go, tempodb/wal/append_block.go, tempodb/wal/replay.go, tempodb/wal/wal.go, tempodb/wal/wal_test.go
Currently min/max times on block ranges are based on the ingestion time of spans. This PR does two things:
- Makes the min/max time range on the blocks dependent on the span times
- Correctly restores min/max time of a block on wal replay
These two changes will improve accuracy of searches.
Ticks a box on #1175
**Checklist**
=> Make min/max block times based on span times

modules/generator/generator.go, modules/generator/instance.go, modules/generator/instance_test.go, modules/generator/processor/interface.go, modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/spanmetrics/spanmetrics_test.go
* Return value of error tooManySpansError instead of reference. As a consequence, `errors.Is` was failing to detect it.
*  Remove error return in PushSpans method
* We don't want to stop processing due to an error in one of the processor. Errors can be handled and logging inside the processors.
**Checklist**
=> Return value of error tooManySpansError instead of reference

CHANGELOG.md, cmd/tempo-serverless/handler.go
Repeated calls to the same serverless function can start to put pressure on the go runtime and massively slow down search. This simple change increases search reliability significantly.
**Checklist**
=> Serverless: Call runtime.GC() in the handler

example/docker-compose/local/docker-compose.yaml
I was banging my head against the wall yesterday trying to figure out why my local application was unable to push traces to tempo, and why I was unable to `curl localhost:3200` without getting `connection refused`.
I assumed that this port stuff worked when looking at it, but the only thing that fixed it for me was explicitly setting the local port in the docker-compose file.
=> add local port to docker-compose.yaml

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, modules/ingester/ingester.go, modules/storage/config.go, tempodb/wal/append_block.go, tempodb/wal/wal.go, tempodb/wal/wal_test.go
Adds a new config option to restrict the time range around now that Tempo will honor when updating the current block start and end times. The new option defaults to `2m` meaning that if a span is received outside of this time range it will be stored and findable by trace id, but the block's time range it is stored in will not reflect this. This will make it less likely to be found using a trace search query.
One gross corner is that during WAL replay we have to assume that we should adjust the block's time range based on the maximum time that a WAL file will be kept since we don't know when it was created.
**Checklist**
=> TempoDB: Restrict Ingestion time range

cmd/tempo-serverless/handler.go
While trying to find some performance improvements in the serverless handler I noticed we weren't closing the iterator.
=> Tempo Serverless: defer iter.Close()

integration/e2e/config-metrics-generator.yaml
Tweak the `TestMetricsGenerator` e2e test to use the same path for the ingester and the metrics-generator WAL. This is more consistent.
Since Tempo runs in microservices mode they don't share this directory, it's just the same path.
=> e2e: store the metrics-generator WAL in /var/tempo

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, modules/frontend/config.go, modules/frontend/frontend.go, modules/frontend/frontend_test.go, modules/frontend/hedged_requests.go
Drastically reduces variance in search requests by hedging. Adds two new config options with defaults:
```
query_frontend:
search:
hedge_requests_at: 5s
hedge_requests_up_to: 3
```
These two defaults were chosen b/c they work well internally.
**Checklist**
=> Backend Search: Hedged Requests

modules/generator/storage/instance.go, modules/generator/storage/instance_test.go
When creating a metrics-generator `storage.Instance`, verify we can write to the given path before creating any resources. If we create Prometheus' `remote.Storage` twice, it will panic as metrics are registered twice.
**Checklist**
=> metrics-generator: verify WAL is writeable

integration/e2e/backend/backend.go, integration/e2e/config-all-in-one-azurite.yaml, integration/e2e/config-all-in-one-gcs.yaml, integration/e2e/config-all-in-one-local.yaml, integration/e2e/config-all-in-one-s3.yaml, integration/e2e/config-microservices.tmpl.yaml, integration/e2e/config-scalable-single-binary.yaml, integration/e2e/e2e_test.go, integration/e2e/serverless/config-serverless.yaml, integration/e2e/serverless/serverless_test.go
Changes:
- Always check `tempo_ingester_traces_created_total` is _at least_ 1.  Some tests expect exactly 1 trace was created, others just expected more than 0. Let's always check traces created is >0. I saw tests fail because 2 traces were created while 1 was expected.
**Checklist**
=> e2e: reduce flakiness

Makefile, cmd/tempo/app/modules.go, modules/generator/generator.go, modules/generator/instance.go, modules/generator/instance_test.go, modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/storage/instance_test.go
Small refactor to pass `log.Logger` to every component that logs something instead of relying on the global logger variable. This makes it easier to add common labels to logs and allows us to control logging better in tests.
=> metrics-generator: consistently pass log.Logger around

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, modules/storage/config.go
- Updates the docs and config defaults to match each other
- Improves the queue_depth default to 10000
Fixes #1344 
**Checklist**
=> Improve defaults for worker pool

docs/tempo/website/api_docs/_index.md, docs/tempo/website/configuration/querying.md, docs/tempo/website/getting-started/example-demo-app.md, docs/tempo/website/operations/deployment.md, docs/tempo/website/release-notes/v1-2.md, example/docker-compose/scalable-single-binary/readme.md, example/helm/readme.md, example/tk/readme.md
We've standardized on this as the terminology we want to use for all of our backends, and have already made the changes in [Loki](https://grafana.com/docs/loki/next/fundamentals/architecture/deployment-modes/) and Mimir. See related slack [thread](https://raintank-corp.slack.com/archives/C02RJ13QB4K/p1645818793120839).
The rationale for moving away from 'single binary' is that Tempo (and Loki, and Mimir) are always a 'single binary', whether or not you are deploying as microservices.(In a microservices deployment, each component is the same 'single binary', but it just has a different value of the target flag.)
=> Updated this page to refer to 'monolithic' instead of 'single binary'

.github/workflows/ci.yml
Update golangci-lint to latest which includes support for 1.18 (even though Tempo isn't using it directly). This PR was having issues:  https://github.com/grafana/tempo/runs/5818491537?check_suite_focus=true  and I think it's related and something changed recently.  Notably the previous step sets up 1.17, but then golangci-lint sets up 1.18 anyway.   The docker images are using 1.18 now too:
```
$ docker run -it golangci/golangci-lint:v1.45.2-alpine go version
go version go1.18 linux/amd64
```
~This means there is more cleanup to do:  golangci-lint has a parameter `skip-go-installation` which can be set to `true` that we aren't using. Options:~
~1. Turn on `skip-go-installation` and stick with 1.17.~
~2. Remove the first `setup-go` step and let golangci-lint do it~ …
=> update golint-ci to latest

modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/store/edge.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/registry/appender_test.go, modules/generator/registry/counter_test.go, modules/generator/registry/histogram.go, modules/generator/registry/histogram_test.go, modules/generator/registry/interface.go, modules/generator/registry/registry_test.go, modules/generator/registry/test.go, modules/generator/registry/test_test.go
Follow up from #1340 and adds the capability to capture and remote write exemplar.
Related to #1303 
**Checklist**
=> metrics-generator: emit exemplars

cmd/tempo-vulture/main.go, modules/generator/processor/servicegraphs/config.go, modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/processor/servicegraphs/store/edge.go, modules/generator/processor/spanmetrics/spanmetrics.go, pkg/util/attributes.go, pkg/util/attributes_test.go, vendor/github.com/prometheus/prometheus/util/strutil/quote.go, vendor/github.com/prometheus/prometheus/util/strutil/strconv.go, vendor/modules.txt
Add dimensions to the service graphs processor config, which attaches
additional labels to the metrics from spans attributes.
It also renames the expired edges internal metric.
=> Service graphs: add dimensions and rename expired edges metric

example/docker-compose/distributed/docker-compose.yaml, example/docker-compose/distributed/grafana-datasources.yaml
Enable exemplars in Prometheus, configure Grafana to link exemplars to Tempo. Together with the latest Tempo image (containing #1364) this should show the full flow.
**Checklist**
=> examples: enable exemplars in distributed docker-compose example

modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/spanmetrics/spanmetrics_test.go, modules/generator/processor/util/util.go, modules/generator/processor/util/util_test.go
If the span metrics processor can not find the custom dimension on the span, updating the metric will panic as our label values will be incomplete.
Changes:
- ensure we always add a label value, even if it's empty (`""`)
- look in both the resource attributes and the span attributes for custom dimensions
- sanitize dimensions to ensure they are valid Prometheus labels
- some formatting/naming changes to make the imports consistent across the processors
Note that if we can't find the dimension in the attributes we will add a label with an empty value (`label=""`). This is fine as empty labels are filtered out before writing them to the WAL.
https://github.com/prometheus/prometheus/blob/main/tsdb/agent/db.go#L706-L708
Just appending an empty label value keeps logic …
=> metrics-generator: handle missing dimensions

modules/generator/storage/config.go, modules/generator/storage/config_test.go, modules/generator/storage/config_util.go, modules/generator/storage/config_util_test.go, modules/generator/storage/instance_test.go
Simplify the config a bit. This does not change how config is parsed.
Related to #1303
**Checklist**
=> metrics-generator: change []*RemoteWriteConfig to []RemoteWriteConfig

docs/tempo/website/api_docs/_index.md, docs/tempo/website/operations/consistent_hash_ring.md
Extend the API reference and the consistent hash ring page to list the new metrics-generator ring.
This is the first (of many) PRs to document the metrics-generator. We will also have to describe the new config options in the configuration section and update various other pages.
Related to https://github.com/grafana/tempo/issues/1303
**Checklist**
=> docs: document metrics-generator ring

CHANGELOG.md, tempodb/encoding/v2/appender.go
A shared instance of xxhash causes a data race and crash in the ingester. This PR fixes by converting the shared instance to a local variable.
Fixes #1384
**Checklist**
=> Prevent data race by using xxhash instance as a local variable

modules/generator/instance_test.go, modules/generator/registry/overrides.go, modules/generator/registry/registry.go, modules/generator/registry/registry_test.go, modules/overrides/limits.go, modules/overrides/overrides.go
Add an override `metrics_generator_disable_collection` which tells the registry to not collect and write samples for this tenant. This will break the link between the registry and the storage layer (which is responsible for remote writing metrics).
The metrics-generator will still generate metrics and keep track of all the counters and histograms. If you don't want to generate metrics at all, you should clear `metrics_generator_processors` for this tenant.
This setting is useful if you want to ingest data into the metrics-generator, observe resource usage and active series, but don't want to write real metrics. This should be especially handy if you are concerned about the generated active series overwhelming a downstream TSDB. …
=> metrics-generator: add override to disable metrics collection

CHANGELOG.md, docs/tempo/website/troubleshooting/max-trace-limit-reached.md, modules/ingester/instance.go, modules/ingester/instance_test.go, modules/ingester/trace.go
This PR adds the tenant ID (internally called instance ID) to the trace too large error messages.
**How to test it**:
Set the `max_bytes_per_trace` override to a pretty small number so sending traces will trigger the "trace too large" error easily and you should see a similar message as the following one:
```
level=warn ts=2022-04-14T12:51:52.707097Z caller=grpc_logging.go:38 method=/tempopb.Pusher/PushBytesV2 duration=275.917µs err="rpc error: code = FailedPrecondition desc = TRACE_TOO_LARGE: max size of trace (1) exceeded while adding 283 bytes to trace a0fbd6f9ac5e2077d90a19551dd67b6f for tenant single-tenant" msg="gRPC\n"
```
Fixes #1367 
**Checklist**
=> Adding tenant ID (instance ID) to the trace too large error messages

CHANGELOG.md, tempodb/backend/azure/azure.go, tempodb/backend/azure/azure_test.go
In certain cases we were not correctly translating errors from ABS into `backend.ErrDoesNotExist`. This PR corrects that issue by doing the following:
- Update `readError` to descend wrapped errors to find errors of type `blob.StorageError`
- Removes the wrapping that was causing the initial issue. It didn't add anything of value.
- Appropriate testing added 
Fixes the other part of #1372 along with #1389
**Checklist**
=> Fix Azure Error Handling

CHANGELOG.md, tempodb/blocklist/list.go, tempodb/blocklist/list_test.go, tempodb/compactor.go, tempodb/retention.go, tempodb/retention_test.go
This PR fixes retention to immediately update the in-memory blocklist for changes.  This prevents errors if retention runs twice before the next polling cycle, where it would try to retain the same block twice.
Note - We already do this [after compaction](https://github.com/grafana/tempo/blob/main/tempodb/compactor.go#L175), but it only added compactedMeta.  Now we are removing too, so there is a new function param and test cases in `blocklist.Update`.
Fixes part of #1372 
**Checklist**
=> Fix retention to immediately update the in-memory blocklists for changes

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/runbook.md, operations/tempo-mixin/yamls/alerts.yaml
* replace the exiting critical alert for TempoIngesterFlushes with a warning, and lengthen the critical threshold duration
* replace the metric used for TempoIngesterFlushes to only measure retries
**Checklist**
=> Update mixin for TempoIngesterFlushes thresholds

integration/e2e/config-all-in-one-azurite.yaml, integration/e2e/config-all-in-one-gcs.yaml, integration/e2e/config-all-in-one-s3.yaml, integration/e2e/e2e_test.go, integration/e2e/serverless/serverless_test.go
Some tweaks to make our integration tests more consistent. Changes made:
**All In One Improvements**
- Removed `max_block_bytes` preferring `max_block_duration` to cut the head block.
- Halved blocklist poll to reduce the chance of failures due to not seeing blocks in the backend
- Removed innocuous `object_` fields from all in one gcs tests
- Increased `max_block_duration` and `complete_block_timeout` to `5s` and retimed tests around it
**All Integration Test Improvements**
- Changed all `tempo_ingester_traces_created_total` to both wait for missing metrics and to pass as long as the value of the metric is less than 3. We were seeing a lot of failures b/c this metric was equal to 2 sometimes. This was likely occuring due to unfortunate timing on pushing a trace in multiple batches.
- …
=> Fix integration tests

.drone/drone.jsonnet, .drone/drone.yml
Here we fix the name of the bucket we use for serverless deployments.
=> Use correct bucket for serverless deployments

cmd/tempo-serverless/Makefile
Here we update the build flags for Lambda to avoid using libc.  This will allow us to compile and execute on platforms that differ in their libc version by building the dependencies we require into the binary.
=> Avoid libc for serverless lambda build

Makefile
Pins goreleaser to a version that works with our CI pipeline. This can be unpinned when we move to 1.18.
=> Pin Go Releaser

docs/tempo/website/configuration/_index.md, modules/overrides/overrides.go
Forgot to update docs in https://github.com/grafana/tempo/pull/1375.
Related to #1303 
**Checklist**
=> docs: document metrics_generator_disable_collection override

operations/tempo-mixin/dashboards/tempo-reads.libsonnet, operations/tempo-mixin/yamls/tempo-reads.json
Amend the `reads` dashboard to include new external endpoint metrics.
**Checklist**
=> Include querier_external_endpoint metrics in mixin dashboard

CHANGELOG.md, modules/generator/storage/config_util.go, modules/generator/storage/config_util_test.go
The metrics-generator will always inject the `X-Scope-OrgID` header set to the current tenant. This doesn't make sense when run in single tenant modus.
**Checklist**
=> metrics-generator: don't inject X-Scope-OrgID header for single-tenant setups

CHANGELOG.md, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/encoding/common/interfaces.go, tempodb/encoding/v2/compactor.go
This PR fixes some things that were broken by refactor #1351.  (1) the `compaction_objects_combined_total` metric is now populated again.  (2) the per-tenant override `max_bytes_per_trace` is honored again, and the corresponding metric `tempo_discarded_spans_total{reason="trace_too_large_to_compact"}` populated.  
**Checklist**
=> Fix compactor missing compaction_objects_combined_total metric and not honoring max_bytes_per_trace 

CHANGELOG.md, cmd/tempo/app/modules.go, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, example/tk/lib/dashboards/grafana.libsonnet, modules/frontend/config.go, modules/frontend/frontend.go, modules/frontend/frontend_test.go, modules/frontend/searchsharding.go, modules/frontend/searchsharding_test.go, modules/overrides/limits.go, modules/overrides/limits_test.go, modules/overrides/overrides.go, modules/overrides/overrides_test.go, operations/jsonnet/microservices/frontend.libsonnet, operations/kube-manifests/Deployment-query-frontend.yaml, tempodb/wal/wal_test.go
Adds the ability to have a per tenant max search duration. By default, if there is no per tenant configuration, the original config value is used. This PR also updates the jsonnet under `./operations` to mount the overrides yaml onto the frontend.
Additional changes
- Documentation as well as catching the missing `block_retention` override
- Updated the jsonnet example to use full backend search
**Checklist**
=> Per tenant max search duration

CHANGELOG.md
Updates CHANGELOG for release v1.4.1 - https://github.com/grafana/tempo/releases/tag/v1.4.1
=> Update changelog for v1.4.1 release

docs/tempo/website/release-notes/v1-4.md
Update release notes for patch release [v1.4.1](https://github.com/grafana/tempo/releases/tag/v1.4.1)
=> Update website docs with release v1.4.1

CHANGELOG.md, modules/generator/registry/registry.go, modules/generator/registry/registry_test.go
The metrics generators add an `instance` label to distinguish between metrics series. This prevents out of order issues with remote write. Unfortunately `instance` is a very common label name and may conflict with custom dimensions on service graphs or span metrics.
This PR proposes a much more unique label name that is far less likely to conflict `__metrics_gen_instance`. Feel free to suggest other options if desired.
**Checklist**
=> Change label name for metrics generator instance

CHANGELOG.md, modules/frontend/frontend.go
- Moves the reference to `resp` to inside of the block where resp != nil
- Adds additional guard code against `resp.Header` being nil.
Fixes #1440 
**Checklist**
=> fix nil pointer error on trace by id path

integration/bench/load_test.go, integration/bench/smoke_test.js, integration/bench/stress_test_write_path.js
Release v0.38.0 from k6 introduced a series of bugfixes and enhancements so our bench tests no longer pass. This PR updates the scripts for this new version.
**Checklist**
=> Update bench test for k6 v0.38.0 release

CHANGELOG.md, integration/e2e/config-metrics-generator.yaml, integration/e2e/metrics_generator_test.go, modules/generator/registry/registry.go
Add a new metric `tempo_metrics_generator_registry_max_active_series` to the metrics-generator. This can be used together with `metrics_generator_registry_active_series` to monitor the active series and its limit.
**Checklist**
=> metrics-generator: expose max_active_series as a metric

CHANGELOG.md, modules/distributor/forwarder.go
Reworks update logic in watchOverrides loop.
The race condition comes from the unpredictable behaviour of ranging over a map.
This could cause that a newly created queueManagers was added to the ranged map,
and be evaluated for update.
Since the queueManager was _just_ created, it wouldn't have enough running workers,
which would trigger another update.
**Checklist**
=> Procect forwarder watchOverrides from race condition

operations/tempo-mixin-compiled/dashboards/tempo-operational.json, operations/tempo-mixin/dashboards/tempo-operational.json
Here we aggregate the data on on the write tab by cluster, rather than per pod.
* sum by(cluster) (rate(tempo_ingester_traces_created_total{cluster="$cluster", namespace="$namespace"}[$__rate_interval]))
* sum by(cluster) (rate(tempo_distributor_spans_received_total{cluster="$cluster", namespace="$namespace"}[$__rate_interval]))
**Checklist**
=> Adjust write panel in operational datashboard

docs/design-proposals/2022-04 TraceQL Concepts.md
Adds a design proposal that outlines the concepts and basic syntax of TraceQL, the upcoming Tempo query language. The full specification for this language is still a WIP, but we feel the core concepts are ready to be shared.  We invite anyone to provide comments and criticisms to better create a language that serves the needs of the tracing community!
Special thanks to @yurishkuro, @tomwilkie, @mdisibio and @cyriltovena for helping build this language over the past months.
=> Design Proposal: TraceQL Concepts

CHANGELOG.md, integration/e2e/metrics_generator_test.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/spanmetrics/spanmetrics_test.go
Changes spanmetric's metric names and labels to match OTel's spanmetrics spec.
Fixes #1444
**Checklist**
=> Change spanmetrics metric names and labels to match OTel conventions

CHANGELOG.md, docs/tempo/website/configuration/_index.md, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go
Here we include an S3 config option to disable TLS verification on HTTPs endpoints.
Fixes #1466
**Checklist**
=> Add s3 config option insecure_skip_verify

docs/design-proposals/2022-04 Parquet.md
This PR adds a design proposal for Parquet blocks. Rendered markdown file can be viewed [here](https://github.com/mdisibio/tempo/blob/design-proposal-parquet/docs/design-proposals/2022-04%20Parquet.md)
n/a
**Checklist**
=> Design proposal: Parquet blocks

CHANGELOG.md, modules/ingester/instance_search.go, modules/ingester/instance_search_test.go, modules/querier/querier.go, pkg/tempofb/searchdatamap.go, pkg/util/distinct_string_collector.go, pkg/util/distinct_string_collector_test.go, tempodb/search/backend_search_block.go, tempodb/search/searchable_block.go, tempodb/search/streaming_search_block.go
This PR adjusts the tags and tag values lookup apis to return partial results up to the size limit instead of failing.  The warning message was updated to include the limit and total size of tags/values encountered.   The core string handling was moved into `pkg/util/distinct_string_collector.go`
Fixes n/a
**Checklist**
=> Return partial results for tags and tag values lookups

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/azure.md, tempodb/blocklist/poller.go, tempodb/config.go, tempodb/tempodb.go
Adds a configurable number of maximum milliseconds to sleep before pulling a block in the poller. This is useful when hosting on Azure to reduce pressure on DNS.
Fixes #1462 
**Checklist**
=> Add `blocklist_poll_jitter_ms` config value

tempodb/encoding/vparquet/create.go, tempodb/encoding/vparquet/create_test.go
Parquet is currently extracting the start/end time from individual objects in the WAL when building the block. Some of these objects could be outside the configured ingestion slack time causing the block to have a very large start/end time.
Instead the Parquet block building logic should honor the Start/EndTime in the wal meta.
**Checklist**
=> Parquet: Honor WAL meta Start/End time

pkg/io/buffered.go, pkg/io/buffered_test.go
Fixes a concurrency issue in the BufferedReaderAt and adds a test. Before this fix a buffer could be chosen twice for two different reads and the "prep" method would be run on a buffer that was currently in use by a different read.
Panics looked like:
```
panic: runtime error: slice bounds out of range [:-361]
goroutine 77 [running]:
github.com/grafana/tempo/pkg/io.(*BufferedReaderAt).read(...)
/home/joe/dev/joe-elliott/tempo/pkg/io/buffered.go:50
github.com/grafana/tempo/pkg/io.(*BufferedReaderAt).ReadAt(0xc000100500, {0xc000186540, 0x62, 0x62}, 0x199)
/home/joe/dev/joe-elliott/tempo/pkg/io/buffered.go:144 +0x545
github.com/grafana/tempo/pkg/io.TestBufferedReaderConcurrency.func1()
/home/joe/dev/joe-elliott/tempo/pkg/io/buffered_test.go:114 +0x36
created by …
```
=> BufferedReaderAt Concurrency Fix

CHANGELOG.md, tempodb/blocklist/poller.go, tempodb/blocklist/poller_test.go
This adds additional blocklist backend metrics as mentioned in #1502 which are total backend objects and total backend bytes. 
Fixes #1502
**Checklist**
=> Adding Blocklist backend metrics

CHANGELOG.md, pkg/model/trace/matches.go, pkg/model/v2/object_decoder.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/block_search_test.go, tempodb/tempodb_search_test.go
This PR fixes a few inconsistencies in backend search between block formats.  But also this adds a set of search tests at the tempodb-level, that will help keep things consistent as we make more changes.   Hint:  I will be making more changes.
Fixes:
* v2 check on span name was exact instead of substring
* v2 request start/end times weren't optional
* vParquet was using the wrong tag to check "status.code"
Fixes n/a
**Checklist**
=> Fix a few inconsistencies in backend search between block formats

docs/tempo/website/operations/backend_search.md
Here we move the configuration docs for the `hedge_requests_up_to` and `hedge_requests_at` options.  This appears to be an oversight in a previous release.
Fixes #1543
**Checklist**
=> Adjust docs for backend search hedge configuration

CHANGELOG.md, modules/distributor/search_data.go, pkg/model/trace/search_data.go, pkg/model/trace/search_data_test.go, pkg/model/trace/search_test_suite.go, pkg/tempofb/search_entry_mutable.go, pkg/tempofb/searchdatamap.go, tempodb/search/backend_search_block_test.go, tempodb/search/streaming_search_block_test.go, tempodb/tempodb_search_test.go
This PR is a followup to #1538.  It runs the same comprehensive search tests against the two block types in the ingester: wal (StreamingSearchBlock) and completed (BackendSearchBlock).  A bug was found and addressed in the StreamingSearchBlock header tag check.
The comprehensive test cases in /tempodb/ were moved to /pkg/model/trace and made reusable, as well as the tag extraction logic from the distributor.  These two PRs are in preparation for #1547.
Fixes n/a
**Checklist**
=> Fix an inconsistency in wal search

.github/dependabot.yml, .github/workflows/dependabot_serverless_gomod.yml
Here we attempt to grant the correct permissions necessary to allow the extra commit action to run the workflow after committing the serverless updates.
Also here is to reduce the run interval of the dependabot jobs.
**Checklist**
=> Dependabot permissions and run interval

docs/tempo/website/grafana-agent/tail-based-sampling.md
Adds tail sampling policies examples to the documentation.
Used the new policy format (same as OTel), merged in https://github.com/grafana/agent/pull/1851
**Checklist**
=> Add sampling policies examples

CHANGELOG.md, modules/generator/storage/config_util.go, modules/generator/storage/config_util_test.go
When metrics-generator is run in single-tenant modus and an `x-scope-orgid` header is set in the remote write config, do not remove it. This is a protection added to multitenant system, in which you don't want each tenant to use the same remote write config. This doesn't make sense in single-tenant setups.
Fixes https://github.com/grafana/tempo/issues/1448
**Checklist**
=> metrics-generator: do not remove x-scope-orgid header in single tenant modus

docs/tempo/website/api_docs/_index.md, docs/tempo/website/configuration/azure.md, docs/tempo/website/getting-started/_index.md, docs/tempo/website/getting-started/example-demo-app.md, docs/tempo/website/getting-started/instrumentation.md, docs/tempo/website/metrics-generator/span_metrics.md, docs/tempo/website/operations/ingester_pvcs.md, docs/tempo/website/operations/monitoring.md, docs/tempo/website/operations/polling.md, docs/tempo/website/operations/serverless_aws.md, docs/tempo/website/troubleshooting/max-trace-limit-reached.md, docs/tempo/website/troubleshooting/too-many-jobs-in-queue.md, docs/tempo/website/troubleshooting/unable-to-see-trace.md
Fixes #1513 to address mismatched h1 and page titles, with some exceptions. The backend search pages were not changed since they will eventually be nested. The release notes were also not changed. 
**Checklist**
=> [1513] Fix mismatch H1 and titles

CHANGELOG.md, modules/querier/querier.go, pkg/hedgedmetrics/metrics.go, tempodb/backend/azure/azure_helpers.go, tempodb/backend/gcs/gcs.go, tempodb/backend/instrumentation/backend_transports.go, tempodb/backend/instrumentation/hedged_requests.go, tempodb/backend/s3/s3.go
- Adds a counter of hedged calls for queriers to external endpoints.
- Moves common code from tempodb to a new shared package: `/pkg/hedgedmetrics`.
- Changelog cleanup
**Checklist**
=> Add Hedged metrics for external endpoints

.github/workflows/dependabot_serverless_gomod.yml
Here we try another approach to get the amendment job on dependabot to have the needed access to run the workflow after commit.
**Checklist**
=> Use existing bot token for dependabot job checkout

CHANGELOG.md, docs/tempo/website/configuration/_index.md, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go, tempodb/backend/s3/s3_test.go
Builds on #1442 to include block_tags for new s3 objects.
Fixes #1442
**Checklist**
=> Add S3 block tags configuration option

tempodb/backend/azure/azure.go, tempodb/backend/backend.go, tempodb/backend/cache/cache.go, tempodb/backend/gcs/gcs.go, tempodb/backend/gcs/gcs_test.go, tempodb/backend/local/local.go, tempodb/backend/local/local_test.go, tempodb/backend/mocks.go, tempodb/backend/raw.go, tempodb/backend/raw_test.go, tempodb/backend/readerat.go, tempodb/backend/s3/s3.go, tempodb/backend/s3/s3_test.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/create.go
Adds a (currently unused) `shouldCache` parameter to the ReadRange interface. This will only be needed for the cache implementation and all other backends can ignore it. PR is in preparation to introduce metadata caching for parquet blocks to speed up queries.
Part of #1480 
**Checklist**
- N/A Tests updated
- N/A Documentation added
- N/A `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Extend ReadRange interface to accept shouldCache parameter

CHANGELOG.md, integration/util.go, pkg/model/trace/search_test_suite.go, pkg/parquetquery/predicates.go, pkg/tempofb/searchdata_util.go, pkg/tempofb/searchdatamap.go, pkg/tempofb/searchdatamap_test.go, tempodb/search/backend_search_block_test.go, tempodb/search/pipeline.go, tempodb/search/streaming_search_block_test.go, tempodb/tempodb_search_test.go
This PR makes all search-related activity (including tag lookups) case-sensitive.  An original intent of this was to reduce cardinality and resource usage of ingester-search, which is extra data stored next to the actual block. Therefore this change will increase usage some, but the amount depends on the traffic.  Parquet backend search will be more efficient due to the removal of `ToLower`.  v2 is unaffected (was already case-sensitive).
An increase in resources at the ingester is likely to cause more occurrence of #1258 so there is an attempt to fix it. We weren't able to conclusively determine the cause of such enormous buffers, but it seems related to tags that are very large. Changes:
1. Only store the first 1024 bytes of tags recorded in flatbuffers.  This …
=> Make search case sensitive

CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, docs/tempo/website/operations/backend_search.md, modules/querier/config.go
Relaxes the defaults for hedged requests on external endpoints. The defaults are far too aggressive and are likely to overwhelm serverless infrastructure on larger installs
**Checklist**
=> Relax External Endpoint Hedged Defaults

operations/tempo-mixin/runbook.md
This PR adds a runbook section for troubleshooting the `queue doesn't have room for <xyz> jobs` error.
Fixes n/a
**Checklist**
=> Add runbook section for 'queue doesn't have room for' error

cmd/tempo/app/config.go
Several times we have seen users confused b/c they are using local storage with their distributed Tempo setup and they can not access their traces after they have been flushed to disk.
=> Add local storage warning to startup

CHANGELOG.md, operations/jsonnet-compiled/ConfigMap-tempo-metrics-generator.yaml, operations/jsonnet-compiled/Deployment-metrics-generator.yaml, operations/jsonnet-compiled/Service-querier.yaml, operations/jsonnet-compiled/util/example/main.jsonnet, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-subtypes.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-types.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/util.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/memcached/memcached.libsonnet, operations/jsonnet/microservices/common.libsonnet, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/generator.libsonnet
Without this change, the generator uses node storage and is not constrianed, and could lead to resource contention on the node.
Here we include a request/limit resource on the generator deployment and an emptydir to constrian the use of local storage.. A side effect of this change is that metrics generator instances will be asked to terminate if the limit is exceeeded, and a new instance will be created.  Storage values should be sufficiently high in order to prevent unnecessary churn on the deployment and memberlist.  If the requested size is not available, the pod will fail to schedule and could lead to data loss.
Fixes grafana/tempo-squad#91
**Checklist**
=> Add ephemeral storage to generator for wal storage

pkg/parquetquery/iters.go, tempodb/encoding/vparquet/block_search.go
- Cleans up a goroutine/memory leak that occurs during search when the search finds matches
- Makes a common "pool put" method for columnIteratorBuffers that cleans up references to memory buffers
=> Parquet Search: Clean up leaks

docs/tempo/website/metrics-generator/service_graphs.md
The feature flag is being removed in Grafana 9.0.4. Let's remove it from our docs.
https://github.com/grafana/grafana/pull/52375
=> Remove mention of the tempoServiceGraph feature flag

pkg/parquetquery/iters.go
This is a minor improvement to the join iterator. It causes the iterator loop to bail early if there is no chance of a matching "lowest row number". I also experimented with moving `j.seekAll(highestRowNumber, j.definitionLevel)` into the loop, but found that in practice it often increased backend i/o.
There is some room for improvement here, but there are no obvious wins. Most improvements would be query dependent.
=> Minor improvement to join iterator

CHANGELOG.md, pkg/model/trace/matches.go, pkg/model/trace/search_test_suite.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/schema.go
Adds support for two special tags to both parquet and v2. Unsure how this is currently not supported in v2. Both of these special tags are supported in ingester/flatbuffer search.
**Checklist**
=> Added root.name and root.service.name support to v2 and parquet

docs/tempo/website/grafana-agent/service-graphs.md
This PR removes `http_listen_port` field from `server` config for the Agent.
See more details about the deprecation [here](https://grafana.com/docs/agent/v0.26/upgrade-guide/#breaking-change-deprecated-yaml-fields-in-server-block-removed).
**Checklist**
=> Remove http_listen_port from server Agent config

CHANGELOG.md, modules/generator/processor/spanmetrics/config.go
Changes the default spanmetric latency bucket sizes to match the default sizes in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor
It will be hard to size these default buckets to a size that fits all systems, but I think wider is better than narrower for a default. The current default maxes out at 4 seconds which imo is a bit low.
**Checklist**
=> Additional default latency buckets for spanmetrics

CHANGELOG.md, modules/ingester/instance.go, operations/tempo-mixin-compiled/alerts.yaml, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/runbook.md
This PR changes the ingester to continue starting up after encountering an error during block rediscovery.  The suspect block is ignored and left on disk for investigation.  Introduces a new metric and alert when this happens.
Fixes #1603 
**Checklist**
=> Ingester continue startup after rediscover block error

example/docker-compose/scalable-single-binary/docker-compose.yaml, example/docker-compose/scalable-single-binary/tempo-scalable-single-binary.yaml, integration/e2e/config-scalable-single-binary.yaml, integration/e2e/e2e_test.go
Without this change, the examples for SSB (Scalabe Single Binary) are missing the configuration necessary for the compactor module to establish cluster membership and coordinate the work of compacting.  Here we ensure that the configuration in the examples works as desired.
Fixes #1594
**Checklist**
=> Test compactor ring for SSB target

.gitignore
Drone goreleaser builds are broken with:
```
/go/bin/goreleaser release --rm-dist
• starting release...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=d3b3bca96a4cd040f68372fadc6485122669aec0 latest tag=v1.5.0-rc.0
⨯ release failed after 0s                  error=git is currently in a dirty state
Please check in your pipeline what can be changing the following files:
?? private-key.key
```
Adding `private-key.key` to rectify.
=> Added private-key.key to gitignore for drone builds

CHANGELOG.md, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go, tempodb/backend/gcs/gcs.go, tempodb/backend/raw.go
**What this PR does**: This PR fixes an issue for GCS when anonymous usage stats is enabled. Due to the cluster seed file being in the same folder, an incorrect tenant id of an empty string gets returned in the List() call. 
**Checklist**
=> Bug fix relating to Cluster Seed File

tempodb/encoding/vparquet/create.go, tempodb/encoding/vparquet/schema.go
Small improvements to help with ingester stability.
- snappy is less resource intensive then zstd
- providing an initial slice of 10k parquet values improves ingester memory reqs.
=> Parquet Ingester Stability

tempodb/encoding/vparquet/block_iterator.go, tempodb/encoding/vparquet/compactor.go
- Lowers size of preallocated slice to reduce total consumption.
- Increases buffer size to reduce calls to the backend.
=> Parquet: Minor compactor tweaks

CHANGELOG.md, cmd/tempo-query/tempo/plugin.go
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
Fixes #1619 
**Checklist**
=> Add support for time range queries on jaeger plugin

tempodb/encoding/vparquet/schema.go, tempodb/encoding/vparquet/schema_test.go
When encoding events we are currently using json. This format is extremely easy to read but currently accounts for 8% of all alloc'ed memory and 12% of all cpu cycles in an ingester. This PR changes the encoded format from json to proto. It is backwards compatible in that it attempts to read proto first and, if that fails, attempts json.
Benchmarks (json -> proto implementation in this PR)
```
name              old time/op    new time/op    delta
EventToParquet-8    11.8µs ± 2%     0.8µs ± 8%  -93.59%  (p=0.000 n=10+9)
name              old alloc/op   new alloc/op   delta
EventToParquet-8    2.91kB ± 0%    0.67kB ± 0%  -76.94%  (p=0.000 n=10+10)
name              old allocs/op  new allocs/op  delta
EventToParquet-8      91.0 ± 0%      10.0 ± 0%  -89.01%  (p=0.000 …
```
=> Parquet: Use proto instead of json for events

tempodb/encoding/vparquet/compactor.go
Improves compaction performance with parquet blocks by skipping equal rows before attempting to combine them.
=> Parquet: Compaction - Don't combine equal traces

cmd/tempo/app/modules.go, pkg/usagestats/reporter.go
Removes the dependency on the store for usage reporting. This dependency is not necessary and was causing the process to access the disk as noticed here: #1648
Thanks to @rlex for highlighting the change in v1.5.0 rc.2
=> Remove usage reporting's depedency on store

docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/parquet.md, docs/tempo/website/metrics-generator/app-performance-mgmt.md
The APM dashboard documentation linked to the /next doc in Grafana. These links have been changed to /latest since those pages are now live. 
Updated the content in the Parquet documentation to match the updated phrasing Jen used in the release notes. 
**Checklist**
=> [Doc] Fix next branch links to latest, update Parquet

CHANGELOG.md, integration/e2e/metrics_generator_test.go, modules/generator/processor/spanmetrics/spanmetrics.go
**What this PR does**: This PR adds span size as a new metrics to metrics generator. 
Fixes #1615
**Checklist**
=> Add span size as a new metrics to metrics generator

tempodb/backend/azure/azure_helpers.go
We are setting MaxIdleConnsPerHost in the customTransport used by Azure backend.
Default MaxIdleConnsPerHost is 2, Increase that to reduce connection turnover and hopefully fix the DNS failures seen in #1462 
Possible fix for https://github.com/grafana/tempo/issues/1462
**Checklist**
=> Set MaxIdleConns and MaxIdleConnsPerHost for Azure backend

CHANGELOG.md, cmd/tempo/app/config.go, cmd/tempo/app/config_test.go, cmd/tempo/main.go
~Hey, would be nice to get some feedback if [this](https://github.com/grafana/tempo/pull/1663/commits/2556b099b05f72da76190a915eff9da1c424e088) roughly looks like what you aimed for. If so, i will continue with persisting the change with some tests. :)~
~cc @joe-elliott @zalegrala~
---
This PR changes the behavior of the `cmd/tempo/app/config.CheckConfig` method. Previously, suspicious values were logged individually. Now a list of warnings and descriptions is returned. The caller can then decide whether and how to use this information. In this PR we decided to reproduce the existing logging behavior.
Fixes #1575
**Checklist**
=> Improve configuration warnings testing and presentation

CHANGELOG.md, operations/jsonnet-compiled/ConfigMap-tempo-compactor.yaml, operations/jsonnet-compiled/ConfigMap-tempo-distributor.yaml, operations/jsonnet-compiled/ConfigMap-tempo-ingester.yaml, operations/jsonnet-compiled/ConfigMap-tempo-metrics-generator.yaml, operations/jsonnet-compiled/ConfigMap-tempo-querier.yaml, operations/jsonnet-compiled/ConfigMap-tempo-query-frontend.yaml, operations/jsonnet-compiled/Deployment-compactor.yaml, operations/jsonnet-compiled/Deployment-distributor.yaml, operations/jsonnet-compiled/Deployment-metrics-generator.yaml, operations/jsonnet-compiled/Deployment-querier.yaml, operations/jsonnet-compiled/Deployment-query-frontend.yaml, operations/jsonnet-compiled/StatefulSet-ingester.yaml, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/grafana.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-custom.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-noname.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/legacy-subtypes.libsonnet, operations/jsonnet/microservices/configmap.libsonnet
Change DNS address fully qualified to reduce DNS lookups in Kubernetes.
See https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
for more details.
also see: similar change in Loki https://github.com/grafana/loki/pull/5789
**Checklist**
=> Make DNS address fully qualified to reduce DNS lookups in Kubernetes

CHANGELOG.md, tempodb/encoding/vparquet/compactor.go
Restores discarded spans to the row pool. Previously these were dropped. Also technically creates one less allocation by not creating a subslice :P.
**Checklist**
=> Parquet Compaction: Restore discarded rows to pool

CHANGELOG.md, cmd/tempo/app/config.go, docs/tempo/website/troubleshooting/_index.md, docs/tempo/website/troubleshooting/response-too-large.md
* Increase default values for `server.grpc_server_max_recv_msg_size` and `server.grpc_server_max_send_msg_size` from 4MB to 16MB
* Add a page in the troubleshot section for `500 Internal Server Error Body: response larger than the max (<size> vs <limit>)` type of errors.
**Checklist**
=> Increase default max size and add troubleshotting page

CHANGELOG.md, tempodb/encoding/vparquet/compactor.go
Parquet compaction currently uses FlushSizeBytes but it makes more sense to use RowGroupSizeBytes in the storage block. Also uses the `estimateProtoSize()` method which should result in a better estimate over the `len(lowestObject)`.
**Checklist**
=> Parquet Compaction: Use row group size bytes

CHANGELOG.md, cmd/tempo-cli/cmd-query-blocks.go, modules/ingester/instance.go, tempodb/encoding/common/interfaces.go, tempodb/encoding/v2/backend_block.go, tempodb/encoding/vparquet/block_findtracebyid.go, tempodb/encoding/vparquet/block_findtracebyid_test.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/readers.go, tempodb/tempodb.go, tempodb/tempodb_test.go, tempodb/wal/local_block.go
- ~Skip bloom filters when loading for trace by id search. (Skipping page index caused an nil pointer panic)~
- Honor cache and buffer settings when searching for traces by id.
**Checklist**
=> Parquet: Make FindTraceByID honor buffer and caching settings

docs/tempo/website/configuration/_index.md
The fact is mentioned here https://github.com/grafana/tempo/blob/97941594d2d4f51da8a45921936483c5e6677ffe/example/docker-compose/local/readme.md#L3 in the example, but it would be great to have it directly in the docs.
**Checklist**
=> Document that local storage backend is supported only in monolithic mode

CHANGELOG.md, cmd/tempo-serverless/cloud-run/go.mod, cmd/tempo-serverless/cloud-run/go.sum, cmd/tempo-serverless/lambda/go.mod, cmd/tempo-serverless/lambda/go.sum, go.mod, go.sum, pkg/cache/redis_client.go, vendor/github.com/go-redis/redis/v8/.golangci.yml, vendor/github.com/go-redis/redis/v8/CHANGELOG.md, vendor/github.com/go-redis/redis/v8/README.md, vendor/github.com/go-redis/redis/v8/command.go, vendor/github.com/go-redis/redis/v8/commands.go, vendor/github.com/go-redis/redis/v8/error.go, vendor/github.com/go-redis/redis/v8/internal/proto/scan.go, vendor/github.com/go-redis/redis/v8/internal/proto/writer.go, vendor/github.com/go-redis/redis/v8/package.json, vendor/github.com/go-redis/redis/v8/pipeline.go, vendor/github.com/go-redis/redis/v8/ring.go, vendor/github.com/go-redis/redis/v8/universal.go, vendor/github.com/go-redis/redis/v8/version.go, vendor/modules.txt
- Upgrades go-redis, which enables `SentinelUsername` to be configured in the redis `UniversalOptions` struct
- Adds fields for `username` and `sentinel_username` in tempo's configuration for redis, which enables ACL-based auth against the redis instances and sentinels, respectively.
N/A
**Checklist**
=> Add Redis ACL Auth Support (and for Sentinels)

CHANGELOG.md, tempodb/encoding/vparquet/schema.go
This PR reverts #1706 . We encountered some errors during compaction after deploying this change, which prevents some blocks from being compacted.  Example: `error iterating input blocks: combining: rs → ils → Spans → DurationNanos → no values found in parquet row for column 27`.   We will bring this column back after determining the cause, but reverting now so that the codebase is functional.
n/a
**Checklist**
=> revert PR 1706

.drone/drone.yml
`drone.yaml` was updated when we [upgraded go to 1.19](https://github.com/grafana/tempo/pull/1665), but the signature was not re-created.
**Checklist**
=> Update drone.yaml signature

CHANGELOG.md, tempodb/encoding/v2/backend_block.go, tempodb/encoding/vparquet/block_findtracebyid.go
**What this PR does**: Logs bloom number that couldn't be retrieved from the backend block, the result of which caused a crash in pulling backend blocks
Fixes #1730
**Checklist**
- [ x] Tests updated
- [ x] Documentation added
- [ x ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Identify bloom that could not be retrieved from backend block

tempodb/encoding/vparquet/block_findtracebyid.go, tempodb/encoding/vparquet/block_iterator.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/block_traceql.go
Removes bloom filter and page index reads for compactors and queriers on all code paths. We never use them.
=> Reduce Parquet Reads

CHANGELOG.md, operations/jsonnet-compiled/Deployment-compactor.yaml, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/memcached/memcached.libsonnet, operations/jsonnet/microservices/compactor.libsonnet
**What this PR does**: Adding GOMEMLIMIT to compactor libsonnet
**Checklist**
=> Adding GOMEMLIMIT to compactor libsonnet

pkg/parquetquery/iters.go, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/block_search_test.go
This PR contains a variety of cpu and memory improvements for parquet iterators.  They significantly help the cases where spans partially match the given tags, but not entirely and are discarded halfway up the chain.  This scenario exercises the iterators a lot and hadn't gotten as much profiling as the other cases.  For example on real data: `foo=...` matches nothing and was performing quite well, but `foo=... && component=...` still matches nothing overall but the component tag caused a lot of churn in joining/filtering.
The changes:
* The join level for span tag-search was wrong which didn't affect accuracy but it wasn't throwing out non-matching spans as early as possible.
* Didn't realize `atomic.Value.Store()` was allocing on every call in …
=> Parquet iterator improvements

tempodb/encoding/vparquet/block_search.go
This PR https://github.com/grafana/tempo/pull/1759 occasionally panics due to a nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a1122]
goroutine 56643 [running]:
github.com/grafana/tempo/tempodb/encoding/vparquet.(*rowNumberIterator).SeekTo(0xc08e0f8f48, {0x7d0, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff}, 0x0)
/drone/src/tempodb/encoding/vparquet/block_search.go:577 +0xe2
github.com/grafana/tempo/pkg/parquetquery.(*JoinIterator).seekAll(0xc0660b1a50, {0x7d0, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff}, 0x0) …
```
=> Fix nil pointer panic

example/docker-compose/agent/agent.yaml, example/docker-compose/agent/docker-compose.yaml, example/docker-compose/azure/docker-compose.yaml, example/docker-compose/azure/tempo-azure.yaml, example/docker-compose/distributed/docker-compose.yaml, example/docker-compose/distributed/grafana-datasources.yaml, example/docker-compose/distributed/tempo-distributed.yaml, example/docker-compose/gcs/docker-compose.yaml, example/docker-compose/gcs/tempo-gcs.yaml, example/docker-compose/local/docker-compose.yaml, example/docker-compose/local/tempo-local.yaml, example/docker-compose/loki/docker-compose.yaml, example/docker-compose/loki/grafana-datasources.yaml, example/docker-compose/otel-collector-multitenant/docker-compose.yaml, example/docker-compose/otel-collector-multitenant/grafana-datasources.yaml, example/docker-compose/otel-collector-multitenant/otel-collector.multitenant.yaml, example/docker-compose/otel-collector/docker-compose.yaml, example/docker-compose/otel-collector/otel-collector.yaml, example/docker-compose/s3/docker-compose.yaml, example/docker-compose/s3/tempo-s3.yaml, example/docker-compose/scalable-single-binary/docker-compose.yaml, example/docker-compose/scalable-single-binary/grafana-datasources.yaml, example/docker-compose/scalable-single-binary/prometheus.yaml, example/docker-compose/scalable-single-binary/tempo-scalable-single-binary.yaml, example/docker-compose/shared/grafana-datasources.yaml
Update all docker-compose examples:
* Update versions of components with pinned versions
* Enable backend search, metrics generation and service graphs
*Note on service graphs:* the respective examples are configured such, that service graphs should work correctly. However, the traces generated by the load generator do not comply with [otel semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/README.md) and therefore service graphs do not show in the UI. This might be fixed along with  grafana/tempo#902. 
Fixes grafana/tempo-squad#136
**Checklist**
=> Update docker-compose examples

Makefile, pkg/util/client.go
Util `client` uses protobuf when querying traces by ID. This prevents a breaking change when we upgraded `opentelemetry-proto` to v0.18.0.
=> Util `client` uses protobuf when querying traces by ID

CHANGELOG.md, cmd/tempo-serverless/cloud-run/Dockerfile, cmd/tempo-vulture/Dockerfile, cmd/tempo/Dockerfile
Here we update alpine to 3.16
**Checklist**
=> Update alpine image version to 3.16

CHANGELOG.md, docs/tempo/website/configuration/_index.md, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/spanmetrics/spanmetrics_test.go
When generating span metrics, extract the non attribute field `status_message` or `status.message`, when it is provided in the span_metrics dimensions.
Fixes #1764
**Checklist**
=> Metrics generator: extract status_message field from spans

cmd/tempo-cli/cmd-query-search.go, pkg/tempopb/prealloc.go, tempodb/encoding/v2/append_block.go, tempodb/encoding/v2/iterator_deduping.go, tempodb/encoding/vparquet/block_findtracebyid_test.go, tempodb/encoding/vparquet/block_search_test.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/encoding/vparquet/combiner_test.go, tempodb/encoding/vparquet/compactor_test.go, tempodb/encoding/vparquet/create.go, tempodb/encoding/vparquet/schema.go, tempodb/encoding/vparquet/schema_test.go
Refactoring to reduce allocations in `traceToParquet` and `CreateBlock`
- `traceToParquet` use pooled slices. ~levelled pooling would be preferred but we are still seeing a performance improvement with this change only.~
- `v2.DedupingIterator` changed to support both `common.Iterator` and `BytesIterator` allowing it to be used directly when completing a block. Previously, if a trace needed to deduped, we would unmarshal the individual byte slices to `*tempopb.Trace`, deupe, marshal back to a byte slice and finall back to `*tempopb.Trace` to be written to the complete block. This change allows the deduping iterator to directly pass the results of the combine to the caller which reduces allocations significantly.
- Added a leveled pooling object for pooling generic …
=> Parquet Ingester/Compactor memory improvements

CHANGELOG.md, modules/distributor/distributor.go, modules/distributor/distributor_test.go
Add a `span_name` field into span logs of distributors, `span.Name` will only be logged if `include_all_attributes` is set to true.
Fixes #1788 
**Checklist**
=> Log span name when include_all_attributes is on

modules/frontend/v1/frontend.go
This change ensures that the `FailureWatcher` is listening to subservices before any services are added to the frontend.  This appears to be the expectation  of the `WatchManager`.
```
panic: FailureWatcher has not been initialized
goroutine 330 [running]:
github.com/grafana/dskit/services.(*FailureWatcher).WatchManager(0x36bad20?, 0xc00070c310?)
/home/zach/go/src/github.com/grafana/tempo/vendor/github.com/grafana/dskit/services/failure_watcher.go:47 +0xdb
github.com/grafana/tempo/modules/frontend/v1.(*Frontend).starting(0xc0006d8750, {0x25c2860, 0xc0002ba500})
/home/zach/go/src/github.com/grafana/tempo/modules/frontend/v1/frontend.go:121 +0x36
github.com/grafana/dskit/services.(*BasicService).main(0xc000758a00) …
```
=> frontend: ensure failure watcher has been initialized

.github/workflows/ci.yml
This PR configures Github actions to cancel running workflows if new push is done on a branch or PR. Previous workflow has little value at that point. (Copied from Mimir)
**Checklist**
- [na] Tests updated
- [na] Documentation added
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Cancel running workflows on new pushes.

pkg/usagestats/reporter.go
Signed-off-by: David <davidcalvertfr@gmail.com>
Raised the log level of a few msg in `pkg/usagestats/reporter.go` from `INFO` to `WARN`.
This is a more accurate level for these logs messages.
Example:
`level=info ts=2022-10-18T09:29:37.761854634Z caller=reporter.go:111 msg="failed to CAS cluster seed key" err="error writing object to s3 backend, object tempo_cluster_seed.json: Access Denied"`
**Checklist**
=> fix: raise log level in pkg/usagestats/reporter.go

pkg/parquetquery/predicates.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/encoding/vparquet/schema.go
This PR adds more TraceQL functionality at the storage layer for parquet format.
1. Re-add duration filtering with original implementation as End-Start (it was removed in #1724). This is not optimal and we still want to add a dedicated column, but introducing new columns still has some things to research, and better to have the traceql functionality.
2. Add remaining operators (!=, >=, <=, etc)
3. Add support for `status` intrinsic
Fixes n/a
**Checklist**
=> Traceql more functionality

modules/ingester/instance_test.go, tempodb/encoding/vparquet/block.go, tempodb/encoding/vparquet/block_findtracebyid_test.go, tempodb/encoding/vparquet/block_search.go
Updates the backendBlock to hold a reference to the backend reader and parquet file so it only has to open a complete block once. Stumbled on this while working on the parquet wal.
```
name                                      old time/op    new time/op    delta
InstanceFindTraceByIDFromCompleteBlock-8    1.75ms ± 4%    1.40ms ± 9%  -19.73%  (p=0.000 n=9+10)
name                                      old alloc/op   new alloc/op   delta
InstanceFindTraceByIDFromCompleteBlock-8    1.02MB ± 1%    0.88MB ± 1%  -12.86%  (p=0.000 n=9+10)
name                                      old allocs/op  new allocs/op  delta
InstanceFindTraceByIDFromCompleteBlock-8     4.28k ± 1%     2.31k ± 2%  -46.11%  (p=0.000 n=10+10)
```
Prior to this change a cpu profile of repeated opens …
=> [Parquet] Improve ingester search and find trace by id time

pkg/traceql/ast.go, pkg/traceql/ast_execute.go, pkg/traceql/ast_execute_test.go, pkg/traceql/engine_test.go
This PR implements the And (&&) and Union (||) spanset operators.  Other operators are unsupported and will return an error.  Also fixes a flaky test by sorting span attributes.
Fixes n/a
**Checklist**
=> [TraceQL] Implement SpansetOperations And and Union

modules/ingester/instance_search.go, modules/ingester/instance_test.go
Sets hardcoded default options to prevent repeated disk i/os on local searches.
```
name                             old time/op    new time/op    delta
InstanceSearchCompleteParquet-8     253ms ±15%      84ms ± 7%  -66.83%  (p=0.000 n=10+9)
name                             old alloc/op   new alloc/op   delta
InstanceSearchCompleteParquet-8    42.4MB ± 3%    25.3MB ± 2%  -40.20%  (p=0.000 n=10+9)
name                             old allocs/op  new allocs/op  delta
InstanceSearchCompleteParquet-8      476k ± 3%      228k ± 1%  -52.01%  (p=0.000 n=10+9)
```
=> Better default options

pkg/parquetquery/iters.go, pkg/parquetquery/predicate_test.go, pkg/parquetquery/predicates.go
Removes locking on the predicate filter. Evaluating the usage in ColumnIterator this seems safe as it's all accessed from the same goroutine.
For larger queries accessing millions or 10s of millions of values this can save 5-7% on query time.
Benchmarks are run against real trace data and evaluating ~30M values:
```
name                             old time/op    new time/op    delta
InstanceSearchCompleteParquet-8     1.77s ± 6%     1.66s ± 5%  -6.25%  (p=0.004 n=9+9)
name                             old alloc/op   new alloc/op   delta
InstanceSearchCompleteParquet-8     320MB ± 1%     320MB ± 1%    ~     (p=0.897 n=10+8)
name                             old allocs/op  new allocs/op  delta
InstanceSearchCompleteParquet-8     2.32M ± 0%     2.32M ± 0%    ~ …
```
=> Remove InstrumentedPredicate Locking

pkg/parquetquery/predicates.go
This PR fixes a panic in RegexInPredicate where the `matches` map is nil.  When used inside an `OrPredicate` then `KeepColumnChunk` may not be called.
Fixes n/a
**Checklist**
=> Fix panic in RegexInPredicate

CHANGELOG.md, tempodb/pool/pool.go, tempodb/pool/pool_test.go
Without this change, jobs will continue to get scheduled, even if the context has been cancelled.  Here we include a check and avoid doing work if we have been asked to stop.
**Checklist**
=> Avoid running pool jobs with a cancelled context

cmd/tempo/app/app.go, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go
Here we avoid logging an error when the context is canceled on the usage stats.
**Checklist**
=> Avoid error return when usage stats context is canceled

tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go
This PR fixes the behavior of span duration filtering for some TraceQL queries.  Span duration is handled specially because it's a computed column, and it wasn't working correctly for these cases:
* `{ } | avg(duration) > 1ms` Projecting the duration column from storage with no filtering. This is fixed with nil check.
* `{ name = "x" || duration 1ms }` Filtering on duration when `AllConditions=false`, it was always rejecting all spans that didn't pass the duration filter. 
Fixes n/a
**Checklist**
=> [TraceQL] Fix duration filtering

operations/tempo-mixin-compiled/dashboards/tempo-resources.json, operations/tempo-mixin/dashboards/dashboard-utils.libsonnet
Tweak promql queries to use `container=~` in the resources dashboard. Fixes an issue in which CPU and memory usage panels would be empty when filtering on a regex expression.
**Checklist**
=> tempo-mixin: use regex for containers in resources dashboard

CHANGELOG.md, docs/tempo/website/configuration/_index.md, modules/compactor/compactor.go, modules/compactor/config.go
Without this change, there isn't a good way to disable compaction when running in single binary or scalable single binary mode.  Normally, when running in microservices mode, operators can simply scale down the compactors to 0 to effectively disable compaction, though this will have other consequences, since the compactors are doing a little more than compaction.
Here we include a config option to disable compaction at the compactor level.  This allows the compactor module to run, but disable compaction, allowing blocks to remain in the backend for debug or investigation purposes.
**Checklist**
=> Allow compactor disablement

cmd/tempo-serverless/cloud-run/go.mod, cmd/tempo-serverless/cloud-run/go.sum, cmd/tempo-serverless/lambda/go.mod, cmd/tempo-serverless/lambda/go.sum, go.mod, go.sum, vendor/github.com/segmentio/parquet-go/buffer.go, vendor/github.com/segmentio/parquet-go/column.go, vendor/github.com/segmentio/parquet-go/config.go, vendor/github.com/segmentio/parquet-go/encoding/bitpacked/bitpacked.go, vendor/github.com/segmentio/parquet-go/encoding/bytestreamsplit/bytestreamsplit.go, vendor/github.com/segmentio/parquet-go/encoding/delta/length_byte_array.go, vendor/github.com/segmentio/parquet-go/errors.go, vendor/github.com/segmentio/parquet-go/row.go, vendor/github.com/segmentio/parquet-go/search.go, vendor/github.com/segmentio/parquet-go/type.go, vendor/github.com/segmentio/parquet-go/value.go, vendor/github.com/segmentio/parquet-go/writer.go, vendor/github.com/segmentio/parquet-go/writer_go18.go, vendor/modules.txt
Updates parquet-go dependency to catch a couple performance improvements:
* https://github.com/segmentio/parquet-go/pull/386
* https://github.com/segmentio/parquet-go/pull/398
Benchmark comparisons, huge memory improvements and also benefits to cpu in some cases. These are on top of the improvements already done in #1818 
```
name                                      old time/op    new time/op    delta
BackendBlockSearchTraces/noMatch-12          239ms ±16%     157ms ±10%  -34.32%  (p=0.000 n=9+10)
BackendBlockSearchTraces/partialMatch-12     2.79s ± 2%     2.54s ± 2%   -8.92%  (p=0.000 n=9+9)
BackendBlockSearchTraces/service.name-12    1.62ms ±14%    1.46ms ±20%     ~     (p=0.165 n=10+10)
BackendBlockSearchTags-12                    1.41s ± 6%     1.08s ± 3% …
```
=> Parquet performance improvements

CHANGELOG.md, operations/tempo-mixin-compiled/alerts.yaml, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/runbook.md
Here I propose delete the undocumented `TempoRequestErrors` alert from the `tempo-mixin`.  This alert has limited utility in a generic sense due to the thresholds here. 
**Checklist**
=> Delete TempoRequestErrors alert from mixin

modules/querier/querier.go
Fixes a context reference to avoid a nil pointer introduced in #1853.
**Checklist**
=> Fix context error reference in querier logging

docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, modules/storage/config.go, tempodb/encoding/vparquet/compactor.go, tempodb/encoding/vparquet/create.go, tempodb/encoding/vparquet/schema_test.go
Currently there are two methods that estimate trace size when building row groups in parquet blocks. Both of these methods do a decent job of estimating the uncompressed proto size of a trace, but are poor at estimating a compressed and encoded version in parquet. The result of this is that the actual row group created has been observed to be anywhere between 5->30% of the configured row_group_bytes.
This PR
- Adjusts the two methods to be lower bounds on row_group_size bytes. In practice on real data the created row groups are 100->150% of the configured size.
- Roughly aligns both methods around the concept of counting the total number of parquet values pushed with the assumption that across enough traces we approach 1 byte per value stored.
- Renames both methods …
=> "Fix" row group size bytes

modules/overrides/limits.go, modules/overrides/overrides.go, pkg/tempopb/tempo.pb.go
Adds `metrics_generator_max_active_series` to limits metrics
=> Add max active series limit to limit metrics

operations/tempo-mixin/config.libsonnet, operations/tempo-mixin/dashboards/dashboard-utils.libsonnet
Changes `tempo-mixin/dashboards/dashboard-utils.libsonnet` to respect `per_cluster_label` from config.libsonnet
Also adds a configurable `namespace_selector_separator` to config.libsonnet. The reason for this is that serviceMonitors from the helm chart don't have job names matching `($namespace)/%s` , but rather `($namespace)-%s`. The config value defaults to current `/`.
=> use per_cluster_label in dashboard-utils.libsonnet

docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/querying.md, docs/tempo/website/configuration/tls.md
Here we include a new page in our docs about how to configure TLS, or Transport Layer Security.  Much of the configuration objects are pulled in from our dependencies, but we also include examples that have been tested to work.
**Checklist**
=> [docs] document the use of TLS

.github/workflows/stale.yml
Increase operations-per-run config for stale workflow, it's defaults to 30 and we have way more issues & PRs to scan.
It fails to scan all issues & PRs with default limit, incrasing it to 100.
See: 
- https://github.com/grafana/tempo/actions/runs/3441389540/jobs/5740868546#step:2:1074
- https://github.com/actions/stale#operations-per-run
**Checklist**
=> Increase operations-per-run for stale workflow

CHANGELOG.md, modules/distributor/receiver/shim.go
* occasionally otel receivers will report a fatal error, and expected behavior is that the Host is stopped
* match this behavior by stopping the receiver shim service and letting the distributor stop itself
If you think we need a test added to prevent regression, let me know
No Issue
**Checklist**
=> Stop Distributor on fatal error

tempodb/encoding/vparquet/block_findtracebyid.go, tempodb/tempodb.go, tempodb/tempodb_test.go
There is currently a [bug](https://github.com/grafana/tempo/issues/1903) with setting the min/max id in the block meta. This PR removes all usage of these values since they are not accurate. In extreme edge cases performance will be very narrowly impacted.
Once the linked issue is fixed this PR can be reverted.
**Checklist**
=> Remove usage of min/max id in trace by id search

CHANGELOG.md, cmd/tempo-vulture/main.go
Add a `tempo-tls` flag to enable TLS negotiation, but not verification, on the gRPC connection to Tempo.
**Checklist**
=> Add TLS support to vulture

pkg/tempopb/prealloc.go, tempodb/encoding/v2/create_block.go, tempodb/encoding/vparquet/create.go, tempodb/encoding/vparquet/schema.go, tempodb/encoding/vparquet/schema_test.go, tempodb/encoding/vparquet/wal_block.go
A collection of performance improvements for a Parquet ingester. Specifically targeting the parquet wal.
- Adjust prealloc bytes pool to catch a larger percentage of write sizes
- Rewrite the complete block logic to use rows instead of Trace objects for better pooling
- Improve extendReuseSlice() to keep existing values on extension
This is observed to improve:
- Heap Bytes by 25%
- Working set by 15%
- CPU by 20%
=> Parquet Ingester: Perf Improvements

tempodb/encoding/vparquet/block_traceql_test.go
Improves tests by adding links to the "fullypopulatedtrace" that is used in a lot of tests. This was missed when link support was added.
=> Add links to fully populated trace

pkg/parquetquery/iters.go, pkg/traceql/storage.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/encoding/vparquet/wal_block.go, tempodb/wal/wal_test.go
This PR reduces the amount of data read during parquet search by not starting column iterators until the first call to `Next()`, and reordering iterators a bit. This benefits highly selective queries in that it will never open/scan the metadata columns such span.ID, traceID, rootServiceName, etc, until results are found.  This benefits TraceQL primarily because it contains more metadata columns (span ID, start, end), but 
Benchmarks:
Tag search:
```
name                                      old time/op    new time/op    delta
BackendBlockSearchTraces/noMatch-12          174ms ±11%      55ms ± 3%  -68.04%  (p=0.000 n=10+10)
BackendBlockSearchTraces/partialMatch-12     2.49s ± 6%     2.47s ± 2%     ~     (p=0.863 n=9+9)
BackendBlockSearchTraces/service.name-12 …
```
=> [TraceQL] I/O Improvements

docs/tempo/website/configuration/gcs.md
Add `storage.objects.list` as required policy
Mention Workload Identity as another valid authentication method
DOCS: Add missing required permissions for GCP Storage Bucket and mention possible use of GCP's Workload Identity as an alternative to `GOOGLE_APPLICATION_CREDENTIALS`
**Checklist**
=> add additional required permissions & auth-method

CHANGELOG.md, pkg/traceql/lexer.go, pkg/traceql/lexer_test.go, pkg/traceql/parse_test.go
This PR changes parsing of most binary operations to work without spacing.  Example:  `{.foo="bar"}`.  Previously this wasn't handled as expected  and the entire `foo="bar"` was considered the attribute name.  This was done purposefully to accommodate searching on attribute names with syntaxy characters like `= ~ - +` etc, but the negative impact to every day usage isn't worth it.
Characters in the changed operations can no longer be included in an attribute name so querying on them is impossible.  Some operations are not changed because the likelihood of those characters in attribute names is enough to  weigh the decision the other way.
Fixed: `= != =~ != > >= < <= ^ && ||`
Unchanged: `+ - / % *`
**Overall**
Currently this isn't in a good spot because we are …
=> Tweak traceql parsing to correctly parse binary operations without space

CHANGELOG.md, modules/ingester/ingester.go, modules/ingester/ingester_test.go, modules/ingester/instance_search_test.go, tempodb/backend/local/compactor.go, tempodb/backend/local/local.go, tempodb/backend/local/local_test.go
This fixes a long running issue where tenants were persisted even if they had a zero length wal. The issue was that when rediscovering local blocks a tenant was still found even if there were no blocks. This PR fixes the issue with two changes:
- When rediscovering local blocks don't include tenants without blocks
- When clearing a block in the local backend remove the tenant as well
Technically only the first of the two is needed and would be a safer change. Having the second is nice because it will clear up folders in our ingester local backends. Should we remove the second change and err towards safety? Especially with the 2.0 release coming up?
**Checklist**
=> Remove tenant when last block is removed from local backend

CHANGELOG.md, operations/jsonnet-compiled/Deployment-compactor.yaml, operations/jsonnet-compiled/Deployment-distributor.yaml, operations/jsonnet-compiled/Deployment-metrics-generator.yaml, operations/jsonnet-compiled/Deployment-querier.yaml, operations/jsonnet-compiled/Deployment-query-frontend.yaml, operations/jsonnet-compiled/StatefulSet-ingester.yaml, operations/jsonnet-compiled/util/example/main.jsonnet, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet/microservices/Readme.md, operations/jsonnet/microservices/compactor.libsonnet, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/distributor.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/microservices/generator.libsonnet, operations/jsonnet/microservices/ingester.libsonnet, operations/jsonnet/microservices/memberlist.libsonnet, operations/jsonnet/microservices/multi-zone.libsonnet, operations/jsonnet/microservices/querier.libsonnet, operations/jsonnet/microservices/tempo.libsonnet
Add zone aware ingesters.
Fixes #1578 
**Checklist**
=> Zone aware ingesters

pkg/parquetquery/predicate_test.go, pkg/parquetquery/predicates.go, tempodb/encoding/vparquet/block_search.go
Improves parquet-query's handling of dictionaries in predicates. Currently we test the dictionary for every page. However, the dictionary is per row group and not per page. Therefore, for row groups that contained multiple pages, we were repeatedly and unnecessarily checking the dictionary.
~~There is also a cardinality question. If every value in the row group is unique then testing the dictionary isn't worth it. We will test n/2 values in the dictionary until we get to the one that suggests we should keep the column and then go back and test n values for whatever the initial condition was. In this case, especially since we've already paid the cost of pulling everything from object storage, it would likely be faster to simply test the values directly.~~
Although …
=> Improve Parquet Dictionary Handling

Makefile, cmd/tempo-serverless/cloud-run/go.mod, cmd/tempo-serverless/cloud-run/go.sum, cmd/tempo-serverless/lambda/go.mod, cmd/tempo-serverless/lambda/go.sum, go.mod, go.sum, pkg/parquetquery/predicates.go, tempodb/encoding/vparquet/wal_block.go, tempodb/encoding/vparquet/wal_block_test.go, vendor/github.com/segmentio/parquet-go/README.md, vendor/github.com/segmentio/parquet-go/config.go, vendor/github.com/segmentio/parquet-go/file.go, vendor/modules.txt
A number of performance improvements for the Parquet wal that are particularly impactful in a highly multitenant environment:
- shared writer schema
- 1KB page buffer size for writers
- don't load page index or bloom filters when opening a wal "page" file
- lazy load wal "page" files
The real winners here were the 1k page buffer size and the lazy loading of the wal page files (instead of loading them immediately after flushing).
By default the page buffer size is 256KB. This page buffer is applied to every column of every tenant which adds up fast. Ideally there would be a way to specify per column page buffers, but this does not exist. The 1KB size does slow down tests. It doubles the length of time to run the tests in the `/tempodb/wal` folder for me, but in …
=> Parquet WAL Improvements: Multitenant envs

example/docker-compose/agent/readme.md, example/docker-compose/azure/readme.md, example/docker-compose/distributed/readme.md, example/docker-compose/gcs/readme.md, example/docker-compose/local/readme.md, example/docker-compose/loki/readme.md, example/docker-compose/otel-collector-multitenant/readme.md, example/docker-compose/otel-collector/readme.md, example/docker-compose/s3/readme.md, example/docker-compose/scalable-single-binary/readme.md
Example README files still mentioned the synthetic-load-generator which is no longer used in most examples. I also regenerated the output of `docker-compose ps` as it also looks quite different now in some cases.
None, I just noticed this while working on the debug example.
**Checklist**
=> Remove mentions of synthetic-load-generator from example README

.golangci.yml, CHANGELOG.md, docs/tempo/website/configuration/_index.md, docs/tempo/website/configuration/manifest.md, modules/generator/config.go, modules/generator/config_test.go, modules/generator/instance.go, modules/generator/instance_test.go, modules/generator/overrides.go, modules/generator/overrides_test.go, modules/generator/processor/spanmetrics/config.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/spanmetrics/spanmetrics_test.go, modules/overrides/limits.go, modules/overrides/overrides.go
The metrics generator always adds the intrinsic dimensions `service`, `span_name`, `span_kind`, `status_code`, and `status_message`. The `status_message` may contain arbitrary strings and can have a very high cardinality (see #1932). Therefore it is safer not to add this dimension by default.
With this PR:
* All above mentioned intrinsic dimensions are configurable via configuration file and overrides.
* The `status_message` is not added by default.
Fixes #1932
**Checklist**
=> Make intrinsic dimensions configurable and disable status_message by default

CHANGELOG.md, modules/frontend/searchsharding.go
=> Collect inspectedBytes from SearchMetrics

CHANGELOG.md, pkg/traceql/storage.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/wal/wal_test.go
Fixes an issue when trying to optimize some queries using only `&&` which turns into the `AllConditions=true` storage layer hint, and including repeated attribute names.
Fixes #1948 
**Checklist**
=> TraceQL: Fix bug trying to optimize queries using only && and repeated attribute name

tempodb/encoding/vparquet/block_search.go
When upgrading the Parquet dependency we caught [this change](https://github.com/segmentio/parquet-go/pull/417) which defaulted page reads to be synchronous. There is likely some nuance for best performance on when to enable this or not, but trace by id search on the backend was heavily (negatively) impacted by this change. 
This should restore the old behavior. 
With this change the wal remains synchronous, which is preferred given the smaller files and increased number of files.
=> Parquet: Restore async read mode

CHANGELOG.md, integration/e2e/e2e_test.go, integration/util.go, modules/ingester/instance_search.go, modules/ingester/instance_search_test.go, pkg/util/client.go
Skips search of live traces and flat-buffers search entries when querying with TraceQL. This resulted in inconsistent results, since live trace search would match all traces.
**Checklist**
=> Skip flatbuffers and live traces search in TraceQL queries

CHANGELOG.md, operations/tempo-mixin/alerts.libsonnet
Signed-off-by: Whyeasy <Whyeasy@users.noreply.github.com>
There are a few alerts left hat used the fixed `cluster` label and not the new `per_cluster_label`.
**Checklist**
=> Fix last few alerts with per_cluster_label

CHANGELOG.md, cmd/tempo-query/main.go, cmd/tempo-query/tempo/config.go, cmd/tempo-query/tempo/plugin.go
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
This PR adds options to HTTP client to do TLS handshake with the query-frontend tempo API.
Something similar to what other components have:
Here is an example of the tempo-query config: 
```
backend: 127.0.0.1:3100
tls_enabled: true
tls_cert_path: /var/run/tls/grpc/server/tls.crt
tls_key_path: /var/run/tls/grpc/server/tls.key
tls_ca_path: /var/run/ca/service-ca.crt
tls_insecure_skip_verify: false
```
Fixes #1998 
**Checklist**
=> Add TLS support to jaeger query plugin

CHANGELOG.md, modules/frontend/search_response.go, modules/frontend/search_response_test.go, tempodb/search/util.go
Makes search results by combining partial results and taking the earliest start time and longest duration.
Fixes #2001
**Checklist**
=> Return more consistent search results by combining partial traces

docs/sources/api_docs/_index.md
I think there should be a v2 in here too but perhaps I am misunderstanding.
=> Fix example call to search_tag_values_v2

docs/sources/configuration/parquet.md, docs/sources/getting-started/tempo-in-grafana.md, docs/sources/operations/architecture.md, docs/sources/operations/backend_search.md, docs/sources/operations/caching.md, docs/sources/operations/consistent_hash_ring.md, docs/sources/operations/deployment.md, docs/sources/operations/generic_forwarding.md, docs/sources/operations/ingester_pvcs.md, docs/sources/operations/monitoring.md, docs/sources/operations/parquet/_index.md, docs/sources/operations/parquet/schema.md, docs/sources/operations/polling.md, docs/sources/operations/server_side_metrics.md, docs/sources/operations/serverless_aws.md, docs/sources/operations/serverless_gcp.md, docs/sources/operations/tempo_cli.md, docs/sources/setup/linux.md
Adds draft Parquet documentation for configuration, schema, and examples. Also: 
* Fixes page weights for the Deployment files
* Fixes broken links in two files
**Checklist**
=> [DOCS] Add Parquet doc, fix page weights

docs/sources/configuration/parquet.md, docs/sources/getting-started/tempo-in-grafana.md, docs/sources/traceql/query-editor.md
Adds feature flag for enabling trace view to TraceQL docs and links between Parquet docs.
**Checklist**
=> [DOC] Added feature flag info for trace view

docs/sources/traceql/_index.md
Fix a broken link to the query editor from the TraceQL doc.
=> Fix broken link in TraceQL doc

CHANGELOG.md, cmd/tempo/app/config.go, cmd/tempo/app/modules.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go, vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go, vendor/modules.txt
Registers all available Go runtime metrics
PR #1528 upgraded prometheus/client_golang to version v1.12.2, which contains the following change:
> Reverting addition of new ~80 runtime metrics by default. You can enable this back with GoRuntimeMetricsCollection option or GoRuntimeMemStatsCollection | GoRuntimeMetricsCollection for smooth transition.
The removed metrics contain some interesting GC metrics (e.g. `go_gc_cycles_total_gc_cycles_total`). This PR (re-)introduces these metrics:
```
```
No currently existing metrics are removed.
This PR is based on https://github.com/grafana/loki/pull/6962.
Alternatively we could also make this configurable if we don't want to export all metrics by default, wdyt?
**Checklist**
=> Register all available Go runtime metrics

docs/sources/getting-started/traces.md
Fixes a typo in the terminology list on traces.md. 
**Checklist**
=> [DOC] Fixed typo in terminology list

modules/querier/http.go
**What this PR does**: Returns http status code 400 for failed tag search requests
Fixes #2021
=> Fix search tag endpoint return code (#2021)

docs/sources/traceql/_index.md
Adds a sentence clarifying resources and spans to link them to the screenshot in the TraceQL documentation. 
**Checklist**
=> [DOC] Clarify resources and spans in doc

cmd/tempo-cli/cmd-list-block.go
Prevents `tempo-cli` from `panic`ing when a compacted block *only* includes a `meta.compacted.json` file (no `index`, ...).
Fixes #2063
**Checklist**
=> Fix panic when scanning blocks with missing files (#2063)

.github/workflows/website-next.yml, .github/workflows/website-versioned.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
=> Update publishing workflows to use organization secret

.github/workflows/website-next.yml, .github/workflows/website-versioned.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
(cherry picked from commit dfc7848f24572dbc04510080a9f91a910e294593)
=> [release-v1.5] Update publishing workflows to use organization secret (#2080)

CHANGELOG.md, modules/generator/registry/counter.go, modules/generator/registry/counter_test.go, modules/generator/registry/registry_test.go
Here we allow new values on counter series to be used by Prometehus by inserting a leading 0 into new counter series.
Fixes #2006 
**Checklist**
=> [generator] Insert leading zero value for new counter series

docs/sources/metrics-generator/app-performance-mgmt.md
Removes the tempoApmTable feature flag, since it was removed in Grafana (see https://github.com/grafana/grafana/pull/62499). 
=> Remove tempoApmTable feature flag info

CHANGELOG.md, tempodb/encoding/vparquet/combiner.go, tempodb/encoding/vparquet/combiner_test.go
The Parquet combiner used during compaction and when combining multiple traces on query does not correctly coalesce root level trace data. This fixes it.
Likely this fixes #2057. At  least it would certainly contribute to it.
**Checklist**
=> Parquet: Fix Combiner

.drone/drone.jsonnet, .drone/drone.yml, .github/workflows/ci.yml, .github/workflows/dependabot_serverless_gomod.yml, CHANGELOG.md, cmd/tempo-cli/cmd-list-block.go, cmd/tempo-serverless/cloud-run/go.mod, cmd/tempo-serverless/lambda/Dockerfile, cmd/tempo-serverless/lambda/go.mod, go.mod, integration/e2e/receivers_test.go, modules/ingester/ingester_test.go, modules/ingester/instance_search_test.go, modules/ingester/instance_test.go, pkg/cache/background_test.go, pkg/io/read_test.go, pkg/model/trace/combine_test.go, pkg/tempopb/prealloc_test.go, pkg/util/test/req.go, tempodb/backend/local/local_test.go, tempodb/encoding/common/bloom_test.go, tempodb/encoding/v2/appender_test.go, tempodb/encoding/v2/data_reader_writer_test.go, tempodb/encoding/v2/index_test.go, tempodb/encoding/v2/iterator_paged_test.go, tempodb/encoding/v2/object_test.go, tempodb/encoding/v2/record_test.go, tempodb/encoding/v2/streaming_block_test.go, tempodb/encoding/v2/wal_block_test.go, tempodb/wal/wal_test.go
[Go 1.20 officially released recently](https://tip.golang.org/doc/go1.20)
There's improvements on the garbage collector. It informs that overall performance improves by up to 2% and reduces memory overheads.
Migrating to v1.20 will provides improved performance, bug fixes, security enhancements and several new features in the languages.
**Checklist**
=> Bump go version to 1.20

docs/sources/configuration/tls.md
Fix the path we hang the Jaeger TLS block in our documentation.
**Checklist**
=> Fix TLS documentation for configuring Jaeger receviers

cmd/tempo/app/app.go, cmd/tempo/app/config.go, cmd/tempo/app/modules.go, pkg/server/internal_server.go
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
The following PR adds support for a custom internal server listener dedicated for the start to serve the ready handler on a separate port and optionally TLS configuration. The key purpose for this one is to serve the Tempo HTTP API via mTLS while serving the readiness endpoints without (i.e. kubernetes readiness/liveness probes do not support authentication)
Fixes https://github.com/grafana/tempo/issues/2044
This is based on https://github.com/grafana/loki/pull/7069
**Checklist**
=> add support for custom internal server

docs/sources/tempo/configuration/_index.md, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go
Minio Sdk supports it，So we need to expose the configuration. For examples: The Volcano Engine product TOS S3 protocol request style only supports virtual host（https://www.volcengine.com/docs/6349/147050）
Fixes #2109 
**Checklist**
=> Expose s3 bucket lookup type config

CHANGELOG.md, cmd/tempo-serverless/lambda/go.mod, cmd/tempo-serverless/lambda/main.go, cmd/tempo-serverless/lambda/main_test.go
Correctly unescapes parameter values in AWS Lambda
Fixes #2114 
**Checklist**
=> Unescape query strings in lambda

CHANGELOG.md, modules/compactor/compactor.go, modules/compactor/compactor_test.go, tempodb/compactor.go, tempodb/compactor_test.go, tempodb/encoding/common/interfaces.go, tempodb/encoding/vparquet/compactor.go, tempodb/encoding/vparquet/compactor_test.go, tempodb/tempodb.go
Log when a trace is too large to compact.
If the total bytes of traces exceeds maximum limit, the following messages will be logged.
```json
{
"msg": "max size of trace exceeded",
"tenant": "XXXXX",
"traceId": "XXXXX",
"discarded_span_count": 100
}
```
There will be some dicussions in this PR.
Please refer to following comments.
Fixes #1931
**Checklist**
=> Log when a trace is too large to compact

CHANGELOG.md, pkg/traceql/ast.go, pkg/traceql/ast_execute_test.go, pkg/traceql/ast_test.go
Previously the following traceql query would always return nothing b/c floats and ints were not comparable via equality:
```
{ 1 = 1. }
```
This PR makes it so that both static and attribute comparisons will work for all number types.
Fixes #2010 
**Checklist**
=> [TraceQL] Add support to directly compare floats and ints

CHANGELOG.md, Makefile, cmd/tempo-cli/Dockerfile, cmd/tempo-cli/cmd-migrate-tenant.go, cmd/tempo-cli/main.go, docs/sources/tempo/operations/tempo_cli.md, tempodb/encoding/v2/block.go, tempodb/encoding/v2/encoding.go, tempodb/encoding/versioned.go, tempodb/encoding/vparquet/copy.go, tempodb/encoding/vparquet/encoding.go
Adds a new tempo-cli command `migrate tenant` which can copy the blocks of a tenant between two tenants and even two backends.
Usage:
```
go run ./cmd/tempo-cli migrate tenant --source-config-file source-config.yaml --config-file dest-config.yaml tenant1 tenant2
```
Note it can not change format of the block, the entire block will be streamed from source to destination without parsing.
I've also added a Dockerfile and Makefile target for tempo-cli. You can run it with `docker run docker.io/grafana/tempo-cli <args>`.
**Checklist**
=> tempo-cli: add command to migrate a tenant

CHANGELOG.md, cmd/tempo/main.go
This pull request introduces a new feature to the application in the form of a config.verify flag. When enabled, this flag allows the user to verify the configuration and then exit the application. This can be useful in scenarios where the user wants to validate the configuration file before launching the application or to troubleshoot configuration-related issues.
Fixes #[2131](https://github.com/grafana/tempo/issues/2131)
**Checklist**
=> Add configuration verification flag to CLI (#2131)

example/docker-compose/readme.md
Cleans up the docker compose readme by removing a dead link:
Fixes #2147
=> Removes a dead link to a docker compose example

CHANGELOG.md, Makefile, integration/e2e/e2e_test.go, integration/util.go, modules/ingester/instance_search.go, modules/querier/querier.go, tempodb/encoding/vparquet/block_search_tags.go, tempodb/encoding/vparquet/block_search_tags_test.go, tempodb/search/util.go
Backport #2085 to `release-v2.0` for patch.
**Checklist**
=> Backport to v2: Remove status.code and error from /api/search/tags (#2085)

pkg/model/trace/search_test_suite.go, tempodb/encoding/v2/backend_block.go, tempodb/tempodb_search_test.go
Adds some basic traceql testing at the tempodb level and rewrites the current search tests to be more broadly applicable. This still needs a lot of work but I think this is a good first step. After old search is removed we can get back into this.
**Checklist**
=> TraceQL Tests

CHANGELOG.md, docs/sources/tempo/traceql/_index.md, docs/sources/tempo/traceql/architecture.md, pkg/traceql/ast.go, pkg/traceql/ast_execute.go, pkg/traceql/ast_execute_test.go, pkg/traceql/ast_test.go, pkg/traceql/ast_validate.go, pkg/traceql/test_examples.yaml
Adds support for arbitrary arithmetic to TraceQL. Also adds support for using duration in binary operations.
**Checklist**
=> Traceql arithmetic

docs/sources/tempo/traceql/_index.md
Adds a link and embeds the video from [Marty's Feb 7 blog](https://grafana.com/blog/2023/02/07/get-to-know-traceql-a-powerful-new-query-language-for-distributed-tracing/) to the TraceQL doc. 
**Checklist**
=> [DOC] Added TraceQL video

CHANGELOG.md, pkg/traceql/engine.go, pkg/traceql/engine_test.go, pkg/traceql/storage.go, tempodb/backend/cache/cache.go, tempodb/backend/local/local.go, tempodb/backend/raw.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_meta.go, tempodb/encoding/vparquet/wal_block.go
**What this PR does**: Close WAL block file before deleting everything
Also added some other files closing that I found during a look around the code.
PS: I not proficient in Go, so I could have misunderstood, so please check if it looks good
Attempt to fix https://github.com/grafana/tempo/issues/2034
Fixes https://github.com/grafana/tempo/issues/2153
**Checklist**
=> Close WAL block file before deleting everything

pkg/traceql/ast_test.go, pkg/traceql/engine.go, pkg/traceql/engine_test.go, pkg/traceql/storage.go, tempodb/encoding/vparquet/block_traceql.go
- Adds an interface method that allows the engine to signal to the fetch layer it is dropping spans
- Use the new method to release spans back to the fetch pool when nothing matches
When doing a needle in the haystack query that is rejected by the engine, we drop millions of spans on the floor which puts a lot of pressure on the GC. This PR releases spans back to the pool when the engine rejects everything. This is the 99.99...% case when searching (b)millions of traces for just one or two.
=> Release spans when nothing matches

example/docker-compose/agent/docker-compose.yaml, example/docker-compose/azure/docker-compose.yaml, example/docker-compose/debug/docker-compose.yaml, example/docker-compose/distributed/docker-compose.yaml, example/docker-compose/gcs/docker-compose.yaml, example/docker-compose/local/docker-compose.yaml, example/docker-compose/otel-collector-multitenant/docker-compose.yaml, example/docker-compose/otel-collector/docker-compose.yaml, example/docker-compose/s3/docker-compose.yaml, example/docker-compose/scalable-single-binary/docker-compose.yaml
Upgrade Grafana to version 9.4.3 in Tempo's docker-compose examples
None
**Checklist**
=> Upgrade grafana to version 9.4.3 in docker-compose examples

docs/sources/tempo/configuration/_index.md, docs/sources/tempo/metrics-generator/span_metrics.md, modules/generator/processor/servicegraphs/config.go, modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/store/edge.go, modules/generator/processor/spanmetrics/config.go, modules/generator/processor/spanmetrics/spanmetrics.go, modules/generator/processor/util/util.go, modules/generator/registry/histogram.go, modules/generator/registry/histogram_test.go, modules/generator/registry/interface.go, modules/generator/registry/registry_test.go, modules/generator/registry/test.go, modules/generator/registry/test_test.go
Adds span multiplier feature by using "X-SampleRatio" attribute.
Fixes #2166
**Checklist**
=> Metrics Span Multiplier

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, docs/sources/tempo/configuration/azure.md, modules/storage/config.go, tempodb/backend/azure/azure_helpers.go, tempodb/backend/azure/azure_helpers_test.go, tempodb/backend/azure/config.go
Adds support for [Azure Workload Identity](https://azure.github.io/azure-workload-identity/docs/) authentication.
Partially based off the following PR https://github.com/grafana/loki/pull/7540 which implemented Azure Workload Identity into Loki.
**Checklist**
---
This is my first time writing anything in Go, so I might have made a mistake with the syntax. If I have feel free to fix it or let me know and I'll fix it myself.  
I have tested this and it seems to work so I'm hoping I haven't made a mistake but you never know.
=> Add Azure Workload Identity authentication support

CHANGELOG.md, tempodb/backend/azure/azure.go, tempodb/backend/gcs/gcs.go, tempodb/backend/s3/s3.go, tempodb/blocklist/poller.go
**What this PR does**: Renamed some spans to match the cloud provider and started a trace around polling tenant index to add context to the "Read" traces. 
Fixes https://github.com/grafana/tempo-squad/issues/193
**Checklist**
=> Add context to Read span

CHANGELOG.md, modules/querier/querier.go
Halts v2 tag values search if any virtual tags are found.
cc @mapno since you're working in this area
cc @mdisibio since you had recently changed the behavior of v1/v2 tag values search w/r to `status`
Fixes #2200 
**Checklist**
=> [TraceQL] Quit tag values search if virtual tags returns anything

cmd/tempo-serverless/cloud-run/go.mod, cmd/tempo-serverless/cloud-run/go.sum, cmd/tempo-serverless/lambda/go.mod, cmd/tempo-serverless/lambda/go.sum, go.mod, go.sum, pkg/traceql/ast_test.go, pkg/traceql/engine.go, pkg/traceql/engine_test.go, pkg/traceql/storage.go, tempodb/encoding/vparquet/block_traceql.go, vendor/github.com/segmentio/parquet-go/buffer.go, vendor/github.com/segmentio/parquet-go/config.go, vendor/github.com/segmentio/parquet-go/file.go, vendor/github.com/segmentio/parquet-go/row.go, vendor/modules.txt
Something of a cheat PR. Includes a Parquet update to catch https://github.com/segmentio/parquet-go/pull/484 and slightly rewrites #2183.
#2183 was rewritten to not overcomplicate the Span interface. Technically this was achievable entirely at the fetch layer.
Memory benchmarks for the parquet update. Seeing some improvement but not the same levels as the original PR. Perhaps due to file differences?
```
name                                               old alloc/op   new alloc/op   delta
BackendBlockTraceQL/spanAttNameNoMatch-8             4.70MB ±10%    4.40MB ± 5%     ~     (p=0.056 n=5+5)
BackendBlockTraceQL/spanAttValNoMatch-8              13.1MB ± 5%    12.9MB ± 3%     ~     (p=0.222 n=5+5)
BackendBlockTraceQL/spanAttValMatch-8                8.91MB ± 6% …
```
=> Parquet Update + Fetch Spans Cleanup

docs/sources/tempo/configuration/_index.md
Adds information about using the Helm chart to set the usage_reporting value. These values were added to tempo-distributed in this PR: https://github.com/grafana/helm-charts/pull/2279 
**Checklist**
=> Added Helm chart values for usage_reporting

docs/sources/tempo/metrics-generator/_index.md
Briefly explains how metrics are exported from the metrics-generator to the metrics backend.
=> [Metrics-generator] Add section about exporting metrics

pkg/traceql/ast_execute.go, pkg/traceql/ast_execute_test.go, pkg/traceql/engine.go, pkg/traceql/storage.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/tempodb_search_test.go
Due to recent performance improvements specific queries can now panic the engine. When executing a query that &&'s or ||'s multiple spansets together like:
```
{} && {} && {} ...
```
The engine would modify the input slices in the "filter" step. These modifications would sometimes place duplicates of the same span in the input spanset slice. Then, when executing this code:
https://github.com/grafana/tempo/blob/70272b8221ae9456c79b8337984068ecd0a91b34/tempodb/encoding/vparquet/block_traceql.go#L285
we would place the same pointer into the span pool multiple times. This has been corrected by cloning the spanset correctly in the engine layer.
Also, removed an unused `matches()` function and rewrote our evaluate tests to confirm the input was not modified.
**Checklist**
=> Fix panic when &&ing or ||ing multiple spansets

CHANGELOG.md, pkg/traceql/ast_execute.go, pkg/traceql/ast_execute_test.go, tempodb/encoding/vparquet/block_traceql.go, tempodb/tempodb_search_test.go
Forces the spanset operations && and || to always return a unique spanset. Before they would return the cross product of all spansets. For instance this query `{ true } && { true }` would return a spanset that was double the input trace. Now it will return a spanset that is equal to the input trace.
Fixes #2246 
**Checklist**
=> [TraceQL] Multiple &&ed or ||ed should return unique spans

operations/jsonnet-compiled/PodDisruptionBudget-ingester.yaml, operations/jsonnet-compiled/StatefulSet-ingester.yaml, operations/jsonnet-compiled/StatefulSet-memcached.yaml, operations/jsonnet-compiled/util/jsonnetfile.json, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet-compiled/util/lib/k.libsonnet, operations/jsonnet-compiled/util/vendor/github.com/grafana/jsonnet-libs/ksonnet-util/util.libsonnet, operations/jsonnet/microservices/ingester.libsonnet
* Rely more heavily on the lib version of `k` and use `kausal` only when needed.
* Update PodDisruptionBudget to policy/v1, which has had [support since v1.21](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125)
Fixes #2186
**Checklist**
=> [jsonnet-microservices] support k8s v1.25

docs/sources/tempo/traceql/architecture.md
Fixes a TraceQL link that should go from architecture to index for Perform a query. 
**Checklist**
=> [DOC] Fix TraceQL query link

.gitignore, CHANGELOG.md, docs/sources/tempo/configuration/_index.md, modules/frontend/config.go, modules/frontend/frontend.go, modules/frontend/frontend_test.go, modules/frontend/searchsharding.go, modules/frontend/searchsharding_test.go, modules/frontend/tracebyidsharding.go, modules/frontend/tracebyidsharding_test.go, pkg/traceql/engine.go
Expose Throughput (for search only) and SLO Metrics, and add config in Query Frontend to configure SLOs
Note: this doesn't work with TraceQL yet because we are not sending SearchMetrics from TraceQL query execution, it will work after we start returning SearchMetrics from TraceQL query execution
**Checklist**
=> Add Throughput and SLO Metrics with SLOConfig in Query Frontend

.github/workflows/metrics-collector.yml
Metrics collection actions cron runs on forks and fails, this PR adds a condition to only run this action on `grafana/tempo` repo.
docs on if condition: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository
this action has [10,555 failed workflow runs](https://github.com/ie-pham/tempo/actions/workflows/metrics-collector.yml) in @ie-pham's fork and [176 failed workflow runs](https://github.com/electron0zero/tempo/actions/workflows/metrics-collector.yml) in my fork.
each failed workflow run sends an email to fork owner, so this will remove that spam as well.
**Checklist**
=> Disbale metrics collection action on forks

.github/workflows/issue_commands.yml, .github/workflows/milestoned_to_project.yml, .github/workflows/snyk.yml, .github/workflows/stale.yml, .github/workflows/website-next.yml, .github/workflows/website-versioned.yml
follow up on https://github.com/grafana/tempo/pull/2284, after https://github.com/grafana/tempo/pull/2284, I noticed that few other workflows are also running in my fork.
This PR limits grafana specific workflow actions to `grafana/tempo` repo.
**Checklist**
=> Limit GitHub workflows to only grafana/tempo repo

CHANGELOG.md, operations/tempo-mixin-compiled/dashboards/tempo-reads.json, operations/tempo-mixin-compiled/dashboards/tempo-resources.json, operations/tempo-mixin-compiled/dashboards/tempo-rollout-progress.json, operations/tempo-mixin-compiled/dashboards/tempo-tenants.json, operations/tempo-mixin-compiled/dashboards/tempo-writes.json, operations/tempo-mixin/dashboards/dashboard-utils.libsonnet
by default all dashboard in tempo-mixin have auto refresh enabled to refresh the dashboard every 10 seconds, this change disables that.
**why disable:**
- most users have scrape internval of 15 seconds or higher so 10 refresh is too aggresive
- auto refresh will keep refreshing dashboard in backgroud, and put extra load on datasource
- users can still enable auto-refresh when looking at dashboard, this will just turn it off by default.
- auto refresh eats up resources in your browser when you have many dashboard open.
**Checklist**
=> tempo-mixin: disable auto refresh every 10 seconds

CHANGELOG.md, pkg/traceql/expr.y, pkg/traceql/expr.y.go, pkg/traceql/test_examples.yaml, tempodb/tempodb_search_test.go
Adds support for negative values in aggregate filters.
Fixes #2182 
**Checklist**
=> TraceQL: Support negative values on aggregates

tempodb/compactor.go, tempodb/retention.go
Makes compactor loops not exit after one iteration
Bug introduced in https://github.com/grafana/tempo/pull/2247.
=> Fix compactor loops

CHANGELOG.md, pkg/traceql/lexer.go, pkg/traceql/lexer_test.go, pkg/traceql/parse_test.go
**What this PR does**: Support float as duration in traceql
Fixes [#2180](https://github.com/grafana/tempo/issues/2180)
**Checklist**
=> Support float as duration in traceql

docs/sources/tempo/getting-started/_index.md, docs/sources/tempo/getting-started/example-demo-app.md, docs/sources/tempo/operations/architecture.md, docs/sources/tempo/operations/caching.md, docs/sources/tempo/release-notes/v1-2.md, docs/sources/tempo/setup/_index.md, docs/sources/tempo/setup/deployment.md, docs/sources/tempo/setup/helm-chart.md, docs/sources/tempo/setup/linux.md, docs/sources/tempo/setup/set-up-test-app.md, docs/sources/tempo/setup/tanka.md, docs/sources/tempo/setup/upgrade.md, docs/sources/tempo/traces.md
Restructures the Set up TOC content and moves the deployment page to the Set up folder. Also, fixes a missing image and some links. 
Completes part of #2223 
**Checklist**
=> [DOC] TOC restructure for Setup content

Makefile
Attempts to fix VERSION in Drone image builds.
VERSION is empty when we are building binaries in Drone `GO111MODULE=on CGO_ENABLED=0 go build -mod vendor -ldflags "-X main.Branch=main -X main.Revision=dc670f461 -X main.Version=" -o ./bin/linux/tempo-arm64  ./cmd/tempo`, but it works fine when tesing locally.
Drone is not evalulating and setting VERSION, so this PR makes it VERSION assignment same as GIT_REVISION, and GIT_BRANCH, which are working in Drone
I have not way to test it locally and have to build it on Drone to test it out. I tested it locally and it works fine with and without this change.
Maybe #2283 & #1908
**Checklist**
=> Fix VERSION in Drone Builds

.drone/drone.jsonnet, .drone/drone.yml, Makefile
`tools/image-tag` script needs bash and it was failing because `golang:1.20-alpine` image used in `build-tempo-binaries` step
is missing bash
due to missing bash `./tools/image-tag` was failing with `env: can't execute 'bash': No such file or directory` and
producing tempo binaries with missing version tag
Tested this locally by building tempo in `golang:1.20-alpine` with bash, and it works ✨ 
here is what I see `GO111MODULE=on CGO_ENABLED=0 go build -mod vendor -ldflags "-X main.Branch=really_fix_version -X main.Revision=53c3e6e9a -X main.Version=really_fix_version-53c3e6e-WIP" -o ./bin/linux/tempo-amd64  ./cmd/tempo` when running `COMPONENT=tempo GOARCH=amd64 make exe` in `golang:1.20-alpine` with bash
#2312 didn't work, so reverted changes made in #2312
**Which …
=> Really fix VERSION in Drone Builds

example/helm/microservices-extras.yaml
Using later versions of k3d bundles newer kubernetes, which includes some deprecations.  This change updates the mentioned resources to allow the `kubectl create` call to succeed in the `microservices` example
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
**Checklist**
=> Update helm microservices example for Kubernetes v1.22 deprecations

.github/workflows/ci.yml, Makefile
Splits Single CI Test Job into 4 differrent CI Jobs (pkg, tempodb, tempodb/wal, and others) to make CI more stable and parallelize the test run.
Tempo grew and we added more tests, and test run time kept going up because we added more and more tests, this breaks CI test run into 4 different jobs to make it more managable and less flaky ✨ 
- changed `go test` to run with `-v` to print out test logs and more details like time take in each test case
- reduced `go test` `-timeout` to `20m`, now tests are split we should timeout early
**Timings:**
**before split:**
all - 22m23s
**after split into pkg, tempodb, and others:**
pkg - **3m23s**, with go test -v **2m39s**
tempodb - killed (SIGTERM) after 14m11s in first run, **20m15s** in second run, with go test -v **16m40s** …
=> Break up CI tests into pkg, tempodb, tempodb/wal and others

tempodb/wal/wal_test.go
The WAL tests only run with the block encodings `v2` and `vParquet`. This change makes sure that the tests use all available block encodings.
None
**Checklist**
=> Use all encodings in WAL tests

docs/sources/tempo/getting-started/_index.md, docs/sources/tempo/getting-started/instrumentation.md
Remove a note with a link to the instrumentation page that is on the instrumentation page. 
**Checklist**
=> [DOC] Remove duplicate link from instrumentation

modules/compactor/compactor.go, tempodb/compactor_test.go, tempodb/retention_test.go, tempodb/tempodb.go, tempodb/tempodb_search_test.go, tempodb/tempodb_test.go
Correctly propagates the compaction error out to the compactor. If the compactor is misconfigured it now logs:
```
level=error ts=2023-04-17T21:03:51.787335269Z caller=app.go:202 msg="module failed" module=compactor err="invalid service state: Failed, expected: Running, failure: failed to enable compaction: Compaction window can't be 0"
```
and exits cleanly.
=> Propogate Compaction Error

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, modules/ingester/instance_search.go, modules/ingester/instance_search_test.go, modules/overrides/limits.go, modules/overrides/overrides.go
Adds a new override param to limit number of blocks inspected in tag value search
**Checklist**
=> Add override to limit number of blocks inspected in tag value search

CHANGELOG.md, docs/sources/tempo/traceql/_index.md, docs/sources/tempo/traceql/query-editor.md, pkg/traceql/ast_execute.go, pkg/traceql/ast_test.go, pkg/traceql/ast_validate.go, pkg/traceql/enum_operators.go, pkg/traceql/enum_operators_test.go, pkg/traceql/test_examples.yaml, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/encoding/vparquet2/block_traceql.go, tempodb/encoding/vparquet2/block_traceql_test.go
**What this PR does**: Supports ranger operators for strings in TraceQL
Fixes #2181
**Checklist**
=> Supports ranger operators for strings in TraceQL

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, modules/storage/config.go, tempodb/backend/raw.go, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go, tempodb/backend/s3/s3_test.go
Enables storing blocks in shared s3 bucket with the prefix option.
Fixes #2100 
**Checklist**
=> Enhancement: Allow configuring a prefix path for s3

docs/sources/tempo/getting-started/_index.md
There's a link in the docs that refers to an outdated blog post. Linking the corresponding config page instead.
=> Update link to docs instead of outdated blog post

.drone/drone.jsonnet, .drone/drone.yml
There is a breaking change in the latest drone manifest plugin that is preventing us from releasing 2.1. Discussion here:
https://github.com/drone-plugins/drone-manifest/issues/41
We will pin to 1.4.0 until we can find a way to resolve.
=> Pin drone manifest plugin to 1.4.0

CHANGELOG.md, docs/sources/tempo/configuration/manifest.md, modules/generator/generator_ring.go
Adds the ability to override the port that metrics-generator advertises for itself in the ring.  This functionality is needed for certain deployments that need to route distributor->generator traffic through a proxy.  This functionality already exists for the ingester and compactor but was missing from the metrics-generator.
Didn't see any of these advanced options in the documentation, but they are in the config manifest and regenerated it.  Seems our yaml indentation changed so diff has a lot of noise, but should be readable ignoring whitespace.
Fixes n/a
**Checklist**
=> Metrics-generator customizable ring port

.github/workflows/website-versioned.yml
It is already present when syncing "next" documentation.
=> Allow no changes when syncing release documentation

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, modules/storage/config.go, tempodb/backend/azure/azure.go, tempodb/backend/azure/azure_test.go, tempodb/backend/azure/config.go, tempodb/backend/gcs/config.go, tempodb/backend/gcs/gcs.go, tempodb/backend/gcs/gcs_test.go, tempodb/backend/s3/s3_test.go
Add a new configuration option `prefix` in azure and gcs storage, with this option the users can now store all traces in a sub path of a shared bucket or container. 
Fixes #2100 
**Checklist**
=> Enhancement: Add `prefix` configuration option to azure and gcs storage

pkg/parquetquery/iters.go, pkg/parquetquery/iters_test.go
When executing large fetches the `Next()` function is called continuously. This PR unrolls `Next()` for better performance.
Next Benchmarks:
```
name    old time/op  new time/op  delta
Next-8  83.8ns ± 1%  66.6ns ± 2%  -20.44%  (p=0.000 n=10+10)
```
Fetch benchmarks:
```
name                                               old time/op    new time/op    delta
BackendBlockTraceQL/spanAttNameNoMatch-8             27.2ms ± 5%    27.0ms ± 1%     ~     (p=1.000 n=5+5)
BackendBlockTraceQL/spanAttValNoMatch-8              36.6ms ±12%    33.9ms ± 2%   -7.25%  (p=0.032 n=5+5)
BackendBlockTraceQL/spanAttValMatch-8                 414ms ± 2%     401ms ± 2%   -3.23%  (p=0.016 n=5+5)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-8        26.1ms ± 2%    25.2ms ± 3%   -3.69%  (p=0.008 …
```
=> Unroll RowNumber Next()

modules/ingester/instance_search.go
In practice this race condition simply meant that occasionally we searched more blocks then was set up in the limit. However this was regularly breaking tests. This PR corrects the race condition.
While making this fix it occurs to me that the way this is written the blocks we search are non deterministic. I think an improvement here would be to guarantee that the same blocks are always searched.
cc @mapno
=> Fix Race Condition on Inspected Blocks

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, docs/sources/tempo/configuration/manifest.md, modules/storage/config.go, tempodb/backend/s3/config.go, tempodb/backend/s3/s3.go, tempodb/backend/s3/s3_test.go
Here we implement the initial TLS configuration options from dskit on the s3 configuration.  The change here is pretty minimal, but will set us up to make use of the other TLS common components, such as CA cert file loading and server name.  Currently only the s3 config is modified, but I can see this impacting the others as well later.
* add tls.ClientConfig inline config
* add documentation for new supported TLS client configurations
* replace the minio TLS configuration with the one based on tls.ClientConfig
* **breaking change** rename `storage.trace.s3.insecure_skip_verify` config option
Fixes #2262
Fixes #1914
Fixes #2373
**Checklist**
=> Use TLS config from `dskit`

CHANGELOG.md, docs/sources/tempo/traceql/_index.md, pkg/parquetquery/predicate_test.go, pkg/parquetquery/predicates.go, pkg/traceql/ast_validate.go, pkg/traceql/test_examples.yaml, tempodb/encoding/vparquet/block_traceql.go, tempodb/encoding/vparquet/block_traceql_test.go, tempodb/encoding/vparquet2/block_traceql.go, tempodb/encoding/vparquet2/block_traceql_test.go
* Enables parsing `!~` in tracql
* Support for filtering values using negated regex pattern
Fixes #1990
**Checklist**
=> Support to filter traces using `!~`

GOVERNANCE.md, MAINTAINERS.md
Proposal to make @knylander-grafana a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/knylander-grafana)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Aknylander-grafana)
https://github.com/orgs/grafana/teams/tempo
=> Add Kim Nylander as a maintainer

pkg/traceql/engine.go, pkg/traceql/engine_test.go
Correctly handles intrinsic attributes in `/api/v2/search/<tag>/values`
**Checklist**
=> Fix intrinsics in v2 tag value search

modules/frontend/search_progress.go
Fixes a nil pointer exception race condition in search streaming. If `.results()` was called before `.init()` then the frontend would panic trying to deference a nil resultsMetrics. This happens sometimes in search streaming.
=> Search streaming: fix race condition

.github/workflows/website-next.yml, .github/workflows/website-versioned.yml
=> Allow manual dispatch of workflows for break glass without commits or tags

modules/frontend/searchsharding.go
Currently if there is a mismatch between the json sent by the querier and the one expected by the query-frontend it will fail to parse. This was recently revealed with the rename of `inspectedBlocks` -> `totalBlocks`.
This PR allows the frontend to leniently parse the response from the querier which prevent this issue and simplifies rollouts.
=> Query-frontend: allow unknown fields

pkg/traceql/engine.go, pkg/traceqlmetrics/metrics.go, pkg/traceqlmetrics/metrics_test.go, pkg/traceqlmetrics/mocks.go
This PR is part of a wider initiative to perform on-demand metrics calculations.  It adds a new package `traceqlmetrics` which can get the metrics from any `SpansetFetcher` given a traceql query and an identifier to group on.  I.e. calculate the duration p90 for the query `{ .service.name="a" && .cluster="prod"}` grouped by `span.customer_id`.  API and integration with https://github.com/grafana/tempo/pull/2368 will follow in a separate PR.
Fixes n/a
**Checklist**
=> Arbitrary span duration metrics from any TraceQL-compatible block

CODEOWNERS, GOVERNANCE.md, MAINTAINERS.md
Proposal to make @stoewer a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/stoewer)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Astoewer)
@grafana/tempo
=> Maintainer - @stoewer

CHANGELOG.md, cmd/tempo/app/app.go, cmd/tempo/app/config.go, cmd/tempo/app/modules.go, docs/sources/tempo/configuration/_index.md, go.mod, go.sum, integration/e2e/api_test.go, integration/util.go, modules/ingester/config.go, modules/ingester/ingester.go, modules/ingester/instance.go, modules/ingester/instance_search.go, modules/ingester/instance_search_test.go, pkg/traceql/engine.go, pkg/traceql/engine_test.go, tempodb/encoding/common/interfaces.go, tempodb/encoding/v2/backend_block.go, tempodb/encoding/v2/wal_block.go, tempodb/encoding/vparquet/block_search_tags.go, tempodb/encoding/vparquet/block_search_tags_test.go, tempodb/encoding/vparquet/wal_block.go, tempodb/encoding/vparquet2/block_search_tags.go, tempodb/encoding/vparquet2/block_search_tags_test.go, tempodb/encoding/vparquet2/wal_block.go, vendor/github.com/grafana/regexp/exec.go, vendor/modules.txt
Add new param `autocomplete_filtering_enabled` to configure filtering results in tag value search `/api/v2/search/<tag>/values`. If disabled, no filtering is done.
It also fallbacks to no filtering if there is no query or it's invalid. It's much faster.
**Checklist**
=> Add config param for autocomplete filtering

cmd/tempo/app/config.go, modules/generator/config.go, modules/generator/generator.go, modules/generator/instance.go, modules/generator/instance_test.go, modules/generator/processor/localblocks/config.go, modules/generator/processor/localblocks/livetraces.go, modules/generator/processor/localblocks/processor.go, modules/storage/config.go, tempodb/config.go, tempodb/encoding/common/config.go
This PR is part of a wider initiative to perform on-demand metrics calculations.  It adds a new processor `local-blocks` that stores a copy of all received traces on disk.  It works almost identically to an ingester with a live traces map, wal, local blocks, retention period, and with similar configuration.  Currently this serves **no purpose** but more functionality will be added in later PRs.
The metrics generator config looks like:
```yaml
metrics-generator:
processor:
local_blocks:
block: (tempodb block config, optional)
flush_check_period: (duration, optional)
trace_idle_period: (duration, optional)
max_block_duration: (duration, optional)
max_block_bytes: (optional)
complete_block_timeout: (optional)
traces_storage:
path: /tmp/tempo/generator/traces (required) …
```
=> New metrics generator processor to store a local copy of traces

integration/util.go
I removed it in https://github.com/grafana/tempo/pull/2433/files#diff-a7eacfbc9abb400eb8d6a88999ad08771790b3c85eba0a1e5ce2366ce8544443L33-L45, thinking it wasn't being used. But it's being used in internal CIs.
=> Undo remove of TEMPO_EXTRA_ARGS in e2e tests

modules/generator/config.go, modules/generator/overrides.go, modules/generator/overrides_test.go, modules/generator/processor/localblocks/config.go, modules/generator/processor/localblocks/livetraces.go, modules/generator/processor/localblocks/metrics.go, modules/generator/processor/localblocks/processor.go, modules/overrides/limits.go, modules/overrides/overrides.go
This PR is part of a wider initiative to perform on-demand metrics calculations. Add per-tenant overrides and limits for settings related to flushing/retaining local blocks, and a few metrics similar to those in the ingester.  
Fixes n/a
**Checklist**
=> Support per-tenant limits in metrics generator local blocks processor

CHANGELOG.md, modules/querier/http.go
Changes the querier to ignore context canceled errors and return 200s. Tempo cancels context as part of normal operation. On the trace by id path, if hedging is turned on, then context will be canceled for other the slower requests. On the search path we commonly kick off thousands of jobs most of which are canceled when the search limit is hit.
Before this change the queriers would spam the logs with "context canceled" errors and metric tons of failed requests.
**Checklist**
=> Queriers: Ignore context canceled

CHANGELOG.md, modules/generator/storage/instance.go
Fixes a bug in our usage of the Prometheus `agent.DB` and `remote.Storage` structures. When we append data onto `agent.DB` we also need to append it onto `remote.Storage` to ensure `prometheus_remote_storage_highest_timestamp_in_seconds` is updated ([append implementation](https://github.com/prometheus/prometheus/blob/5c5fa5c319fca713506fa144ec6768fddf00d466/storage/remote/write.go#L268
)).
This timestamp is used to determine how many shards are needed, since this metric wasn't updated desired shards is always set to 1, even if remote write is running behind and needs to catch up.
**Checklist**
=> metrics-generator: use fanout storage to correctly update Prometheus remote write

modules/generator/processor/localblocks/processor.go, tempodb/encoding/common/interfaces.go, tempodb/encoding/v2/wal_block.go, tempodb/encoding/vparquet/wal_block.go, tempodb/encoding/vparquet2/wal_block.go, tempodb/wal/wal_test.go
This PR is part of a wider initiative to perform on-demand metrics calculations.  Adds a new WAL write path `AppendTrace` which takes a `tempopb.Trace` instead of encoded bytes, which allows the LocalBlocks processor to write more efficiently since it already has the traces in `tempopb.Trace` form.  No change made to ingester write path, except there will be a small difference in flushing going from `len(proto)` to `estimateMarshalledSizeFromTrace()` in the parquet encodings.
Updated just the one test `tempodb/wal/TestFindByTraceID` to cover both write paths.
Fixes n/a
**Checklist**
=> Wal blocks AppendTrace method

CHANGELOG.md, modules/ingester/ingester.go
**What this PR does**: Move the flush queue worker to start after wal replay and block rediscovery. 
Address https://github.com/grafana/tempo-squad/issues/223
Fixes https://github.com/grafana/tempo-squad/issues/242
**Checklist**
=> Start flush queue worker after wal replay

CHANGELOG.md, operations/jsonnet-compiled/StatefulSet-memcached.yaml, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet/microservices/config.libsonnet
We're a couple years out of date, so here we update the memcached image after testing it a bit.
**Checklist**
=> [jsonnet-microservices] Update memcached image

pkg/parquetquery/predicates.go, tempodb/encoding/vparquet2/block_traceql_test.go
Makes regex predicate faster.  Particularly the case where there are found matches because of all the map access.
Tweak originally discussed https://github.com/grafana/tempo/pull/2410#discussion_r1181532807
```
name                                                 old time/op    new time/op    delta
BackendBlockTraceQL/spanAttIntrinsicRegexNoMatch-12    2.51ms ± 2%    2.45ms ± 0%   -2.52%  (p=0.000 n=9+8)
BackendBlockTraceQL/spanAttIntrinsicRegexMatch-12      72.1ms ± 2%    49.5ms ± 2%  -31.36%  (p=0.000 n=9+10)
name                                                 old speed      new speed      delta
BackendBlockTraceQL/spanAttIntrinsicRegexNoMatch-12   385MB/s ± 2%   395MB/s ± 0%   +2.58%  (p=0.000 n=9+8)
BackendBlockTraceQL/spanAttIntrinsicRegexMatch-12     186MB/s …
```
=> Regex tweak

CHANGELOG.md, cmd/tempo/app/app.go, cmd/tempo/app/modules.go, modules/compactor/compactor.go, modules/distributor/distributor.go, modules/distributor/forwarder.go, modules/distributor/forwarder/manager.go, modules/distributor/ingestion_rate_strategy.go, modules/frontend/frontend.go, modules/frontend/search_streaming.go, modules/frontend/searchsharding.go, modules/generator/registry/overrides.go, modules/ingester/ingester.go, modules/ingester/limiter.go, modules/overrides/interface.go, modules/overrides/overrides.go, modules/querier/querier.go
A lot of modules in Tempo rely on the overrides package for runtime config, they directly use the `overrides.Overrides` struct. This makes the coupling very tight and limits modularity.
Changes:
- extract `overrides.Interface` from the methods of `overrides.Overrides`
- use this interface in as much places as possible
- export the Overrides module from `App`
**Checklist**
=> Introduce `overrides.Interface` to decouple implementation from usage

.drone/drone.jsonnet, .drone/drone.yml, CHANGELOG.md, cmd/tempo-serverless/lambda/Dockerfile
**What this PR does**: Update go 1.20 -> 1.20.4 to match GET
**Checklist**
=> update go 1.20.4

modules/generator/processor/localblocks/config.go, modules/generator/processor/localblocks/processor.go, modules/generator/processor/localblocks/processor_test.go
This PR is part of a wider initiative to perform on-demand metrics calculations.  Updates the `/generator/api/metrics` API to query all blocks.  Includes some basic caching with simplelru that definitely needs to be replaced with something more robust.  Finally added a test but it's a good one 😬 
Fixes n/a
**Checklist**
=> Local blocks processor query all blocks

docs/sources/tempo/traceql/query-editor.md
Preparing to share the content from the query editor page to the Cloud and the Grafana docs. This update: 
* Changes the image calls from the TraceQL query editor page to use the asset storage in GCP instead of local storage
* Removes calls to specific Tempo versions
* Adds a few words about Grafana Cloud vs Grafana
=> [DOC] Update query-editor.md

tempodb/encoding/vparquet/compactor_test.go, tempodb/encoding/vparquet2/compactor_test.go
`TestCountSpans` randomly selects a batch and span size to run the tests with. When high numbers are chosen for both values, the tests will allocate > 10 GB memory. This PR makes the 
batch and span size more predictable in order to avoid excess memory allocation.
**Checklist**
=> Run TestCountSpans with predictable batch and span size

Makefile, tempodb/tempodb_search_test.go
Previously we created 4 vParquet and 4 vParquet2 block. one for each of the different search tests and then ran the tests.
This PR flips things around and creates 1 vParquet and vParquet2 block and runs all 4 tests on each.
=> Possibly reduce cost of tempodb tests

docs/sources/tempo/metrics-generator/service_graphs.md, modules/generator/processor/servicegraphs/servicegraphs.go, modules/generator/processor/servicegraphs/servicegraphs_test.go, modules/generator/processor/servicegraphs/testdata/trace-with-virtual-nodes.json
Simplify default peer attributes for virtual nodes.
**Checklist**
=> [servicegraph] Simplify default peer attributes

docs/sources/tempo/traceql/architecture.md, docs/sources/tempo/traceql/query-editor.md
Removes the early access warning from the TraceQL architecture page. 
**Checklist**
=> [DOC] [TraceQL] Remove early access message

CHANGELOG.md, operations/jsonnet-compiled/ConfigMap-tempo-query.yaml, operations/jsonnet-compiled/Deployment-query-frontend.yaml, operations/jsonnet-compiled/Service-query-frontend-discovery.yaml, operations/jsonnet-compiled/Service-query-frontend.yaml, operations/jsonnet-compiled/util/Makefile, operations/jsonnet-compiled/util/example/main.jsonnet, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet/microservices/config.libsonnet, operations/jsonnet/microservices/configmap.libsonnet, operations/jsonnet/microservices/frontend.libsonnet, operations/jsonnet/single-binary/config.libsonnet, operations/jsonnet/single-binary/configmap.libsonnet, operations/jsonnet/single-binary/tempo.libsonnet
tempo-query was required for Grafana version <7.5 for compatibility with jaeger-ui. grafana version <7.5 didn't have Tempo datasource, and we used jaeger datasource to query tempo via tempo-query.
Grafana 7.5 was released on Mar 25, 2021, which was 2+ year ago.
It is already disabled by default in helm-chart: https://github.com/grafana/helm-charts/pull/2387
**Checklist**
=> Disable tempo-query by default in Jsonnet libs

cmd/tempo/app/config.go, cmd/tempo/app/modules.go
Adds an internal config hook to disable the new grpc over http behavior.  It impacted the enterprise traces gateway module because it does its own protocol mux to handle grpc and http over the same port already, and is not straight-forward to make it work again when this behavior is enabled.    I don't consider this setting user-facing so it's not exposed in the yaml.
Fixes n/a
**Checklist**
=> Add internal hook to disable the grpc over http behavior

pkg/api/http.go, pkg/api/http_test.go
This PR fixes an issue introduced in https://github.com/grafana/tempo/pull/2468  where calling `/api/search` with no parameters would turn into an ingester search for the tags `start="0"` and `end="0"`  The root cause is the new [ingesterRequest function](https://github.com/grafana/tempo/pull/2468/files#diff-37a55d5d14039ce02a2185b21f3180c569bc546cfedbbe4bf8ede63408f68892R382).  Previously it always filled in the start/end request time range, but now it preserves the case where start/end=0, and they get interpreted as tag conditions.   This fix unfortunately prevents actually searching against the tags "start" and "end".  I'm not sure if that's why they were originally left out of the if statement, but since this is all very deprecated, I think this makes the most …
=> SearchRecent ignore start and end parameters

CHANGELOG.md, cmd/tempo/app/config_test.go, docs/sources/tempo/configuration/_index.md, docs/sources/tempo/configuration/manifest.md, docs/sources/tempo/configuration/parquet.md, docs/sources/tempo/operations/schema.md, tempodb/encoding/versioned.go
The new block format `vParquet2` has been tested extensively over the past weeks. This PR makes it the new default. 
**Checklist**
=> Make vParquet2 the default block format

CHANGELOG.md, modules/frontend/search_progress.go, modules/frontend/search_progress_test.go, modules/frontend/search_streaming.go, modules/frontend/search_streaming_test.go, modules/frontend/searchsharding.go, modules/frontend/searchsharding_test.go
Uses a channel to return jobs instead of a returning them as a slice from backendRequests. This nicely improves performance for queries that create a huge number of jobs.
**Other Changes**
- Fixes a bug in `searchProgress.internalShouldQuit()` where we needed 1 more than the limit to quit
- Switches `totalBlockBytes` to be a `uint64` throughout
Benchmarks:
```
name                           old time/op    new time/op    delta
SearchSharderRoundTrip5-8         181ms ± 1%       1ms ± 9%  -99.54%  (p=0.008 n=5+5)
SearchSharderRoundTrip500-8       184ms ± 1%      12ms ± 1%  -93.27%  (p=0.008 n=5+5)
SearchSharderRoundTrip50000-8     318ms ± 4%     472ms ± 2%  +48.65%  (p=0.008 n=5+5)
name                           old alloc/op   new alloc/op   delta …
```
=> Reduce impact of backendRequests on latency

CHANGELOG.md, tempodb/encoding/vparquet/block_search.go, tempodb/encoding/vparquet2/block_search.go, tempodb/encoding/vparquet2/block_traceql_test.go
The new synchronous iterator added in #2165 has been running internally for awhile and going well, so this makes it the default.  Environment variables were swapped around so that we can revert back if needed.
I was also very lax about updating the changelog lately, and adds some missing entries. 
Fixes n/a
**Checklist**
=> Make synchronous parquet iterator default

modules/generator/registry/counter_test.go
Fixes the commonly flaking test:
```
=== RUN   Test_counter
counter_test.go:249: 
Error Trace:	/home/joe/dev/joe-elliott/tempo/modules/generator/registry/counter_test.go:249
/home/joe/dev/joe-elliott/tempo/modules/generator/registry/counter_test.go:53
Error:      	elements differ
extra elements in list A:
([]interface {}) (len=1) {
(registry.sample) {
l: (labels.Labels) (len=2) {
...
```
The test recalculated `collectionTimeMs`, but failed to recalculate `offsetCollectionTimeMs` based on the new value. If the current ms happened to tick over between lines 27 and 42 the test would fail.
=> Fix Counter Test

operations/tempo-mixin-compiled/alerts.yaml, operations/tempo-mixin/alerts.libsonnet, operations/tempo-mixin/runbook.md
Here we include a new mixin alert to notify when the block list growth is over 40% over the last 7 days.  This may indicates an under-scaled compactor deployment.
**Checklist**
=> [tempo-mixin] add new alert to identify block list growth

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, docs/sources/tempo/configuration/manifest.md, modules/storage/config.go, tempodb/blocklist/poller.go, tempodb/blocklist/poller_test.go, tempodb/config.go, tempodb/tempodb.go
Currently, if flakey errors occur during polling, the entire loop exits early and doesn't restart until the next timer. This can effectively starve some tenants and cause their indexes to fall out of date both due to failure to be written and failure to be read.  This PR changes the high-level error handling to be a circuit-breaker style where it will keep going until a configurable amount of consecutive errors happen.  The idea is that flakey errors will not halt polling, but consistent errors due to misconfiguration, auth, or networking will, so that we don't keep hammering the backend.   By default it's set to tolerate 1 error only, meaning it will fail if there are 2 consecutive errors.  It can also be set to 0 to revert to the prior behavior where every error …
=> Continue polling remaining tenants on error

CHANGELOG.md, docs/sources/tempo/configuration/_index.md, modules/ingester/config.go, modules/ingester/flush.go, modules/ingester/ingester.go
[Ingester] Add ability to completely flush on shutdown
Fixes #699
**Checklist**
=> FIX-699: Add capability to completely flush on shutdown

modules/overrides/interface.go, modules/overrides/limits.go, modules/overrides/overrides.go, modules/overrides/overrides_test.go, tempodb/backend/block_meta.go
Adds dedicated columns config to overrides, and wire up the write path to work with dynamic columns
Fixes #2548 
**Checklist**
=> [vParquet3] Add dedicated columns to overrides module

docs/sources/tempo/setup/linux.md
Corrects the version of Tempo called in the Linux set up guide from 1.5 to 2.1.1.
Fixes #2572 
**Checklist**
=> [DOC] Fix Tempo version in Linux doc

CHANGELOG.md, modules/ingester/instance.go, modules/ingester/instance_search.go, modules/ingester/instance_test.go
Fixes #2534 by keeping the lock until the search is complete, but also splits out a separate mutex for the headblock ease contention on the core write path (live traces -> disk).   I added a new `BenchmarkInstanceContention` to help measure the effect, which is similar to the `xxxDoesNotRace` methods but prints out the op/sec of each thing.   Comparison between `main` and this branch are below. There's definitely a draw back in reads due to the increased lock time, but the write path actually looks better, since it only has to lock the headblock, and I took care to ensure that the read paths release the headblock as soon as possible.
```
name                   old time/op            new time/op            delta
InstanceContention-12             2.37s ±21% …
```
=> Fix ingester locking

modules/frontend/searchsharding.go, modules/frontend/searchsharding_test.go
A bug [was introduced](https://github.com/grafana/tempo/pull/2530) by changing the `searchReq` param on `ingesterRequest` from a value type to a pointer. The pointer allowed the struct to be modified by the calling code which broke request ranges that included ingester requests.
Fixes #2577 
**Checklist**
=> Fix range calculation on recent searches

operations/tempo-mixin-compiled/dashboards/tempo-operational.json, operations/tempo-mixin/dashboards/tempo-operational.json
To gain a little more visibility into the metrics-generator on the Tempo Operational dashboard, we make the following updates.
* Add QPS and latency metrics in the read path for the gateway, frontend, querier and the metrics-generator
* Add metrics-generator spans accepted/refused in the write path as well as push latency
**Checklist**
=> Include metrics-generator in Operational dashboard

cmd/tempo/app/modules.go, modules/ingester/config.go, modules/ingester/ingester.go, modules/ingester/ingester_test.go, modules/ingester/instance.go, modules/ingester/overrides.go, modules/overrides/overrides.go, modules/overrides/overrides_test.go, pkg/util/test/req.go, tempodb/backend/block_meta.go, tempodb/encoding/common/config.go, tempodb/encoding/v2/encoding.go, tempodb/encoding/v2/streaming_block.go, tempodb/encoding/versioned.go, tempodb/encoding/vparquet/encoding.go, tempodb/encoding/vparquet2/create.go, tempodb/encoding/vparquet2/encoding.go, tempodb/encoding/vparquet2/wal_block.go, tempodb/encoding/vparquet2/wal_block_test.go, tempodb/tempodb.go, tempodb/wal/wal.go, tempodb/wal/wal_test.go
Propagates dynamic columns configuration to the write path. Ingesters now are able to create and write to blocks with dedicated columns.
Fixes #2552
**Checklist**
=> [vParquet3] Write path

modules/frontend/searchsharding.go, modules/frontend/searchsharding_test.go
Recent improvements to the search sharding logic broke the jobs reporting. It no longer reports the ingester request as a job and we stopped adding this info to the span.
Since this was broken and fixed in the same release I'm leaving off a changelog entry.
=> Fix Reporting of Total Jobs

operations/jsonnet/microservices/multi-zone.libsonnet
Upgrade podDisruptionBudget policy API from v1beta1 to v1 as the v1beta1 deprecated in k8s 1.25.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
**Checklist**
=> Update podDisruptionBudget policy API version [ksonnet]

modules/frontend/tracebyidsharding.go
404 is valid response for TraceByID search, and should be recorded in SLOs.
=> fix: record TraceByIDSLO for 404 response

tempodb/compactor.go
We will flood compactor logs with `compaction cycle complete. No more blocks to compact` in clusters with agreesive `compaction_cycle` and multiple tenants. this will contribute to extra log volume as well, so tone it down from Info to debug level.
=> Change compaction cycle complete log line to Debug level

tempodb/tempodb_test.go
Consecutive calls to `time.Now()` when instatiating `now`, `oneHourAgo` and `oneHour` were sometimes slow enough that it'd jump 1 second, causing the test to fail.
Example: https://github.com/grafana/tempo/actions/runs/5519373314/jobs/10064554388?pr=2622
=> Fix instability of `TestCompleteBlockHonorsStartStopTimes`

CHANGELOG.md, cmd/tempo/main.go
While adding config warnings in https://github.com/grafana/tempo/pull/2543 I noticed the warnings never got printed. Because we print the warnings while loading the configuration, we log them using the default NoopLogger...
This PR holds on to the warnings until we initialized the logger and can correctly log them. 
End result:
```
level=warn ts=2023-07-12T16:30:04.59588Z caller=main.go:78 msg="-- CONFIGURATION WARNINGS --"
level=warn ts=2023-07-12T16:30:04.595906Z caller=main.go:78 msg="c.Distributor.LogReceivedTraces is deprecated. The new flag is c.Distributor.log_received_spans.enabled"
level=warn ts=2023-07-12T16:30:04.595911Z caller=main.go:78 msg="Trace storage conflict with user-configuirable overrides storage"
level=info ts=2023-07-12T16:30:04.595916Z …
```
=> Delay logging config warnings until the logger has been initialized

cmd/tempo-cli/main.go, cmd/tempo-serverless/handler.go, cmd/tempo-serverless/handler_test.go, cmd/tempo/app/config.go, cmd/tempo/app/config_test.go, cmd/tempo/app/modules.go, integration/e2e/backend/backend.go, integration/e2e/serverless/serverless_test.go, modules/ingester/ingester_test.go, tempodb/backend/backend.go, tempodb/compactor_test.go, tempodb/retention_test.go, tempodb/tempodb.go, tempodb/tempodb_search_test.go, tempodb/tempodb_test.go
The linter is complaining we have too many copies of `"local"` and `"gcs"`. This introduces constants in the backend package that we can use in other places.
It satisfies the linter but we end up introducing more dependencies on the backend package.
**Checklist**
=> Introduce constants for the backend types

CHANGELOG.md, pkg/util/math/math.go, tempodb/encoding/vparquet2/block_traceql.go, tempodb/tempodb_search_test.go
A few fixes in the structural operators:
1. Need to skip over spans with broken nesting. This is detected as any value of either span == 0.  Without this it was falsely identifying matches on partial traces where the spans had broken nesting
2. Sibling operator would falsely identify a span as its own sibling if it was present in multiple spansets.  I.e. `{ .foo} ~ {.foo}` because each input technically had the same parent.  There are two ways to fix this, and I chose the more efficient one.  Theoretically we could loading both Parent and Left and ensure Lefts are different (not same spans).  However instead I am just checking struct pointers to ensure not the same `*span`.  This works until the TraceQL engine starts making multiple passes over a file (which is not …
=> Fix a few bugs in vParquet2 structural operators

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md, docs/sources/tempo/setup/helm-chart.md
Updates Helm chart doc based on feed back from @danstadler-pdx. 
**Checklist**
=> [DOC] Updates from working session on Helm docs

pkg/traceql/ast_execute.go, pkg/traceql/ast_execute_test.go
Under certain circumstances the descendant operators will adjust the input slice by setting a member to nil for record keeping:
https://github.com/grafana/tempo/blob/3b618cc343ed79399985bc06a553662994a3cf9c/pkg/traceql/ast_execute.go#L193
Later when the encoding layer attempts to recover the span it panics b/c the span is nil:
https://github.com/grafana/tempo/blob/3b618cc343ed79399985bc06a553662994a3cf9c/tempodb/encoding/vparquet2/block_traceql.go#L414
This PR fixes the issue by not modifying the input slice and adds a test to check for this condition.
**Checklist**
=> Fix panic with unmatched descendant selectors

modules/querier/external/client_test.go, tempodb/backend/mocks.go, tempodb/backend/raw.go, tempodb/backend/raw_test.go, tempodb/blocklist/poller.go
When a tenant stops writing to tempo, the blocks eventually get cleaned up by the retention, but the tenant index is still left and so the tenant is still left in the list when the poller determines which indexes to pull.  This can create additional load for no benefit long term if the tenant doesn't return with traffic.
Here we call the recently implemented `Delete` on the `RawWriter` to remove the tenant indexes from the backend to complete the deletion of all tenant objects when no blocks or compacted blocks have been found to exist.
Fixes #2520
**Checklist**
=> Delete the index for empty tenants

modules/overrides/userconfigurableapi/client.go, pkg/cache/cache.go, tempodb/backend/azure/azure.go, tempodb/backend/cache/cache.go, tempodb/backend/gcs/gcs.go, tempodb/backend/local/local.go, tempodb/backend/mocks.go, tempodb/backend/raw.go, tempodb/backend/s3/s3.go
Here we pass the cache.Delete() call on to the nextWriter instead of panic in cases where we do not want to cache.  Cache deletion is still not supported and will panic.
**Checklist**
=> Avoid panic in cachedWriter

docs/sources/tempo/configuration/_index.md, docs/sources/tempo/configuration/manifest.md, docs/sources/tempo/configuration/parquet.md, docs/sources/tempo/operations/dedicated_columns.md
Add `vParquet3` and dedicated columns configuration.
Depends on https://github.com/grafana/tempo/pull/2649 and https://github.com/grafana/tempo/pull/2622
Fixes #2663
**Checklist**
=> [vParquet3] docs

operations/jsonnet-compiled/ConfigMap-tempo-compactor.yaml, operations/jsonnet-compiled/ConfigMap-tempo-distributor.yaml, operations/jsonnet-compiled/ConfigMap-tempo-ingester.yaml, operations/jsonnet-compiled/ConfigMap-tempo-metrics-generator.yaml, operations/jsonnet-compiled/ConfigMap-tempo-querier.yaml, operations/jsonnet-compiled/ConfigMap-tempo-query-frontend.yaml, operations/jsonnet-compiled/Deployment-compactor.yaml, operations/jsonnet-compiled/Deployment-distributor.yaml, operations/jsonnet-compiled/Deployment-metrics-generator.yaml, operations/jsonnet-compiled/Deployment-querier.yaml, operations/jsonnet-compiled/Deployment-query-frontend.yaml, operations/jsonnet-compiled/StatefulSet-ingester.yaml, operations/jsonnet-compiled/StatefulSet-metrics-generator.yaml, operations/jsonnet-compiled/util/jsonnetfile.lock.json, operations/jsonnet/microservices/configmap.libsonnet
Related: https://github.com/grafana/loki/pull/9723
The current default configuration will result in a connection to each member returned by a DNS entry and result in more connections than is necessary.  In large clusters, this can become a problem.
Here we include the fix that Loki has for using a `dns+` lookup feature of memberlist to ensure that only a few members of the DNS entry are added.
**Checklist**
=> microservices: use DNS lookup for memberlist.join_members by default

tempodb/tempodb_search_test.go
Now that the structural operator bugs are fixed in vParquet3, the disabled test cases can be re-enabled
Is related to #2674
**Checklist**
=> Re-enable test cases for structural operators

RELEASES.MD
- It's no longer dang easy
- Added an explicit instruction to create release branch. Suggested the same commit as the RC
- Added a note about what "cleaning up the changelog" means in the face of an RC
=> improve release instructions

modules/querier/external/client.go, modules/querier/external/token_provider.go, modules/querier/querier.go, modules/querier/querier_test.go
I implemented a feature enabling RBAC on Google Cloud Run endpoints, which was merged last week: https://github.com/grafana/tempo/pull/2593
But there is a bug with the configuration, as described below. This PR fixes that bug.
**Repro:**
Run Tempo with the following config:
```
querier:
search:
external_backend: google_cloud_run
google_cloud_run:
external_endpoints: ["https://my-cloud-run-endpoint.run.app"]
```
Open the Grafana Tempo explore panel, and search for traces.
We'll see traces in our results, but they should be coming from our external Cloud Run endpoint, not an internal block search.
**Expected:**
Block queries are sent to the external Cloud Run endpoint.
**Actual:**
An internal search is performed instead of an external search. This is because the …
=> Queriers: Fix external search config when using RBAC with Google Cloud Run

tempodb/encoding/vparquet2/schema.go, tempodb/encoding/vparquet3/schema.go, tempodb/encoding/vparquet3/schema_test.go
Struggling to find a good test for this, but can confirm it fixes the issue in intro to mlt. The nested set model values were not being correctly wiped out while translating from proto -> parquet which resulted in some values bleeding through.
This needs to be backported to 2.2.
Fixes #2725 
**Checklist**
=> Wipe nested set model fields

tempodb/encoding/vparquet2/schema.go
Backports https://github.com/grafana/tempo/pull/2729 to release v2.2 to fix structural queries.
=> Backport #2729 to release v2.2
