CHANGELOG.md

Renames the 2.2-rc.0 changelog to 2.2 now that the release is published:
https://github.com/grafana/tempo/releases/tag/v2.2.0

2.2 Changelog Cleanup

---

CHANGELOG.md
pkg/traceqlmetrics/metrics.go
pkg/traceqlmetrics/metrics_test.go

Fixes a panic for very large uint64s.  This was seen in the wild and my best guess is its from calculating `duration = endTime - startTime` when endTime is less than startTime (leading to unsigned wrap-around).  So this doesn't address the root cause, per se, but prevents the panic and bad data will be visible.
Fixes n/a
**Checklist**

Metrics Summary:  fix panic edge case

---

modules/overrides/userconfigurableapi/limits.go

We were missing some `omitempty` struct tags on the user-configurable overrides. Setting these avoids you get potentially confusing responses like
```json
{
"forwarders": null,
}
```
**Checklist**

Add missing `omitempty` struct tags to user-configurable API

---

docs/sources/tempo/release-notes/v2-2.md
docs/sources/tempo/traceql/_index.md

Add the link to the blog post for the 2.2 release: [Tempo 2.2 blog post](/blog/2023/08/02/grafana-tempo-2.2-release-traceql-structural-operators-are-here/) 
**Checklist**

[DOC] Add blog link to release notes

---

cmd/tempo/app/app.go
pkg/api/http.go

https://github.com/grafana/tempo/pull/2702 added a new public endpoint to Tempo to view the current version of Tempo running. Since this is part of the API now it should respect `http_api_prefix`.
**Checklist**

Ensure `/api/status/buildinfo` respects `http_api_prefix`

---

CHANGELOG.md
tempodb/backend/s3/awssdkauth.go
tempodb/backend/s3/s3.go

Backports Cortex fix to tempo to fix issue with IDMSv1 and node role auth.
Fixes #2743 
**Checklist**

Backport https://github.com/cortexproject/cortex/pull/4897 to fix IDMSv1

---

docs/sources/tempo/configuration/_index.md
modules/distributor/forwarder/forwarder.go
modules/distributor/forwarder/forwarder_test.go
modules/distributor/forwarder/manager.go
modules/distributor/forwarder/manager_test.go
modules/frontend/frontend.go

Unfortunate merge timing meant that we re-introduced some weaveworks packages which we intended to drop.  Here we make the weaveworks -> dskit transition that was intended.
**Checklist**

Replace weavework with dskit for recent merge

---

docs/sources/tempo/operations/troubleshooting/_index.md
docs/sources/tempo/operations/troubleshooting/metrics-generator.md

Adds a trouble shooting page for metrics generator. There have been a lot of questions like
https://github.com/grafana/tempo/issues/2771
and I feel like this is a gap in the docs.

Add a generator troubleshooting page

---

CHANGELOG.md
modules/ingester/instance_search.go
modules/ingester/instance_search_test.go

Uses the block meta time range in the ingesters to only search some of the blocks
**Checklist**

Enforce the time range on ingester search

---

CHANGELOG.md
tempodb/backend/azure/azure.go
tempodb/backend/gcs/gcs.go
tempodb/backend/mocks.go
tempodb/backend/raw.go
tempodb/backend/raw_test.go
tempodb/blocklist/poller.go

Here we ensure that when Tempo tries to delete a tenant index that has already been deleted, that this is not an error condition, and doesn't not log or count against the metrics.  This can happen when an index was deleted because no blocks have been found, but for block paths that still contain spurious objects.
**Checklist**

Avoid index errors for deleted tenants

---

docs/sources/tempo/traceql/_index.md

Small proposal to remove "b/c" from the [Query with TraceQL](https://grafana.com/docs/tempo/latest/traceql/#query-with-traceql) documentation page, more precisely in the [Selection](https://grafana.com/docs/tempo/latest/traceql/#selection) section:

Avoid using "b/c" in official documentation

---

CHANGELOG.md
modules/overrides/user_configurable_overrides.go
operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet

Add metric to count failed overrides reloads and alert on it.
**Checklist**

Add TempoUserConfigurableOverridesReloadFailing alert

---

CHANGELOG.md
modules/generator/instance.go
modules/generator/instance_test.go
vendor/golang.org/x/exp/maps/maps.go
vendor/modules.txt

We have a concurrent read/write panic while reading from `desiredProcessors`, this is the only place we modify it really. Let's copy it before modifying it.
Fixes https://github.com/grafana/tempo/issues/2785
**Checklist**

Fix panic in the metrics-generator when using multiple tenants with default overrides

---

pkg/dataquality/warnings.go
tempodb/compactor.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/v2/wal_block.go
tempodb/encoding/vparquet/wal_block.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/block_search_test.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet3/combiner.go
tempodb/encoding/vparquet3/combiner_test.go
tempodb/encoding/vparquet3/compactor.go
tempodb/encoding/vparquet3/compactor_test.go
tempodb/encoding/vparquet3/create.go
tempodb/encoding/vparquet3/nested_set_model.go
tempodb/encoding/vparquet3/nested_set_model_test.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/schema_test.go
tempodb/encoding/vparquet3/wal_block.go

Counts disconnected traces in two "phases" of a trace's lifetime. The first is when the trace is cut from live traces to the head block. The second is when the trace is combined in the compactor. These counters should be combined with other metrics to get a percentage of traces disconnected:
```
rate(tempo_warnings_total{reason="disconnected_trace_flushed_to_wal"}[1m]) /
rate(tempo_ingester_traces_created_total{}[1m])
```
```
rate(tempo_warnings_total{reason="disconnected_trace_compactor_combine"}[1m]) /
rate(tempodb_compaction_objects_combined_total{}[1m])
```
*Thoughts*
- The first metric percentage above isn't exact. "Traces created" is counted when a live trace is created. The warning is counted when a live trace is flushed to the wal.
- There is an opportunity …

Add trace quality metrics

---

CHANGELOG.md
cmd/tempo-query/tempo/config.go
cmd/tempo-query/tempo/plugin.go

Reverts #2414. This config field was in use by RH for authentication through jaeger-query.

Revert "Remove tenant_header_key from config (#2414)"

---

CHANGELOG.md
modules/generator/instance.go
modules/generator/instance_test.go
vendor/golang.org/x/exp/maps/maps.go
vendor/modules.txt

Backport 9af6bb2eccd7c04c2f06097278f6b92f8d74860b from #2786
---
We have a concurrent read/write panic while reading from `desiredProcessors`, this is the only place we modify it really. Let's copy it before modifying it.
Fixes https://github.com/grafana/tempo/issues/2785
**Checklist**

[release-v2.2] Fix panic in the metrics-generator when using multiple tenants with default overrides

---

tempodb/backend/azure/azure.go
tempodb/backend/gcs/gcs.go
tempodb/backend/mocks.go
tempodb/backend/raw.go
tempodb/backend/raw_test.go

Backport e960fd03a8ee4a1208dbf4fe449a7700e61ed225 from #2781
---
Here we ensure that when Tempo tries to delete a tenant index that has already been deleted, that this is not an error condition, and doesn't not log or count against the metrics.  This can happen when an index was deleted because no blocks have been found, but for block paths that still contain spurious objects.
**Checklist**

[release-v2.2] Avoid index errors for deleted tenants

---

CHANGELOG.md
cmd/tempo-query/tempo/config.go
cmd/tempo-query/tempo/plugin.go

Backport d9210d04c6782c155b537299b9f7923506fe0f95 from #2795
---
Reverts #2414. This config field was in use by RH for authentication through jaeger-query.

[release-v2.2] Revert "Remove tenant_header_key from config (#2414)"

---

build/tools.mk

Without this change, the `go list` used to track with tools are required by the project is broken in Go 1.21, resulting in the following error.
```
tools.go:6:2: import "github.com/psampaz/go-mod-outdated" is a program, not an importable package
```
Here we add `-e` to the `go list` to allow the list to complete and handle the tool management as before.
**Checklist**

Fix tools package listing on Go 1.21

---

docs/sources/tempo/api_docs/_index.md

Clarified that a feature flag must be enabled for this `q` parameter to be accepted
**Checklist**

Updated the tag values v2 docs

---

cmd/tempo-vulture/main.go
pkg/util/trace_info.go

Fix vulture problems:
* Since #2649 the function `RandomAttrFromTrace()` may return attributes with resource scope. This caused several problems in vulture:
* When searching for `service.name` the matching traces can exceed the limit and the relevant trace could be missing from the result
*Solution: skip the `service.name` attribute when selecting random attributes*
* Vulture's `searchTraceql()` function was only searching through span attributes
*Solution: change query template from `span.%s="%s"` to `.%s="%s"`*
* The order of attributes in generated data can differ from the order of attributes in traces retrieved from the API.
*Solution: sort attributes before testing traces for equality*
Fixes #2792
**Checklist**

Fix incorrectly reported vulture errors

---

.drone/drone.jsonnet
.drone/drone.yml
cmd/tempo-serverless/lambda/Dockerfile

PR #2829 missed to update some of the Go build images which broke the [drone build](https://drone.grafana.net/grafana/tempo/2411).
This PR updates the build images to Go 1.21
**Checklist**

Fix upgrade go to 1.21.0

---

modules/overrides/config_test.go

Follow-up to #2688. Adds a test that checks that the number of overrides in the new and legacy configs is the same. It's main purpose is to alert when adding new overrides that they should be added to the legacy config as well.

Add a count check for legacy and new overrides

---

CHANGELOG.md
cmd/tempo-cli/cmd-convert-parquet-2to3.go
cmd/tempo-cli/main.go
docs/sources/tempo/operations/tempo_cli.md
tempodb/encoding/vparquet2/block_findtracebyid.go
tempodb/encoding/vparquet2/block_findtracebyid_test.go
tempodb/encoding/vparquet2/schema.go
tempodb/encoding/vparquet2/schema_test.go
tempodb/encoding/vparquet2/wal_block.go

Adds a CLI command to convert a vParquet2 _file_ to a vParquet _block_. The ergonomics are weird, but I couldn't find a better way to do it.
I had to make a vParquet2 method public to pull this off. Again, I'm not sure if this is possible otherwise. WDYT?
**Checklist**

Add tempo-cli command: convert parquet-2-to-3

---

pkg/parquetquery/iters.go
pkg/parquetquery/predicates.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet3/block_traceql_test.go

Cleans up/tightens up the Iterator.String() output.
Before:
```
rebatchIterator: 
JoinIterator: 0	
SyncIterator: RootServiceName 
InstrumentedPredicate{1, nil}
SyncIterator: RootSpanName 
InstrumentedPredicate{1, nil}
SyncIterator: DurationNano 
InstrumentedPredicate{1, nil}
SyncIterator: TraceID 
InstrumentedPredicate{1, nil}
SyncIterator: StartTimeUnixNano 
InstrumentedPredicate{1, nil}
LeftJoinIterator: 1
required: 
LeftJoinIterator: 3
required: 
bridgeIterator: 
rebatchIterator: 
JoinIterator: 0	
LeftJoinIterator: 1
required: 
LeftJoinIterator: 3
required: 
UnionIterator(LeftJoinIterator: 4
required: 
SyncIterator: rs.list.element.ss.list.element.Spans.list.element.Attrs.list.element.Key 
InstrumentedPredicate{8, StringInPredicate{foo, }}
optional: 
SyncIterator: …
```

Improve Iterator String() output

---

CHANGELOG.md
modules/distributor/distributor.go

**What this PR does**: Adds `userID` to log message about rate limiting
**Which issue(s) this PR fixes**: https://github.com/grafana/tempo/issues/2842
Fixes #2842 
**Checklist**

[Logs] Adds userID to log message about rate limiting

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Adds warning for Helm chart to not use MinIO in a production environment. 
**Checklist**

[DOC][Helm] Helm chart warning

---

CHANGELOG.md
example/docker-compose/shared/tempo.yaml
integration/e2e/e2e_test.go
integration/e2e/encodings_test.go
modules/frontend/frontend.go
modules/frontend/frontend_test.go
modules/frontend/handler.go
modules/frontend/search_streaming.go
modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go
modules/frontend/slos.go
modules/frontend/slos_test.go
modules/frontend/tracebyidsharding.go
modules/frontend/tracebyidsharding_test.go

This PR reworks the way our SLO metrics are recorded with these goals in mind;
- Push the calculations out to be as close the http.Server as possible
- Clearly metric both total queries and SLO queries in one spot
- Cleanup and remove unused metrics
This PR accomplishes the above with the following sharp corners:
- In order to pass the throughput up to the code that calculates the SLOs a *float was added to the context. This works, but is brittle and difficult to detect if it breaks.
- Specialized code needed to be added to the streaming endpoint
TODO
**Checklist**

Rework SLO metrics

---

docs/sources/tempo/api_docs/_index.md

Fixes a  broken link (missing parenthesis) for filtered tag values.
**Checklist**

[DOC] Fix broken link format in api docs

---

CHANGELOG.md
tempodb/backend/azure/azure_helpers.go

**What this PR does**: To fix #2774 issue, as mentioned it support blob storage in azure stack hub as backend.
Fixes #2774 
**Checklist**

to support blob storage in azure stack hub as backend

---

docs/sources/tempo/troubleshooting/_index.md
docs/sources/tempo/troubleshooting/agent.md
docs/sources/tempo/troubleshooting/bad-blocks.md
docs/sources/tempo/troubleshooting/max-trace-limit-reached.md
docs/sources/tempo/troubleshooting/metrics-generator.md
docs/sources/tempo/troubleshooting/response-too-large.md
docs/sources/tempo/troubleshooting/search-tag.md
docs/sources/tempo/troubleshooting/too-many-jobs-in-queue.md
docs/sources/tempo/troubleshooting/unable-to-see-trace.md

Backports changes from https://github.com/grafana/tempo/pull/2798 to make the troubleshooting directory top-level. 
**Checklist**

[release-v2-2][DOC] Backport 2798 to release v2.2

---

CHANGELOG.md
modules/ingester/instance.go

Moves the location we are calculating `tempo_ingester_traces_created_total` to the point at which a trace is appended to the wal block. This will allow for better alignment with `tempodb_warnings_total{reason="disconnected_trace_flushed_to_wal"}` which improves the accuracy of the formulas recommended here:
https://github.com/grafana/tempo/pull/2790
Preferring this to adding a new multitenant metric. This change doesn't really lower the value of `tempo_ingester_traces_created_total` it just subtly changes it's meaning. Given that it still broadly metrics traces created total this feels fine to me, but willing to be disagreed with.
**Checklist**

Move ingester_traces_created_total

---

CHANGELOG.md
modules/frontend/search_progress.go
modules/frontend/search_progress_test.go
modules/frontend/searchsharding_test.go
modules/querier/querier.go

This PR moved the substitution of empty root span to the query frontend, to be applied on results coming from backend blocks.
Fixes [#2671](https://github.com/grafana/tempo/issues/2671)
**Checklist**

substitute empty root span in query frontend

---

docs/sources/tempo/api_docs/metrics-summary.md

Fixes a typo and missing comma in the metrics-summary API doc. 
**Checklist**

[DOC] Fix typo in metrics-summary API

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/parquet.md
docs/sources/tempo/operations/backend_search.md
docs/sources/tempo/operations/dedicated_columns.md
docs/sources/tempo/operations/schema.md
docs/sources/tempo/operations/tempo_cli.md

A number of small documentation improvements related to vParquet3
Fixes grafana/tempo-squad#307
**Checklist**

vParquet3 documentation improvemens

---

CHANGELOG.md
pkg/api/search_tags.go
pkg/api/search_tags_test.go

Tag names are currently not escaped (encoded) by Grafana when using them in URLs, such as for the `/api/v2/search/tag/<tag>/values` endpoint. We have a [PR in Grafana](https://github.com/grafana/grafana/pull/74437) to fix this issue by escaping tag names, but we need Tempo to unescape (decode) them.
**Checklist**

Unescape (decode) tag names

---

CHANGELOG.md
cmd/tempo/app/overrides_validation.go
cmd/tempo/app/overrides_validation_test.go
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go
modules/overrides/userconfigurable/client/limits.go
pkg/spanfilter/config/config.go

Extends the user-configurable overrides added in https://github.com/grafana/tempo/pull/2543 with spanmetrics filter policies override.
New JSON Payload example:
```json
{
"forwarders": [],
"metrics_generator": {
"processors": [
"service-graphs",
"span-metrics"
],
"disable_collection": false,
"processor": {
"service_graphs": {
"dimensions": [
"service.namespace"
],
"enable_client_server_prefix": true,
"peer_attributes": [
"peer.service",
"db.name",
"db.system",
"db.url"
]
},
"span_metrics": {
"dimensions": [
"service.namespace"
],
"enable_target_info": true,
"filter_policies": [
{
"include": {
"match_type": "strict",
"attributes": [
{
"key": "span.kind",
"value": "SPAN_KIND_SERVER"
}
]
}
},
{
"include": {
"match_type": "strict",
"attributes": [
{
"key": "span.kind", …
```

Add span metrics filter policies to user-configurable overrides api

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go

Returns an error from the metrics summary API if the time range in the request looks back further than the available data.  For instance if the local blocks processor is only configured to store 1 hour of data, and the caller requests the past 24 hours, then it will return an error.
Fixes n/a
**Checklist**

Metrics summary API - Validate the requested time range 

---

modules/generator/registry/registry_test.go

This pull request implements a solution to the flaky `TestManagedRegistry_externalLabels` test.
`TestManagedRegistry_externalLabels` is flaky since it relies on a specific label order which is not guaranteed. The solution is particularly tricky as neither sample order nor label order is guaranteed across the test suite, meaning `collectRegistryMetricsAndAssert` must assert agnostic of both sample _and_ label order.
**This pull request contains no functional changes to Tempo.**
Fixes #2881.
**Checklist**

Fix flaky `TestManagedRegistry_externalLabels`

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
tempodb/backend/s3/config.go
tempodb/backend/s3/s3.go

Configures the S3 credentials chain based on what S3 auth method is configured.
Added a config param to S3 config `native_aws_auth_enabled`. When enabled, Tempo will use the default authentication methods of the AWS SDK for go based on known environment variables and known AWS config files.
Fixes #2888 
**Checklist**

Configure S3's credential chain based on config

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
tempodb/backend/s3/config.go
tempodb/backend/s3/s3.go

Configure S3's credential chain based on config (#2889)

[release-v2.2] Backport #2889 to release v2.2

---

docs/sources/traceql/architecture.md

Fixed this error: 
```
WARN  [en] REF_NOT_FOUND: Ref "traceql": "/usr/app/hugo/content/docs/tempo/v2.0.x/traceql/architecture.md:26:58": page reference "/docs/tempo/v2.0.x/traceql/traceql" is ambiguous
```
Part of https://github.com/grafana/technical-documentation/issues/811

[DOC] Fix broken link in TraceQL architecture

---

pkg/model/trace/combine.go
tempodb/encoding/vparquet3/block_findtracebyid.go

Removes the trace size from the max trace size message. This value is misleading b/c it's not the actual full trace size. It will lead users to think that their traces are just barely over the limit (b/c we test on every combine) when they may be significantly larger.

Adjust exceeds max trace size message to remove trace size

---

docs/sources/tempo/configuration/grafana-agent/service-graphs.md

When backported, this will fix six links in Grafana docs.

Fix alias and add comment explaining intended redirect

---

modules/distributor/distributor.go
modules/generator/instance.go
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go

Adds the necessary plumbing so that the generator local blocks processor (and the metrics summary api) honors any per-tenant parquet dedicated columns in the overrides.  Also fixed the local blocks processor to honor the block version setting (instead of always using DefaultEncoding())
**Checklist**

Metrics Generator - local blocks dedicated columns

---

modules/distributor/distributor.go
tempodb/backend/azure/azure.go
tempodb/backend/azure/v1/v1.go
tempodb/backend/azure/v2/v2.go
tempodb/encoding/vparquet/block_iterator.go
tempodb/encoding/vparquet2/block_iterator.go
tempodb/encoding/vparquet3/block_iterator.go

In https://github.com/grafana/tempo/pull/2955 tempo replaced usage of github.com/pkg/errors
with errors package from the standard library.
In that process errors.Wrap calls were replaced with fmt.Errorf,
and there a difference in the way both work with `nil` error.
e.g: `errors.Wrap(nil, "test")` is `<nil>`, but `fmt.Errorf("test", nil)` is `test%!(EXTRA <nil>)`
so we need to guard fmt.Errorf calls to avoid returning errors when `err` is `nil`.

Fix error returns that didn't check `err != nil`

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/_index.md
modules/generator/storage/config.go
modules/generator/storage/config_test.go
modules/generator/storage/config_util.go
modules/generator/storage/config_util_test.go
modules/generator/storage/instance.go

Adds option to disable addition of X-Scope-OrgID header in metrics generator with remote writing
Fixes #1554
**Checklist**

metrics-generator disable x-scope-orgid header append

---

modules/frontend/handler.go
modules/overrides/user_configurable_overrides.go
modules/overrides/userconfigurable/api/api.go
modules/overrides/userconfigurable/api/http.go
pkg/util/tracing/tracing.go
tempodb/compactor.go

Small refactor in preparation for a bigger change to our tracing SDK setup.
Changes:
- move `ExtractTraceID` to its own package, from `pkg/util` to `pkg/util/tracing`
- in some places we were calling `dskit/tracing.ExtractTraceID` directly instead of our helper, for consistency all calls will now go through our own `ExtractTraceID` (which calls dskit's version) 
**Checklist**

Move ExtractTraceID from util to util/tracing

---

tempodb/encoding/vparquet2/block_findtracebyid.go
tempodb/encoding/vparquet3/block_findtracebyid.go
tempodb/encoding/vparquet3/block_findtracebyid_test.go

Since there ended up being issues in the index due to #2867, we decided to disable it by default in the next release.  
Fixes n/a
**Checklist**

Disable parquet trace index by default

---

Makefile
cmd/tempo-cli/cmd-analyse-block.go
tempodb/encoding/vparquet3/dedicated_columns.go

Adds support for dedicated columns to the `analyze block(s)` cli command.
Now when calculating total column size the commands will include dedicated columns if they exist.

Tempo: add dedicated columns to block analyze

---

modules/generator/processor/localblocks/metrics.go
modules/generator/processor/localblocks/processor.go

Also keeps root spans in the local-blocks processor so that things like `traceDuration`, `rootServiceName` can work in the metrics summary API.  It's best effort and has the same limitations as other cross-span traceql features:  when the root span and matching span are not in the same segment (wal flush or complete block) then it doesn't work.
Also adds a metric to track spans after filtering.
Fixes n/a
**Checklist**

Metrics summary API root spans

---

CHANGELOG.md
Makefile
cmd/tempo/app/config.go
cmd/tempo/app/config_test.go
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
integration/e2e/config-limits-query.yaml
modules/distributor/config.go
modules/distributor/distributor.go
modules/distributor/distributor_test.go

Adds a config block to the distributor to produce debug metrics. These can be particularly useful when tracking down a process that is creating an exceptional amount of spans.
```
distributor:
metric_received_spans:
enabled: false
root_only: false
```
Fixes #
**Checklist**

Add metrics debugging options

---

CHANGELOG.md
modules/overrides/userconfigurable/api/http.go
modules/overrides/userconfigurable/api/limits.go
modules/overrides/userconfigurable/api/limits_test.go

While reviewing https://github.com/grafana/tempo/pull/3012 I noticed some fields weren't being populated correctly. This was a massive oversight on my part as the PR adding the merge logic (#2915) was merged during the same time window as PRs adding extending the limits struct (#2899, #2928, #2945, ).
When merged the code got merged without issues but the merge function wasn't updated.
Fields that weren't being populated:
- `metrics_generator.collection_interval`
- `metrics_generator.service_graphs.histogram_buckets`
- `metrics_generator.span_metrics.histogram_buckets`
- `metrics_generator.span_metrics.target_info_excluded_dimensions`
Before this change they would always be returned from the result even though a value would be set. …

Add missing fields in overrides API merged response

---

CHANGELOG.md
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go
modules/overrides/userconfigurable/client/limits.go

When userconfigurableoverrides are enabled, we were returning metrics_generator `filter_policies` as empty even when it's set in per tenant runtime overrides.
This is a bug, we should return per tenant runtime overides when filter_policies are not set at userconfigurableoverrides.
this PR added a len > 0 check to fix this for multiple attribuets, and adds a test for all overrides when userconfigurableoverrides is enabled.
**Checklist**

Fix: pass-through to runtime overrides for FilterPolicies and TargetInfoExcludedDimensions

---

CHANGELOG.md
docs/sources/tempo/traceql/_index.md
pkg/traceql/lexer.go
pkg/traceql/lexer_test.go
pkg/traceql/parse_test.go
tempodb/tempodb_search_test.go

This PR extends the traceql lexer to lex quoted attribute names (ex: `span."foo bar"`) this will help searching tempo with span attributes containing breaking characters like `=, "` etc. 
Fixes #2805
**Checklist**

Support quoted attribute in traceql

---

CHANGELOG.md
modules/ingester/ingester_test.go
modules/ingester/instance_search.go
pkg/search/results.go
pkg/search/results_test.go
tempodb/backend/local/local.go
tempodb/encoding/vparquet2/readers.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/readers.go
tempodb/encoding/vparquet3/wal_block.go

Big queries sent to Ingester.SearchRecent may keep running after a context timeout.  The root cause is the Local backend wraps local file i/o which is not context aware.  This fixes the Local backend to check errors, but also addresses some handling in instance.Search to properly wait for all goroutines to complete before releasing the lock.
**Checklist**

Ingester Search honor ctx errors

---

CHANGELOG.md
cmd/tempo/app/config.go

Set correct defaults on the internal server
For some reason the some logs settings were not set correctly as it's defaults, which makes the code crash due some nils.
This PR fixes that.
Fixes #3040
**Checklist**

Fix load default settings for internal server

---

CHANGELOG.md
docs/sources/tempo/api_docs/_index.md

We are currently undecided about how to move forward with trace streaming. Let's leave the websocket endpoint undocumented and not deprecate the grpc endpoint.
This way we can cut 2.3 and have something solidified by 2.4.

Revert websocket doc changes

---

CHANGELOG.md
cmd/tempo-cli/Dockerfile
cmd/tempo-serverless/cloud-run/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile
cmd/tempo/Dockerfile_debug

Updates our base image to 3.18.x to patch CVE-2022-48174
Update the Alpine image to fix [3.18](https://github.com/grafana/tempo/issues/3044) for Tempo. We will need to build a new release to fix GET.
**Checklist**

Update Alpine Image to 3.18.x

---

CHANGELOG.md
tempodb/encoding/vparquet/compactor.go
tempodb/encoding/vparquet3/compactor.go

Recently we have discovered that tenants with extremely large strings in their attributes will cause Tempo to cut large row groups whose dictionary sizes can overflow an int32:
https://github.com/parquet-go/parquet-go/issues/79
This PR adjusts the size estimation to better take into account these very large strings. in an environment with a target rg size of 50MB the above change had the following impact to min/max/avg row group sizes:
https://github.com/grafana/tempo/issues/2731
This PR, along with the fix to the parquet-go issue above, will help alleviate https://github.com/grafana/tempo/issues/2987 and https://github.com/grafana/tempo/issues/2731.
**Checklist**

Improves the size estimation when cutting new rows

---

CHANGELOG.md
cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/parquet-go/parquet-go/README.md
vendor/github.com/parquet-go/parquet-go/column.go
vendor/github.com/parquet-go/parquet-go/merge.go
vendor/github.com/parquet-go/parquet-go/node.go
vendor/github.com/parquet-go/parquet-go/print.go
vendor/github.com/parquet-go/parquet-go/schema.go
vendor/github.com/parquet-go/parquet-go/writer.go
vendor/modules.txt

Among other changes the parquet-go update contains a fix that avoids blocks with overflows in the uncompressed page size
Helps to mitigate #2987
**Checklist**

Update parquet-go dependency

---

CHANGELOG.md
cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/cloud-run/go.sum
cmd/tempo-serverless/lambda/go.mod
cmd/tempo-serverless/lambda/go.sum
go.mod
go.sum
vendor/github.com/parquet-go/parquet-go/README.md
vendor/github.com/parquet-go/parquet-go/column.go
vendor/github.com/parquet-go/parquet-go/merge.go
vendor/github.com/parquet-go/parquet-go/node.go
vendor/github.com/parquet-go/parquet-go/print.go
vendor/github.com/parquet-go/parquet-go/schema.go
vendor/github.com/parquet-go/parquet-go/writer.go
vendor/modules.txt

Backport 419288d49dae887d8887aae24e83f3407665f8f1 from #3068
---
Among other changes the parquet-go update contains a fix that avoids blocks with overflows in the uncompressed page size
Helps to mitigate #2987
**Checklist**

[release-v2.3] Update parquet-go dependency

---

docs/sources/tempo/metrics-generator/service_graphs/_index.md

Existing URL to open-telemetry github results in a 404. Replaced it with new URL with information on trace Semantic Specifications.
Fixes broken URL on docs page

[docs] Fix broken URL for Semantic Specifications

---

CHANGELOG.md
pkg/traceql/ast_execute.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet3/block_traceql.go

Prevents additional columns from being added as iterators when doing structural queries. For the query `{ resource.service.name = "loki-querier" } >> { resource.service.name = "loki-querier" }`, the following iterators were generated.
Before:
```
rebatchIterator: 
JoinIterator: 0: traceCollector()	
LeftJoinIterator: 1: batchCollector(true, 0)
required: 
LeftJoinIterator: 3: spanCollector(0)
required: 
SyncIterator: rs.list.element.ss.list.element.Spans.list.element.Kind : InstrumentedPredicate{2, nil}
optional: 
LeftJoinIterator: 4: attributeCollector{}
required: 
SyncIterator: rs.list.element.ss.list.element.Spans.list.element.Attrs.list.element.Key : InstrumentedPredicate{0, StringInPredicate{intrinsic(11), }}
optional: 
SyncIterator: …
```

[TraceQL] Reduce work performed for structural operators due to a bug

---

docs/sources/tempo/release-notes/v2-2.md
docs/sources/tempo/release-notes/v2-3.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md

Creates release notes for Tempo 2.3 and adds a 2.3 section to Setup/Upgrade.md. This PR also corrects some other formatting issues and typos. 
The published release notes will appear at: https://grafana.com/docs/tempo/latest/release-notes/v2-3/
Part of #2985 
**Checklist**

[DOC] Tempo 2.3 release notes

---

docs/sources/tempo/release-notes/v2-3.md

Hyphenates the  not structural operators to be consistent with the documentation. 
**Checklist**

Fix hyphenation in not- structural operators

---

docs/sources/tempo/_index.md
docs/sources/tempo/traceql/query-editor/traceql-editor.md
docs/sources/tempo/traceql/query-editor/traceql-search.md

It was working in "next" because the fallback behavior is to use the page's version for any "SOMETHING_VERSION" lookup.
Therefore, the `docs/shared` lookup coincidentally targeted "next" which exists in the Grafana documentation.
Now that we have cut a new release with these docs, the released version is being used which is causing errors because `v2.3.x` is not a valid Grafana version.

Set GRAFANA_VERSION used throughout shared lookups

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md

The changelog was missed in [the](https://github.com/grafana/tempo/pull/2652) as well as the docs for the `gcs.list_blocks_concurrency`.
**Checklist**

Update changelog and docs for polling updates

---

docs/sources/tempo/getting-started/instrumentation.md

Updates the structure of the instrumentation page to restructure to focus on OTel and add links from the Grafana OTel documentation.
Which issue(s) this PR fixes:
Fixes https://github.com/grafana/tempo-squad/issues/211
**Checklist**

[DOC] Update instrumentation doc to focus on OTel

---

docs/sources/tempo/community/_index.md
docs/sources/tempo/getting-started/instrumentation.md

Add a deprecation warning for Jaegar SDKs and update the community page. 
Fixes  https://github.com/grafana/tempo-squad/issues/211
**Checklist**

[DOC] Update instrumentation and community pages

---

CHANGELOG.md
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go
pkg/util/listtomap/list_to_map.go
pkg/util/listtomap/list_to_map_test.go

By default overrides set through user-configurable overrides take precedence over runtime overrides. For `processors` however it makes more sense to merge both layers with an OR logic.
This makes it possible to enable processors for all tenants through the runtime overrides, regardless of the setting the user-configurable overrides.
As a downside it will not be possible to disable processors set in the runtime overrides.
**Checklist**

Merge the processors overrides set through runtime overrides and user-configurable overrides

---

tempodb/encoding/vparquet3/block_findtracebyid.go
tempodb/encoding/vparquet3/block_findtracebyid_test.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/schema_test.go
tempodb/encoding/vparquet3/wal_block.go

* Drop unsupported attribute values and increment dropped attribute count
* Remove support for array and kv-list attribute values
Fixes grafana/tempo-squad#346
**Checklist**

vParquet4: handle unsupported / dropped attributes

---

docs/sources/tempo/troubleshooting/unable-to-see-trace.md

Fixes an outdated flag from `tempo` which is now `-distributor.log-received-spans.enabled`
**Checklist**

Incorrect flag name for new version

---

docs/sources/tempo/configuration/ipv6.md
operations/jsonnet/microservices/common.libsonnet

Update the listen address on the server after https://github.com/grafana/dskit/commit/5729ba4790f2c6ef0cf735f030d47885abcc6285 introduced a subtle breaking change for IPv6 specification.
**Checklist**

Update IPv6 jsonnet and docs after dskit update

---

CHANGELOG.md
cmd/tempo/app/config_test.go
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
docs/sources/tempo/configuration/parquet.md
tempodb/encoding/versioned.go

Now that Tempo 2.3 is released it is safe to make vParquet3 the default block encoding. 
Fixes #2721
**Checklist**

Make vParquet3 the default encoding

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/compactor/compactor.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/config_test.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go
tempodb/compactor.go
tempodb/compactor_test.go
tempodb/tempodb.go

Add a `compaction_window` override to be used per-tenant.  This will allow large and small tenants to scale the window independently and be a little more flexible.
**Checklist**

Add per-tenant compaction window

---

CHANGELOG.md
pkg/traceql/ast.go
pkg/traceql/ast_conditions.go
pkg/traceql/ast_execute.go
pkg/traceql/ast_stringer.go
pkg/traceql/ast_validate.go
pkg/traceql/test_examples.yaml

Fixes a nasty performance issue when regexp matches get to the engine layer. Currently we are calling `regexp.MatchString()` which recompiles the regex on every span.
Uses benchmarks from [this PR](https://github.com/grafana/tempo/pull/3113) against main plus one to highlight the improvement:
`{resource.namespace!=""} && {resource.service.name="loki-distributor"} && {duration>2s} && {resource.cluster=~"prod.*"}`
```
name                                             old time/op    new time/op    delta
BackendBlockTraceQL/spanAttValNoMatch-8            6.71ms ± 0%    6.73ms ± 0%     ~     (p=0.151 n=5+5)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-8      5.80ms ± 0%    5.91ms ± 2%     ~     (p=0.056 n=5+5)
BackendBlockTraceQL/resourceAttValNoMatch-8        12.1ms ± 1% …
```

TraceQL: Improve regexp perf

---

CHANGELOG.md
tempodb/backend/s3/s3.go

Support was removed in https://github.com/grafana/tempo/pull/3006
**Checklist**

readd session token to s3 credentials

---

docs/make-docs
docs/sources/tempo/traces.md

Incorporates changes from PR https://github.com/grafana/tempo/pull/2694 (author never signed CLA)
**Checklist**

[DOC] Update definition for traces

---

operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/tempo-mixin-compiled/dashboards/tempo-reads.json
operations/tempo-mixin-compiled/dashboards/tempo-resources.json
operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/dashboards/dashboard-utils.libsonnet
operations/tempo-mixin/dashboards/tempo-writes.libsonnet

Updates rate queries in the mixin to use `$__rate_interval`, instead of `$__interval`. `$__rate_interval` has been the correct variable to use in rate queries for [some time](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/).

Update Tempo mixin rate queries

---

docs/sources/tempo/operations/architecture.md

This link wasn't rendering nicely in the docs[1]
[1] https://grafana.com/docs/tempo/latest/operations/architecture/
**Checklist**

Fix malformed link in Tempo docs

---

CHANGELOG.md
pkg/parquetquery/iters.go
tempodb/encoding/vparquet/block_search_tags.go
tempodb/encoding/vparquet/block_traceql.go
tempodb/encoding/vparquet2/block_search_tags.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet3/block_search_tags.go
tempodb/encoding/vparquet3/block_traceql.go

No query should ever result in a left-join with no required iterators. If that happens, it's a bug in the iter building code, so it returns an error.
`LeftJoinIterator` is not designed to handle this case and will loop forever.
**Checklist**

Prevent `LeftJoinIterator`s with no required conditions from being built

---

CHANGELOG.md
cmd/tempo/main.go

This PR corrects the exit status behavior in Tempo. Now, when -config.verify=true is used and the configuration is valid, the application will exit with status 0.
Fixes #3172
**Checklist**

Fix Exit code for -config.verify

---

CHANGELOG.md
modules/generator/processor/spanmetrics/spanmetrics.go
modules/generator/processor/spanmetrics/spanmetrics_test.go

If not sanitized, Prometheus incompatible labels can be sent.
**Checklist**

[spanmetrics] Sanitize name in mapped dimensions

---

tempodb/encoding/vparquet3/block_autocomplete.go

f9100fb added a second return value to `NewLeftJoinIterator()`, which was not handled in all places.

Fix handling for returned error added in f9100fb

---

CHANGELOG.md
cmd/tempo-cli/cmd-analyse-block.go
cmd/tempo-cli/cmd-analyse-blocks.go

Bug #3131 occurs doe to the sometimes long processing times of individual blocks. This causes the list of blocks to analyse to become outdated. As a consequence the `analyse blocks` sub command encounters more and more compacted blocks, which the program fails to open.
With this change the sub command refreshes the block list whenever a compacted block is encountered.
It also improves the clarity of the error message when the `analyse block` sub command is called on a compacted block.
Fixes #3131
**Checklist**

tempo-cli analyse blocks skips compacted blocks and updated block list

---

docs/sources/tempo/_index.md
docs/sources/tempo/release-notes/v2-3.md

Add release notes for v2.3.1
Adds an opening paragraph about TraceQL to the main index page. 
@joe-elliott FYI
Fixes: https://github.com/grafana/tempo/issues/3187
Related to: https://github.com/grafana/tempo/pull/3186
**Checklist**

[DOC] Add 2.3.1 releaes notes

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/configuration/_index.md

Changes the doc for autocomplete filtering to be true by default, per https://github.com/grafana/tempo/pull/3178 
FYI @mapno 
Relates to https://github.com/grafana/tempo/pull/3178
**Checklist**

[DOC] Update autocomplete filtering doc

---

pkg/parquetquery/iters.go
tempodb/encoding/vparquet3/block_traceql_test.go

Adds a seekRows method to the sync iterator to skip rows (traces). This has nice performance improvements for queries that seek a lot and is break even for others. There was a small increase in cpu in one benchmark.
Note this line:
```
if rowSkip > 5 { // made up threshold worth skipping
```
This threshold is impossible to tune (and very easy to overtune). The issue is that we are skipping rows at the trace level but often iterating at the span level or even deeper. A single row skip may avoid 100k nexts or 1 next and I don't think it's possible to know that at the row level, but I'd love to hear otherwise.
Another consideration is that perhaps the rowSkip threshold should be based on the definition level? The deeper the level the more likely we can avoid a large …

[TraceQL] SyncIterator seekWithinPage for improved performance

---

CHANGELOG.md
Makefile
cmd/tempo/app/modules.go
docs/sources/tempo/configuration/_index.md
modules/cache/config.go
modules/frontend/cache.go
modules/frontend/cache_test.go
modules/frontend/frontend.go
modules/frontend/frontend_test.go
modules/frontend/search_streaming.go
modules/frontend/search_streaming_test.go
modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go
pkg/cache/cache.go
pkg/util/test/cache.go
tempodb/backend/cache/cache_test.go

Companion PR to https://github.com/grafana/tempo/pull/3196
This PR adds light structure and the basics of frontend job search caching.
**Checklist**

Frontend Search Caching

---

go.mod
tempodb/encoding/vparquet3/block_findtracebyid_test.go
tempodb/encoding/vparquet3/block_search_test.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet3/dedicated_columns_test.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/schema_test.go
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/modules.txt

This PR adds support for storing arrays with homogeneous, primitive types in Tempo blocks
Fixes grafana/tempo-squad#360
**Checklist**

Add support for attributes with array values

---

pkg/parquetquery/predicates.go

Fixes a small bug created in https://github.com/grafana/tempo/pull/3231.
The err condition was written incorrectly.

Fixes a bug where page bounds are being ignored

---

integration/e2e/e2e_test.go

Downstream repos (i.e. Grafana Enterprise Traces) is very unhappy with this lint error. Fixing it.... There may be more.
**Checklist**

Fix lint errors that are affecting downstream repos

---

docs/sources/tempo/configuration/azure.md

I am proposing this update to the Tempo configuration for Azure Storage in the light of issues I encountered when trying to run Tempo in Distributed Mode.
I found that, when using the existing documentation the trace specification did not get successfully applied to the storage object - it was still pointing to 'local' as its backend.
I also found that the extraArgs and etraEnv configuration did not seem to cascade down to any of the relevant services - so they were unable to retrieve the Storage Account key. This meant that the services threw errors during initialization and were unable to start up.
It seems to me that Tempo Monolithic and Tempo Distributed have different architectures so they each need their own distinct configuration for Azure Storage.
**Which …

Add specific configuration for Tempo Distributed Mode

---

integration/e2e/multi_tenant_test.go
modules/frontend/tenant.go

Recently added metrics collided with names in GET. This PR changes the names to reflect the fact that they are frontend multitenant metrics and also to avoid the collision.
cc @electron0zero

Fix frontend metric names to not collide with GET

---

example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/shared/tempo.yaml

Removes `multitenancy_enabled: true` in non-multi-tenant` docker-compose examples
Fixes #3260 
**Checklist**

Remove multi-tenancy config in docker-compose examples

---

modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go
modules/frontend/tracebyidsharding.go
modules/frontend/tracebyidsharding_test.go

Here we ensure that 429 on the search and tracebyid paths are returned to the caller instead of a 500.
Fixes #2843
**Checklist**

Ensure 429 internal status is passed back to the caller

---

docs/sources/tempo/api_docs/pushing-spans-with-http.md

A code block breaks the numbering of list items:
Indenting it, as done in the preceding list, should fix the issue:

Docs: indent code block to allow proper list numbers

---

Makefile

This fixes compatibility issues with Apple silicon (m1/2/3) and `make gen-proto`.  Previously it would fail with the error: 
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
--gogofaster_out: protoc-gen-gogofaster: Plugin killed by signal 11.
```
**Note** I didn't pin down the exact change that fixed it. Any version 0.18+ works, so it was likely in [this diff](https://github.com/open-telemetry/build-tools/commit/312c7ff0a2faa52cb0d6d363c8968316e1b94c1c#diff-a8bde4bfc923aab18efd4967f7b92bf5eb95095043616a52e2b49b151a1f1a02) but I'm not sure it's as simple as the TARGETARCH changes.  I am using `DOCKER_DEFAULT_PLATFORM=linux/amd64` to force running non-arm images already.  And confirm this with:
```
$ docker inspect otel/build-protobuf:0.23.0 …
```

Upgrade otel/build-protobuf image for apple silicon compatibility

---

CHANGELOG.md
tempodb/encoding/vparquet3/block_autocomplete.go
tempodb/encoding/vparquet3/block_autocomplete_test.go

It prevents a panic when a filtering query is passed to `/search/tag/<tag>/values` with a attribute condition (`.a=b`) where `b` is a special type (`server/client`, `ok/error/unset`) but `.a` is of a different type (`string`, `int`). For example, `span.http.status_code=server`. This would create iterators with nil predicates and panics when it called `iter.Next()`.
Now, such conditions are ignored and iterators are not built for them.
**Checklist**

Fix autocomplete panic when condition has wrong type

---

modules/frontend/query_range_sharding.go

Here we fix the http response when conforming to the prometheus body that grafana is expecting.  This avoids a situation where the generator has returned an error, but a user querying grafana is unaware there is an error, or what the error is.
**Checklist**

Fix prom response in query range sharder

---

docs/sources/tempo/setup/set-up-test-app.md

Updates the Set up the test app doc to use Agent Flow and Intro to MLTP as an option. 
Fixes #3226 
**Checklist**

[DOC] Update Set up test app to use agent flow

---

CHANGELOG.md
pkg/traceql/lexer.go
pkg/traceql/lexer_test.go

**Solves the error when searching for span attributes that start with resource.**:
Fixes #2605
**Checklist**

FIX-2605: Make span.resource.xyz attributes work

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/generator/processor/localblocks/config.go
modules/generator/processor/localblocks/processor.go

Here we bring back the localblocks processor filtering for kind==server, but with a config option to modify the code path.
**Checklist**

Bring back localblocks filtering with config option

---

CHANGELOG.md
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/generator/processor/localblocks/livetraces.go
modules/generator/processor/localblocks/metrics.go
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go
modules/generator/processor/localblocks/traceSizes.go

Updates the local-blocks processor to honor the per-tenant override `max_trace_bytes`.  The generators already make use of the per-tenant overrides but this field.  This goes one step further than the trace size limits in the ingesters.  The ingesters keep track of the historical trace size only for the lifetime of the headblock, and that means long-running traces can eventually append more data.  This goes one step further and maintains the historical trace size for as long as the trace is active (continues to send spans).
**Checklist**

Local blocks processor honor per-tenant max trace size

---

CHANGELOG.md
operations/jsonnet-compiled/StatefulSet-memcached.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/config.libsonnet

Update the default memcachced image in jsonnet to patch for multiple CVEs.
**Checklist**

Update jsonnet memcached image version for multiple CVE

---

pkg/parquetquery/iters.go
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go
tempodb/encoding/vparquet3/block_traceql_test.go

This contains some query optimizations for TraceQL metrics queries, and some low-level tweaks in parquetquery.  **Update** I removed the more aggressive string clone cache.  The memory benefit for metrics queries was very good, but there was a slight regression in searches.  This is because a metrics query will exhaust every value of some string intrinsic/attribute whereas a search will exit early after finding enough matches.  Will need to revisit this area after some more thought.
Metrics:
```
│ before_queryrange.txt │        after_queryrange2.txt        │
│        sec/op         │   sec/op     vs base                │
BackendBlockQueryRange/{}_|_rate()-12                                                   1.557 ± 1%    1.553 ± 1%        ~ (p=0.684 n=10) …
```

[Traceql Metrics] Variety of performance improvements

---

example/docker-compose/debug/readme.md

Clarifies the location where you should build the debug docker image. Original changes are from https://github.com/grafana/tempo/pull/3194
**Checklist**

[DOC] Clarify debug example readme

---

CHANGELOG.md
docs/sources/tempo/metrics-generator/span_metrics.md
pkg/spanfilter/spanfilter.go
pkg/spanfilter/spanfilter_test.go

Here is an issue that was identified when trying to use multiple include policies against the same intrinsic attribute.  Without this change, multiple policies operating on the same attributes will never match since we find the first opportunity to reject a span from being included in the metrics.  Here we make a change to continue evaluating additional filter policies even if the current one is unmatched.  This means that a filter policy uses `AND` logic internally, but multiple polices use `OR` logic to determine if the span should be included.  Any filter policy that is matched will include the metric.
**BREAKING CHANGE** Exclude policies are no longer global
The documentation currently suggests the following policy to include and
exclude using two filter …

Change spanmetrics filtering with multiple policies

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/generator/processor/localblocks/config.go
modules/generator/processor/localblocks/processor.go

Backport #3303 to r131
---
Here we bring back the localblocks processor filtering for kind==server, but with a config option to modify the code path.
**Checklist**

[r131] Bring back localblocks filtering with config option

---

CHANGELOG.md
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/generator/processor/localblocks/livetraces.go
modules/generator/processor/localblocks/metrics.go
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go
modules/generator/processor/localblocks/traceSizes.go

Backport #3305 to r131
---
Updates the local-blocks processor to honor the per-tenant override `max_trace_bytes`.  The generators already make use of the per-tenant overrides but this field.  This goes one step further than the trace size limits in the ingesters.  The ingesters keep track of the historical trace size only for the lifetime of the headblock, and that means long-running traces can eventually append more data.  This goes one step further and maintains the historical trace size for as long as the trace is active (continues to send spans).
**Checklist**

[r131] Backport #3305

---

docs/sources/tempo/metrics-generator/service-graph-view.md
docs/sources/tempo/metrics-generator/service_graphs/_index.md

Seems like we updated the metric names from tempo_ to traces_ in the section below, but not in this specific example.

Fix typo in service graph metric name

---

.gitignore
CHANGELOG.md
Makefile
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/multi-tenant/grafana-datasources.yaml
example/docker-compose/multi-tenant/readme.md
example/docker-compose/multi-tenant/tempo.yaml
integration/e2e/config-multi-tenant-local.yaml
integration/e2e/e2e_test.go
integration/e2e/encodings_test.go
integration/e2e/https_test.go
integration/e2e/multi_tenant_test.go
integration/util.go
modules/frontend/combiner/noop.go
modules/frontend/search_progress.go
modules/frontend/search_streaming.go
modules/frontend/search_streaming_test.go
modules/frontend/searchsharding.go

Add multi-tenant query support in streaming search endpoints.
follow up on https://github.com/grafana/tempo/pull/3087
Fixes #1858
```[tasklist]
```
**Checklist**

Add support for multi-tenant queries in streaming search

---

tempodb/encoding/vparquet3/schema.go

Fix a small typo
**Checklist**

vParquet4: Fix typo in event name encoding

---

docs/sources/tempo/configuration/grafana-agent/_index.md
docs/sources/tempo/configuration/grafana-agent/tail-based-sampling.md

Backport 865383b0be7a9bd03ac8f02429ca0dca42ef37e8 from #3167
--- Backport info 
We've updated the tail-based sampling doc to include a River configuration file example for Agent Flow mode. 
Fixes #2455
**Checklist**

[release-v2.3] [DOC] Update Tail based sampling doc for Grafana Agent

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/frontend/searchsharding.go
modules/frontend/searchsharding_test.go

Currently if the configured max limit is exceeded Tempo will just cut off results at the max limit. Instead we should return a 400 to clearly notify the user their request is invalid.
**Checklist**

Return Bad Request when exceeding limit

---

CHANGELOG.md
tempodb/encoding/vparquet3/block_autocomplete.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/tempodb_search_test.go

In certain circumstances filtered autocomplete would return incorrect results due to an incorrect iterator scope. The actual fix is [this line](https://github.com/grafana/tempo/pull/3339/files#diff-75a709e18d228f16dc762d46a5b3d80e86ac0c8c632d12d6618f72052f26c58aR503)
- removed an unused param in `createDistinctAttributeOperator`
- added integration tests for filtered autocomplete
**Checklist**

Fix autocomplete returning erroneous values

---

docs/sources/tempo/operations/cross_tenant_query.md

Adds a note about the case where multiple spansets with conditions satisfied in different tenants will not be returned correctly.
**Checklist**

Add a note/warning about cases in which cross tenant queries perform unexpectedly 

---

docs/design-proposals/2023-11 TraceQL Extensions.md

This PR adds a design doc aimed at the next set of functionality for the TraceQL language. We are looking for community feedback, consensus and comments before merging and beginning this work.
Please jump in and comment!

Design Doc: TraceQL Extensions

---

CHANGELOG.md
cmd/tempo/app/app.go
cmd/tempo/app/modules.go
docs/sources/tempo/api_docs/_index.md
modules/overrides/interface.go
modules/overrides/overrides_tenant_status_http.go
modules/overrides/overrides_tenants_http.go
modules/overrides/runtime_config_overrides.go
modules/overrides/tenant_status.gohtml
modules/overrides/tenants.gohtml
modules/overrides/user_configurable_overrides.go

Changes `/status/overrides` and `/status/overrides/{tenant}` to HTML page which are nicer and easier to use.
Examples:
`/status/overrides` with user-configurable overrides disabled
> ![Screenshot 2024-01-25 at 20 13 38](https://github.com/grafana/tempo/assets/7748404/cfb8864b-3dd0-4383-b644-46bf11197158)
`/status/overrides/{tenant}` with user-configurable overrides disabled
> ![Screenshot 2024-01-25 at 20 13 54](https://github.com/grafana/tempo/assets/7748404/e5318391-26d9-4943-a1ca-e6a5b0cf402a)
`/status/overrides` with user-configurable overrides enabled
> ![Screenshot 2024-01-25 at 20 12 08](https://github.com/grafana/tempo/assets/7748404/a0fc1859-ebc0-4fb1-8540-1e6eb1ab018d)
`/status/overrides/{tenant}` with user-configurable overrides enabled
> ![Screenshot …

Add HTML pages to view tenants with overrides

---

CHANGELOG.md
modules/ingester/ingester.go
modules/ingester/ingester_test.go

This is one of those bugs that makes you wonder "how did this ever work?"   This PR changes the ingester to enter a read-only state on startup (similar to shutdown) until wal replay and local blocks rediscover are complete.  This prevents pushes from creating headblocks that get tangled up in the replay process (and broken).  I really like having the startup error different than the shutting down error.  It makes it easy to check logs for `Ingester is starting` and verify the fix is working.
**Description of the Bug**
Here is a full sequence of the bug:
1. An Ingester unexpectedly terminates (OOM, panic, readinessprobe failure etc)
2. The ingester restarts and begins WAL replay
3. Because it didn't leave the ring gracefully and propagating the new state takes some …

Ingester readonly on startup until replay and rediscover is done to prevent broken head blocks

---

CHANGELOG.md
cmd/tempo-query/tempo/config.go
cmd/tempo-query/tempo/plugin.go
integration/e2e/config-plugin-test.yaml
integration/e2e/config-tempo-query.yaml
integration/e2e/query_plugin_test.go

Add configuration for fetch services older than complete_block_timeout

---

CHANGELOG.md
tempodb/encoding/vparquet3/block_iterator.go
tempodb/encoding/vparquet3/block_search.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/wal_block.go

Precalculate and reuse the vParquet3 schema. This performance optimization saves a small amount of CPU time when blocks are opened for search
**Checklist**

Precalculate and reuse the vParquet3 schema before opening blocks

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/parquet.md
tempodb/config_test.go
tempodb/encoding/common/config.go
tempodb/encoding/versioned.go
tempodb/wal/wal.go

**What this PR does**: Deprecating vParquet v1. vParquet v1 blocks can still be read but write is no longer allowed. 
**Checklist**

deprecating vparquet v1

---

CHANGELOG.md
example/docker-compose/distributed/agent.river
example/docker-compose/distributed/docker-compose.yaml
modules/frontend/v1/frontend.go
modules/querier/worker/frontend_processor.go

Fixes trace context propagation between query-frontend and querier. The context was not being correctly passed and unpacked between both.
It also adds tracing to the distributed docker-compose example.
**Checklist**

Fix trace context propagation in the read path

---

modules/generator/processor/localblocks/processor.go
modules/querier/querier_query_range.go
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go
tempodb/encoding/vparquet3/block_traceql_test.go

This PR circles back to a metrics TODO and uses the trace-level timestamp columns to more quickly filter the relevant traces in a block.   The columns are not free and hinder performance unless they are able to filter out enough values.   So it is decided at runtime based on the request and the block in question.
For now, did some local benchmarking, and using the simple heuristic that if we are looking at less than 20% of the block, then it's worth pulling in the columns.  Between 20 and 100%, we avoid the extra I/O but spend more cycles throwing away traces (this is the current behavior).   Open to suggestions on a better heuristic.
**Checklist**

Update traceql metrics to use the trace-level timestamp columns

---

CHANGELOG.md
cmd/tempo/app/app.go
cmd/tempo/app/config.go
cmd/tempo/app/server_service.go
integration/e2e/e2e_test.go

Adds a shutdown delay configurable parameter modeled after mimir:
https://github.com/grafana/mimir/pull/3298
After receiving SIGTERM Tempo will drop its readiness handler and wait the configured seconds. In a k8s environment this will allow Tempo to cleanly roll its frontend without dropping queries.
**Checklist**

Add shutdown delay and e2e test

---

CHANGELOG.md
cmd/tempo/app/app.go
cmd/tempo/app/modules.go
cmd/tempo/app/server_service.go

Recent changes (I suspect https://github.com/grafana/tempo/pull/3300) broke middleware on our querier requests. We have HTTP middleware that provides tracing and metrics. Requests sent to the querier are routed slightly differently and due to this change we didn't get metrics anymore for the HTTP routes.
__Issue__
So `tempo_request_duration_seconds` does not show up for routes like `querier_api_search_tags` and `querier_api_traces_traceid`. GRPC routes were still instrumented correctly (`/tempopb.Querier/FindTraceByID` and `/tempopb.Querier/SearchTags`).
__How it works__
Normal middleware flow:
```
http.Handler.Serve --> middleware (tracing, metrics) --> mux.Router (calls the correct http.Handler for each path)
```
When we set `stream_over_http_enabled: false` this …

Restore tempo_request_duration_seconds metrics for querier_api_* requests

---

docs/sources/tempo/operations/prometheus_datasource.md

Changes the prometheus data source to a Tempo data source in the prometheus-datasource.md file. 
Fixes #https://github.com/grafana/tempo-squad/issues/394
**Checklist**

[DOC] Update Prometheus API doc

---

modules/frontend/tracebyidsharding.go
modules/frontend/tracebyidsharding_test.go

Here we aim to improve the context handling on the TraceByID path in the case of cancellation and timeouts.
Related https://github.com/grafana/tempo/issues/2680
**Checklist**

Improve query cancellation handling in tracebyidsharding

---

docs/sources/tempo/configuration/_index.md

Removes documentation on two caching options that we don't use. I also believe these cache options are not even correctly used by Tempo.

Undocument cache options

---

docs/sources/tempo/release-notes/v2-4.md

Minor updates to the 2.4 release notes: 
* Removes the inactive blog post link for 2.4. This should be able to be live in the enxt day or two. 
**Checklist**

[DOC] Updates to 2.4 rel notes

---

CHANGELOG.md
modules/frontend/query_range_sharding.go
modules/generator/instance.go
modules/generator/instance_test.go
modules/querier/querier_query_range.go
pkg/api/http.go
pkg/tempopb/tempo.pb.go
pkg/tempopb/tempo.proto
pkg/traceql/engine_metrics.go

Basically this overhauls the handling of timeseries labels for metrics queries.  There are several fixes in here, but it also lines up behavior with: https://github.com/grafana/grafana/pull/83619
* Empty strings were previously dropped but now they are preserved. For example: `{rootName=""} | rate() by (rootName)`.  This would look like a completely empty labelset in the response and cause issues downstream.  Now it's preserved as the single label `rootName` with an empty string value.
* When all labels are nil, we were backfilling a single label with the text "<nil>" to make Grafana happy like.  This was actually premature specialization for the prometheus-compatible API, and now that we have the new dedicated Tempo-UI we can fix this.  Now nils are dropped …

[TraceQL Metrics] Fix handling of empties and nils + other fixes

---

docs/sources/tempo/getting-started/instrumentation.md

The Grafana OTEL documentation is being deprecated. This PR removes the links to the /docs/opentelemetry documentation. 
Related: https://github.com/grafana/website/pull/18482
**Checklist**

[DOC] Remove OTEL doc links from Tempo

---

CHANGELOG.md
modules/frontend/combiner/common.go
modules/frontend/combiner/search_test.go
modules/frontend/pipeline/sync_handler_retry.go
modules/frontend/search_handlers_test.go
modules/frontend/slos.go
modules/frontend/slos_test.go
modules/frontend/v1/frontend.go

**What this PR does**
- Correctly translates "queue full" into a 429 for the http pipeline
- Correctly propagates ResourceExhausted gRPC error instead of InvalidArgument
- Correctly prevents 429s from counting against SLOs
**Checklist**

Fix 429s tripping SLOs

---

CONTRIBUTING.md
docs/sources/tempo/getting-started/example-demo-app.md

Removes a reference to ctl.sh which was [removed from mltp](https://github.com/grafana/intro-to-mltp/commit/13354c1919a8153a02b62cea986ad2f575da9d1b).
Additionally, I noticed when doing a PR for the first fix that all the labels on the project are singular, so I went with what is live in the repo and (presumably) corrected the markdown.

Doc update

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/frontend/config.go
modules/frontend/query_range_sharding.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go

Fixes the time range check in query_range, and adds a new per-tenant override that is separate from the search duration. This matches the main config which already has a separate `metrics:max_duration`.  I think we are technically trying to avoid additions to the "legacy" overrides but did it anyway for ease and completeness. 
Also updates docs and improves defaults.
Fixes #3479 
**Checklist**

[TraceQL Metrics] Use new per-tenant max_metrics_duration and fix duration check

---

docs/sources/tempo/setup/operator/monolithic.md

fixes a typo in setup/operator/monolithic.md
**Checklist**

[DOC] fix typo in setup/operator/monolithic.md

---

CHANGELOG.md
modules/frontend/query_range_sharding.go

This PR aligns metrics time ranges to the step parameter.  Without this, the output can subtly change across refreshes of queries like "Last 1 Hour" because spans fall into different buckets a little differently.   We have to align in three places: overall, for the generators, and the backend.  There's some slightly tricky order of operations, i.e. do we check the max_duration limit before or after alignment?  I chose to align first, so that the limit check is against what will actually be executed, but can see an argument for the reverse.
Also a bunch of other mainly cosmetic stuff:  code cleanup, error handling, fewer pointers.
Fixes n/a
**Checklist**

[TraceQL Metrics] Step align query_range time range

---

CHANGELOG.md
integration/e2e/config-all-in-one-azurite.yaml
integration/e2e/config-all-in-one-gcs.yaml
integration/e2e/config-all-in-one-s3.yaml
integration/e2e/e2e_test.go
integration/e2e/overrides_test.go
integration/poller/poller_test.go
tempodb/backend/azure/azure_test.go
tempodb/backend/gcs/gcs.go
tempodb/backend/gcs/gcs_test.go
tempodb/backend/s3/s3.go
tempodb/backend/s3/s3_test.go

Backport 8e6e7fe86f79d1e02972d0d01b35174d25237f81 from #3466
---
**What this PR does**:  Adjusts the logic to list blocks from S3 and GCS to consider object path prefix.
You can see that `tempodb/backend/s3/s3.go` would ignore any results whose key, upon splitting by `/`, did not have 3 elements.  When a prefix is configured, e.g. `a/b/c/`, the returned key will instead be something like `a/b/c/<tenantID>/<blockID>/meta`.  Stip the prefix off this path before pulling out those 3 useful bits from the path.
Fixes #3465
**Checklist**

[release-v2.4] Handle prefixes when listing blocks from S3 and GCS

---

docs/sources/tempo/release-notes/v2-4.md

Add release notes for 2.4.1
Related: https://github.com/grafana/tempo/pull/3503
**Checklist**

[DOC] Add 2.4.1 release notes

---

pkg/util/traceidboundary/traceidboundary.go
pkg/util/traceidboundary/traceidboundary_test.go
tempodb/encoding/vparquet3/block_traceql_test.go

This PR is more changes to the sharding of 8-byte trace IDs for metrics.  Previously I did #3399 but it ended up with a regression on large blocks.  It accomplished making the job sizes more even, but inadvertently inspected a lot more row groups per job (because the traces responsible by the shard were "too" spread out).  This reverts things more closely to the original, but with more hand-picked regions.  It reduces row groups a lot while losing only a little bit of job uniformity.
traces per shard:
```
Before:
Shards:10   Traces: Min:232157 Max:333721 Total:2571975 Avg:257197.5  Quality:69.6 %
Shards:100  Traces: Min:22932  Max:61940  Total:2571975 Avg:25719.8   Quality:37.0 %
Shards:1000 Traces: Min:2202   Max:16181  Total:2571975 Avg:2572.0    Quality:13.6 % …
```

[TraceQL Metrics] More changes to 8-byte trace ID sharding

---

modules/frontend/pipeline/async_handler_multitenant.go
modules/frontend/pipeline/async_sharding.go
modules/frontend/pipeline/async_sharding_test.go
modules/frontend/pipeline/collector_grpc.go
modules/frontend/pipeline/collector_http.go
modules/frontend/pipeline/responses.go
modules/frontend/pipeline/responses_test.go
modules/frontend/search_handlers_test.go
modules/frontend/search_sharder.go

- Add Send/NextComplete methods that must be called by the producer/consumer to guarantee cleanup of resources
- Add goroutine leak tests using built pipelines and the async response

Query Frontend Refactor: Fix goroutine leaks

---

pkg/parquetquery/iters.go
pkg/parquetquery/pool.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet3/block_traceql_test.go

This removes pooling from the parquetquery iterator hot paths.  Instead of getting/putting an IteratorResult every iteration, get one at creation time and reuse it.  `Next()/SeekTo()` still return a `*IteratorResult` but it's the same one each time and only valid until the next call.  
Although I really wanted to eliminate pooling altogether, it's still needed to keep memory down.  Pooling lets results be used across entire jobs, which clearly shows in benchmarks and in practice will help a busy querier. And we still need to keep pool items organized by size (i.e. spansets (large) vs attrs (small)).
For metrics it looks like memory usage is higher in some cases, but I think that's GC noise.  The single-run memory usage is the same before and after.  I.e. if we fetch …

parquetquery iterator less pooling

---

CHANGELOG.md
modules/querier/worker/frontend_processor.go
modules/querier/worker/frontend_processor_test.go
modules/querier/worker/worker.go

Adds two metrics to provide observability into read path and query processing
1. `tempo_querier_worker_request_executed_total` is a counter, measuring the requests executed by the querier
2. log the concurrency of a querier
**Checklist**

Add querier metrics for requests executed

---

modules/querier/worker/frontend_processor.go
modules/querier/worker/frontend_processor_test.go

only register `tempo_querier_worker_request_executed_total` when we create a new frontend processor...before this change it was registerd in all tempo componentns.
it would add `tempo_querier_worker_request_executed_total` with 0 in all tempo components like query_frontend, compactor, and increase the cardinality of metric...
follow up fix for https://github.com/grafana/tempo/pull/3524.
**Checklist**

only register metric for new frontendProcessor

---

operations/jsonnet-compiled/Deployment-query-frontend.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/frontend.libsonnet

Modify maxSurge in query-frontend deployment to 0, this config makes the rollouts of query-frontends more stable.
During a rollout, maxSurge added extra replicas, and it would result in queriers splitting the the connections across the old and new frontends. that resulted in reduced capacity on the old query frontends, and queries getting `context cancelled` or timeout when we rolled out query frontends.
With updated config, k8s will rollout one pod at a time and that makes rollout more stable.
Fixes #
**Checklist**

operations: change query-frontend maxSurge to 0 for better rollouts

---

CHANGELOG.md
modules/frontend/cache_keys.go
modules/frontend/cache_keys_test.go
modules/frontend/search_handlers_test.go
modules/frontend/search_sharder.go
modules/frontend/tag_handlers_test.go
modules/frontend/tag_sharder.go

Simple PR to add the tenant to the frontend cache key. The block guid is already in the key which should prevent cross tenant shenanigans, but I would feel more comfortable with this extra layer of protection.
**Checklist**

Frontend: Add tenant to cache key

---

docs/sources/tempo/configuration/grafana-agent/tail-based-sampling.md

the link to the "river language" was leading to a 404
just fixes a link in the docs
no related issue exists

Fix a broken link in tail-based-sampling.md

---

modules/distributor/distributor.go
modules/overrides/config.go
modules/overrides/runtime_config_overrides.go

**What this PR does**: Currently, for all rate_limited errors regardless of the ingestion rate strategy, Tempo returns the local strategy limit. This causes confusion for setups that use the global strategy. This PR correctly returns the limit according to the ingestion rate strategy. 
**Checklist**

Return rate limit error according to ingestion rate strategy

---

CHANGELOG.md
modules/frontend/search_handlers_test.go
modules/frontend/search_sharder.go
modules/frontend/search_sharder_test.go

Currently if you repeat a search with different limits and spans per spanset values it will potentially grab incorrect results from cache. This PR adds limit and spss to the cache key to make the job goes through to the backend in this case.
**Checklist**

Add spss and limit to search request hash

---

.drone/drone.jsonnet
.drone/drone.yml
tools/Dockerfile

Each drone builder is running on the native platform, and so there is no TARGETPLATFORM passed here, and so we can drop it from the tools image. Here we make the adjustment that was required to get r143 to build.
**Checklist**

Fix tools image

---

cmd/tempo/app/modules.go

Without this change, SSB mode will end up running multiple pollers per instance; one for the compactor, and one for the frontend.  The frontend only needs the poller when we are running it with the QueryFrontend target.
**Checklist**

Ensure poller only runs on the frontend for the frontend target

---

CHANGELOG.md
tempodb/backend/local/local.go

Use os path separator to split blocks path so local backend works also on Windows
Fixes #3552
**Checklist**

Use os path separator to split blocks path

---

CHANGELOG.md
tempodb/encoding/vparquet3/block_iterator.go

Two small improvements to compactors that I noticed in #3537 .  Bringing them forward since it is currently paused for a bit, and the changes are very small.
Async pages improves throughput by ~40% in our internal cluster. Below are screenshots showing total output traces and data rate.  Benchmarks don't show this since there is no latency like object storage.  (Aside, the benchmarks could use some work but skipping for now).
The pooling leak is mentioned [here](https://github.com/grafana/tempo/pull/3537#discussion_r1551637156)  It only happens when compacting blocks of different trace counts. The benchmarks are also lacking this (they compact blocks of identical counts).  Small but useful reduction in memory. …

Compactor tweaks:  Fix pool leak when iter exhausted and async pages for better throughput

---

pkg/parquetquery/iters.go
pkg/parquetquery/iters_test.go

Unrolls EqualRowNumber in way that still allows inlining and is faster.  This is a small portion of overall read path, but it's enough to show up in TraceQL search benchmarks.  I expected it to have a stronger effect for metrics (which processes more spans), but it doesn't show up there at all.
<details>
<summary>BenchmarkEqualRowNumber</summary>
```
pkg: github.com/grafana/tempo/pkg/parquetquery
│  before.txt  │              after.txt              │
│    sec/op    │    sec/op     vs base               │
EqualRowNumber/0-12   2.1220n ± 2%   0.2474n ± 1%  -88.34% (p=0.002 n=6)
EqualRowNumber/1-12   2.1215n ± 0%   0.2474n ± 1%  -88.34% (p=0.002 n=6)
EqualRowNumber/2-12   2.1215n ± 0%   0.2474n ± 3%  -88.34% (p=0.002 n=6)
EqualRowNumber/3-12   2.1220n ± 3%   0.2474n ± …
```

Unroll EqualRowNumber

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
pkg/cache/memcached_client.go

This is just a copy of https://github.com/grafana/loki/pull/12318#top but for Tempo.
- Adds TLS to the Memcached Client.
- Expose new configs to configure Memcache TLS.
Fixes #3564
**Checklist**

Add TLS support for Memcached client

---

example/docker-compose/agent/docker-compose.yaml
example/docker-compose/azure/docker-compose.yaml
example/docker-compose/cross-cluster/docker-compose.yaml
example/docker-compose/debug/docker-compose.yaml
example/docker-compose/distributed/docker-compose.yaml
example/docker-compose/gcs/docker-compose.yaml
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/otel-collector/docker-compose.yaml
example/docker-compose/s3/docker-compose.yaml
example/docker-compose/scalable-single-binary/docker-compose.yaml

The Grafana image used in the `docker-compose` examples are hardcoded to `10.1.1` which does not support the functionality of creating dashboard variables out of Tempo. I believe this is a great feature which everyone would like to be able test the moment when they run these examples.
More of such features will definitely come along with improvements in Tempo. Therefore, I would suggest to keep the Grafana images up-to-date just like the images for Prometheus and Tempo in these examples.

Updated Grafana image in the docker-compose examples to latest

---

cmd/tempo/app/modules.go

Here we disable a log message which fires far too often and provides very little value. 
**Checklist**

Disable log message in http timeout middleware

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/service_graphs/_index.md
modules/generator/config.go
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/generator/processor/servicegraphs/config.go
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/servicegraphs/servicegraphs_test.go
modules/generator/processor/servicegraphs/store/edge.go
modules/generator/processor/servicegraphs/store/interface.go
modules/generator/processor/servicegraphs/store/store.go
modules/generator/processor/servicegraphs/store/store_test.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go
modules/overrides/userconfigurable/client/limits.go

For the servicegraphs processor:
- Gates this feature behind the EnableExtraUninstrumentedServicesLabels flag in the Config
- If enabled, adds new labels to `traces_service_graph_request_*`:
- `virtual_node` with a value of `client` or `server`, so the un-instrumented service's node can be identified.
- `client|server_db|messaging_system` with the corresponding resource attribute value, to surface and identify the service and the node.
Fixes #3461 
**Checklist**

Surface new labels for uninstrumented services and systems

---

modules/generator/registry/counter.go

Fix misuse of a preallocated slice in `counter.collectMetrics`: we prepare a slice `baseLabels` with the static labels (metric name and externals labels) + room for the series specific labels. We didn't reset the length though, so when we append the static labels this just increases the capacity further 🙃
Noticed it will debugging another feature:
As you can see we nicely allocate 3 places (metric name + 2x external label) and then just append them anyways.
With the fix we don't get the empty labels
This wasn't harmful since `Appender` has code to remove empty labels.
**Checklist**

metrics-generator counter: reset length of pre-allocated slice

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
integration/poller/poller_test.go
tempodb/backend/azure/v1/v1.go
tempodb/backend/azure/v2/v2.go
tempodb/backend/backend.go
tempodb/backend/cache/cache.go
tempodb/backend/gcs/gcs.go
tempodb/backend/local/local.go
tempodb/backend/mocks.go
tempodb/backend/raw.go
tempodb/backend/s3/s3.go
tempodb/blocklist/poller.go
tempodb/blocklist/poller_test.go
tempodb/config.go
tempodb/tempodb.go

In previous attempts to delete the tenant index, it was possible that undiscoverable objects remained in the backend as a partial blocks, which lead to unintended behavior for the poller, whereby the poller would discover a tenant, determine there were no blocks, and delete the index.  However, the partial blocks kept the tenant in the list and so would repeat this forever, or until bucket retention policies removed the objects.
Here we take a more complete approach to tenant deletion.  Upon deletion of a tenant index, we search the backend for objects on a given tenant, and then delete them after a configurable amount of time has expired since the object was last modified.
* Implement Find() on backend readers
* Implement Delete() on backend writers
* Add …

Implement tenant deletion for empty tenants

---

pkg/parquetquery/iters.go
tempodb/encoding/vparquet3/block_traceql_test.go

This is a redo of the join/leftjoin iterator core loops.  This new loop uses the first iterator as the "driving" iterator to which we try to find match amongst all the others. Instead of peeking the tip of them all, it starts the next pass as soon as iterator 2..N don't match iterator 1.   There is also a dynamic re-sort of iterators at runtime.  If iterators 2...N are able to filter further into the file than iterator 1, it is swapped to the top and becomes the new iterator 1.
This has a nice performance improvement on mixed traceql queries, and metrics queries.  The 20% speed on mixed queries is interesting. To dig a bit:  the new loop was responsible for ~15%, and the dynamic re-sort another 5%.
<details>
<summary>BenchmarkBackendBlockTraceQL</summary>
```
│ …
```

Parquetquery join performance improvement

---

CHANGELOG.md
tempodb/encoding/vparquet3/block_autocomplete.go
tempodb/encoding/vparquet3/block_autocomplete_test.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/block_autocomplete.go
tempodb/encoding/vparquet4/block_autocomplete_test.go
tempodb/encoding/vparquet4/wal_block.go

Improves the performance of SearchTagsV2 and fixes the benchmark to actually test SearchTagsV2. 
**Changes:**
- Don't unnecessarily pass null values up through the iterator OtherEntries
- Stop repeatedly building attribute name strings to double check the iterators
- Don't send the same value twice (Skips the cost of repeated allocations to and from `interface{}`)
- Consolidate the 3 samey distinct value collectors into one
**Benches:**
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet3
│ before.txt  │           dontsend2x.txt            │
│   sec/op    │   sec/op     vs base                │
FetchTagValues/tag:_span.http.url,_query:_{resource.namespace="tempo-ops"}-11                                252.7m ± 1%   251.9m ± 1% …
```

SearchTagValuesV2 perf improvements

---

CHANGELOG.md
tools/packaging/tempo-postinstall.sh
tools/packaging/verify-deb-install.sh
tools/packaging/verify-rpm-install.sh

The motivation for this PR is to fix the deb and rpm Drone test process, but we decided it's also a good improvement that should be shipped in the packages.
The deb and rpm packages install Tempo as a systemd service, under a newly-created user `tempo`.  However the services can't start out of the box because the `tempo` user lacks permissions to create and write to `/var/tempo` which is the default storage path.   This updates the post install process to create and assign perms to `/var/tempo`.  Unfortunately we couldn't pin down when this became a problem or what changed.
**Note**  A tricky bit is that Drone only runs for tags and PRs of branches in the Tempo repo itself.  If you PR is from a fork, it doesn't run. This made the failures go unnoticed for some time …

Update deb and rpm packages to create and assign permissions for /var/tempo

---

CHANGELOG.md
pkg/traceql/extractmatcher.go
pkg/traceql/extractmatcher_test.go

This improves the regexes used by autocomplete (and I think the search tags v2 endpoint?) so that they work with queries like `{ resource.service.name = "app" && resource.k8s.cluster.name=~"prod-.+" }`.
Fixes #3635.

fix(traceql): fix extract matcher regexes to work with regexp-type matchers

---

cmd/tempo-cli/cmd-convert-parquet-2to3.go
cmd/tempo-cli/cmd-convert-parquet-3to4.go
cmd/tempo-cli/main.go
tempodb/encoding/vparquet3/block_findtracebyid.go
tempodb/encoding/vparquet3/block_findtracebyid_test.go
tempodb/encoding/vparquet3/schema.go
tempodb/encoding/vparquet3/schema_test.go
tempodb/encoding/vparquet3/wal_block.go

Add sub command `tempo-cli parquet convert-3-to-4` that converts vParquet3 blocks to vParquet4
Contribute to grafana/tempo-squad#299
**Checklist**

Add tempo-cli sub command to convert from vParquet3 to vParquet4

---

docs/sources/tempo/configuration/_index.md
modules/frontend/config.go
modules/frontend/frontend_test.go
modules/frontend/metrics_query_range_handler.go
modules/frontend/search_handlers_test.go
modules/frontend/slos.go
modules/frontend/slos_test.go
modules/frontend/tag_handlers_test.go
modules/frontend/traceid_handlers_test.go

In https://github.com/grafana/tempo/pull/3584/ we decided to count metrics queries as part of search slo. split metrics slo out of search because metrics are still experimental and should not share the SLO with search.
**Checklist**

Split metrics slo out from search slo

---

.github/workflows/ci.yml
Makefile

As a follow up to #3610, here we update CI to use the `make lint` target.  This will mean the local and CI version of golangci-lint will match.
**Checklist**

Use tools image for lint in CI and allow passing base ref

---

CHANGELOG.md
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go

SpanDeduper uses the last byte of the trace ID to shard into a submap of seen values.  It didn't protect against an empty trace ID, which led to a panic.  
**Checklist**

Fix panic in SpanDeduper when traceID is empty slice

---

CHANGELOG.md
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go

Backport d8c69d487eaa1f64af291793ef3b667c133342f0 from #3668
---
SpanDeduper uses the last byte of the trace ID to shard into a submap of seen values.  It didn't protect against an empty trace ID, which led to a panic.  
**Checklist**

[r147] Fix panic in SpanDeduper when traceID is empty slice

---

Makefile
build/tools.mk

Without this change, goreleaser@latest requires a newer version of Go than is currently supported by the project.  Here we pin the version.
**Checklist**

Pin the goreleaser version for Go version support

---

docs/sources/tempo/configuration/grafana-agent/_index.md

No longer needed the vale exceptions per https://github.com/grafana/writers-toolkit/pull/644
**Checklist**

Remove unnecessary vale exceptions

---

modules/frontend/search_sharder_test.go
modules/ingester/instance_search.go
modules/querier/querier.go
pkg/traceql/engine.go
pkg/traceql/engine_test.go
pkg/traceql/storage.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/v2/backend_block.go
tempodb/encoding/v2/wal_block.go
tempodb/encoding/vparquet2/block.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/block_autocomplete.go
tempodb/encoding/vparquet3/block_autocomplete_test.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/block_autocomplete.go
tempodb/encoding/vparquet4/block_autocomplete_test.go
tempodb/encoding/vparquet4/wal_block.go
tempodb/tempodb.go
tempodb/tempodb_search_test.go

Renames a few elements in Tempo from "Autocomplete" to "FetchTagValues" to better match established patterns and make room for "FetchTags" functionality.
The only change that was not a simple rename was the code in instance_search.go
https://github.com/grafana/tempo/pull/3692/files#diff-8c9aac72ec16ad39eb093753942cde7f893be0b5950578ffe10ef003d2ff5237

Fetch Tag Values Refactor

---

CHANGELOG.md
cmd/tempo-cli/cmd-query-blocks.go

**What this PR does**:add tempo cli support for % of blocks to scan and dump using cli `query blocks` option.
Fixes #3690
**Checklist**

Tempo CLI - add percentage support for query blocks

---

CHANGELOG.md
modules/distributor/receiver/shim.go

This sleep is being removed in favor of using the configuration item `shutdown_delay` for generic server shutdown across all Tempo components introduced in #3395.
Fixes #2353 
**Checklist**

Remove hardcoded sleep in shutdown for distributor

---

docs/sources/tempo/setup/operator/api-docs.md

update links to operator API docs
fixes outdated links
**Checklist**

[DOC] update links to tempo-operator API docs

---

CHANGELOG.md
pkg/traceql/ast_conditions.go
pkg/traceql/ast_conditions_test.go

Fixes an issue where TraceQL will pass a bad condition to the fetch layer when you use add a static and attribute such as:
```
{ span.http.status_code > span.http.status_code + 1 }
```
Currently this returns an error:
**Checklist**

Fix TraceQL failures on boolean operations with statics and attributes

---

tempodb/encoding/vparquet3/compactor.go
tempodb/encoding/vparquet3/compactor_test.go
tempodb/encoding/vparquet4/compactor.go
tempodb/encoding/vparquet4/compactor_test.go

Follow up to https://github.com/grafana/tempo/pull/3628. `ReplicationFactor` was not being set during compaction.
**Checklist**

Keep replicationFactor in meta file after compaction

---

CHANGELOG.md
cmd/tempo-cli/Dockerfile
cmd/tempo-serverless/cloud-run/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile
cmd/tempo/Dockerfile_debug

Upgrading alpine for the 2.5 release.

Upgrade alpine to 3.20.x

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go

If a `meta.json` for a completed block on the generator fails to parse correctly, the instance never comes up cleanly.  Here we add a condition to check if the error is a `*json.SyntaxError`, and ensure we also clear the local block on startup.
**Checklist**

Clear completed, partial blocks on generator startup

---

CHANGELOG.md
docs/sources/tempo/metrics-generator/service_graphs/_index.md
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/servicegraphs/servicegraphs_test.go
modules/generator/processor/servicegraphs/testdata/trace-with-queue-database2.json
modules/generator/processor/servicegraphs/testdata/trace-with-queue-database3.json
modules/generator/processor/servicegraphs/testdata/trace-with-queue-database4.json
modules/generator/processor/servicegraphs/testdata/trace-with-queue-database5.json
modules/generator/processor/servicegraphs/testdata/trace-without-database-name.json

Currently, the `db.name` attribute is used as the node identity on the service graph.  This leads to situations where the name of the database may be reused between services, leading to a single node on the graph where more than one actual service is in use.
This PR changes the node identity when newer OTEL semantic conventions are available as attributes on the span.  The following attributes are considered in order:
- `peer.service`
- `server.address`
- `network.peer.address` -- additionally `network.peer.port` will be used if available
- fall back to `db.name`
Fixes #3010
**Checklist**

Improve servicegraph handling of newer OTEL semantic conventions

---

example/docker-compose/agent/docker-compose.yaml
example/docker-compose/cross-cluster/docker-compose.yaml
example/docker-compose/debug/docker-compose.yaml
example/docker-compose/distributed/docker-compose.yaml
example/docker-compose/local/docker-compose.yaml
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/otel-collector/docker-compose.yaml
example/docker-compose/scalable-single-binary/docker-compose.yaml
example/helm/microservices-extras.yaml
example/helm/single-binary-extras.yaml

Use the latest release of grafana and xk6-client-tracing in Tempo's docker-compose examples. This improves support for event and links in the examples.
**Checklist**

Upgrade grafana and xk6-client-tracing in examples

---

docs/sources/tempo/release-notes/v2-5.md
docs/sources/tempo/setup/upgrade.md

Adds draft release notes for Tempo 2.5
Fixes #https://github.com/grafana/tempo/issues/3694
**Checklist**

[DOC] Draft release notes for 2.5

---

docs/sources/tempo/release-notes/v2-5.md
docs/sources/tempo/traceql/architecture.md

Removes the blog post link from the release notes. 
**Checklist**

[DOC] Remove  blog link from 2.5 release notes

---

docs/sources/tempo/operations/traceql-metrics.md
docs/sources/tempo/traceql/metrics-queries.md

Adds missing doc for quantile_over_time, histrogram, and rate. 
Related: https://github.com/grafana/tempo/pull/3605, https://github.com/grafana/tempo/pull/3633, https://github.com/grafana/tempo/pull/3644
Questions for reviewers: 
* Are the listed functions correct? There are only three. Should there be additional ones? 
* Please add any additional content or examples. It's rather sparse. 
**Checklist**

[DOC] Add missing doc for metrics

---

CHANGELOG.md
modules/frontend/combiner/common.go
modules/frontend/tag_sharder.go
modules/querier/http.go

The frontend communicates with the queriers using json, and this is becomes a bottleneck for large autocomplete lookups.  This PR switches /api/v2/search/tag/.../values to use http/protobuf instead.  Testing locally and in a larger cell on a large lookup, the savings are around 30% user-facing latency to Grafana. Timings:  15s -> 10s, 5s -> 3s.   We like graphs, so here is one showing the second set:
The encoding is implemented optionally where the querier will reply with proto only if the request header is `Accept: application/protobuf`.  Else it defaults to json.  This helps with compatibility during rollouts of old/new pods, and also curl-ability. 
A couple future steps:
(1) It might be worth swapping over the remaining apis with large payloads like search/tags …

SearchTagValuesV2 use protobuf internally instead of json to reduce latency

---

modules/generator/processor/localblocks/processor.go

Fix for bug introduced in https://github.com/grafana/tempo/pull/3691.
If `FlushToStorage` was set to `false` (default), complete blocks were not handled correctly:
* local blocks are no longer pushed to the queue to be flushed during reload (start-up)
* complete blocks can now be deleted if old (`endTime < now + completeBlockTimeout`)

Fix block reload in local-blocks

---

pkg/traceql/ast.go
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
pkg/traceql/parse_test.go
tempodb/encoding/vparquet3/block_traceql_test.go

On creation of binary and unary operations this PR attempts to collapse values down to a single static where possible. This allows the fetch layer to directly apply predicates for conditions like `{ span.foo = 1 + 1 }` b/c they turn into `{ span.foo = 2 }`.
In order to make this PR work I needed to split out integer math from float. Currently the engine processes all values as floats. However, it's important not to change the type when collapsing or it breaks the fetch layer. `{ span.foo = 1 + 1 }` needs to collapse to `{ span.foo = 2 }` and not `{ span.foo = 2. }`
This has interesting consequences. Note the changed test. This used to be true `{ 1 / 10 = .1 }` but, due to integer division it is not. These two statements are now true: `{ 1 / 10. = .1 }` and `{ 1 / 10 …

TraceQL: Collapse statics

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go
modules/querier/http.go

Similar to #3731 but for query_range.  For high cardinality metrics queriers on larger clusters, the marshaling/unmarshaling of json was becoming the bottleneck in the query-frontend.   Metrics queries have larger and more numerous jobs than autocomplete, so the improvement is even better.   I was thinking about why this was just now being noticed, since autocomplete and query_range have existed for some time and the request/response formats haven't changed.  I believe it is due to the recently added asynchronous frontend pipeline.  Two changes (1) It is more efficient at issuing jobs, so the bottleneck in the frontend from unmarshaling is now readily apparent (2) the unmarshaling was moved to a single goroutine, which will be restored in #3713 however this PR is …

QueryRange use protobuf internally instead of json to reduce latency

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
integration/e2e/limits_test.go
modules/frontend/combiner/common.go
modules/frontend/combiner/common_test.go
modules/frontend/combiner/search_tag_values.go
modules/frontend/config.go
modules/frontend/frontend.go
modules/frontend/metrics_query_range_handler.go
modules/frontend/pipeline/collector_grpc.go
modules/frontend/pipeline/collector_http.go
modules/frontend/pipeline/responses_test.go
modules/frontend/search_handlers.go
modules/frontend/tag_handlers.go
modules/frontend/tag_handlers_test.go
modules/frontend/traceid_handlers.go

Adds a configurable number of dedicated goroutines per request to consume the responses and add them to the combiner. The combiner was also adjusted to move the unmarshalling steps outside of the locking logic so we could do multiple unmarshals in parrallel.
- Added a parameter to configure the number of goroutines. Default: 10
- Added tests to confirm the combiner doesn't race with the new changes
- Found and fixed an issue where tag values v2 was not initializing its status code to 200 which caused it to fail if GRPCDiff was called before a response was received.
**Checklist**

Query-frontend: Parrallelize unmarshalling of responses

---

CHANGELOG.md
cmd/tempo-query/Dockerfile

Bump `jaeger-query` image to 1.57.0.
Fixes #3652

[CHANGE] Update base image for tempo-query to 1.57.0

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
docs/sources/helm-charts/tempo-distributed/release-notes/_index.md

Updates the Helm chart doc for Tempo 2.5 and GET 2.4.1. Fixes quite a few Vale linter stylistic issues.
**Checklist**

[DOC] Update Helm chart doc to 2.5

---

docs/sources/tempo/metrics-generator/span_metrics.md

Fixes a broken link in the span metrics doc. 
The span metrics processor in the OTEL Collector has been deprecated, which is why the link was broken. The span metrics processor has been replaced with the span metrics collector. 
Any reviewers - Please verify that the updated text is correct for our implementation. 
**Checklist**

Fix span metrics info

---

modules/ingester/instance_search_test.go
pkg/search/util.go
pkg/traceql/enum_attributes.go

This PR adds new intrinsic names to the response of `/v2/search/tags` endpoint.
The response now looks like, 
```
{"scopes":[{"name":"intrinsic","tags":["duration","kind","name","rootName","rootServiceName","span:duration","span:kind","span:name","span:status","span:statusMessage","status","statusMessage","trace:rootName","trace:rootServiceName","traceDuration"]}]}
```
It is missing `trace:traceDuration`. I wasn't sure what to call it in the code ?
Fixes #3714
**Checklist**

search/utils: added missing new intrinsic names to search/tags endpoint

---

.drone/drone.yml

Follow-up to https://github.com/grafana/tempo/pull/3757
This might the reason we see some weird CI behaviour in Drone right now.

CI: Update signature in drone.yml

---

cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/lambda/go.mod
go.mod
tools/go.mod

**What this PR does**: Change toolchain from go 1.22 => go 1.22.0 in `go.mod`. [Toolchain requires a specific version.](https://github.com/golang/go/issues/62278#issuecomment-1693538776) .
```
% make docker-tempo
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
```
**Checklist**

Change toolchain from go 1.22 => go 1.22.0

---

CHANGELOG.md
modules/ingester/ingester.go
modules/ingester/ingester_search.go

Adds a defer/recover to all ingester gRPC endpoints to prevent poison reads from panicing ingesters.
**Checklist**

Defer recover all read endpoints

---

CHANGELOG.md
tempodb/backend/gcs/gcs.go
tempodb/backend/s3/s3.go

**What this PR does**: 
Fixes connection reuse for S3 range requests and increases the number of MaxIdleConnsPerHost for the S3 backend to 100 to match the azure settings. Also, assumes GCP has the same connection reuse problem for range requests and performs the same fix. Note: I have tested the fix for S3 range requests and verified it is a problem and the change fixes the problem but I have not verified that it is a problem for GCP or that it fixes the problem for GCP. The GCP HTTP google storage code does look like it effectively returns the body reader so it does look like GCP would have a similar issue.
Fixes #3750
**Checklist**

Improve http connection reuse

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go

This fix addresses an issue where complete blocks were not being properly processed in the `localblocks` processor. Before, complete blocks were kept for longer than necessary. This was a problem specially when enabling flushing to storage for the first time.
The condition for deleting complete blocks has been changed to be based on block end time. If the block has been flushed and it's past it the cutoff time, it's deleted.
**Checklist**

Bugfix: Improved handling of complete blocks in localblocks processor after enabling flushing

---

docs/sources/tempo/traceql/_index.md

Adds example for rootName in TraceQL intrinsics doc. 
Fixes #https://github.com/grafana/support-escalations/issues/10769
**Checklist**

[DOC] Add examples for rootName

---

CHANGELOG.md
cmd/tempo/app/config_test.go
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
docs/sources/tempo/configuration/parquet.md
tempodb/config_test.go
tempodb/encoding/versioned.go

**What this PR does**: Make vParquet4 the default block encoding
**Checklist**

make vparquet4 the default block encoding

---

modules/generator/registry/histogram.go

Simplify the `histogram.ObserveWithExemplar` a tad. Since we lock a `Mutex` for the entire method, we don't have to check whether the map was updated in the meantime. This code was added when we still used a `RWMutex` which was removed by #3412.
**Checklist**

Drop unnecessary concurrency check in metrics-generator histogram

---

docs/sources/tempo/api_docs/metrics-summary.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/operations/traceql-metrics.md

Clarifies instructions for configuring the local-blocks for the metrics-generator and the Metrics API. 
Fixes #https://github.com/grafana/tempo/issues/3064
**Checklist**

[DOC] Clarify local-block config

---

CHANGELOG.md
pkg/dataquality/warnings.go
tempodb/compactor.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/vparquet3/compactor.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/compactor.go
tempodb/encoding/vparquet4/wal_block.go

Adds new reason `rootless_trace` to data quality metric warnings.
**Checklist**

Add data quality metric to measure traces without a root

---

docs/sources/tempo/traceql/_index.md

Backport d0a92cafa9aa6150444335dd504fcb8bdd99289f from #3809
---
Adds example for rootName in TraceQL intrinsics doc. 
Fixes #https://github.com/grafana/support-escalations/issues/10769
**Checklist**

[release-v2.5] [DOC] Add examples for rootName

---

docs/sources/tempo/troubleshooting/unable-to-see-trace.md

Applying a fix from [another PR](https://github.com/grafana/tempo/pull/3767).
CTA remains unsigned from the other PR, but it's a fix that we need. 
**Checklist**

[DOC] Fix distributor.log_received_spans.enabled in unable-to-see-trace.md

---

docs/sources/tempo/api_docs/metrics-summary.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/operations/traceql-metrics.md

Backport b3f06d4c839c660eb5d4544d9faf962e1d36ed5e from #3807
---
Clarifies instructions for configuring the local-blocks for the metrics-generator and the Metrics API. 
Fixes #https://github.com/grafana/tempo/issues/3064
**Checklist**

[release-v2.5] [DOC] Clarify local-block config

---

docs/sources/tempo/configuration/_index.md

Removes two unused examples from the cache documentation. 
Fixes #https://github.com/grafana/tempo/issues/3801
**Checklist**

[DOC] Remove unused caches from example

---

pkg/util/traceid.go

Small change in ID conversion that avoids an allocation. Since this is called in the `spanCollector` and `traceCollecor` this has a significant impact on allocations for metrics queries.
None
**Checklist**

Avoid allocations in ID conversions

---

CHANGELOG.md
integration/e2e/README.md
integration/util.go

It can be handy to debug Tempo code when running an e2e test. This can be done in different ways. This PR aims to ease this task by providing a new function to spin a Tempo docker container based on the tempo-debug image, without modifying any aspect of the test so it can be run in the same way either locally or in the CI.
**Limitations**:
I haven't found a way to expose the docker host port locally ie: -p 2345:2345. 
This could be enhanced to allow that:
https://github.com/grafana/e2e/blob/db90b84177fccb4f023ea9f71ec0e8dcd2d3bdad/service.go#L328
**How to use it**:
The debug process is a bit cumbersome right now:
1. In our e2e test use the new function ``NewTempoAllInOnDebug`` to spin the debug container 
2. Set a breakpoint before the action we want to test
3. …

feat: added new helper function to allow debugging e2e tests

---

CHANGELOG.md
tempodb/encoding/vparquet4/block_traceql.go

It was observed that queries such as `{} | rate() by (event.name)` can cause panics in the `batchCollector`. Here is a stack trace taken from the logs:
```
2024-07-04 14:01:01.425	
github.com/grafana/tempo/pkg/traceql.(*MetricsEvalulator).Do(0xc0bd65db00, {0x3305e18, 0xc08a0a7440}, {0x32e1c60?, 0xc06f4f8cd0?}, 0x0?, 0xc099578f68?)
2024-07-04 14:01:01.425	
/drone/src/tempodb/encoding/vparquet4/block_traceql.go:1312 +0x1f
2024-07-04 14:01:01.425	
github.com/grafana/tempo/tempodb/encoding/vparquet4.(*spansetIterator).Next(0xc097d151e0?, {0x3324f20?, 0xc08e5dad20?})
2024-07-04 14:01:01.425	
/drone/src/tempodb/encoding/vparquet4/block_traceql.go:1198 +0x11f
2024-07-04 14:01:01.425	
github.com/grafana/tempo/tempodb/encoding/vparquet4.(*rebatchIterator).Next(0xc08a0a7f50) …
```

Avoid panic by cheking whether entry is a span in batchCollector

---

CHANGELOG.md
Makefile

For newcomers to the repo it can be handy to have a self-documented Makefile, that way instead of doing a:
``cat Makefile``
you can do:
``make``
**How it looks like**
**Checklist**
- [ X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

feat: Make Makefile self-documented

---

CHANGELOG.md
operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin-compiled/dashboards/tempo-reads.json
operations/tempo-mixin-compiled/dashboards/tempo-resources.json
operations/tempo-mixin-compiled/dashboards/tempo-rollout-progress.json
operations/tempo-mixin-compiled/dashboards/tempo-tenants.json
operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/jsonnetfile.lock.json
operations/tempo-mixin/rules.libsonnet
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/grafana-builder/grafana.libsonnet
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/mixin-utils/test/.gitignore
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/mixin-utils/test/Makefile
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/mixin-utils/test/jsonnetfile.json
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/mixin-utils/test/test_native-classic-histogram.libsonnet
operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/mixin-utils/utils.libsonnet

* Updating the mixin deps (needed to have newer version of `histogramRules` which allows specifying range_interval)
* Adding a mixin config option `recording_rules_range_interval` to allow overriding the range_interval in recording rules.
Fixes #3815
**Checklist**

chore: update mixin deps and add recording_rules_range_interval

---

modules/ingester/instance_search.go

A previous PR:
https://github.com/grafana/tempo/pull/3822
accidentally caused Tempo to search for tags using both the old and the new search paths. This correctly returns early if we can do the unfiltered/faster search.

Fix Tags v2 API

---

CHANGELOG.md
pkg/util/traceid.go
pkg/util/traceid_test.go

Control unbounded spans kinds
**Checklist**

fix: handle out of boundaries spans kinds

---

CHANGELOG.md
tempodb/blocklist/poller.go
tempodb/blocklist/poller_test.go

Here we fix a bug where a single tenant experiences an error during polling,
which is not enough to trip the max error threshold.  In this case, the tenant
which experienced the error would be removed from the blocklist, and would not
be re-added until the next time the poller runs.  Inconsistent results in the
blocklist can cause issues on the query path for this tenant.
**Checklist**

Fix poller to maintain previous blocklist results on tenant error

---

CHANGELOG.md
pkg/traceql/extractmatcher.go
pkg/traceql/extractmatcher_test.go

Tiny fix to autocomplete parsing of the new scoped intrinics inside the filtering query.  Ex:
`/api/v2/search/tag/resource.service.name/values?q={event:name="exception"}`   Missing colon lead to the extracted matchers dropping the scope and became `name="exception"`.
Fixes n/a
**Checklist**

Fix autocomplete parsing of new scoped intrinsics

---

operations/jsonnet-compiled/StatefulSet-ingester.yaml
operations/jsonnet-compiled/StatefulSet-metrics-generator.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/generator.libsonnet
operations/jsonnet/microservices/ingester.libsonnet

New PVCs may get exposed to the container with root permissions despite the UID of the container.  Here we set the `securityContext.fsGroup` of the statefulset which run the tempo container.
**Checklist**

Include securityContext.fsGroup on jsonnet statefulset

---

modules/frontend/combiner/common.go
modules/frontend/combiner/common_test.go
modules/frontend/combiner/metrics_query_range.go
modules/frontend/combiner/search_test.go
modules/frontend/metrics_query_range_sharder.go
modules/frontend/pipeline/context.go
modules/frontend/pipeline/pipeline.go
modules/frontend/pipeline/responses.go

A simple refactor PR that renames the "additional data" concept to more clearly indicate what it's for. This feature is meant as a way to attach a specific piece of data to a request that is returned in the response.

Refactor: Rename AdditionalData for clarity

---

CHANGELOG.md
cmd/tempo-vulture/main.go
cmd/tempo-vulture/mocks.go
pkg/httpclient/client.go
pkg/httpclient/client_test.go

It enables trace ID lookup for a selected time range from Tempo Vulture. This will reduce the number of blocks that Tempo has to scan to find the trace
Fixes #3700
**Checklist**
- [ X] Tests updated
- [ X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

feat: improve trace id lookup by defining a time range

---

CHANGELOG.md
pkg/traceql/ast.go

This fixes support for computing quantiles and histograms on `traceDuration`.   This is done by fixing support for any `Duration` type attribute (so far it's only this one I think), and also includes cleanup.   Example queries:
```
{ } | quantile_over_time(traceDuration, 0.9)
{ } | histogram_over_time(traceDuration)
```
Fixes n/a
**Checklist**

[TraceQL Metrics] Fix quantiles/histograms of generic duration attributes (i.e. traceDuration)

---

modules/frontend/metrics_query_range_sharder.go

Given an unknown set of conditions the query frontend can issue commands to the queriers on blocks where start = end and the step is 0s. This materializes in the frontend with the error:
```
end must be greater than start
```
This has been most commonly observed when the duration is the last 15m and query_backend_after is also set to 15m.
Example query-frontend query:
```
GET /tempo/api/metrics/query_range?query=%7BnestedSetParent%3C0%26%26resource.cluster%3D%22dev-us-central-0%22%7D%20%7C%20histogram_over_time(duration)&start=1721402456&end=1721403356&step=37s (500) 173.192079ms Response: \"end must be greater than start\\n\
```
gets translated to the following. note that start = end and step = 0
```
GET /querier/tempo/api/metrics/query_range?blockID=948dc707-4945-4 …
```

TraceQL Metrics: skip blocks with no overlap

---

CHANGELOG.md
modules/ingester/config.go

expose availability-zone cli flag (needed for zone aware ingester in helm chart) 
Fixes #3877 
**Checklist**

feat: expose availability-zone as a cli flag for ingester

---

CHANGELOG.md
modules/distributor/distributor.go
modules/distributor/receiver/shim.go
modules/frontend/pipeline/sync_handler_retry.go
modules/frontend/slos.go
modules/frontend/v1/frontend.go
modules/ingester/flush.go
modules/querier/external/client.go
pkg/cache/memcached.go
pkg/cache/redis_cache.go
tempodb/backend/instrumentation/backend_transports.go
tempodb/blocklist/poller.go
tempodb/tempodb.go

Here we include the necessary options for the Prometheus client to expose
native histograms for internal metrics.  Users will need to scrape the native
histograms explicitly, but this will allow a migration to begin.  There will be
some follow up to add the necessary changes to dashboards etc, but here we can
begin the process.
**Checklist**

Add native histograms for internal metrics

---

CHANGELOG.md
tempodb/encoding/vparquet4/block_traceql.go

**What this PR does**: Primary iter is appended twice before. This fixes the issue in query range group by event attributes. 
**Checklist**

[bugfix] Remove extra primary iter

---

modules/generator/registry/registry.go
modules/generator/storage/instance_test.go

It appears that in two locations, we have a race between the generator storage instance shutdown, and the appender.
In the case of the registry, we have a [routine](https://github.com/zalegrala/tempo/blob/80b4f3b4008061c3408ee96f89b74723e925f4f2/modules/generator/registry/registry.go#L132) that is running to collect the metrics on an interval.  The wrapper `job` captures the context to avoid the next loop iteration when the context is canceled.  However, once the loop is started, the context is not checked.  If the shutdown has started a "file already closed" error is generated when trying to [commit](https://github.com/zalegrala/tempo/blob/7e76255073bb7647e4b00e3a6b9277a13cd09946/vendor/github.com/prometheus/prometheus/storage/fanout.go#L208) new metrics to the …

Skip "file already closed" errors in generator storage instance test

---

example/docker-compose/scalable-single-binary/docker-compose.yaml

**What this PR does**: Due to changes in Minio Docker image, [Tempo's Scaling monolithic mode example](https://grafana.com/docs/tempo/latest/setup/deployment/#scaling-monolithic-mode) didn't work. Now the Docker Compose file works again.
Fixes #3893 
**Checklist**

Update docker-compose.yaml to get Minio up

---

CHANGELOG.md
docs/sources/tempo/traceql/_index.md
integration/e2e/api_test.go
modules/ingester/instance_search_test.go
pkg/search/util.go
pkg/traceql/ast.go
pkg/traceql/enum_attributes.go
pkg/traceql/expr.y
pkg/traceql/expr.y.go
pkg/traceql/lexer.go
pkg/traceql/lexer_test.go
pkg/traceql/parse_test.go
pkg/traceql/test_examples.yaml
pkg/util/test/req.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/encoding/vparquet4/block_traceql_meta_test.go
tempodb/encoding/vparquet4/block_traceql_test.go
tempodb/tempodb_search_test.go

**What this PR does**: Add Traceql support for event timestamp. User will be able to query for events by how much time as elapsed since span start time to the timestamp of the event using `event:timeSinceStart`. 
Example:
`{ event:timeSinceStart > 1m }`
This query can help find spans where an event took place at least 1 minute after the span start time. 
**Checklist**

[Traceql] Add support for event timestamp 

---

Makefile

fix make vendor-check

---

pkg/api/http.go
pkg/api/http_test.go
pkg/api/query_builder.go
pkg/api/search.go
pkg/api/search_tags.go
pkg/api/search_test.go

Reduces allocs incurred by calling `.Query()` repeatedly. This method allocs a map under the hood. Benchmarks attached only address the frontend side of the improvements. The querier side would also be quite dramatic.
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/modules/frontend
│  before.txt  │           after.txt           │
│    sec/op    │    sec/op     vs base         │
SearchPipeline-11   608.1m ± ∞ ¹   606.9m ± ∞ ¹  ~ (p=0.310 n=5)
¹ need >= 6 samples for confidence interval at level 0.95
│   before.txt   │              after.txt               │
│      B/op      │     B/op       vs base               │
SearchPipeline-11   10.645Mi ± ∞ ¹   9.149Mi ± ∞ ¹  -14.05% (p=0.008 n=5)
¹ need >= 6 samples for confidence interval at level 0.95
│ …
```

Reduce allocs in query path

---

cmd/tempo-vulture/Dockerfile

Follow-up to #2265 which missed tempo-vulture
**Checklist**

Update vulture container image to run as non-root

---

CHANGELOG.md
pkg/traceql/engine.go
pkg/traceql/storage.go
pkg/traceql/storage_test.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/encoding/vparquet4/block_traceql_test.go

This PR updates the trace-level iterators to push down predicates for all queries, even where AllConditions=false.   An example query is `{ rootServiceName = "tempo-gateway" && (status = error || span.http.status_code = 500)}`. This wasn't actually filtering for "tempo-gateway" at the fetch layer.
The reason this wasn't done before was interaction with metadata on search responses.  If the query was already using a metadata column (i.e root service name), we didn't want to read it again.  But this meant that queries like above had to be reverted to do no filtering in the fetch layer, and pass everything up to the engine.
By updating the metadata second pass to be a bit more precise and splitting it out better, we can let those predicates be pushed down, and then …

Change trace-level iterators to push predicates down for all queries

---

.github/workflows/ci.yml

It fixes an error with the actions/setup-go@v5 cache: https://github.com/actions/setup-go/issues/427
It takes the Go version from the `go.mod` file
It also uses a matrix strategy to remove boilerplate
**Checklist**

fix: enable cache for Set up Go action

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
integration/poller/poller_test.go
modules/storage/config.go
tempodb/blocklist/poller.go
tempodb/blocklist/poller_test.go
tempodb/config.go
tempodb/tempodb.go

Here we implement basic polling for tenants concurrently.  This is another step
towards making the polling more efficient.  The next step will be to implement
a weighted polling strategy to poll tenants by some priority.  For now, I think
this is a reasonable start and should stand on its own.
**Checklist**

Implement polling tenants concurrently

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go

Fixes a divide-by-0 bug in the recently merged exemplar logic.  For very small blocks or containing few traces, there could be a divide by 0 bug in the query-frontend when calculating the number of exemplars for a sub-request.
Fixes n/a
**Checklist**

Fix divide by 0 bug in exemplar sharding calculations

---

modules/generator/config.go
modules/generator/instance.go
modules/generator/instance_test.go
modules/generator/overrides_test.go
modules/generator/processor/servicegraphs/config.go
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/spanmetrics/config.go
modules/generator/processor/spanmetrics/spanmetrics.go
modules/generator/registry/interface.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/registry.go
modules/generator/registry/registry_test.go
modules/generator/registry/test.go
modules/generator/registry/test_test.go

Here we make an adjustment the processor replacement logic to include the previous and current values of the desired histogram implementation.  When moving from the new implementation to the old implementation, the servicegraph and span-metrics processors need to be replaced so that when NewHistogram is called on the registry, it can make the determination about which implementation to use.
**Checklist**

Update processor replacement logic for native histograms

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/_index.md

Native histogram support was recently added to the generator.  Here we include some docs about how to use this feature.
**Checklist**

Add docs for native histograms in the generator

---

CHANGELOG.md
modules/frontend/frontend.go
modules/frontend/metrics_query_range_sharder.go
modules/frontend/tag_sharder.go
modules/querier/http.go

Follow up to #3745 and #3731 .  Swaps /api/search and almost all remaining endpoints (except metrics summary api), to use proto between the frontend and queriers.  Improves latency, cpu, and memory.   Now that this is universal for all communication between frontend and queriers, did the next step of cleanup and centralized in `prepareRequestForQueriers`. 
For a bit more context - this started out as troubleshooting performance and resource usage for some searches. When limit and spans per spanset are high, it reached a point where the json encoding/decoding was the bottleneck.  For example limit=1000 and spss=100, means up to 100K spans per job.  This could easily lead to 100MB+ json response sizes.
Fixes n/a
**Checklist**

Swap querier /api/search and remaining endpoints to proto

---

cmd/tempo/app/modules.go

Fixes the route registration for `/static` to happen with the memberlist service, since it is currently the only consumer.
**Checklist**

Fix /static object mapping on memberlist as the only consumer

---

CHANGELOG.md
tempodb/backend/block_meta.go
tempodb/backend/block_meta_test.go
tempodb/encoding/v2/streaming_block_test.go
tempodb/encoding/vparquet2/block_findtracebyid_test.go
tempodb/encoding/vparquet3/block_findtracebyid_test.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet4/block_findtracebyid_test.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/tempodb_test.go

To shrink the size of the BlockMeta, here we drop two fields that should have very little overall impact due to their light use.
**Checklist**

Drop MinID/MaxID from BlockMeta

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go
tempodb/backend/block_meta.go
tempodb/encoding/vparquet3/compactor_test.go
tempodb/encoding/vparquet4/compactor_test.go
tempodb/tempodb.go

Here we reduce the size of the integer representing a block replication factor.  Normal values are 1-3.
**Checklist**

Change ReplicationFactor to uint8 in BlockMeta

---

CHANGELOG.md
tempodb/backend/block_meta.go
tempodb/backend/json.go
tempodb/backend/json_test.go
tempodb/blocklist/poller.go

Here we cache the unmarshaled DedicatedColumns in a package level map variable which is keyed by the bytes that were used to unmarshal.
* This works because we are not dealing with maps, which are unordered.  Otherwise the json should be in a consistent order.
* This has the potential to grow unbounded, but there are not an unbounded set of dedicated columns, so this is probably fine.
* The string of the json is used as the map key, which could be large.
A reasonable follow up might be to do the same kind of caching, but for each dedicated column.  This would mean that we use the cached set of columns first, and if that isn't available, then use the cache for a single column.  
**Checklist**

Unmarshal identical dedicatedColumns fields less often

---

CHANGELOG.md
tempodb/backend/block_meta.go
tempodb/backend/block_meta_test.go
tempodb/encoding/v2/streaming_block.go
tempodb/encoding/v2/wal_block.go
tempodb/encoding/v2/wal_block_test.go
tempodb/encoding/vparquet2/create.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/create.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/create.go
tempodb/encoding/vparquet4/wal_block.go
tempodb/wal/wal_test.go

This PR addresses a bug where traces older than the ingestion slack are ingested. When that happened, the block start time exceeded the block end time. This led the compactor to remove those blocks, and the inability to search them by id.
**Example of the current error**
Trace data:
```json
{
"traceId": "5B8EFFF798038103D269B633813FC703",
"spanId": "EEE19B7EC3C1B100",
"name": "I am a span!",
"startTimeUnixNano": 1689969302000000000,
"endTimeUnixNano": 1689970000000000000,
"kind": 2,
"status": {
"code": "STATUS_CODE_OK"
},
"attributes": [
{
"key": "my.span.attr",
"value": {
"stringValue": "some value"
}
}
```
The start and date are from 2023
Resulting block:
```
window: 2023-07-21T20:00:00Z
start: 2024-08-07T17:21:44+02:00
end: 2023-07-21T22:06:40+02:00
duration: …
```

fix: correct end time when a trace is outside the ingestion slack range

---

.drone/drone.jsonnet
.drone/drone.yml

Here we publish a docker image for the Tempo CLI.
**Checklist**

Publish a docker image for Tempo CLI

---

cmd/tempo/app/overrides_validation.go
modules/generator/config.go
modules/generator/instance.go
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/generator/processor/servicegraphs/config.go
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/servicegraphs/servicegraphs_test.go
modules/generator/processor/spanmetrics/config.go
modules/generator/processor/spanmetrics/spanmetrics.go
modules/generator/registry/interface.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/overrides.go
modules/generator/registry/registry.go
modules/generator/registry/registry_test.go
modules/generator/registry/test.go
modules/generator/registry/test_test.go
modules/generator/storage/instance_test.go
modules/generator/storage/overrides.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/interface.go
modules/overrides/overrides.go
modules/overrides/runtime_config_overrides.go

Plumb an enum into the native histograms and update overrides.
As a follow up to https://github.com/grafana/tempo/pull/3923
**Checklist**

Native histograms processor replacement enum

---

CHANGELOG.md
modules/frontend/combiner/common.go

Clones the diff in GRPC streaming to prevent panics
**Checklist**

Clone the diff in GRPC streaming to prevent panics

---

CHANGELOG.md
modules/frontend/combiner/common.go

Backport 89b8d7d783e7e4c8b2955bd3b39c9e084f75ca4c from #3961
---
Clones the diff in GRPC streaming to prevent panics
**Checklist**

[r160] Clone the diff in GRPC streaming to prevent panics

---

CHANGELOG.md
modules/frontend/combiner/common.go

Backport 89b8d7d783e7e4c8b2955bd3b39c9e084f75ca4c from #3961
---
Clones the diff in GRPC streaming to prevent panics
**Checklist**

[r161] Clone the diff in GRPC streaming to prevent panics

---

CHANGELOG.md
modules/querier/querier.go

The search options from here: https://github.com/grafana/tempo/blob/cb35a075268deaf501ac4d25bbd58d687c1f9f35/modules/querier/querier.go#L892
was not passed downstream. 
**Checklist**

fix: pass search options to the backend

---

CHANGELOG.md
RELEASES.MD

Cleans up the changelog for 2.6 rc.0. Also, tidies up some language in the release instructions.

Changelog 2.6.0 rc.0

---

docs/sources/tempo/configuration/network/ipv6.md

**What this PR does**: Removed address: '::' from ingester config.
**Which issue(s) this PR fixes**: The inclusion of the address: '::' parameter caused an issue where the expected addresses did not appear, and the curl command failed to work as intended.
Fixes #3981
**Checklist**

Update Documentation for IPv6 Configuration in Grafana Tempo Ingester

---

docs/sources/tempo/troubleshooting/_index.md
docs/sources/tempo/troubleshooting/long-running-traces.md

Here we add a bit of doc to point folks at when they are using the long-running trace pattern.
**Checklist**

Add doc about long-running traces

---

CHANGELOG.md
cmd/tempo/app/modules.go
docs/sources/tempo/configuration/manifest.md
modules/frontend/config.go
modules/frontend/queue/queue.go
modules/frontend/queue/queue_test.go
modules/frontend/queue/user_queues.go
modules/frontend/v1/frontend.go

This PR cleans up unused code that Tempo inherited that allows the configuration of the max number of queriers a tenant has access to. This code is complicating attempts to improve this element of the frontend. It is currently unused and not even usable.
Additionally, I've moved the clean up of user queues to a timer. This prevents "flapping" of user queue creation/deletion. Currently, we delete the queue if we [notice it has 0 jobs](https://github.com/grafana/tempo/blob/8a0b0e72a0db8374152333b1a7401d184face9e0/modules/frontend/queue/queue.go#L182-L185). This requires us to over provision go routines to shove jobs into the queue to prevent it from being constantly recreated. This PR should allow us to reduce the number of goroutines used to put pressure on the [user …

Frontend cleanup and perf improvement

---

CHANGELOG.md
example/docker-compose/distributed/tempo-distributed.yaml

It updates Tempo metrics-generator configuration in the distributed example to serves TraceQL metrics
**Checklist**

feat: update distributed docker compose example to serve TraceQL metrics

---

tempodb/backend/cache/cache.go

use the same cache name in the log line as the cache roles in config, some users are using this log line to see if the cache config is picked up correctly and find this difference [confusing](https://github.com/grafana/tempo/discussions/3553#discussioncomment-10453202)
use the same names to avid the confusion.
old log line looked something like `"caches available to storage backend" footer=true bloom=true offset_idx=false column_idx=false trace_id_idx=false page=false`
updated log line looks like `"caches available to storage backend" parquet-footer=true bloom=true parquet-offset-idx=false parquet-column-idx=false trace-id-index=false parquet-page=false`
frontend cache is configured in frontend, and is logged correctly like `"init frontend cache" …

consistnent cache names in config and log line

---

CHANGELOG.md

Update the changelog for v2.6-rc.1

Changelog v2.6-rc1

---

cmd/tempo-cli/cmd-analyse-block.go
cmd/tempo-cli/cmd-analyse-blocks.go

Add `--jsonnet` flag to enable writing output for `analyse blocks` with jsonnet support.  This makes for easy updates.
**Checklist**

[cli] add jsonnet support to analyse blocks

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
docs/sources/tempo/getting-started/instrumentation.md

Corrects spelling from Jaegar to Jaeger. 
Recreates https://github.com/grafana/tempo/pull/3940
**Checklist**

[DOC] Correct Jaeger spelling mistake

---

CHANGELOG.md
modules/generator/storage/config_util.go
modules/generator/storage/config_util_test.go

This PR changes the header precedence in Generator remote write, so that statically configured X-Scope-OrgID is honored. This change is necessary to unlock a use case that is currently not possible.  Will do my best to explain.  The desired behavior is to have a setup like this:
* 2 remote write targets with different headers and auth:
* remote write target A:
* The usual setup:
* dynamically set X-Scope-OrgID header == tenant ID
* remote write target B:
* statically configured X-Scope-OrgID (we want to target a fixed metrics tenant)
* Dynamically injected metrics label with the tenant ID like `{__id__="<tenantid>"}`
Target B doesn't work currently because the logic gives highest precedence to dynamically set X-Scope-OrgID.  The statically configured header is …

Generator remote write update handling of X-Scope-OrgID

---

operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin/dashboards/tempo-operational.json

Here we borrow a technique from the mimir operational dashboard to enable native histograms with a cheap toggle.  This PR adds the queries necessary for poll and retention duration. 
**Checklist**

Begin adding native histograms to operational dashboard

---

docs/sources/tempo/configuration/parquet.md
docs/sources/tempo/operations/tempo_cli.md

Updating the doc to note that analyse blocks CLI subcommand supports vParquet4, per https://github.com/grafana/tempo/pull/3868
Fixes #4036 
**Checklist**

[DOC] Add vParquet4 to analyse blocks CLI and update parquet doc

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/_index.md
docs/sources/tempo/traceql/_index.md

Adds or updates documentation for the 2.6 release. 
* Adds doc for `compaction_disabled`,  https://github.com/grafana/tempo/pull/3965
* Updates TraceQL for intrinsics, events, and links
* Adds more info to native historgram doc
Fixes https://github.com/grafana/tempo-squad/issues/414
**Checklist**

[DOC] TraceQL, metrics-gen, and overrides doc updates for 2.6

---

docs/sources/tempo/_index.md

https://grafana.com/docs/writers-toolkit/write/shortcodes/#center-an-image-example
Also removes rogue image at the end of the page.
**Checklist**

Use canonical centering an image example

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/_index.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md

Backport 3e262042cd4efa270ef4a33b2c9141e54f2b6526 from #4041
---
Adds or updates documentation for the 2.6 release. 
* Adds doc for `compaction_disabled`,  https://github.com/grafana/tempo/pull/3965
* Updates TraceQL for intrinsics, events, and links
* Adds more info to native historgram doc
Fixes https://github.com/grafana/tempo-squad/issues/414
**Checklist**

[release-v2.6] [DOC] TraceQL, metrics-gen, and overrides doc updates for 2.6

---

.gitignore

Remove tempo-query binary from source and add `cmd/tempo-query/tempo-query` to `.gitignore`.
Originally introduced in: 0448492dc317f3e2a5fc9e071639552abf40dddc
I assume we can skip the changelog?

tempo-query: remove binary from source

---

cmd/tempo-cli/cmd-analyse-block.go

Invert the logic to know which columns are currently dedicated.  Includes resource attributes in dedicated column tracking.
Related #4012
**Checklist**

Fix cli analyse block dedicated text output

---

CHANGELOG.md
modules/frontend/pipeline/collector_grpc.go
modules/frontend/search_handlers_test.go

This change impacts all streaming endpoints. Instead of returning a complete final message this has the query frontend send only a final diff. For searches with very large limits and span limits we were seeing enormous final messages returned to Grafana which [tripped a limit in their websocket implementation](https://github.com/grafana/grafana/pull/93033).
The initial intention of sending the final message was to make sure the frontend got a complete response in case one of the intermediate messages was lost due to a bug. This seems to be unlikely and the rare case it does happen is not worth the cost of always sending the full response all the time.
cc @adrapereira 
**Checklist**

GRPC Streaming: Send diff instead of full response

---

CHANGELOG.md
docs/sources/tempo/traceql/metrics-queries.md
pkg/traceql/ast.go
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go
pkg/traceql/enum_aggregates.go
pkg/traceql/expr.y
pkg/traceql/expr.y.go
pkg/traceql/lexer.go
pkg/traceql/parse_test.go

It implements the max_over_time aggregation function
**Checklist**

feat: TraceQL metrics: max over time

---

CHANGELOG.md
cmd/tempo/app/config.go
cmd/tempo/app/config_test.go
modules/frontend/traceid_sharder.go

concurrent shards grater then query shards should not be allowed because it would create more goroutines then the jobs to send these jobs to queriers.
if that happens, set concurrent_shards=query_shards and log a warning 
**Checklist**

TraceByID: don't allow concurrent_shards greater than query_shards

---

CHANGELOG.md
modules/querier/external/client.go
pkg/hedgedmetrics/metrics.go
tempodb/backend/instrumentation/hedged_requests.go

Replace hedged requests round trips total with a counter
Fixes #4060
**Checklist**

replace hedged requests roundtrips total with counter

---

example/docker-compose/local/tempo.yaml

Fixes mamcache host path issue for local tempo example which was introduced in https://github.com/grafana/tempo/pull/4032
**Checklist**

Fix memcache host for local tempo setup

---

docs/sources/tempo/configuration/_index.md

This PR fixes a typo in the docs. `TSL` => `TLS`.

Fix Small Typo in Documentation

---

.drone/drone.jsonnet
.drone/drone.yml

auto merge pr in drone

---

.gitignore
CHANGELOG.md
modules/ingester/instance_search.go
modules/ingester/instance_search_test.go
modules/ingester/local_block.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/vparquet4/block_search_tags.go
tempodb/encoding/vparquet4/wal_block.go

cache the response for TagValuesV2 requests alongside the local blocks on the ingesters, this should speedup the autocomplete queries hitting ingesters.
In our dev env, it shows sizeable difference in p90, p95 of latency and throughout for tags that has values with high cardinality.
also updated instrumentation to make the ingester search spans more closer to the code.
**Checklist**

Add disk caching in ingester SearchTagValuesV2 for completed blocks

---

CHANGELOG.md
modules/generator/generator.go

Currently on shutdown the generators set a flag to stop receiving traffic and then remove themselves from the ring. This causes distributors to continue to send to a generator that is refusing traffic for a few seconds.
This PR:
1) Correctly drops out of the ring first and then sets the flag to stop ingestion
2) Adds a sleep in between these steps. Tempo by default uses memberlist for ring propagation which often requires a few seconds to propagate state from one component to another. Without this sleep the change was ineffective. I do not like the sleep but I'm not sure there's a better solution.
To the left of the red line is what a generator rollout looks like today. To the right is what this change looks like. Note that there are still a few drops but it's …

Generators: Drop out of the ring before stopping ingestion

---

pkg/traceql/ast_execute.go
pkg/traceql/enum_statics.go
tempodb/encoding/vparquet4/block_traceql.go

Some micro-optimizations to improve traceql engine attribute checks. Search bottleneck is usually in the storage layer, but some complex queries, particularly ones with unscoped attributes, are bottlenecked in the engine. 
The **memory** improvement primarily comes from fixing the for loop in span.AttributeFor.
This loop allocs because the address of the loop var must escape:
```go
for _, st := range attrs {
if st.a == a {
return &st.s
}
}
```
But this version doesn't because we take the address of the existing slice entry, which was the intention.
```go
for i := range attrs {
if attrs[i].a == a {
return &attrs[i].s
}
}
```
The **speed** improvement is from also short-circuiting binary operations more like a real compiler if statement does.  Two cases can exit early …

TraceQL performance improvements

---

CHANGELOG.md
modules/frontend/combiner/metrics_query_range.go
modules/frontend/combiner/search.go
modules/frontend/combiner/search_tag_values.go
modules/frontend/combiner/search_tags.go

This pr brings back the `application-json ` content-type header.
Previously the common combiner harcoded the header to application json. Now we need to initialize the combiner with default values
Fixes #4121
**Checklist**

fix: bring back content-type header

---

CHANGELOG.md
cmd/tempo-cli/cmd-query-trace-id.go
cmd/tempo-cli/main.go
cmd/tempo-cli/shared.go
docs/sources/tempo/operations/tempo_cli.md
pkg/httpclient/client.go

Use `/api/v2/traces` by default to query trace by id and get partial traces for bigger traces, also add `--v1` flag in `tempo-cli query api trace-id` command to query `/api/traces` endpoint.
see https://github.com/grafana/tempo/pull/3941 for more details on  `/api/v2/traces`.
example usage: `tempo-cli query api trace-id http://tempo:3200 fd9b20c52c74f67de6a69279bfba3936 --v1 > trace.json`
there is a change in default behaviour and you need to use `--v1` if you are on a older version of tempo that doesn't support `/api/v2/traces` or want to use `/api/traces`, because of that, this change is marked as **BREAKING CHANGE**
---
This PR also includes a small change in the way we Marshal the trace.
`encoding/json` package can't handle +Inf, -Inf, NaN values and will fail …

tempo-cli: add support for /api/v2/traces endpoint

---

cmd/tempo-cli/cmd-analyse-block.go
cmd/tempo-cli/cmd-analyse-blocks.go

**What this PR does**: Add `print-full-summary` flag to allow user to omit the summary and `simple-summary` to only print only the names of the top attributes. 
**Checklist**

[tempo-cli] Add flags to print simple summary vs full summary

---

.github/workflows/add-to-docs-project.yml
docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/setup/upgrade.md

Clarifies the vParquet4 requirements in the release notes and upgrade docs. 
Redo of https://github.com/grafana/tempo/pull/4107
**Checklist**

[DOC] Clarify Parquet requirements in 2.6

---

CHANGELOG.md
integration/e2e/api_test.go
modules/frontend/combiner/common.go
modules/frontend/combiner/search_test.go
modules/frontend/search_handlers.go
modules/frontend/slos.go
modules/frontend/slos_test.go

Correctly handle 400 Bad Request and 404 Not Found in gRPC streaming.
Status codes in gRPC are changed to return `InvalidArgument` for 400 and `NotFound` for 404. Other non-special HTTP status codes are `Unknown`.
This also allows fixing how 400 responses are counted towards SLO calculations.
**Checklist**

Correctly handle 400 Bad Request and 404 Not Found in gRPC streaming

---

docs/sources/tempo/configuration/_index.md

It updates the documentation to reflect the real default value for the grpc server message size, which is forced to 16MB here: https://github.com/grafana/tempo/blob/109f8d0b2bf64d83b97242af9d793425652eaa2a/cmd/tempo/app/config.go#L90
**Checklist**

[docs] use proper default value for grpc server message size

---

docs/sources/tempo/troubleshooting/_index.md
docs/sources/tempo/troubleshooting/alloy.md

Adds information about how to view metrics from Alloy and how to check them in Grafana Cloud using Explore 
Fixes https://grafana.com/docs/alloy/latest/troubleshoot/controller_metrics/
**Checklist**

[DOC] Update metrics for Alloy troubleshooting doc

---

pkg/model/trace/combine.go
pkg/model/trace/combine_test.go

Wrap mutex around combiner now that results are processed in parallel

---

cmd/tempo/app/overrides_validation.go
go.mod
modules/distributor/distributor_test.go
modules/distributor/forwarder/manager_test.go
modules/generator/instance.go
modules/overrides/overrides_tenant_status_http.go
modules/overrides/overrides_tenants_http.go
modules/overrides/runtime_config_overrides.go
modules/overrides/user_configurable_overrides.go

use slices and map from the go stdlib instead of golang.org/x/exp
`nil`
**Checklist**

use slices and map from the go stdlib instead of golang.org/x/exp

---

CHANGELOG.md
modules/generator/registry/histogram.go
modules/generator/registry/histogram_test.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/registry_test.go

Pushes a 0 to classic histogram's counter when the series is new to allow Prometheus to start from a non-null value.
**Checklist**

Init histogram counters with 0

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/metrics-generator/_index.md
docs/sources/tempo/metrics-generator/service_graphs/_index.md
docs/sources/tempo/metrics-generator/span_metrics.md

Addresses a customer issue that it wasn't clear that you can enable Metrics Generator for Grafana Cloud in Application Observability. 
Original PR update: https://github.com/grafana/tempo/pull/4141
This PR: 
* Cleans up the copied-from-cloud admonition notes
* Removes references to Cloud metrics-generator vs OSS in the Tempo docs
* Instead, points readers to the Grafana Cloud Traces documentation for metrics-generator
Fixes https://github.com/grafana/support-escalations/issues/12501
**Checklist**

[DOC] Update statement for metrics-generator for Cloud

---

CHANGELOG.md
cmd/tempo-query/main.go
cmd/tempo-query/tempo/config.go
cmd/tempo-query/tempo/plugin.go
go.mod

Improves performance for tempo query for searching traces. There is a new configuration option to submit multiple gettracebyid requests from a search. 
Uses can scale up queriers and get faster queries. A single querier can process 20 queries https://grafana.com/docs/tempo/latest/operations/backend_search/#querier-and-query-frontend-configuration 
Tested with TempoStack on OCP. Image `pavolloffay/tempo-query:concurrency-main-15`
**Checklist**

Tempo-query: improve performance of FindTraces

---

docs/sources/tempo/configuration/hosted-storage/s3.md

Relates to https://github.com/grafana/tempo/issues/3899.
Add EKS Pod Identity as supported.
**Checklist**

docs: Add EKS Pod Identity as supported

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

Proposal to make @javiermolinar a maintainer. An approving review is a vote in favor.
[Tempo Updates](https://github.com/grafana/tempo/pulls/javiermolinar)
[Tempo Reviews](https://github.com/grafana/tempo/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Ajaviermolinar)
@grafana/tempo

Javi Maintainer

---

CHANGELOG.md
pkg/traceql/ast.go
pkg/traceql/ast_execute.go
pkg/traceql/util.go

This PR builds on #4114 which introduced short-circuiting boolean expressions like true || false.  Now we are going a step further and dynamically profiling and reordering statements at runtime to be choose the fastest path first.   Consider a statement like `trueSlow || trueFast`.   It's better to put `trueFast` first because it will allow us to return faster, and skip processing the `trueSlow` expression.  
This PR is the result of digging even more into the `particularly tough query run internally` mentioned in #4114 .
The way it works is by not short-circuiting for the first 1000 executions, and instead measuring the runtime and usefulness of each branch.  Then it checks whether the right-hand-side is the better choice and then flips the expression.  `trueSlow …

TraceQL performance improvement: dynamic reordering of binop branches

---

.gitignore
CHANGELOG.md
modules/frontend/combiner/search_tag_values.go
modules/frontend/combiner/search_tags.go
modules/ingester/instance_search.go
modules/querier/querier.go
pkg/collector/distinct_string_collector.go
pkg/collector/distinct_string_collector_test.go
pkg/collector/distinct_value_collector.go
pkg/collector/distinct_value_collector_test.go
pkg/collector/scoped_distinct_string.go
pkg/collector/scoped_distinct_string_test.go
tempodb/tempodb_search_test.go

This PR makes the DistinctString and ScopedDistinctString collectors go faster by not tracking diff in cases where we don't use the diff
We made similar performance improvements in DistinctValue collector in https://github.com/grafana/tempo/pull/4104, and now making the similar performance improvements in the DistinctString and ScopedDistinctString collectors in this PR.
how fast?
- DistinctString collector is around 54.93% faster with 43% improvements in mem. usage.
- ScopedDistinctString collector is from 27% to 49% faster with 45% improvements in mem. usage.
**Benchmarks:**
<details>
<summary>DistinctString collector</summary>
```text
goos: darwin
goarch: amd64
pkg: github.com/grafana/tempo/pkg/collector
cpu: VirtualApple @ 2.50GHz
│ …
```

Speedup DistinctString and ScopedDistinctString collectors

---

CHANGELOG.md
cmd/tempo-query/main.go
cmd/tempo-query/tempo/config.go

This PR extends tempo-query with the possibility to configure tls for server and client individually.
cc @pavolloffay 
**Checklist**

tempo-query: separate tls settings for server and client

---

cmd/tempo-vulture/mocks.go
pkg/httpclient/client.go

Extends `pkg/httpclient` adding a new function `SearchTraceQLWithRangeAndLimit`, and the ability to set custom headers to be sent along with requests.
None.
**Checklist**

Extend httpclient with new method + custom headers

---

CHANGELOG.md
cmd/tempo-query/main.go
cmd/tempo-query/tempo/config.go

Backport a2f70c975850ac4ad31c8d92a11f85bf74a945e4 from #4177
---
This PR extends tempo-query with the possibility to configure tls for server and client individually.
cc @pavolloffay 
**Checklist**

[release-v2.6] tempo-query: separate tls settings for server and client

---

CHANGELOG.md
modules/frontend/combiner/metrics_query_range.go
modules/frontend/combiner/search.go
modules/frontend/combiner/search_tag_values.go
modules/frontend/combiner/search_tags.go

Backport 6afedd95e5b94d7f4dcac0175116d305ce4c619e from #4123
---
This pr brings back the `application-json ` content-type header.
Previously the common combiner harcoded the header to application json. Now we need to initialize the combiner with default values
Fixes #4121
**Checklist**

[release-v2.6] fix: bring back content-type header

---

CHANGELOG.md
pkg/parquetquery/predicates.gen.go
pkg/parquetquerygen/predicates.go

**What this PR does**: Remove earlier comment to add range condition to byte predicates. 
```
│ before-onlyid.txt │           after-onlyid.txt           │
│      sec/op       │    sec/op     vs base                │
BackendBlockTraceQL/trace:id_=_`xxx`-16        17.421m ± 3%   9.895m ± 13%  -43.20% (p=0.000 n=20)
│ before-onlyid.txt │           after-onlyid.txt            │
│        B/s        │      B/s       vs base                │
BackendBlockTraceQL/trace:id_=_`xxx`-16        540.3Mi ± 3%   837.7Mi ± 11%  +55.03% (p=0.000 n=20)
│ before-onlyid.txt │          after-onlyid.txt          │
│     MB_io/op      │  MB_io/op   vs base                │
BackendBlockTraceQL/trace:id_=_`xxx`-16          9.870 ± 0%   8.691 ± 0%  -11.95% (p=0.000 n=20)
```
Fixes …

Add range condition to bytes predicates

---

docs/sources/tempo/traceql/_index.md
example/docker-compose/local/docker-compose.yaml
example/docker-compose/local/readme.md
example/docker-compose/multi-tenant/docker-compose.yaml
example/docker-compose/multi-tenant/readme.md
example/docker-compose/otel-collector-multitenant/docker-compose.yaml
example/docker-compose/shared/grafana-datasources.yaml

Removes the traceQLStreaming feature toggle, per https://github.com/grafana/grafana/issues/94528
Also, updates the version of Grafana to 11.2 in some of the docker-compose files that reference the feature toggle. 
Part of https://github.com/grafana/grafana/issues/94528
**Checklist**

[DOC] Remove traceQLStreaming feature flag

---

.drone/drone.jsonnet
.drone/drone.yml

use the proper path to get tempo secrets
**Checklist**

drone: use the proper path to get tempo secrets

---

CHANGELOG.md
integration/e2e/limits_test.go
modules/frontend/combiner/trace_by_id.go
modules/frontend/combiner/trace_by_id_test.go
modules/frontend/handler.go
modules/frontend/pipeline/sync_handler_adjust_response_code.go
modules/querier/http.go

Here we make an adjustment to the return value at the querier and query-frontend for the case where a trace is larger than the max configured size.  Previously this was reported as a 500 status code and has now been changed to a 422.  This will allow these conditions to be excluded from SLO failures, which is more appropriate since this is based on a configured max trace size.
**Checklist**

Avoid returning 500 for TRACE_TOO_LARGE

---

docs/sources/tempo/api_docs/pushing-spans-with-http.md

Corrects a typo in date calculation command in the push HTTP doc. There was an extra 8 that needed to be removed. 
Fixes https://github.com/grafana/support-escalations/issues/12401
**Checklist**

[DOC] Fix wrong date command in push HTTP API doc

---

CHANGELOG.md

Not sure what happened but it looks like the max_over_time entry got overwritten or had the wrong PR link?
Related PRs:
https://github.com/grafana/tempo/pull/4065
https://github.com/grafana/tempo/pull/3975

Update CHANGELOG.md to add max_over_time

---

CHANGELOG.md
tempodb/backend/compression.go
tempodb/backend/tenantindex.go
tempodb/backend/tenantindex_benchmark_test.go

Here we pool the `zstd` encoders and decoders for better performance when handling the tenant index.
**Checklist**

Pool zstd encoding/decoding

---

tempodb/compactor.go
tempodb/encoding/vparquet2/compactor.go
tempodb/encoding/vparquet3/compactor.go
tempodb/encoding/vparquet4/compactor.go

Clean up compactor logging after proto change
**Checklist**

Clean up compactor logging after proto change

---

docs/sources/tempo/api_docs/metrics-summary.md

Adds a deprecation note for metrics summary API. Aggregate by is already marked as deprecated in Grafana Cloud.
Part of https://github.com/grafana/website/pull/22148 and https://github.com/grafana/tempo-squad/issues/438
**Checklist**

[DOC] Add deprecation for metrics summary

---

CODEOWNERS
GOVERNANCE.md
MAINTAINERS.md

This PR creates the definition of Maintainer Emeritus for the Tempo projects and moves two former, inactive maintainers into this category.
Thank you for your contributions @annanay25 and @dgzlopes!

Create Maintainer Emeritus title

---

.gitignore

drone is failing with:
```
/go/bin/goreleaser release --rm-dist 
Flag --rm-dist has been deprecated, please use --clean instead
• starting release...
• loading                                          path=.goreleaser.yml
• DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
• loading environment variables
• using token from  $GITHUB_TOKEN 
• getting and validating git state
• git state                                      commit=c4fad424e0f0b7e32187edb88b29a59b38198478 branch=HEAD current_tag=v2.6.1 previous_tag=v2.6.0 dirty=true
⨯ release failed after 0s                  error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
?? gh-token.txt
```

Ignore gh-token.txt

---

docs/sources/tempo/operations/traceql-metrics.md

Added the breaking changes content to the local-blocks configuration section in the TraceQL metrics config doc. 
**Checklist**

[DOC] Update local-block processor config for 2.6 changes

---

docs/sources/tempo/traceql/_index.md

Adds a sum() example to TraceQL docs
Fixes https://github.com/grafana/support-escalations/issues/8031
**Checklist**

Add sum() example to TraceQL docs

---

docs/sources/tempo/operations/traceql-metrics.md
docs/sources/tempo/traceql/metrics-queries.md

Add docs for flush_to_storage for the TraceQL metrics configuration.  
Part of https://github.com/grafana/tempo/issues/4064
**Checklist**

Add flush_to_storage config doc

---

CHANGELOG.md
modules/generator/registry/config.go
modules/generator/registry/counter.go
modules/generator/registry/counter_test.go
modules/generator/registry/gauge_test.go
modules/generator/registry/histogram.go
modules/generator/registry/histogram_test.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/registry.go

It fixes an issue with adaptive metrics: when a series is new the init sample ends in the same aggregation bucket as the span one, and the later one is downsampled. The fix consists of backdating the initial one to the end of the previous minute:
previously:
(t-1ms, 0)
(t, 1)
current:
(t-1m, 0)
(t, 1)
**Checklist**

fix: counter samples being downsampled when series is new

---

CHANGELOG.md
docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/traceql/metrics-queries.md
integration/e2e/config-query-range.yaml
modules/frontend/config.go
modules/frontend/frontend.go
modules/frontend/metrics_query_range_sharder.go

Currently, we are computing the exemplars for `query_range` and ` instant queries`. Since exemplars are not supported for instant queries (same as Prometheus) we can save that computing time.
It also fix a bug where the `exemplars` query param was not being honored 
**Checklist**

fix: skip exemplars for instant queries

---

CHANGELOG.md
cmd/tempo-cli/cmd-gen-bloom.go
cmd/tempo-cli/cmd-gen-index.go
cmd/tempo-cli/cmd-migrate-overrides-config.go
cmd/tempo/Dockerfile
integration/e2e/ca/ca.go
integration/util/util.go
modules/generator/generator.go
modules/generator/generator_test.go
modules/generator/storage/instance.go
modules/overrides/runtime_config_overrides_test.go
modules/overrides/user_configurable_overrides_test.go
modules/overrides/userconfigurable/client/client.go
tempodb/backend/local/local.go
tempodb/encoding/v2/wal_block.go
tempodb/encoding/vparquet2/schema_test.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/schema_test.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/schema_test.go
tempodb/encoding/vparquet4/wal_block.go
tempodb/wal/wal.go
tempodb/wal/wal_test.go

Here we adjust adjust permissions of files and directories which are managed by the tempo process at runtime.  Additionally, this changes the docker image permissions of `/var/tempo` to remove group and world access entirely (`0700`).
**Checklist**

Tighten file permissions

---

CHANGELOG.md
modules/generator/processor/localblocks/metrics.go
modules/generator/processor/localblocks/processor.go

Institutes a very generous limit of 100 on failed flush attempts as well as a metric to help track this. This prevents constant retries on blocks that cannot be flushed due to corruption.
**Checklist**

Metrics Generator: Max limit on number of failed flushes

---

modules/generator/generator_test.go
modules/generator/registry/counter.go
modules/generator/registry/gauge.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/registry.go

Improve performance in the native histograms implementations.  This is following in the footsteps of #4232.
**Checklist**

Native histogram performance

---

CHANGELOG.md
integration/e2e/api_test.go
modules/frontend/combiner/common.go
modules/frontend/combiner/trace_by_id.go
modules/frontend/frontend.go
modules/frontend/metrics_query_range_handler.go
modules/frontend/metrics_query_range_sharder.go
modules/frontend/pipeline/pipeline.go
modules/frontend/search_handlers.go
modules/frontend/search_sharder.go
modules/frontend/search_sharder_test.go
modules/frontend/tag_handlers.go
modules/frontend/tag_sharder.go
modules/frontend/tag_sharder_test.go
modules/frontend/traceid_sharder.go
modules/frontend/traceid_sharder_test.go
pkg/api/query_builder.go

Some small perf improvements and cleanup noticed while working on the [ordered results PR](https://github.com/grafana/tempo/pull/4238).
- Use our `ReadAllWithEstimate()` instead of `io.ReadAll()`. 
- Standardized the way we clone child requests and dropped unnecessary headers.
- Standardized our response logging. We were using both "results" and "response" so i picked one.
- Pre-alloc 100 bytes on the query builder slice
**Checklist**

Query-Frontend: Perf improvements

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go
modules/ingester/flush.go
modules/ingester/ingester_test.go
modules/ingester/instance.go
modules/ingester/instance_search.go
modules/ingester/instance_search_test.go
modules/ingester/instance_test.go
pkg/usagestats/reporter.go
tempodb/blocklist/poller.go

I set out to clean up our traces and remove all orphaned spans, but there were fewer than expected. Our query path is entirely connected.
- Connected some local block operations in the generator.
- Similar fix in the ingester and also updated log lines to use "tenant" over "userID" which is preferred.
- Gave context to some orphanned s3.Reads in usage stats
- Connected some orphanned spans in our polling cycle
There are still two orphanned spans I can't figure out how to fix related to ring management. They create single span "CAS" and "GET" traces. I'll let the next person figure those out :).
https://github.com/grafana/dskit/blob/a4a4dca2b2e64cc70a1a719c5f3dbf7a5c81adba/kv/metrics.go#L97
https://github.com/grafana/dskit/blob/a4a4dca2b2e64cc70a1a719c5f3dbf7a5c81adba …

Traces Cleanup

---

modules/generator/registry/counter.go
modules/generator/registry/counter_test.go
modules/generator/registry/gauge.go
modules/generator/registry/gauge_test.go
modules/generator/registry/histogram.go
modules/generator/registry/histogram_test.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/registry.go
modules/generator/registry/test.go

Here we make some performance improvements to the `counter` and `gauge` in the registry.  This is a follow-on to #4232 and #4244.  Additionally, we modify the `metric` interface to skip passing of the `externalLabels` now that each implementation has been updated to take those labels at time of `new`.
**Checklist**

Registry performance

---

pkg/cache/redis_client.go

Here we modify a utility method in the redis client which is used to retrieve the bytes of the array backing a string.  New `unsafe` methods exist to support this use case, which is considerably more readable.
**Checklist**

Improve the readability of redis_client util method

---

CHANGELOG.md
cmd/tempo-cli/main.go
docs/sources/tempo/operations/tempo_cli.md

This PR fixes the unused S3Pass and S3User parameters in the CLI options by implementing them in the code. Additionally, it introduces a skip verify option to bypass SSL certificate validation when connecting to the S3 backend, enhancing flexibility for self-signed or internal certificates.
**Checklist**

Fix tempo cli arguments

---

.github/dependabot.yml

groups the dependabot update PRs to make them more useful and not break things.
also bump the max open PRs to 10 so we can have 10 open PRs from dependabot.
**Checklist**

dependabot: group dependencies and increase PR limit to 10

---

docs/sources/tempo/traceql/_index.md

Update the example filter to match the actual intrinsic name.
This fixes a reference to `trace:rootServiceName` in the query intrinsics table. (`trace:rootServiceName` produces an error when you try to use it.)
**Checklist**

Docs: fix trace:rootService example code

---

modules/frontend/frontend.go

https://github.com/grafana/tempo/pull/4242 broke compatibility with non-vanilla distributions of Tempo that rely on headers in the read path.
This PR respects headers in queries and forwards them to queriers as before.
**Checklist**

Respect passed headers in read path requests

---

CHANGELOG.md
modules/generator/processor/localblocks/processor_test.go
modules/ingester/ingester_test.go
modules/ingester/instance.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/v2/backend_block.go
tempodb/encoding/v2/wal_block.go
tempodb/encoding/vparquet2/block.go
tempodb/encoding/vparquet2/wal_block.go
tempodb/encoding/vparquet3/block.go
tempodb/encoding/vparquet3/wal_block.go
tempodb/encoding/vparquet4/block.go
tempodb/encoding/vparquet4/block_test.go
tempodb/encoding/vparquet4/wal_block.go

Adds a `Validate()` method to backend blocks and uses it in ingester startup to do basic confirmation of block health before reloading them. This prevents corrupt blocks from being loaded and eventually pushed to object storage.
Fixes #4166 as near as we can tell. At least it covers the instance seen internally.
**Checklist**

Ingester: Validate completed blocks

---

cmd/tempo-cli/cmd-rewrite-blocks.go
tempodb/compactor.go
tempodb/encoding/common/interfaces.go
tempodb/encoding/vparquet4/combiner.go
tempodb/encoding/vparquet4/combiner_test.go
tempodb/encoding/vparquet4/compactor.go

This PR adds telemetry to help the team understand the impact of compaction of RF1 data. It is likely these are temporary changes to help inform an improvement to prevent duplicate RF1 data. Due to this there is no changelog. Two things were added:
1) A log message when a compaction job completes if the compactor no longer owns that job
2) A metric to count deduped spans per replication factor. Presumably this should show 0 at RF1
Note that I changed the meaning of the returned spans count from the combiner. Nothing was using it so this seemed acceptable.

[Compaction] Add signals for duplicate rf1 data

---

README.md

This PR introduces a feature enhancement that integrates the Explore Traces app into the Tempo documentation to guide users on visualizing tracing data through a user-friendly, queryless interface.
**Checklist**

docs: Update readme with explore traces info

---

cmd/tempo/app/modules.go
integration/e2e/ingest/ingest_storage_test.go
integration/e2e/ingest/kafka.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/config.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/distributor/distributor_test.go
modules/ingester/instance_search_test.go
pkg/ingest/blockbuilder/consumer.go
pkg/ingest/encoding.go
pkg/ingest/encoding_test.go
pkg/ingest/util.go
pkg/util/test/logger.go
pkg/util/test/req.go

Added basic unit test for the block-builder module.

Add unit test for block-builder

---

operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet

Adjust jsonnet mixin alert to require failed compactions for a longer period of time to alert. Currently, if object storage has a short blip we will see this alert hit. However, this alert is really not concerning unless it continues for a significant period of time. Hence increasing the 'for' value to 1h.

Increase length of time compactions have to fail

---

CHANGELOG.md
cmd/tempo-serverless/readme.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/operations/backend_search.md
docs/sources/tempo/operations/serverless_aws.md
docs/sources/tempo/operations/serverless_gcp.md

we are deprecating serverless, so mark it as deprecated in the tempo docs
we are discussing it in https://github.com/grafana/tempo/issues/4014
**Checklist**

docs: mark serverless as deprecated

---

docs/sources/tempo/operations/traceql-metrics.md

This removes duplicates examples from the [Configure TraceQL](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/) metrics page.
Fixes #4294
**Checklist**

docs: Remove duplicated examples

---

CHANGELOG.md
cmd/tempo-cli/cmd-rewrite-blocks.go
cmd/tempo-cli/cmd-rewrite-blocks_test.go
cmd/tempo-cli/main.go
docs/sources/tempo/operations/tempo_cli.md

This PR introduces support for dropping multiple traces from a single block in tempo-cli. The new command syntax allows specifying multiple trace IDs separated by commas:
```console
tempo-cli rewrite-blocks drop-traces --backend=local --bucket=./cmd/tempo-cli/test-data --drop-trace single-tenant 04d5f549746c96e4f3daed6202571db2,0fb764d54d68a10734268771fb3e00f0
```
Fixes #4246
**Checklist**

tempo-cli: support dropping multiple traces in a single operation

---

docs/sources/tempo/api_docs/metrics-summary.md

Backport d730dfc91f3ccb57cca7b9637687a18392b85305 from #4316
---
Adds additional details to the metrics-summary.md page from [this comment](https://github.com/grafana/tempo/pull/4193#issuecomment-2462441907).
**Checklist**

[release-v2.6] [DOC] Add clarification for metrics summary and traceQL metrics

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go
pkg/ingest/encoding.go

Introduces deterministic IDs for partition section cycles and added a test to verify that it works. IDs are generated based on the section's end ts and the number of blocks produced in that section.

[rhythm] Deterministically build blocks for partition sections

---

docs/sources/tempo/configuration/network/tls.md

Here we include some information about how to get a working TLS configuration using the `tempo-distributed` Helm chart.
**Checklist**

Add doc about configuring TLS with Helm

---

cmd/tempo/app/modules.go
modules/generator/config.go
modules/generator/generator.go
modules/generator/generator_kafka.go
modules/generator/generator_test.go
modules/generator/instance.go
modules/generator/processor/localblocks/processor.go

If enabled, reads from kafka every 2 seconds.  The data is sent to span metrics and service graphs, but not local blocks, to ensure that it doesn't get flushed to storage, which is now the task of the block builder.   
TODO - Maintain a separate local blocks processor to serve queries over recent data (that doesn't flush).  
**Checklist**

[Rhythm] Metrics generator read from kafka first pass

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/config.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go

This PR contains multiple fixes in the block-builder, mostly around thread-safety.

[rhythm] Multiple fixes in block-builder

---

CHANGELOG.md
pkg/traceql/ast.go
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_average.go

Fixes several issues with exemplars that were found when testing: https://github.com/grafana/grafana/pull/96859
1. quantile_over_time(duration) was returning exemplars in nanos instead of float seconds like the samples. This is fixed as well as for any other function like avg_over_time(duration).
2. Finishes the TODO for the other functions that were capturing placeholder exemplars but without values (always zero):
- rate()/count_over_time() exemplars are attached to the final sample value. See screenshot below
- min/max_over_time() use the value from the span
3. avg_over_time was accidentally dropping exemplars because of struct address issue.
4. Actually randomly samples a span.  Maybe it's my test dataset but the current approach of Spans[0] wasn't working well. …

Exemplar fixes

---

CHANGELOG.md
integration/e2e/limits_test.go
modules/generator/processor/localblocks/livetraces.go
modules/generator/processor/localblocks/livetraces_test.go
modules/generator/processor/localblocks/metrics.go
modules/generator/processor/localblocks/processor.go
modules/ingester/instance.go
modules/ingester/instance_search_test.go
modules/ingester/instance_test.go
modules/ingester/trace.go
modules/ingester/trace_test.go
pkg/tracesizes/traceSizes.go

Moves the livetraces struct in the generator into shared location for both the ingester and metrics generator to use. This will cause the ingester to more aggressively (and correctly) refuse live traces.
Other changes:
- Fixed a bug in the live traces struct that was double counting the first batch
- Added a metric to both generator and ingester to count total bytes consumed
- Removed unnecessary and confusing traceCount atomic
**Checklist**

Ingester/Generator Live trace cleanup

---

tools/go.mod

I believe this is a chicken-or-egg problem where we have to bump tools first, so that it will tag the new tempo-ci-tools image, that we can use to bump Tempo.
https://github.com/grafana/tempo/pull/4380
**Checklist**

Bump tools to 1.23.3

---

.github/workflows/dependabot_serverless_gomod.yml
CHANGELOG.md
build/tools.mk
cmd/tempo-serverless/cloud-run/go.mod
cmd/tempo-serverless/lambda/go.mod
go.mod

Bump golang to resolve occasional compactor panics for `too many concurrent timer firings`.  The fix is released in 1.23.3: https://github.com/golang/go/issues/69882
It's possible that we are using timers sub-optimally, but I believe the the timer change in the framework was unintentional, and not worth digging into at this time.
**Checklist**

Bump to 1.23.3

---

CHANGELOG.md
example/docker-compose/local/tempo.yaml
modules/frontend/combiner/common.go
modules/frontend/combiner/common_test.go
modules/frontend/handler.go
modules/frontend/pipeline/collector_grpc.go
modules/frontend/pipeline/collector_http.go
modules/frontend/search_handlers_test.go
modules/frontend/slos.go
modules/frontend/slos_test.go
modules/frontend/tag_handlers_test.go
modules/querier/querier_query_range.go
pkg/util/errors.go

We count all request cancellations outside SLO, but that's not right because request cancellations are done by users and should fall within SLO.
Request cancellations are now exposed under `result` label in `tempo_query_frontend_queries_total` and `tempo_query_frontend_queries_within_slo_total` with `completed` or `canceled` values to differentiate between completed and canceled requests.
operators can filter `tempo_query_frontend_queries_within_slo_total` with `result=completed` to get the old behaviour of the metric where cancellations where excluded from the  metric.
with the result label, we also expose the information about the cancelled requests, and you can filter on `result=canceled` to see cancelled requests.
I also added a span and span events in the http …

slo: include all request cancellations within SLO

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/frontend/config.go
modules/frontend/search_sharder.go
modules/frontend/search_sharder_test.go

Add maximum spans per span set.
Fixes #4275
**Checklist**

Add maximum spans per span set

---

cmd/tempo/app/modules.go
modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/config.go
modules/generator/config.go
modules/generator/generator_kafka.go
pkg/ingest/config.go
pkg/ingest/writer_client.go
vendor/github.com/twmb/franz-go/pkg/sasl/plain/plain.go
vendor/modules.txt

This PR contains a couple of changes to simplify operations
* Adds support for SASL auth in the Kafka clients
* Changes `assigned_partitions` from a slice to a map. Now, the partition config for all instances can be passed, and each instance can pick up their own via their instance ID. This is simpler operationally than passing a different config per pod.

[rhythm] Changes to simplify operations

---

.github/workflows/drone-signature-check.yml

saw this workflow run and fail in my fork, this change will limit this workflow to only run in grafana/tempo repo and skip running in forks
**Checklist**

ci: Don't run check drone signature workflow in forks

---

CHANGELOG.md
modules/ingester/instance_search.go
modules/ingester/instance_search_test.go

In case of a bad TraceQL query, disk cache for search tag values v2 endpoints would fail to set and get cache.
bug was that we returned `""` as cache key when we failed to parse the TraceQL filter query. 
Invalid filter TraceQL query is treated as empty query in the tag values v2 endpoint so follow the same semantics for disk cache.
I also added some tests for search tag values v2 to make sure we test for the invalid TraceQL query behaviour.
**Checklist**

Handle invalid TraceQL query filter in tag values v2 disk cache

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/tenant_store.go
modules/distributor/distributor.go

Adds metrics to the distributor and block-builder to measure different parameters of the new ingest path.

[rhythm] Add more metrics

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
modules/frontend/config.go
modules/frontend/frontend.go
modules/frontend/pipeline/async_query_validator_middleware.go
modules/frontend/pipeline/async_query_validator_middleware_test.go
modules/frontend/search_handlers_test.go

In order to protect tempo from massive queries, it's helpful to put a cap on the max query length.
Having a limit on the size of the query saves us from being DOSed by issuing huge queries against tempo.
Added `query_frontend.max_query_expression_size_bytes` config param for query frontends, defaults to 128 KiB.
this can be configured to a value lower of higher by setting it in query_frontend config section like:
```yaml
query_frontend:
max_query_expression_size_bytes: 10000
```
users will see it as an error like this:
Loki also limits the size of query expression to 128kb and Mimir has a configurable limit with same name (see https://github.com/grafana/mimir/pull/4604), and both were added for same reasons.  …

Add query-frontend limit for max length of query expression

---

CODEOWNERS

we missed adding @javiermolinar in `/docs/` and `/.github` overrides, in https://github.com/grafana/tempo/pull/4171. 
This means that if a PR contains changes in `/docs` or `/.github`, @javiermolinar's review is not counted as a valid review, this PR fixes that.
**Checklist**

Fix Javi in CODEOWNERS

---

CHANGELOG.md
modules/frontend/combiner/metrics_query_range.go
pkg/traceql/ast.go
pkg/traceql/engine_metrics.go

(1) Fix placeholder exemplars (NaNs) to be attached at the last step in the query-frontend. The previous location was too early and was partial job results instead of the final.
(2) Fix histogram_over_time to use placeholder exemplars. It outputs counts like count_over_time(), this means splitting out its case statement from quantile_over_time.
**Checklist**

More exemplar fixes

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go
pkg/tempopb/utils.go
pkg/traceql/ast.go
pkg/traceql/ast_test.go
pkg/traceql/engine.go
pkg/traceql/engine_metrics.go
tempodb/tempodb_metrics_test.go

Fixes issues with using unscoped attributes in metrics queries: https://github.com/grafana/tempo/issues/3806#issuecomment-2505900926
The summary is that metrics queries do a lot of work to optimize away the engine callback, relying solely on storage predicate pushdowns.  Unscoped queries like `{ .foo && .bar }` were optimizing it away when they shouldn't.  
~Unfortunately still thinking about the best fix for `{ false } | rate()`.  To the storage layer it looks identical to `{ true } | rate()`.~
Finally introduces some high-level metrics queries tests by writing test blocks with known frequencies of spans and querying them.
Fixes #3806 
**Checklist**

Fix metrics queries with unscoped attributes

---

CHANGELOG.md
modules/distributor/distributor.go
modules/distributor/distributor_test.go

Return trace id length when it is invalid.
I got the error when using k6 with a large number of traces and although I didn't manage to find the root cause,
returning the length will be helpful.
**Checklist**

distributor: return trace id length when it is invalid

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/commit_meta.go
modules/blockbuilder/commit_meta_test.go
modules/blockbuilder/config_test.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go

This PR contains multiple fixes around block-builder consumption:
(1) Block IDs were identical between tenants. Now, the tenant ID has been added as parameter to generate IDs.
(2) `lag.Commit.At` was being used as the timestamp of the last commit, when in reality is the offset of the commit. This made calculations for consuming partition sections wrong and it was always falling back to `lookback_on_no_commit`. Now that the commit's timestamp is passed in the its meta and logic has been updated to fallback only when there is no commit meta.
(3) It was possible to consume the same section multiple times because we were using the commit's timestamp, instead of the commit's section end time.
Other fixes:
(4) Added more logs and reduced the level of some very noisy ones. …

[rhythm] Multiple fixes to block-builder consumption

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Adds a section to the tempo-distributed Helm chart documentation explaining overrides and provide a sample configuration. 
The overrides section in the tempo-distributed Helm chart wasn't documented well and the configuration used didn't quite match the explanation in the Tempo configuration doc. This PR adds an example to the tempo-distributed Helm chart guide. We'll have another PR that will address issues in the tempo-distributed README. 
Fixes https://github.com/grafana/tempo/issues/3820
Related: 
- https://github.com/grafana/helm-charts/issues/2802, 
- https://github.com/grafana/tempo/issues/3987, 
- https://github.com/grafana/tempo/issues/4326
- https://github.com/grafana/tempo/issues/3855
- …

[DOC] Add overrides info to tempo-distributed doc

---

CHANGELOG.md
modules/ingester/instance.go
pkg/util/log/rate_limited_logger.go

- Drops the max live traces log in the ingesters. This information is redundant with the `tempo_discarded_spans_total` metrics and costly to log in high volume envs
- Rate limit "max byte per trace" log lines.
- Convert instance to use a local logger instead of the global one
**Checklist**

Ingester: Rate limit max trace logs and drop too many live traces

---

CHANGELOG.md
modules/frontend/grpc_util.go
modules/frontend/metrics_query_handler.go
modules/frontend/metrics_query_range_handler.go
modules/frontend/search_handlers.go
modules/frontend/tag_handlers.go

The gRPC streaming endpoints are unintentionally dropping auth-related headers when issuing jobs to the queriers, so streaming + auth fails.  We need to extract them from the gRPC metadata and include them in the job.  The fix is here, but it is for downstream [Grafana Enterprise Traces](https://grafana.com/docs/enterprise-traces/latest/)
**Checklist**

Fix Grpc streaming handling of Authorization header

---

modules/blockbuilder/config.go
modules/generator/config.go
modules/generator/generator.go
modules/generator/generator_test.go
modules/generator/instance.go
modules/generator/instance_test.go
modules/generator/processor/localblocks/processor_test.go
modules/generator/processor/localblocks/query_range.go
pkg/traceql/engine_metrics.go
tempodb/config.go
tempodb/wal/wal.go

As part of the new architecture rollout, this introduces a secondary instance of the local blocks processor.  It is used to serve traceql metrics queries of recent data received from the queue, and never flushes to object storage.  This isn't the long-term setup, but a transition between the current and new architectures. 
Some notes:
* The secondary local blocks processor lifetime follows the main processor. It is added or removed with it.
* It requires a separate WAL and config to ensure there is never any overlap with the data received to the normal processor.
* Updated some of the WAL config validation.
**Checklist**

Rhythm: Separate non-flushing local blocks processor to store new queue data for reads

---

pkg/traceql/engine.go
pkg/traceql/engine_test.go

This fixes a gap in autocomplete where it's possible to autocomplete an attribute that's already being filtered in the query. This should be a noop but is actually executed.
Example:
`/api/v2/search/tag/name/values?query={name="foo"}`   
Since we already know `name` must be `foo`, there is no reason to scan for the autocomplete values.  
This PR adds the check to ExecuteTagValues in the engine. This is lower than preferred, ideally we would add this to the query-frontend, but the amount of pipeline reuse, and the location of the loose parsing of `query` make that non-trivial.  But want to get this fix in sooner.
Notes:
It's only valid to exit early when it is the Equal operation, and not any case where the attribute is present in the query.  For example these …

Exit early on autocomplete noops

---

docs/sources/tempo/configuration/_index.md

Adds documentation for max_spans_per_span_set (https://github.com/grafana/tempo/pull/4383) and max_query_expression_size_bytes (https://github.com/grafana/tempo/pull/4397)
Fixes #https://github.com/grafana/tempo-squad/issues/533
**Checklist**

[DOC] Add doc updates for query frontend and limits per spanset

---

docs/sources/tempo/api_docs/_index.md

Backport fe8bb268d1d211856bc10639ee4617a6a3f05d43 from #4425
---
Updates the filtered tag values example under Search tag values V2 section of the Tempo HTTP API documentation. 
Part of #4423 
**Checklist**

[release-v2.6] [DOC] Updated examples for filtered tag values

---

.github/workflows/ci.yml
.gitignore
Makefile
build/tools.mk

Make use of the linter cache to shorten duration in CI and locally.
In CI it goes approximately 2:30 to 1:30 minutes.
**Checklist**

Add golangci-lint cache

---

modules/generator/generator_test.go
modules/generator/processor/spanmetrics/config.go
modules/generator/processor/spanmetrics/spanmetrics.go
modules/generator/processor/util/util.go

**What this PR does**: Generator improvements based on @mdisibio 's notes for things relating to target_info. 
```
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
│ before-mg.out │            after-mg.out             │
│    sec/op     │   sec/op     vs base                │
PushSpans     3.006m ± 3%   1.308m ± 1%  -56.49% (p=0.000 n=10)
│ before-mg.out │            after-mg.out            │
│  heap_in_use  │ heap_in_use  vs base               │
PushSpans     15.73M ± 0%   15.79M ± 0%  +0.36% (p=0.000 n=10)
│ before-mg.out │             after-mg.out             │
│     B/op      │     B/op      vs base                │
PushSpans    705.9Ki ± 0%   568.6Ki ± 0%  -19.44% (p=0.000 n=10)
│ before-mg.out │            after-mg.out             │
│   allocs/op   │  allocs/op   vs base …
```

Metrics Generator Performance

---

CHANGELOG.md
pkg/traceql/ast.go
pkg/traceql/ast_conditions_test.go
pkg/traceql/ast_test.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet4/block_traceql_test.go

This fixes the internal processing of some traceql queries to support more cases where AllConditions should be true- notably `select()` queries. This means we can push all of the filtering down to storage more efficiently.    The code change is to remove the check at the top when any multiple pipeline stages exist, and instead push let the individual elements decide.  There are some remaining queries that maybe should also be AllConditions like `{ } | avg(duration) > 1s`, but they are left unchanged until they can be reviewed more thoroughly.  
Benchmark:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet3
cpu: Apple M4 Pro
│  before.txt  │              after.txt               │
│    sec/op    │    sec/op      vs base …
```

[TraceQL] Improve performance of select() queries

---

CHANGELOG.md
tempodb/blocklist/list.go
tempodb/blocklist/list_test.go
tempodb/retention_test.go
tempodb/tempodb_test.go

Fixes an issue where the blocklist could get doubled entries for the same block after quick compactions, leading to incorrect results for TraceQL metrics queries.  Searches are unaffected because they dedupe, but the metrics path requires RF1. 
This issue is only present for the SingleBinary, where the compactor and the read paths are in the same process.  In distributed mode this isn't a problem, the indexes shared through object storage are correct.
Example:
* block A  -> compacted to B
* block B -> compacted to C
* both B and C would be in the in-memory blocklist
Notes:
tempodb Retention Test had to be updated because it was relying on previous bug.  It expected the same block couldn't be compacted and retained within the same polling cycle, which was because the …

Blocklist update fix

---

.github/workflows/docker-ci-tools.yml

Migrate the docker-ci-tools pipeline from Drone to Github Actions.
This includes building the Docker images, pushing them and creating the final manifest.
I've tested this in a branch of the main repo: https://github.com/grafana/tempo/actions/runs/12352580265/job/34469919545
Once merged, I'll test it by updating tools/go.mod and verifying that the produced image works.
Then we can delete the pipeline from Drone.
One change I've made from the original, to make it more efficient, is to trigger the workflow only when the tools directory changes, instead of on every commit.
**Checklist**

Migrate docker-ci-tools workflow to Github Actions

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go
modules/frontend/search_sharder.go

Improves the deterministic ID generator to allocate less memory and be robust to all kinds of inputs.
Probably not a fair comparison, but still:
<details>
<summary>
Benchmark vs `uuid.New()` 
</summary>
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/modules/blockbuilder/util
cpu: Apple M2 Pro
BenchmarkDeterministicID-12    	 8512278	       125.5 ns/op	     120 B/op	       4 allocs/op
BenchmarkDeterministicID-12    	 9522423	       124.7 ns/op	     120 B/op	       4 allocs/op
BenchmarkDeterministicID-12    	 9609878	       126.4 ns/op	     120 B/op	       4 allocs/op
BenchmarkDeterministicID-12    	 8931763	       136.2 ns/op	     120 B/op	       4 allocs/op
BenchmarkDeterministicID-12    	 8639715	       136.5 ns/op	     120 B/op	       4 allocs/op …
```

[rhythm] Make ID generator more robust

---

.github/workflows/drone-signature-check.yml

Currently, the workflow is broken as the reusable workflow requires `id-token: write` _and_ `contents: read`, but since we have overridden the default permissions, we need to re-add `contents: read`. 
[Workflow error example](https://github.com/grafana/tempo/actions/runs/12400150268):
> The workflow is not valid. .github/workflows/drone-signature-check.yml (Line: 17, Col: 3): Error calling workflow 'grafana/shared-workflows/.github/workflows/check-drone-signature.yaml@main'. The nested job 'check-drone-signature' is requesting 'contents: read', but is only allowed 'contents: none'.
Fixes #
**Checklist**

fix(drone-sig): add missing `contents: read` permission

---

example/nomad/tempo-distributed/README.md
example/nomad/tempo-distributed/config.yml
example/nomad/tempo-distributed/tempo.hcl

- Adding HashiCorp Nomad job example (microservices mode)
**Checklist**

Nomad job example

---

modules/blockbuilder/blockbuilder.go
modules/generator/generator.go
pkg/ingest/reader_client.go
pkg/ingest/writer_client.go

Correctly register reader client metrics.

[rhythm] Fix registering of kafka read client metrics

---

CHANGELOG.md
cmd/tempo/app/modules.go
modules/ingester/flush.go

A few improvements that I wanted to keep out of https://github.com/grafana/tempo/pull/4483
- Set pool workers and queue len to 0 in all components that are not queriers. This just spins up dead goroutines for no reason.
- ~Complete all inflight jobs on ingester shutdown but refuse to do any new jobs. This should improve shutdown/restart time.~
**Checklist**

Remove pool goroutines from all components that don't need it

---

example/nomad/tempo-monolith/README.md
example/nomad/tempo-monolith/tempo.hcl

- Adding HashiCorp Nomad job example (monolithic mode)
**Checklist**

Add Tempo Nomad job example in Monolithic Mode

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go

Restore https://github.com/grafana/tempo/pull/4416. It was lost in 881888b9c56b009cc59c403e7582232d25d66a5a.

[rhythm] Make ID generator more robust (#4416)

---

modules/blockbuilder/blockbuilder.go

Initializes the startoffset more correctly when rewinding.  Works for Kafka locally but then found to be an issue for other installs internally.
**Checklist**

[Rhythm] Fix rewind to latest commit

---

Makefile

Adds new make target `docker-tempo-multi` that builds a multi-arch image with both x64 and arm.  This is a recent need for testing out changes in kubernetes clusters with different node types, and the multi-arch image simplifies things.  The main thing to call out is that storing these images locally in docker requires some customization to switch to the `containerd` image store (the default image store doesn't support multi-arch images).  So this isn't expected to be widely used but mainly for the Tempo team.
**Checklist**

Add make targets for multi-arch tempo docker image

---

modules/blockbuilder/util/id.go
modules/blockbuilder/util/id_test.go

Fixes a bug in the deterministic ID generator in which the tenant ID was not being correctly copied to the bytes buffer
**Checklist**

[rhythm] Fix ID generator copy bug

---

CHANGELOG.md

Missed one important detail in the previous PR:
https://github.com/grafana/tempo/pull/4542

Changelog Cleanup 2.7

---

docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md
docs/sources/tempo/traceql/metrics-queries/functions.md

Creates release notes for Tempo 2.7.
Fixes #https://github.com/grafana/tempo/issues/4520
**Checklist**

]DOC] Tempo 2.7 release notes

---

CHANGELOG.md
cmd/tempo-cli/cmd-query-metrics-query-range.go
cmd/tempo-cli/shared.go
pkg/api/http.go
pkg/api/http_test.go

Currently the http query range endpoint will choose a default step if none is provided, but the gRPC streaming endpoint will simply return an error: `code = Unknown desc = step required`.
This PR uses the same logic in the gRPC streaming as http to choose a default step if the passed value is 0.
**Checklist**

Bugfix: Default step for gRPC streaming query range queries

---

CHANGELOG.md
modules/distributor/distributor.go

Removes the `internal_error` reason from `tempo_discarded_spans_total`. We are removing this reason for two reasons:
1) It's unnecessary. The sending process (otel collector, alloy, whatever) receives a gRPC error and is aware of any lost spans.
2) This metric was being incremented when the sending client cancelled context for any reason and stopped sending through no fault of Tempo's.
This change puts the responsibility of reporting failed sends on the sending process which has more context about why a send failed and can better log/metric the event.
**Checklist**

Tempo: remove internal error reason for discarded spans

---

docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md

Updates the Upgrade considerations for 2.7 release notes and Upgrade pages. 
**Checklist**

[DOC] Update upgrade considerations for 2.7

---

CHANGELOG.md
operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin/dashboards/tempo-operational.json

* Adds new block-builder component to the drop down
* Fixes the Read panels to handle new v2 traces api
Other usability changes that weren't required but help performance because this is a very heavy dashboard:
* Disable automatic refresh
* Disable choosing All pods by default, instead default to ingesters
**Checklist**

Update tempo operational dashboard for block builder and v2 traces api

---

cmd/tempo-serverless/readme.md

Fixes a small typo - `serverlesss` -> `serverless`
**Checklist**

Fix typo in `tempo-serverless` README

---

CHANGELOG.md
cmd/tempo-cli/Dockerfile
cmd/tempo-query/Dockerfile
cmd/tempo-vulture/Dockerfile
cmd/tempo/Dockerfile

This image contains busybox, making debugging easier by running /busybox/sh
In addition, the latest ca-certificates from alpin are copied, as the ones in Debian are
severely out of date.
**Checklist**

Use distroless base image for tempo

---

modules/blockbuilder/blockbuilder_test.go
tempodb/encoding/vparquet4/schema.go
tempodb/encoding/vparquet4/wal_block.go

vParquet4 WAL computes the dedicated column definitions for every trace that is written. The mapping doesn't change once the block is created, so this fixes it to be done once.
This is about a 10% perf improvement in the block builder.  Probably will be noticeable in ingesters also but didn't check.
**Checklist**

vParquet4 WAL mapping fix

---

cmd/tempo/app/modules.go
docs/sources/tempo/configuration/manifest.md
example/docker-compose/distributed/tempo-distributed.yaml
example/docker-compose/ingest-storage/docker-compose.yaml
example/docker-compose/ingest-storage/prometheus.yaml
example/docker-compose/ingest-storage/tempo.yaml
example/docker-compose/shared/redpanda-console.yaml
modules/generator/config.go
modules/generator/generator.go
modules/generator/generator_kafka.go
pkg/ingest/balancer.go
pkg/ingest/reader_client.go

This PR introduces group consuming to the generators, instead of the previously used direct consuming. Group consuming delegates partitions assignment to Kafka, which greatly simplifies operations for the generators.
It uses a custom balancer that combines Kafka's cooperative sticky balancing with partition ring awareness. This implementation is [forked from Loki](https://github.com/grafana/loki/blob/889404791d9125d2d17a7da963ae0fc2b268e2e7/pkg/kafka/partitionring/consumer/balancer.go).
**Checklist**

[rhythm] Implement group-consuming in the metrics-generator

---

CHANGELOG.md
modules/blockbuilder/blockbuilder.go

It parses the list of partitions into a string 
**Checklist**

[rhythm] fix: starting consuming cycle log

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/setup/upgrade.md

Adds documentation for flush_to_storage to the metrics-generator configuration section. 
Fixes #4139 
**Checklist**

[DOC] Add flush_to_storage to metrics-gen config doc

---

docs/sources/tempo/introduction/trace-structure.md
docs/sources/tempo/shared/trace-structure.md
docs/sources/tempo/traceql/trace-structure.md

Chunks the traces structure content from the TraceQL doc. This content can now be shared to Grafana Cloud Traces and Explore Profiles content. 
Related to https://github.com/grafana/tempo-squad/issues/468
**Checklist**

[DOC] Share trace structure from docs

---

docs/sources/tempo/configuration/grafana-alloy/service-graphs.md

I got error when deploy Alloy Helm Chart 0.11.0
```
Error: /etc/alloy/config.alloy:152:42: missing ',' in expression list
interrupt received
Error: could not perform the initial load successfully
```
After adding this trailing comma, I can deploy successfully ☺️
N/A
**Checklist**

docs: fix missing comma issue

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md

Adds an admonition about gRPC compression to make it more prominent in the release notes, uprade, and configuration doc. 
Related to https://github.com/grafana/tempo/issues/4606
**Checklist**

[DOC] Update gRPC compressiong admonition

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md

Backport c7b435db37650cbfef9e301420e2419d7498d08f from #4644
---
Adds an admonition about gRPC compression to make it more prominent in the release notes, uprade, and configuration doc. 
Related to https://github.com/grafana/tempo/issues/4606
**Checklist**

[release-v2.7] [DOC] Update gRPC compressiong admonition

---

modules/ingester/instance_test.go

Fixes some flakey ingester tests where the generated test data is a little larger or smaller than before and it's not above or below the tested limits anymore. 
Example:
```
=== RUN   TestInstancePartialSuccess
instance_test.go:641: 
Error Trace:	/Users/marty/src/tempo/modules/ingester/instance_test.go:641
Error:      	Not equal: 
expected: true
actual  : false
Test:       	TestInstancePartialSuccess
--- FAIL: TestInstancePartialSuccess (0.01s)
```
**Checklist**

Fix flakey ingester tests

---

docs/sources/tempo/setup/size.md

Adds a basic cluster sizing doc. 
Relates to https://github.com/grafana/tempo/issues/1540
**Checklist**

Add basic cluster sizing for Tempo doc

---

CHANGELOG.md
modules/blockbuilder/tenant_store.go
pkg/livetraces/livetraces_test.go

Accidentally left a redundant live traces ID sort in #4647 .  Also adds a benchmark for live traces. There are no changes but I was exploring some ideas and wanted to keep the benchmarks.
**Checklist**

[Rhythm] Remove redudant live traces sort

---

CHANGELOG.md
pkg/traceql/engine.go
pkg/traceql/engine_test.go

Return the operand as the only value if the tag is already filtered in the query. I think this is more in line with what one would expect.
**Checklist**

Return the operand as the only value if the tag is already filtered in the query

---

example/tk/tempo-microservices/main.jsonnet
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/block-builder.libsonnet
operations/jsonnet/microservices/config.libsonnet
operations/jsonnet/microservices/multi-zone.libsonnet
operations/jsonnet/microservices/replica-template.libsonnet
operations/jsonnet/microservices/replica-templates.yaml
operations/jsonnet/microservices/rollout-operator.libsonnet
operations/jsonnet/microservices/tempo.libsonnet

Introduced the rollout-operator so the pods in the block-builder's statefulset can simultaneously update. Otherwise there is the risk of ownership conflicts in partitions during rollouts.
There are 6 partitions and 3 block-builders.
Partition assignment is as follows:
- `block-builder-0` has assigned partitions `0` and `3`.
- `block-builder-1` has assigned partitions `1` and `4`.
- `block-builder-2` has assigned partitions `2` and `5`.
If a new block-builder is deployed, partition assignment will change to
- `block-builder-0` has assigned partitions `0` and `4`.
- `block-builder-1` has assigned partitions `1` and `5`.
- `block-builder-2` has assigned partitions `2`.
- `block-builder-3` has assigned partitions `3`.
As soon as block-builders are rolled out, they'll …

[rhythm] Add rollout-operator and allow simultaneous update of block-builder pods

---

CHANGELOG.md
cmd/tempo/app/config.go
docs/sources/tempo/configuration/manifest.md
modules/querier/config.go

Sets gRPC compression between all components to be "snappy". This feels like a balanced approach to compression between components that will work for most installs. If you prefer a different balance of CPU/Memory and bandwidth consider disabling compression or using zstd. 
Some details here: https://github.com/grafana/tempo/discussions/4683
Revisits the choice made here: https://github.com/grafana/tempo/pull/4429

Set gRPC compression default to snappy in all cases

---

CHANGELOG.md
pkg/parquetquery/iters.go

Restores the old behavior of `EqualRowNumber`. The current version is no longer inlineable. This can be checked using a command like:
```
go build -gcflags="-m" . 2>&1 | grep 'can inline' | grep EqualRowNumber
```
The old version is inlineable and shows a perf improvement.
<details>
<summary>benches</summary>
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet4
cpu: Apple M3 Pro
│ before.txt  │        after-old-eq-rn.txt         │
│   sec/op    │   sec/op     vs base               │
BackendBlockTraceQL/spanAttValMatch-11                82.76m ± 1%   82.36m ± 0%  -0.48% (p=0.000 n=10)
BackendBlockTraceQL/spanAttValNoMatch-11              5.468m ± 1%   5.524m ± 0%  +1.03% (p=0.001 n=10)
BackendBlockTraceQL/spanAttIntrinsicMatch-11 …
```

Improve EqualRowNumber

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
modules/distributor/artificial_delay.go
modules/distributor/artificial_delay_test.go
modules/distributor/distributor.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go

Add a tenant-specific override to pad push requests with an artificial delay. This makes it possible to simulate a slower version of Tempo and see how it impacts the tracing pipeline.
**Checklist**

Add ability to add artificial delay to push requests

---

docs/sources/tempo/getting-started/metrics-from-traces.md

Remove an unused feature flag, traceToMetrics. 
Fixes https://github.com/grafana/tempo/issues/4684
**Checklist**

[DOC] Remove traceToMetrics from docs

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-7.md
docs/sources/tempo/setup/upgrade.md

Updates docs to change the default value for gRPC compression to snappy, per https://github.com/grafana/tempo/pull/4696
**Checklist**

[DOC] Release notes for 2.7.1

---

docs/sources/tempo/introduction/_index.md
docs/sources/tempo/introduction/solutions-with-traces/traces-app-insights.md
docs/sources/tempo/introduction/solutions-with-traces/traces-diagnose-errors.md
docs/sources/tempo/shared/traceql-query-structure.md
docs/sources/tempo/traceql/_index.md
docs/sources/tempo/traceql/architecture.md
docs/sources/tempo/traceql/metrics-queries/_index.md
docs/sources/tempo/traceql/trace-structure.md

Backport 02ec38e47b178222ef085845909bff242a3f8484 from #4680
---
This PR addresses some requirements for mounting the intro and TraceQL docs into Grafana Cloud Traces, Explore Traces, and Tempo data source. 
Notes for doc team reviewer: 
(Feb 18. Checked by Kim and Beverly from the Docs team)
Notes for reviewer: 
* Check for any typos or introduced mistakes 
Related: https://github.com/grafana/tempo-squad/issues/468
**Checklist**

[release-v2.7] [DOC] Updates for sharing content to GTC, Tempo data source

---

go.mod
go.sum
vendor/github.com/parquet-go/parquet-go/column.go
vendor/github.com/parquet-go/parquet-go/format/parquet.go
vendor/github.com/parquet-go/parquet-go/page.go
vendor/github.com/parquet-go/parquet-go/schema.go
vendor/github.com/parquet-go/parquet-go/type.go
vendor/modules.txt

Backport 1b63c9fffc78af00a341e659f5d4d18d9990b466 from #4730
---
Upgrades parquet-go to catch https://github.com/parquet-go/parquet-go/pull/246#pullrequestreview-2631732037

[r188] Upgrade parquet-go to fix trace by id regression

---

CHANGELOG.md
modules/generator/instance.go

**What this PR does**: Allows to put "span-metrics-size", "span-metrics-count", "span-metrics-latency" into user configurations overrides via API
Fixes [#3945](https://github.com/grafana/tempo/issues/3945)
**Step 1.** Run docker compose (here I used example/docker-compose/otel-collector-multitenant) with the following tempo.yaml:
```yaml
overrides:
defaults:
metrics_generator:
processors: [local-blocks] # leave only local-blocks
generate_native_histograms: both
user_configurable_overrides:
enabled: true
poll_interval: 5s 
client:
backend: local
local:
path: /var/tempo/overrides
```
**Step 2.** Check current configurations:
1. Set processors to "local-blocks" (the same as in configurations):
```
curl -X POST -v -H "If-Match: 1697726795401423" -H …
```

Issue 3948: user cfg override fix

---

CHANGELOG.md
modules/generator/processor/localblocks/processor.go
modules/generator/processor/localblocks/processor_test.go

Fixes [#4742](https://github.com/grafana/tempo/issues/4742)
The bug was introduced in https://github.com/grafana/tempo/pull/4721
1. Run docker compose from `example/docker-compose/local`. Before running, make sure /var/tempo (mounted as ./tempo-data) is empty.
Expected results: tempo starts up and runs well (no panics).
this and main branches results: same as expected.
1. Stop docker compose and run it again.
Expected results: tempo starts up and runs well (no panics).
this branch results: same as expected.
main branch results: panics with the following message:
```
tempo-1  | panic: runtime error: invalid memory address or nil pointer dereference
tempo-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fe2170]
``` …

Issue 4742: fix panic on startup

---

CHANGELOG.md
modules/blockbuilder/blockbuilder.go

The sort was inverted. We want to sort for older timestamp first
**Checklist**

rhythm: fix partition sorting

---

CHANGELOG.md
modules/blockbuilder/tenant_store.go
modules/blockbuilder/tenant_store_test.go

This fixes the previous behavior, where the end date was always set to the start time. This was a translation of our behavior in the ingesters, where the start and end dates are set to now() if they are outside the time range.
**How it works now**:
It checks independently the start and the end.
If the end is before the start it will set it to the start
If the end is after the end range it will set it to the end range
**Checklist**

rhythm: fix block time range adjustment

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go

Fix offset handling in BlockBuilder to prevent double consumption:
Align the return value of `consumePartition` with the committed offset (`lastRec.Offset + 1`). This ensures consistency between what's committed to Kafka and what's tracked in memory. This prevents records from being processed multiple times within the same consumption cycle.
Taken from https://github.com/grafana/tempo/pull/4750
**Checklist**

[rhythm] blockbuilder: fix cycle handling

---

integration/e2e/api/api_test.go
integration/e2e/api/compression_test.go
integration/e2e/api/cross_cluster_reads_test.go
integration/e2e/api/https_test.go
integration/e2e/api/multi_tenant_test.go
integration/e2e/api/query_range_test.go

Fixes flaky test TestSearchTagValuesV2 by changing sleep to waiting traces to be queryable.
Fixes #4578
- CI
- run TestSearchTagValuesV2 and TestSearchTagsV2 with -count=10
main branch results: fails
current branch results: passes (checked 3 times for TestSearchTagValuesV2 just in case, 30 runs in total)
**Checklist**

Issue 4578: Fix flaky test

---

CHANGELOG.md
tempodb/encoding/vparquet4/block_traceql.go

Reorder iterators in `createSpanIterator`: move iterators of well-known attributes, intrinsic, and dedicated columns before attribute iterators (and link / event iterators).
This change shows improvements for some benchmarks.
<details>
<summary>Benchmark result</summary>
```
goos: linux
goarch: amd64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet4
cpu: AMD Ryzen 7 PRO 6850U with Radeon Graphics     
│ bench-traceql-02-dh-no-reorder.txt │   bench-traceql-02-dh-reorder.txt   │
│               sec/op               │   sec/op     vs base                │
BackendBlockTraceQL/spanAttVal01Match-16                                   11.43 ± 1%    11.80 ± 1%   +3.22% (p=0.000 n=10)
BackendBlockTraceQL/spanAttVal01NoMatch-16                                879.6m ± 3% …
```

Reorder span iterators

---

CHANGELOG.md
Makefile

This PR makes the following changes to Tempos build options:
* Remove debug info from production builds `-ldflags -w`. This reduces the tempo binary size by ~20%
* Set the architecture API version for amd64 and arm64. This allows the compiler to use more advanced instructions and has a small positive effect on code execution time on amd64 (see benchmark below).
* Remove `GO111MODULE=on` as this is the default since [Go 1.16](https://go.dev/doc/go1.16). 
The changes are inspired by the 2025 FOSDEM talk [Build better Go release binaries](https://cuddly.tube/w/e7Ks1zQhFovnGwbZFRcL1d)
<details>
<summary>Benchmarks amd64 v1 vs v2 vs v3</summary>
```
goos: linux
goarch: amd64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet4
cpu: AMD Ryzen 7 PRO 6850U with Radeon …
```

Improve Tempo build options

---

Makefile

This fixes a bug introduced by https://github.com/grafana/tempo/pull/4755 that caused the CI to fail while building the arm64 docker image ([see here](https://github.com/grafana/tempo/actions/runs/13563657111))
**Checklist**

Fix GOARM64 build option

---

CHANGELOG.md
modules/frontend/slos.go
modules/frontend/slos_test.go

Convert throughput SLO metrics from histogram to counter

---

operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/runbook.md

Removes the TempoRequestLatency alert and the associated runbook.
The alert is very noisy and it is no longer needed.
**Checklist**

Remove TempoRequestLatency alert and associated runbook section

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/live_traces_iter.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/tenant_store_test.go
modules/generator/generator_kafka.go
pkg/ingest/metrics.go
pkg/util/test/req.go

Some small cleanup. This came about while writing tenantStore tests to verify handling of historical data, and decided to get a few more things:
* Block-builder move to the common `partition_lag_seconds` metric in pkg/ingest
* Clear old metrics when partitions are revoked
* Record lag at the end of the block builder loop so that we can see both the high and low-water marks, and fix to record zero lag when it knows the partition is caught up.
* Reorganize liveTracesIter and other consts
**Checklist**

[Rhythm] Block-builder metrics and code cleanup

---

CHANGELOG.md
modules/frontend/metrics_query_range_handler_test.go
modules/frontend/metrics_query_range_sharder.go

Cache keys were not being generated for query range backend jobs due to a mismatch between seconds and nanoseconds. Block metas are only included if their start/end times are completely encapsulated in the query start/end times. The start/ends were ns but the blocks were seconds which made it so no cache keys were ever generated.
**Checklist**

Fix query range frontend caching

---

docs/sources/tempo/metrics-generator/span_metrics.md

Fixes a broken link from the span metrics documentation to the metrics generator configuration page.
N/A
**Checklist**

docs: Fix broken link to metrics generator from span metrics doc.

---

CHANGELOG.md
tempodb/encoding/vparquet4/wal_block_test.go

It fix a test with a non deterministic behaviour 
**Checklist**

fix: flaky TestWalBlockFindTraceByID test

---

modules/frontend/cache_keys.go
modules/frontend/cache_keys_test.go
modules/frontend/frontend.go
modules/frontend/metrics_query_range_handler_test.go
modules/frontend/metrics_query_range_sharder.go
modules/frontend/search_handlers_test.go
modules/frontend/search_sharder.go
modules/frontend/tag_handlers_test.go
modules/frontend/tag_sharder.go

Currently if you perform a query range search and the end of the time range matches the end second of a block it will fail with:
`end must be greater than start`
This is due a consolidation of code when [adding the most_recent=true query hint](https://github.com/grafana/tempo/pull/4238). A bug was introduced when consolidating `blockMetasForSearch`. The query range pipeline respects a nanosecond range but blockMetasForSearch was not. As a result it was possible for a block to be incorrectly included in the search if it's end time shared the same second as the end time of the requested range.
- Applied the same fix to the cache key function.
**Checklist**

BugFix: Blocks whose end second matches a query range throw an erroneous error

---

CHANGELOG.md
integration/e2e/api/api_test.go
integration/util/util.go
modules/frontend/combiner/common.go
modules/frontend/combiner/interface.go
modules/frontend/metrics_query_range_handler_test.go
modules/frontend/search_handlers_test.go
modules/frontend/tag_handlers.go
modules/frontend/tag_handlers_test.go
modules/ingester/instance_search.go
modules/ingester/instance_search_test.go
modules/querier/querier.go

Fixes #4769 by ensuring intrinsic tags are added first to the value collectors.  Because they are static, there is also no need to return them from queriers and ingesters, and instead the query-frontend adds them statically.
**Checklist**

Move all intrinsic tag lookup to the query-frontend and prioritize them in the results

---

CHANGELOG.md
modules/querier/querier.go
modules/querier/querier_query_range.go

A panic was [introduced here](https://github.com/grafana/tempo/pull/4100) by abusing the ring forEach function to collect results. [replicationSet.Do](https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L404) can return before all reads are complete if quorum is reached. Under certain, rare circumstances this caused the forEach function to modify a result [here](https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L240) after it has already been returned and was being marshalled by the gRPC stack into proto. 
**Checklist**

Fix querier panics

---

operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/runbook.md

This PR adds new alerts to monitor Kafka partition lag in consumer groups. It introduces two alert levels:
* Warning alert when a partition lags by more than 5 minutes
* Critical alert when a partition lags by more than 15 minutes

[rhythm] Add partition lag alerts for Kafka consumers

---

CHANGELOG.md
tempodb/encoding/vparquet2/compactor.go
tempodb/encoding/vparquet3/compactor.go
tempodb/encoding/vparquet4/compactor.go

**What this PR does**:  The compactor logs displays each completed block along with its columns, allowing us to verify whether dedicated columns were in use.
Fixes # https://github.com/grafana/tempo/issues/4087
https://github.com/grafana/tempo/discussions/4824
**Checklist**

add dedicated column logging

---

CHANGELOG.md
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/spanmetrics/spanmetrics.go

It removes low value traces that generate a massive amount of telemetry data
**Checklist**

chore: skip creating one span-traces for every pushed spans in metrics generator

---

CHANGELOG.md
modules/ingester/instance_test.go

Try to fix a flaky test and improve the assert output
```
modules/ingester TestInstanceFailsLargeTracesEvenAfterFlushing (0.04s)
instance_test.go:564: 
Error Trace:	/home/runner/work/tempo/tempo/modules/ingester/instance_test.go:564
Error:      	Should be false
Test:       	TestInstanceFailsLargeTracesEvenAfterFlushing
Messages:   	push failed: %!w([]tempopb.PushErrorReason=[2])
```
**Checklist**

chore: fix ingester flaky test

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/manifest.md
docs/sources/tempo/operations/backend_search.md
modules/frontend/config.go

This PR increases the default batch size from 5 to 7 to improve workload handling and reduce latency.
We recently introduced a mechanism to assign weights to query frontend jobs, allowing for better workload distribution between the frontend and queries: [#4076](https://github.com/grafana/tempo/pull/4076).
Our tests showed that the previous default batch size of 5 led to increased overall latency. With the new weighted scheduling in place, we can safely push more jobs simultaneously, making it beneficial to raise the batch size.
**Checklist**

chore: increase query frontend default batch size from 5 to 7

---

CHANGELOG.md
pkg/traceql/ast_conditions.go
pkg/traceql/ast_conditions_test.go
tempodb/encoding/vparquet4/block_traceql_test.go

Fix behavior for queries single attributes that are &&ed or ||ed with a boolean.
Fixes #4839
**Checklist**

TraceQL: fix queries like {.foo && true} and {.foo || false}

---

modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
operations/jsonnet-compiled/StatefulSet-block-builder.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/block-builder.libsonnet
pkg/ingest/testkafka/cluster.go

Added proper graceful shutdown to the block builder component to ensure operational safety during service termination. Instead of abruptly terminating, it now:
1. Uses a separate cancelable context for consume operations
2. Properly signals when consumption cycles are complete
3. Waits for the current cycle to finish during shutdown
**Checklist**

[rhythm] Block-builder graceful shutdown

---

CHANGELOG.md
modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/partition_writer.go
modules/blockbuilder/tenant_store.go
modules/blockbuilder/tenant_store_test.go
modules/frontend/search_sharder_test.go
tempodb/tempodb.go

Blocks in Tempo are immutable.  Once written, they are never changed, and the compactor and polling rely on this.  The current implementation of the block builder violates this by reflushing a new data.parquet to the same ID, with possibly different contents.    This gives the situation where the info in the block index no longer matches the contents and queries fail.
This changes the block builder to detect when a block from a previous attempt exists, and instead of overwriting it, mark it compacted and flush a new block.   Eventually the blocks will be repolled and effectively the old block is replaced with the new one.   Any number of replays are tolerated, because we use the deterministic block ID generator to continue forward until the next unused ID is found. …

[Rhythm] Block builder not mutate blocks across replays

---

CHANGELOG.md
modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go

It implements a retry strategy to handle transient commit errors
**Checklist**

rhythm: retry on commit error

---

CHANGELOG.md
operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet

Fix `TempoBlockListRisingQuickly` alert grouping. This change ensures the alert properly compares blocklist growth within the same cluster and namespace, preventing potential false positives caused by cross-cluster or cross-namespace comparisons
**Checklist**

Fix `TempoBlockListRisingQuickly` alert grouping

---

docs/sources/tempo/introduction/glossary.md

Inline shortcodes are powerful templating tools and allow source projects to iterate on HTML templates without a PR to the website repository.
However, by accident or malintent, they can be used break the website or expose information.
On the balance of things, the Docs Platform team believes that the risk outweighs the reward and will be disabling the feature.
The team believes it can support the prompt and safe creation of central shortcodes to satisfy the needs of the source projects.
All existing inline shortcodes have already been translated into central shortcodes that everyone can use.
Created-By: reverse-changes
Repository: grafana/tempo
Website-Pull-Request: https://github.com/grafana/website/pull/24705

Remove inline shortcodes

---

docs/sources/tempo/introduction/glossary.md

Inline shortcodes are powerful templating tools and allow source projects to iterate on HTML templates without a PR to the website repository.
However, by accident or malintent, they can be used break the website or expose information.
On the balance of things, the Docs Platform team believes that the risk outweighs the reward and will be disabling the feature.
The team believes it can support the prompt and safe creation of central shortcodes to satisfy the needs of the source projects.
All existing inline shortcodes have already been translated into central shortcodes that everyone can use.
Created-By: reverse-changes
Repository: grafana/tempo
Website-Pull-Request: https://github.com/grafana/website/pull/24705

[v2.7.x] Remove inline shortcodes

---

example/nomad/tempo-distributed/README.md
example/nomad/tempo-distributed/tempo.hcl
example/nomad/tempo-monolith/README.md
example/nomad/tempo-monolith/tempo.hcl

Fix typo in nomad job definitions. Add missing `endpoint` for otlp configuration. Update README.md for nomad  exmples
**Checklist**

Fix typo in nomad job definition. Fix tempo-monolith config

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/introduction/glossary.md

Inline shortcodes are powerful templating tools and allow source projects to iterate on HTML templates without a PR to the website repository.
However, by accident or malintent, they can be used break the website or expose information.
On the balance of things, the Docs Platform team believes that the risk outweighs the reward and will be disabling the feature.
The team believes it can support the prompt and safe creation of central shortcodes to satisfy the needs of the source projects.
All existing inline shortcodes have already been translated into central shortcodes that everyone can use.
Created-By: reverse-changes
Repository: grafana/tempo
Website-Pull-Request: https://github.com/grafana/website/pull/24705

[v2.5.x] Remove inline shortcodes

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/introduction/glossary.md

Inline shortcodes are powerful templating tools and allow source projects to iterate on HTML templates without a PR to the website repository.
However, by accident or malintent, they can be used break the website or expose information.
On the balance of things, the Docs Platform team believes that the risk outweighs the reward and will be disabling the feature.
The team believes it can support the prompt and safe creation of central shortcodes to satisfy the needs of the source projects.
All existing inline shortcodes have already been translated into central shortcodes that everyone can use.
Created-By: reverse-changes
Repository: grafana/tempo
Website-Pull-Request: https://github.com/grafana/website/pull/24705

[v2.6.x] Remove inline shortcodes

---

CHANGELOG.md
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go
tempodb/encoding/vparquet4/block_traceql_test.go

A bug was identified with traceql metrics where some queries return incorrect data, see screenshot:
In this example it is returning other values for `http.flavor` even though it is clearly restricted to a single value in the query.
The bug is that traceql metrics engine has optimizations for performance that expect behavior from the storage layer that wasn't happening.  Specifically, the parquet layer isn't (and never has) honored AllConditions=true when there are multiple attributes of the same type being filtered in the generic attribute columns.   It requires the engine callback to finalize the resultset, which traceql metrics is trying to optimize away.
This fix excludes these queries from optimization and fixes their output.   Because this is not the first bug …

TraceQL Metrics: Fix incorrect optimization for some queries

---

modules/querier/querier.go
modules/querier/querier_query_range.go

Backport 6d707056521ce46c79179fc16fc12126579f66a0 from #4790
---
A panic was [introduced here](https://github.com/grafana/tempo/pull/4100) by abusing the ring forEach function to collect results. [replicationSet.Do](https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L404) can return before all reads are complete if quorum is reached. Under certain, rare circumstances this caused the forEach function to modify a result [here](https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L240) after it has already been returned and was being marshalled by the gRPC stack into proto. 
**Checklist**

[release-v2.7] Fix querier panics

---

docs/sources/tempo/operations/manage-advanced-systems/user-configurable-overrides.md
modules/generator/config.go
modules/generator/instance.go
modules/generator/instance_test.go
modules/generator/overrides.go
modules/generator/overrides_test.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go
modules/overrides/userconfigurable/api/api_test.go
modules/overrides/userconfigurable/api/limits.go
modules/overrides/userconfigurable/api/limits_test.go
modules/overrides/userconfigurable/client/limits.go
modules/overrides/userconfigurable/client/limits_test.go

This PR adds support for the host info processor to the user configurable overrides api.
**Checklist**

add host info to userconfigurable overrides api

---

operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin/dashboards/tempo-operational.json

In the operational dashboard currently, the queries are restricted to the compactor `job`.  Here we drop the `job` label from the query so that we can match against any component, which realistically only means the workers.
**Checklist**

Adjust operational dashboard query to include compactions from any component

---

CHANGELOG.md
modules/backendscheduler/backendscheduler_test.go
modules/blockbuilder/blockbuilder_test.go
modules/blockbuilder/tenant_store_test.go
tempodb/blocklist/poller.go
tempodb/tempodb.go

Currently, the module context is passed to the poller.  In the event of a termination request, this context is used on the backend reader/writer and fail because of the cancellation.  Here we use a background context for the polling so that once a poll for a tenant has started to ensure the index is written.  The store module is updated to block shutdown until the poller is done.  This is necessary because the polling process is run in a routine, and during rollout of the index-writers, we see alerts due to stale index.  Allowing the poller to complete tenants which it has started should improve this siutaiton.
**Checklist**

Finish polling current tenants before shut down

---

CHANGELOG.md
modules/distributor/artificial_delay.go
modules/distributor/artificial_delay_test.go
modules/distributor/config.go
modules/overrides/config.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go

This PR extends the artificial delay feature with default configuration in the distributor.
**Checklist**

Extend artificial delay with default configuration

---

.github/workflows/backport.yml

This change does following things:
- move away from `pull_request_target` as it's not recommended
- move to using github app to trigger CI on backport PRs, see more https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
- limit the workflow to only run on grafana/tempo so it doesn't run in forks.
**Checklist**

adjust backport workflow to use github app

---

CHANGELOG.md
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/runtime_config_overrides_test.go

It includes the cost attribution when converting from default config to legacy one
**Checklist**

fix: include cost attribution when converting from default config to legacy one

---

CHANGELOG.md
operations/jsonnet-compiled/ConfigMap-tempo-querier.yaml
operations/jsonnet-compiled/Deployment-querier.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/configmap.libsonnet

Queriers are the only components that we ship by default with log_level DEBUG. This PR set them to the default level which is INFO
**Checklist**

chore: set querier default log level to INFO

---

cmd/tempo/main.go

Adds the `config.Target` value to the startup log message for clearer observability.
None (minor logging enhancement).
**Checklist**

chore: log target mode in Tempo startup message

---

.github/workflows/ci.yml

It is a matter of fact that we introduce flaky tests from time to time. While we are always speedy in fixing them, in the meantime, it is quite annoying having to retry all the matrix steps when one of them fails:
Setting the `fail-fast: false` will make all the test steps to finish so only the failed one will need to be retried

ci: set fail fast to false in the tests jobs

---

CHANGELOG.md
modules/compactor/compactor.go
pkg/io/buffered.go
pkg/io/buffered_test.go
tempodb/encoding/vparquet4/block_iterator.go

Compactors rarely panic with a stack like:
```
/enterprise-traces/vendor/github.com/parquet-go/parquet-go/page.go:129 +0xfd
created by github.com/parquet-go/parquet-go.AsyncPages in goroutine 33664
/enterprise-traces/vendor/github.com/parquet-go/parquet-go/page.go:264 +0x178
github.com/parquet-go/parquet-go.readPages({0x3bc5390, 0xc06ed2f360}, 0xc0b09b2f50, 0xc0acc4b780, 0x3bea488?, 0xc0b09b3030)
/enterprise-traces/vendor/github.com/parquet-go/parquet-go/file.go:801 +0x9f
github.com/parquet-go/parquet-go.(*FilePages).ReadPage(0xc06ed2f360)
/enterprise-traces/vendor/github.com/parquet-go/parquet-go/file.go:916 +0x65
github.com/parquet-go/parquet-go.(*FilePages).readPage(0xc06ed2f360, 0xc096766f30, 0xc0795b8000) …
```

Fix compactor panic

---

cmd/tempo-cli/cmd-gen-attrindex.go
cmd/tempo-cli/main.go

Add the sub command `tempo-cli gen attr-index`. The sub command is can be used to generate indexes for existing tempo blocks. The command is meant to be used to experiment with different kind of indexes
Contributes to grafana/tempo-squad#608
**Checklist**

Sub-command for tempo-cli to generate attribute indexes

---

operations/tempo-mixin-compiled/dashboards/tempo-rollout-progress.json
operations/tempo-mixin/dashboards/rollout-progress.libsonnet

Starting in Grafana 11, [angular plugins support was deprecated](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) and users were asked to migrate to React. The Rollout Progress dashboard is still using the [deprecated graph plugin](https://github.com/grafana/jsonnet-libs/blob/357eee054c4a50b1033e22493fd9503c1174bf56/grafana-builder/grafana.libsonnet#L217), so users installing this dashboard via the mixin are seeing a deprecation warning (and it will be completely unavailable in Grafana 12).
This PR moves this panel to the `timeseriesPanel`.

chore(tempo-mixin): update rollout-progress dashboard

---

CHANGELOG.md
cmd/tempo/app/config.go
docs/sources/tempo/configuration/manifest.md
docs/sources/tempo/configuration/use-trace-data.md

This PR changes the default http-listen-port from 80 to 3200.
No open issue. See discussion here: https://github.com/grafana/tempo/discussions/4945 
**Checklist**

Change default http-listen-port from 80 to 3200

---

CHANGELOG.md
cmd/tempo/main.go

This adds default value for blocking and mutex contention. They are very low defaults to have minimal impact on cpu. In practice alloy has been running these same defaults for years. There is no documentation, I will add that in a separate PR since it will be a larger new section on starting tempo.
**Checklist**

Add support for pprof mutex/blocking

---

CHANGELOG.md
tempodb/encoding/vparquet4/compactor.go
tempodb/encoding/vparquet4/compactor_test.go

Compactor memory usage and frequency of OOMs has increased over time and investigation showed that almost all of it is via the parquet row pool.  It's been hard to ascertain the exact reasons, but the pooling slices for large traces is not providing the benefit that it used to.  It seems that the large amount of pooled data no longer gets GC'ed like expected and accumulates.  I couldn't spot any bugs in repooling, so I think it is a change in behavior at runtime due to a combination of factors:  vParquet4 event/link attribute columns significantly increasing row sizes vs the prior json blobs, golang runtime, and environmental factors.  
This PR removes pooling for large traces, and it has been tested to have a huge improvement in memory, cutting memory high-water …

Compactor pooling changes

---

tempodb/backend/cache/cache.go

Restores copy logic for parquet pages. Initial investigation made this feel safe but we (read I) had forgotten about the background cache functionality here:
https://github.com/grafana/tempo/blob/main/pkg/cache/background.go#L44

Caching: Restore parquet page copy logic

---

docs/sources/tempo/getting-started/metrics-from-traces.md

Backport of https://github.com/grafana/tempo/pull/4942
---------
Manually created backport since the original backport label failed. 
**Checklist**

Add a table explaining metrics types to docs (#4942)

---

docs/sources/tempo/api_docs/_index.md

Update the Tempo API documentation to address a difference between available API support between Tempo and GET. The API docs are mounted from Tempo into GET. 
Fixes https://github.com/grafana/enterprise-traces/issues/1600
**Checklist**

[DOC] Update Ingest API for GET

---

.github/workflows/backport.yml

- move back to using pull_request_target because pull_request lacks required permissions.
- update back the actions/create-github-app-token to v2.0.2
**Checklist**

github: move back to pull_request_target and undo downgrade

---

CHANGELOG.md
modules/frontend/metrics_query_range_handler_test.go
modules/frontend/metrics_query_range_sharder.go

Frontend caching is broken for TraceQL Metrics queries. The cache key generation was incorrectly using the step instead of the start page which caused all jobs for the same block to collide.
**Checklist**

BUGFIX: Metrics Frontend Caching

---

CHANGELOG.md
pkg/traceql/ast.go
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
pkg/traceql/ast_stringer.go
pkg/traceql/ast_test.go
pkg/traceql/enum_operators.go
pkg/traceql/enum_operators_test.go
pkg/traceql/expr.y
pkg/traceql/expr.y.go
pkg/traceql/parse_test.go
pkg/traceql/test_examples.yaml
tempodb/tempodb_search_test.go

Currently the TraceQL engine treats all != comparisons to nil as existence checks (as opposed to equality). This is different from the fetch layer which will not collect spans where an attribute is not present. For example consider:
```
{ span.foo != "bar" } 
```
If foo is not present on a span the fetch layer will not return it. In this case the fetch layer is effectively evaluating `nil != "bar"` as false. However, the engine will currently evaluate `nil != "bar"` as true. This is apparent when running queries like:
```
{} >> { span.foo != "bar" }
```
In this case b/c the engine is evaluating the condition and not the fetch layer, Tempo will return spans that do not have an attribute "foo" unlike the first example.
This PR disambiguates the concept of existence from equality in the …

TraceQL Bugfix: Disambiguate existence from equality

---

go.mod
vendor/modules.txt

This replace in the go.mod does not impact the codebase and is just clutter.

Remove innocuous(?) replace

---

CHANGELOG.md
modules/distributor/distributor.go

It uses a canonical bytesize when parsing the partition.id. Currently it uses `31` bytes as byte size. 
**Checklist**

fix: use canonical byte size when parsing partition.id

---

modules/backendscheduler/backendscheduler.go
modules/backendscheduler/cache.go
modules/backendscheduler/provider/compaction.go
modules/backendscheduler/provider/metrics.go
modules/backendscheduler/work/job.go
modules/backendscheduler/work/job_test.go

Previous to #5019 a lock for the RPC calls was sufficient, but we only need it for the work, which has its own lock.  Here we drop the locking from the backendworker entirely to rely on the job and work mutex.
**Checklist**

Reduce lock contention in backendscheduler

---

CHANGELOG.md
modules/distributor/distributor.go

This PR fixes an issue measuring Kafka write latency when all append record operations fail.
It also improves the accuracy of the latency measurement by moving the start time and duration calculation closer to the actual append operation, avoiding interference from the encoding step.
Additionally, the PR changes the error handling to return the first encountered error (if any), rather than the last. This simplifies the logic and more clearly indicates that the response is partially erroneous.
**Checklist**

fix: measure the write latency on append errors

---

CHANGELOG.md
pkg/cache/memcached.go
pkg/cache/memcached_test.go

Updates the memcached client to honor a cancelled context. This prevents a somewhat rare panic from occurring:
```
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/page.go:129 +0xfd
created by github.com/parquet-go/parquet-go.AsyncPages in goroutine 610894
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/page.go:269 +0x178
github.com/parquet-go/parquet-go.readPages({0x3fdf8f0, 0xc0bf919ae0}, 0xc10c1dc310, 0xc095e75880, 0x4007b18?, 0xc10c1dc3f0)
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/file.go:801 +0x9f
github.com/parquet-go/parquet-go.(*FilePages).ReadPage(0xc0bf919ae0)
/Users/joe/dev/joe-elliott/tempo/vendor/github.com/parquet-go/parquet-go/file.go:916 +0x65 …
```

Updated memcached client to honor a cancelled context

---

CHANGELOG.md
pkg/parquetquery/iters.go
pkg/parquetquery/iters_test.go

Fixes an issue where ReadPage errors were ignored causing the iterator to blindly iterate past any issues.
**Checklist**

SyncIterator: Correctly propagate ReadPage errors

---

CHANGELOG.md
docs/sources/tempo/configuration/_index.md
tempodb/retention.go
tempodb/retention_test.go

Here we modify the behavior of the retention handler to skip tenants which have compaction disabled.
**Checklist**

Change retention to honor compaction disablement

---

CHANGELOG.md
cmd/tempo-cli/cmd-rewrite-blocks.go

Here we modify the output long-running command `rewrite-blocks` to use a logger rather than the use of `fmt.Print`.  This should be sufficient for both local and non-local use cases.
Additionally, we continue on error such that in case one block has a problem, we don't halt the entire process.
**Checklist**

[tempo-cli] Replace fmt.Print with logger, continue on error in `rewrite-blocks`

---

.golangci.yml

Address the following deprecation warning.
```
WARN [lintersdb] The linter named "megacheck" is deprecated. It has been split into: gosimple, staticcheck, unused.
```
**Checklist**

Update golangci config for deprecation

---

docs/sources/tempo/traceql/metrics-queries/_index.md
docs/sources/tempo/traceql/metrics-queries/functions.md

Clarifies the `count_over_time` TraceQL metrics function and adds info about `step`. 
Fixes https://github.com/grafana/tempo/issues/5053
**Checklist**

[DOC] Update count_over_time docs

---

CHANGELOG.md
pkg/parquetquery/column.go

Uses a somewhat recently exposed method on parquet.FilePages to prevent decoding of the first page of a column chunk when the dictionary allows us to skip it.
<details>
<summary>benches</summary>
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet4
cpu: Apple M3 Pro
│ before.txt  │             after.txt              │
│   sec/op    │   sec/op     vs base               │
BackendBlockTraceQL/spanAttValMatch-11                79.16m ± 1%   77.39m ± 1%  -2.24% (p=0.000 n=10)
BackendBlockTraceQL/spanAttValNoMatch-11              5.504m ± 1%   5.265m ± 2%  -4.35% (p=0.000 n=10)
BackendBlockTraceQL/spanAttIntrinsicMatch-11          56.43m ± 0%   55.98m ± 1%  -0.80% (p=0.000 n=10)
BackendBlockTraceQL/spanAttIntrinsicNoMatch-11 …
```

Perf: Prevent unnecessary page decoding

---

docs/sources/tempo/traceql/metrics-queries/_index.md
docs/sources/tempo/traceql/metrics-queries/functions.md

Backport a7df1e3c4c5593057384275451a0a6baeb74cf7a from #5052
---
Clarifies the `count_over_time` TraceQL metrics function and adds info about `step`. 
Fixes https://github.com/grafana/tempo/issues/5053
**Checklist**

[release-v2.7] [DOC] Update count_over_time docs

---

CHANGELOG.md
operations/jsonnet-compiled/StatefulSet-memcached.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/config.libsonnet

Here we update the default jsonnet versions for memcached and its exporter.
**Checklist**

[jsonnet] update memcached and exporter version

---

CHANGELOG.md
operations/tempo-mixin-compiled/dashboards/tempo-operational.json
operations/tempo-mixin-compiled/dashboards/tempo-rollout-progress.json
operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/dashboards/rollout-progress.libsonnet
operations/tempo-mixin/dashboards/tempo-operational.json
operations/tempo-mixin/dashboards/tempo-writes.libsonnet

Adds new write path otlp/v1/traces to dashboards.
**Checklist**

Update dashboards for new otlp_v1_traces write path

---

CHANGELOG.md
build/tools.mk
go.mod

This is a continuation to https://github.com/grafana/tempo/pull/5057. 
This second PR updates:
- the actual go version to 1.24.2
- update `TOOLS_IMAGE_TAG` to use the latest tag.
Fixes #5040
**Checklist**

Update go version to 1.24.2

---

tempodb/blocklist/poller.go

Here we modify the poller so that it does not log a "complete" message if the context has been cancelled.  Occasionally we see a log message in a test which is written after a test is complete, which causes the test to fail.  Additionally, we don't signal to the user that the work has been completed when the work has actually been canceled or we exit for other reasons.
An example test failure can be seen [here](https://github.com/grafana/tempo/actions/runs/14781775278/job/41502068459#step:4:1432).
Additionally, [this issue](https://github.com/golang/go/issues/67701) describes the behavior.
**Checklist**

Change poller to not log completion in the event of early return

---

tools/Dockerfile
tools/go.mod

Update Go version in tools image to v1.24.3. This is the first of two PRs. The follow up is #5110 which will be ready once the new tools image is built.
Contributes to fixing CVE-2025-22873
**Checklist**

Update tools image to Go v1.24.3 (part 1)

---

CHANGELOG.md
build/tools.mk
go.mod

Update Go version to 1.24.3. This is a follow up for #5109.
Fixes CVE-2025-22873
**Checklist**

Update to go 1.24.3 (part 2)

---

docs/sources/tempo/configuration/_index.md
docs/sources/tempo/troubleshooting/querying/long-running-traces.md

Adds content from #5051 to the troubleshooting docs and add a note in the ingester config block pointing to the new info about data quality metrics. 
Fixes #5051 
**Checklist**

[DOC] Add metrics warning info to troubleshooting

---

CHANGELOG.md
pkg/ingest/encoding.go

This PR resets the field `SkipMetricsGeneration` introduced in #4728 before reusing the containing `PushBytesRequest` struct. Without this, if there's a tenant for which this flag is set, all other tenants will also have that flag set most of the time.
Since the affected code path is used only in the new architecture, the classic architecture is not affected by this.
**Checklist**

Reset `SkipMetricsGeneration` field before reusing `PushBytesRequest`

---

CHANGELOG.md
modules/frontend/metrics_query_range_sharder.go
modules/frontend/metrics_query_range_sharder_test.go
modules/frontend/search_sharder.go

- Request at least 1 exemplar per shard
- Correct exemplars calculation: with totalRecords > pages, page should be the numerator and total records the denominator
- Correct calculation of required pages per request (fix for case `small block`)
Fixes #4632
**Checklist**

Issue 4632: fix exemplars calculation

---

docs/sources/tempo/setup/operator/_index.md

The supported Kubernetes versions of the operator change regularly, therefore it makes more sense to link to the operator changelog instead of hardcoding the versions in the Tempo docs.
The Tempo operator changelog will contain the supported Kubernetes versions with the next release (v0.16.0, planned for this week).
**Checklist**

[DOC] operator: Remove hardcoded supported Kubernetes versions

---

CHANGELOG.md
modules/backendworker/backendworker.go

Right now we can have a case where the scheduler comes up, all the workers connect to it and wait for jobs and fails due to issues or when the scheduler has no jobs or failed to handout jobs to workers. all the workers will start backing off with retry with the same backoff durations.
This can cause waves of thundering herd on the scheduler if we have a sizeable amount of workers.
This PR add a jitter in workers so they are offset by jitter and won't cause waves of thundering herd on the scheduler.
This is even more important because backend scheduler is a singleton component and can be easily overwhelmed in bigger clusters.
Jitter code in play: https://go.dev/play/p/qb5GU11lKF5
**Checklist**

Add jitter in backendworker to avoid thundering herd from workers

---

CHANGELOG.md
modules/generator/processor/spanmetrics/spanmetrics.go
modules/generator/processor/spanmetrics/spanmetrics_test.go

It is technically possible to send a resource attribute with an empty key over the wire, and these cause issues for span metrics target_info.  It will lead to invalid label errors downstream in metrics datasources. This skips over them.
Note - Target info pulls in all resource attributes dynamically (minus any exclusions). So I think it is ok to skip silently here.  Versus, for the regular span metrics, dimensions are configured explicitly. In that case I think the current behavior of bubbling those errors up is preferred.
**Checklist**

Protect span metrics target_info against resource attributes with empty key

---

CHANGELOG.md
cmd/tempo-vulture/main.go
cmd/tempo-vulture/testdata/trace.json
pkg/util/trace_info.go

Currently all spans emitted by vulture are root spans. With this change, most spans will have a parent, making the traces a bit more realistic. The main motive is to test spans with a parent.
**Checklist**

vulture: add parent to generated spans

---

CHANGELOG.md
modules/distributor/distributor.go
modules/distributor/distributor_test.go

The artificial latency was not being applied on errors. For Tempo clusters with lot of refused spans this means that the artificial latency is not always used
**Checklist**

fix: apply the artificial latency even on pushTrace errors

---

.golangci.yml

It adds
- forbidigo: https://github.com/ashanbrown/forbidigo
- gocritic: https://github.com/go-critic/go-critic
- gosec: https://github.com/securego/gosec

chore: add extra linters to golangci

---

CHANGELOG.md
cmd/tempo-vulture/main.go
cmd/tempo-vulture/main_test.go

1. Refactoring to simplify code and reduce copy-paste
2. For reads, do two checks: for recent traces that are <5 minutes old, and for older traces. This allows to check read path that hits to generators and ingesters.
**How it has been tested**:
1. unit tests
2. run the new version in k8s for 4h+. Results: no errors reported
Additionally, checked via debug logs that checks run correctly
**Checklist**

Vulture: check recent traces

---

.github/workflows/docker.yml
.github/workflows/release.yml

Release CI is failing with "would clobber existing tag" b/c we are pulling the release tag twice. Remove the fetch tags step and push into checkout.

CI: Push fetch tags into checkout

---

CHANGELOG.md
operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin-compiled/dashboards/tempo-backendwork.json
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet
operations/tempo-mixin/dashboards.libsonnet
operations/tempo-mixin/dashboards/tempo-backendwork.json
operations/tempo-mixin/dashboards/tempo-operational.libsonnet
operations/tempo-mixin/runbook.md

Here we include an initial dashboard for "backendwork" to track the state of jobs through the backend scheduler/worker components.  Additionally, include a new alert for a metric which was recently added to notify on "empty job rate".
**Checklist**

Include Backendwork dashboard and include alert on empty job rate

---

CHANGELOG.md
modules/distributor/distributor.go
modules/distributor/distributor_test.go
pkg/util/hash.go
pkg/util/hash_test.go

Distributors rebatch incoming writes by trace ID, in order to ensure that all spans for a given trace end up on the same ingesters over time.  It's using a 32-bit hash which can lead to collisions.  When 2 traces in the incoming write request have the same hash (collide), their spans will get intermixed, i.e. bad data.
The core issue is that the distributor logic was conflating hashing for the ring, and hashing for dedupe.  These don't need to be the same hash, nor should they be.  Because the ring requires 32-bit hashes and collisions there don't matter, it just means 2 traces go the same ingesters (normal and unavoidable).   
But collisions for dedupe must be avoided, and we do this by swapping that part to a 64-bit hash.  Same approach as in trace combiner for …

Fix distributor rebatch bug

---

CHANGELOG.md
integration/e2e/api/query_range_test.go
pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go

1. Fixes a bug with unmarshalling of TraceQL Metrics response in tests.
2. Fixes a bug when for histogram and quantiles exemplars were put in wrong series.
In this loop: https://github.com/ruslan-mikhailov/tempo/blob/17e20a43af0881ef0841d2e33eaeb190c422e549/pkg/traceql/engine_metrics.go#L1477
it iterates over the series set while putting all the exemplars into each resulting series without any filtration: https://github.com/ruslan-mikhailov/tempo/blob/17e20a43af0881ef0841d2e33eaeb190c422e549/pkg/traceql/engine_metrics.go#L1488
For example, if in total, we have the following exemplars:
E1 - span_attr=val_A
E2 - span_attr=val_A
E3 - span_attr=val_B
E4 - span_attr=val_C
For the following query:
```
{span.span_attr!=nil} | quantile_over_time(span:duration, 0.9) by(span.span_attr)
```
we have: …

TraceQL Metrics: right exemplars for histogram and quantiles

---

docs/sources/tempo/configuration/grafana-alloy/span-metrics.md

Corrects Alloy config for span metrics to use a `.` instead of `_`: 
```
namespace = "traces.spanmetrics"
```
**Checklist**

[DOC] Fix traces.spanmetrics in Alloy config doc

---

CHANGELOG.md
pkg/traceql/engine_metrics_compare.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/encoding/vparquet4/block_traceql_test.go

* Exclude parent span id from selectAll
* update test
* Fix to ignore nestedSetParent and other intrinisics from compare(). Fix where a nil attribute could be returned from selectall from scopes without any attributes
* changelog
* lint
* woops lint again
**Checklist**

Backport #5196 to 2.8

---

CHANGELOG.md
pkg/traceql/ast_metrics.go
pkg/traceql/engine_metrics_test.go
pkg/traceql/storage.go
tempodb/encoding/vparquet4/block_traceql_test.go

When using structural operators for metrics queries in combination with a `rate by` aggregator, it is necessary for each of the span set filters to contain the attributes for which we expect to produce a metrics series.
`{name=~"noop"} > {} | rate() by (name)`
In the above query, the first filter matches spans against the `name` attribute the results are then further filtered by the `childOf` operator against the second "empty" filter.  The `rate() by` is performed on the against the second spanset filter, but we have not loaded any columns, and so when we go to generate the series, in some cases we have nil values.
Here we make an adjustment so that each attribute which we want to `rate() by` is included in the second pass when the `AllConditions` is set to false, …

Fix structural metrics rate by aggregation

---

tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet2/block_traceql_test.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet3/block_traceql_test.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/encoding/vparquet4/block_traceql_test.go
tempodb/tempodb_search_test.go

**What this PR does**
This PR enables comparisons between `span:duration` and floating-point values.
Previously, the query engine only supported integer comparisons.
The new helper `createIntPredicateFromFloat` rewrites float predicates into
equivalent integer predicates while preserving semantics. Because some floats
cannot be represented exactly as integers, the function adjusts the operator
accordingly. For example:
- `>= 10.1`   ->  `> 11`
- `< 10.1`    ->  `<= 10`
It seems that `v2` already handles floats internally due to different design. So no changes are required there.
**Which issue(s) this PR fixes**
Fixes #4046
**Checklist**

TraceQL: Allow comparison duration to float

---

.golangci.yml

G115: Potential integer overflow when converting between integer types
This rule introduced a lot of noise as we have a lot of cases where we truncate or change the sign of an integer type. In addition, in many cases protobuf definitions are involved, which require regeneration. But most importantly, `len` always returns `int`, which means we should add a conditional every time we need to convert it, potentially affecting performance.
**Checklist**

linter: disable gosec rule g115

---

CHANGELOG.md

Moved sentences that were inserted after the link to the PR to be before the link.
**Checklist**

[DOC] Correct out-of-place sentences in Changelog for 2.8RC

---

modules/backendscheduler/backendscheduler.go
modules/backendscheduler/provider/compaction.go

Here we save a few memory allocations when retrieving the blocklist for tenants.  This happens at metric time, and also when we re-prioritize the tenant list. 
**Checklist**

[backendscheduler] small memory allocation improvements

---

.github/copilot-instructions.md
README.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/release-notes/v2-8.md
docs/sources/tempo/traceql/_index.md
docs/sources/tempo/traceql/metrics-queries/functions.md

Draft Tempo 2.8 release notes. 
* Update docs for some of the release items
* Fixes some mistakes in previous release notes (missing periods, etc.)
* Adds copilot-instructions under .github to allow automation using CoPilot 
Fixes #5201 
Related: https://github.com/grafana/tempo/pull/5259
**Checklist**

[DOC] Tempo 2.8 release notes 

---

.github/copilot-instructions.md
README.md
docs/sources/tempo/configuration/_index.md
docs/sources/tempo/configuration/grafana-alloy/span-metrics.md
docs/sources/tempo/operations/manage-advanced-systems/multitenancy.md
docs/sources/tempo/release-notes/v2-6.md
docs/sources/tempo/release-notes/v2-8.md
docs/sources/tempo/setup/upgrade.md
docs/sources/tempo/traceql/_index.md
docs/sources/tempo/traceql/metrics-queries/functions.md

Manual backport of doc changes for 2.8 from these PRs: 
* #5258 
* #5205 
* #5095 
* #5260 
**Checklist**

[release-2.8][DOC] Backport doc changes for v2.8 release

---

docs/sources/tempo/release-notes/v2-8.md
docs/sources/tempo/setup/upgrade.md

Adds upgrade docs for Tempo 2.8, fixes a reference to 2.7 in the release notes. 
Manually added these chagnes to #5259 
Fixes #5201 
**Checklist**

[DOC] Add upgrade docs for 2.8

---

CHANGELOG.md
modules/distributor/distributor.go
pkg/dataquality/warnings.go

This will allow us to find customers that send spans in the future,
which can't be found using the Search API.
**Checklist**

distributor: add counter for spans in the future

---

CHANGELOG.md
tempodb/encoding/vparquet4/block_traceql.go

Batch/Instrumentation/Trace collectors were doing a lot of work to iterate/append when they didn't need to.  This has the most impact for metrics queries that process a lot of spans.
<details>
<summary> Benchmarks for Metrics</summary>
```
│ before.txt  │              after.txt              │
│   sec/op    │   sec/op     vs base                │
BackendBlockQueryRange/{}_|_rate()/5-14                                                                     83.41m ± 0%   73.54m ± 5%  -11.83% (p=0.000 n=10)
BackendBlockQueryRange/{}_|_rate()_by_(span.http.status_code)/5-14                                          193.4m ± 1%   173.6m ± 1%  -10.23% (p=0.000 n=10)
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-14 …
```

[TraceQL] Performance increase for simple queries

---

docs/sources/tempo/shared/tempo-in-grafana.md
docs/sources/tempo/traceql/_index.md

Clarifies non-deterministic and deterministic search with most_recent="true" in the doc. 
**Checklist**

[DOC] Add non-deterministic content back to doc

---

CHANGELOG.md
example/docker-compose/multi-tenant/tempo.yaml

The port was exposed but the Tempo config didn't allow HTTP writes.
**Checklist**

example: enable http writes in the multi-tenant example

---

CHANGELOG.md
modules/frontend/slos.go
modules/frontend/slos_test.go

This counter show the total bytes read from disk and object storage.
**Checklist**

Expose inspected bytes metric to Prometheus

---

modules/backendscheduler/backendscheduler.go
modules/backendscheduler/cache.go
modules/backendscheduler/provider/compaction.go
modules/backendscheduler/work/work.go
modules/backendscheduler/work/work_test.go

In order to get a better understanding of where the time is spent, here we add a few spans and a tracer on the work package.  Additionally, the main loop is no longer blocked measuring tenants to avoid an area where we do block handing out jobs, but the duration is unknown and unmeasured, which we try to rectify here.
**Checklist**

Improve backend-scheduler observability

---

modules/backendscheduler/provider/compaction.go
modules/backendscheduler/provider/compaction_test.go

Here we make a few small improvements to the compaction provider.
* skip tenants which have too low a priority to create a compaction job
* relocate a backoff to make testing easier and simplify
* allow jobs of any status which have input blocks to reduce what is visible to the block selector
**Checklist**

Compaction provider improvements

---

modules/backendscheduler/backendscheduler.go

Fix a nil pointer in the scheduler, which was added as part of https://github.com/grafana/tempo/pull/5321 to include some instrumentation.  We only want to check the ID of the job if the job is not nil.  This only shows up on shutdown of the scheduler.
**Checklist**

[backend-scheduler] fix nil pointer on shutdown

---

CHANGELOG.md
docs/sources/tempo/configuration/usage-tracker.md
example/docker-compose/local/docker-compose.yaml
example/docker-compose/local/tempo.yaml
example/docker-compose/shared/tempo.yaml

There was a bug in the documentation. 
The YAML should look like:
```yaml
myMap:
key1: value1
key2: value2
````
Previously it was:
```yaml
myMap:
- key1: value1
- key2: value2
```
This is a list of maps: []map[string]string, not a map[string]string.
I have also enabled cost attribution for the docker-compose local example
**Checklist**

fix: usage tracker docs

---

CHANGELOG.md
cmd/tempo/app/app.go
cmd/tempo/app/app_test.go
pkg/util/freeport.go

Adds a `Stop` method to `app.App`.
see https://github.com/grafana/tempo/discussions/5225
tl;dr it's helpful when embedding Tempo inside a Go application to be able to control it's full lifecycle, not just the start.
**Checklist**

Stop method

---

CHANGELOG.md
docs/sources/tempo/configuration/manifest.md
modules/backendscheduler/provider/compaction.go

With the new scheduled compactions, we're observing that jobs handed out in sequence of difficulty often mean that the jobs are too easy for workers to complete, which results in lower throughput because the scheduler has to spend more time scheduling and handling the jobs.  Eventually the jobs handed out are more difficult, but it can take some time before this happens, which results in a valley of low throughput.  This may happen at the beginning of working on a new tenant, for example, and in a large environment with many tenants, the performance is sub-optimal.  I believe this warrants an allowable configuration on the compaction provider, proposed here.
Historically, the min/max input blocks have been hard-coded to match the parquet version performance.  It …

Allow configuration of min/max input blocks for compaction provider

---

CHANGELOG.md
modules/overrides/runtime_config_overrides.go
modules/overrides/runtime_config_overrides_test.go
modules/overrides/user_configurable_overrides.go
modules/overrides/user_configurable_overrides_test.go

Adds the missing YAML document separator `---\n` to the `/status/runtime_config` endpoint output. This fixes invalid YAML that was causing validation failures with tools like `yq`.
Fixes #5146
**Checklist**
be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`:
Notes:
- Tests updated: Existing tests pass and
verify the YAML output now includes the separator
- Documentation added: Not needed - this is a bug fix that
doesn't change user-facing functionality
- CHANGELOG.md: You should add an entry under [BUGFIX]
section if there is one, something like:
* [BUGFIX] Fix invalid YAML output from
/status/runtime_config endpoint by adding document
separator. #5146

feat(overrides): Add separator line in `WriteStatusRuntimeConfig` method

---

CHANGELOG.md
pkg/parquetquery/predicates.gen.go
pkg/parquetquerygen/predicates.go
tempodb/encoding/vparquet2/block_traceql.go
tempodb/encoding/vparquet3/block_traceql.go
tempodb/encoding/vparquet4/block_traceql.go
tempodb/tempodb_search_test.go

Trace IDs are stored with leading zeros, no need to trim
1. Fixes search by short trace id in query: `{trace_id!="abc"}`. 
2. Fixes regression bug for search by `link:spanID`. The bug was hidden because with `bytes.TrimLeft(id, "\x00")` results after `HexStringToTraceID` and `HexStringToSpanID` were the same
Fixes https://github.com/grafana/tempo/issues/4437 and https://github.com/grafana/tempo/issues/4967
**Checklist**

[Bugfix] Fix search by trace:id with short trace ID

---

CHANGELOG.md
docs/sources/tempo/metrics-generator/service_graphs/_index.md
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/servicegraphs/servicegraphs_test.go
modules/generator/processor/servicegraphs/testdata/trace-with-virtual-nodes.json

This PR gives client service virtual nodes a more descriptive name when a peer attribute is present in the received span.
Related to #5268
**Checklist**

Service graph: Use peer attribute for client service virtual nodes

---

CHANGELOG.md
docs/sources/tempo/configuration/manifest.md
modules/backendscheduler/provider/compaction.go
modules/backendscheduler/provider/compaction_test.go
modules/backendscheduler/provider/config.go
modules/backendscheduler/provider/metrics.go

Here we use a minimum cycle time to ensure we move fast when we can, but not too fast when we don't need to.
New blocks arrive at the end of a poll cycle, and we shouldn't expect to find new work on a tenant which has been drained until then.
**BREAKING CHANGE**
The config setting `provider.compaction.backoff` has been removed in favor of this simplified approach.
Additionally the `compaction_tenant_backoff_total` metric has been renamed to `compaction_empty_tenant_cycle_total` for clarity.
**Checklist**

[backend-scheduler] require minimum time between tenant sorting

---

CHANGELOG.md
cmd/tempo/app/config.go
cmd/tempo/app/config_test.go
integration/backendscheduler/backendscheduler_test.go
integration/backendscheduler/config.yaml
modules/backendscheduler/backendscheduler.go
modules/backendscheduler/config.go
modules/backendscheduler/provider/compaction.go
modules/backendscheduler/provider/compaction_test.go

This is an alternative approach to the same issue described in #5405.
Here we fix the race by keeping track of the recent jobs which were created and their blocks.  This cache is used to skip blocks on the block selector from being considered.  Once the next blockselector is called, we use the job list to identify what cache needs to be pruned.  This allows a small delay between when the compaction provider created the job and when the scheduler assigns the job, but without the additional overhead of looping through the work list as proposed in #5405.
Fixes #5405
**Checklist**

[backend-scheduler] fix race condition between scheduler and compaction provider

---

CHANGELOG.md
docs/sources/tempo/configuration/manifest.md
modules/blockbuilder/blockbuilder.go
modules/blockbuilder/blockbuilder_test.go
modules/generator/generator.go
modules/generator/generator_kafka.go
pkg/ingest/config.go
pkg/ingest/metrics.go
pkg/ingest/partition_offset_client.go
pkg/ingest/partition_offset_client_test.go
pkg/ingest/testkafka/cluster.go

The goal of this PR is to replace the 
kadm.ListStartOffsets and kadm.ListEndOffsets by a built-in compatible methods that accept a list of partitions. This is important to reduce the number of ListOffsets requests. Tests show a 50% reduction in requests
**Checklist**

feature: implement a listOffset by partition client

---

CHANGELOG.md
modules/distributor/distributor.go
modules/distributor/receiver/shim.go

It includes the tenant id when logging an error writing to Kafka. It also set the `distributor.ConsumeTraces` span status to `error` on error. This would make it easier to spot problems consuming traces
**Checklist**

feat: improve logging and tracing in the write path to include tenant info

---

modules/backendscheduler/backendscheduler.go
modules/backendscheduler/work/work.go

Sorting the job list is only useful in the status handler.  Here we move the sorting to the status handler and reverse the order so that more recent jobs are on top to improve the UX.
**Checklist**

[backend-scheduler] move job sorting

---

integration/e2e/api/query_range_test.go
modules/frontend/metrics_query_range_handler.go

**What this PR does**: Align request in grpc query range call only when default step is applied.
The bug was introduced in https://github.com/grafana/tempo/pull/5366 in commit https://github.com/grafana/tempo/pull/5366/commits/c26423c7a824d45affd96b583f2b3b9c2f8de4cf
**How it has been tested:**
1. http in e2e tests
2. Because we don't have e2e tests for it, grpc was checked manually, by calling MetricsQueryRange grpc method with step=0.
Before the fix (main branch):
```
StatusCode.UNKNOWN, start required
```
After the fix: returned 301 intervals, no errors
**Checklist**

[Bugfix] Default step for grpc

---

cmd/tempo/app/app_test.go
integration/e2e/metrics_generator_test.go

Security is working on rolling out semgrep across our codebase. Because of some parser deficiencies in semgrep (the user-configurable rule engine runs after AST parsing, which discards comments), we can't just force it to respect #nosec, so this PR converts lines with valid gosec suppression directives into lines that also contain a valid equivalent semgrep suppression. I know it's ugly, sorry.
**Checklist**
- [NA] Tests updated
- [NA] Documentation added
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

chore: Autofixing so that semgrep can also understand our #nosec lines

---

CHANGELOG.md
modules/frontend/metrics_query_handler.go
modules/frontend/metrics_query_range_handler.go
modules/frontend/search_handlers.go
modules/frontend/tag_handlers.go
modules/frontend/traceid_handlers.go
modules/frontend/util.go
modules/frontend/util_test.go

There was some inconsistencies and duplication.
Now the tenant extraction must succeed for all endpoints, or else fail.
**Checklist**

frontend: unify tenant ID extraction across handlers

---

docs/sources/tempo/release-notes/v2-8.md

Updates the 2.8 release notes for changes in 2.8.2. 
Related to https://github.com/grafana/tempo/pull/5484
**Checklist**

[DOC] Release notes update for 2.8.2

---

CHANGELOG.md
cmd/tempo/app/server_service.go

Removes the .005 bucket and adds a 1.5 bucket to increase granularity of all histograms around 1s.
**Checklist**

Adjust histogram buckets to have more granularity around 1s

---

CHANGELOG.md
operations/tempo-mixin-compiled/dashboards/tempo-writes.json
operations/tempo-mixin/dashboards/tempo-writes.libsonnet

This PR improves the tempo write dashboard:
1. It uses the proper envoy metric
2. It adds more envoy panels
3. Distributor now aggregates the discarded spans by reason
5. Kafka records/s and Kafka failed appends now use: `tempo_distributor_kafka_write_bytes_total` and `tempo_distributor_produce_failures_total` metrics
**Checklist**

feat: improve tempo writes dashboard

---

operations/tempo-mixin-compiled/alerts.yaml
operations/tempo-mixin/alerts.libsonnet
operations/tempo-mixin/config.libsonnet

**What this PR does**: vulture error rate alert proved to be very useful for early problem detection. Elevating alert criticality to `critical` and making it more sensetive.
**Checklist**

Adjust tempo vulture alert

---

pkg/traceql/engine_metrics.go
pkg/traceql/engine_metrics_test.go

Fixes an edge case bug: if span matches block's
start time (e.g. spans in a block with a single trace), it could not be queried if span's timestamp is rounded to seconds.
**What this PR does**: cherry-picks #5507 to `r213`.
**Checklist**

[Bugfix] TraceQL Metrics fix for edge case

---

CHANGELOG.md
pkg/util/slices.go
tempodb/encoding/vparquet4/block_traceql.go

**What this PR does**: 
This PR fixes origin issue that was unnoticed until it introduced a panic. Explanation why it panics can be found here: https://github.com/grafana/tempo/pull/5514
**The bug explanation.**
https://go.dev/play/p/P78nVSN44BP
The reason the value's changed in both slices is because they both point to the same array.
If we have two slices that point to one array:
then we append to the first slice:
The same happens here.
1. We init struct with buffer [here](https://github.com/ruslan-mikhailov/tempo/blob/c73964fc471cdc2d10edb2f268e9bf90e9fce337/tempodb/encoding/vparquet4/block_traceql.go#L3337)
1. We reset buffer and append [here](https://github.com/ruslan-mikhailov/tempo/blob/c73964fc471cdc2d10edb2f268e9bf90e9fce337/tempodb/encoding/vparquet4/block_traceql.go#L3298-L3323) …

[bugfix] TraceQL Metrics: panic in compare

---

modules/backendscheduler/provider/compaction.go
modules/backendscheduler/provider/compaction_test.go
modules/frontend/search_sharder_test.go
tempodb/tempodb.go
tempodb/tempodb_test.go

This change addresses two issues.
First, on startup, the scheduler hands out jobs on a potentially out of date blocklist, which means the scheduler possibly hands out jobs for blocks which don't exist.
Second, when we cycle for the min period, we only sleep the period, which is only useful if we expect new blocks to show up on this interval.  In reality, it will cycle here several times until the blocklist is polled.
In both cases, I think we want to know the moment a blocklist is updated, so that we can a) start the compaction provider and hand out accurate jobs and b) sleep until new work shows up once we've drained all tenants.
An implicit assumption here is that the poller on the worker is on the same interval as the poller on the scheduler.
**Which issue(s) …

Implement poller hook on compaction provider for accurate delay

---

modules/overrides/userconfigurable/api/api_test.go

Add one more test to make assert that PATCH behaviour
**Checklist**

Add one more test case in the cost attribution tests

---

cmd/tempo/app/modules.go
docs/sources/tempo/configuration/manifest.md
example/docker-compose/ingest-storage/docker-compose.yaml
modules/livestore/config_test.go
modules/livestore/instance_search_test.go
pkg/ring/config.go

- correctly set all partition ring fields to the live store when configured
- expose instance zone in the config and set it correctly for livestores. this makes the query path behave as expected

Livestore: Partition ring fixes

---

CHANGELOG.md
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
tempodb/tempodb_search_test.go

**What this PR does**: fixes queries like `{ span:name = "not-exist" } !< { span:name = "exist" }` and `{ span:name = "not-exist" } !> { span:name = "exist" }`. The bug was in early exit if the first part of the query has no spans.
Fixes #4804
**Checklist**

[Bugfix] Fix for not-parent operation

---

modules/blockbuilder/blockbuilder_test.go
modules/livestore/instance.go
modules/livestore/live_store.go
modules/livestore/live_store_test.go
modules/livestore/partition_reader.go
pkg/livetraces/livetraces.go

Primarily this PR correctly persists the span start/end timestamps to the block start/end meta while using ingestion slack and record.timestamp. The blockbuilder already correctly did this.
Other changes:
- Adds a test to confirm that record.Timestamp, ingestion slack and span start/end are correctly used to generate block metas in the livestore
- Adds the same test in blockbuilder (no changes to blockbuilder logic. just locking down this behavior)
- Changed the consume loop to take a kgo.RecordIter to remove unnecessary allocs/transformations. [this was a change request on the original PR](https://github.com/grafana/tempo/pull/5563#discussion_r2298876135)
- Preferred dropping records to perfectly persisting data in the face of errors. Added drop reasons to metric failed records. I'm …

Livestore: Consume improvements

---

example/docker-compose/ingest-storage/tempo.yaml
modules/livestore/instance.go
modules/livestore/instance_search.go
modules/livestore/instance_search_test.go
modules/livestore/live_store.go
modules/livestore/query_range.go

This PR consolidates query logic in the livestore to remove redundant code and standardize the way we iterate through blocks in an instance. It is a combination of behaviors from the ingester and metrics generator read paths.
- Created an [iterateBlocks](https://github.com/grafana/tempo/pull/5583/files#diff-708a69e1ac83ae4c6c95163e2ef2a54174a348aa2c350864e928d65419d83f58R48) function and used it through all 5 search paths (search tags, tag values, search/traceql, query range and trace id lookup). This function standardizes
- use of the concurrency setting
- error handling
- exit early behavior and context cancelling
- logging/tracing
- testing block range for inclusion in the query
- Cleaned up [some places](https://github.com/grafana/tempo/pull/5583/files#diff-708a69e1ac83ae4c6c95163e2ef2 …

Livestore: Consolidate query logic

---

pkg/ingest/encoding.go
pkg/ingest/encoding_test.go

We were resetting the length or the underlying slices but not clearing the contents.
This makes a potential future data leak due to a bug less likely.
Also add a test to ensure the data is reset when reusing it.
Benchmark in this branch:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/pkg/ingest
cpu: Apple M3 Pro
BenchmarkEncoderPoolPutDifferentSizes/Small_Original-11         	80590712	        15.56 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoderPoolPutDifferentSizes/Small_WithClear-11        	48544262	        25.38 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoderPoolPutDifferentSizes/Medium_Original-11        	19074123	        62.93 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncoderPoolPutDifferentSizes/Medium_WithClear-11       	10028392	       117.1 …
```

ingest:  make Enconding sync.Pool more robust

---

CHANGELOG.md
modules/generator/storage/instance.go
modules/generator/storage/instance_test.go

**What this PR does:**
Prevents metrics-generator from deleting the entire WAL root directory when an empty tenant is encountered. This issue could cause data loss for all tenants
**Root Cause:**
• Empty tenant ("") causes filepath.Join(cfg.Path, tenant) to resolve to the WAL root directory
• os.RemoveAll(walDir) then deletes the entire root, affecting all tenant WAL data
• This occurs when X-Scope-OrgID header is missing or internal metrics lack tenant labels
**Solution:**
• Throw Error when tenant is  empty when  multi tenancy environment enabled
**Testing:**
• Added TestInstance_emptyTenantValidation with 2 test cases
• All existing tests pass
• Verified WAL directory structure remains intact for existing tenants
Which issue(s) this PR fixes:
Fixes potential WAL data loss in …

fix(metrics-generator): prevent WAL deletion when tenant is empty

---

CHANGELOG.md
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/common.libsonnet

Changes the ownership of the folder used by the live-store's volumes. Missed in https://github.com/grafana/tempo/pull/5591
**Checklist**

[jsonnet] chown livestore's volumes

---

modules/backendworker/backendworker.go
tempodb/retention.go

Here we improve the logging, error handling, and shutdown context in the retention job.  This should give more information when a worker is shutting down and avoid attempting to retain a tenant if we've been asked to halt.
**Checklist**

[backend-worker] adjust the retention error and context handling, improve logging

---

CHANGELOG.md
docs/sources/tempo/metrics-from-traces/service_graphs/_index.md
modules/generator/processor/servicegraphs/servicegraphs.go
modules/generator/processor/servicegraphs/servicegraphs_test.go
modules/generator/processor/servicegraphs/testdata/trace-with-both-db-attributes.json
modules/generator/processor/servicegraphs/testdata/trace-with-db-namespace.json

The latest DB semantic conventions have renamed the `db.name` attribute to `db.namespace`.
This updates the service graph to support the new attribute.
**Checklist**

service-graph: Support the new `db.namespace` attribute

---

modules/livestore/live_store.go
modules/livestore/live_store_background.go

Adds jitter to enqueuing blocks for completition in the live stores. This eases the memory pressure at startup and makes live-stores more stable in high-load scenarios.
**Checklist**

Add jitter to queuing blocks in the live-store

---

CHANGELOG.md
pkg/traceql/ast_execute.go
pkg/traceql/ast_execute_test.go
pkg/traceql/ast_validate.go
tempodb/tempodb_search_test.go

Fixes a bug in the traceql engine comparing strings starting with numbers.  `"5" > ""` should be true, but the engine bug was making this false.  Internally it was quoting both hand sides first, so it became ```"`5`" > "``"```, the backtick is before numbers in the ascii table.  The fix is not quote both hand sides, which is both more correct and more performant. 
**Checklist**

[TraceQL] Fix string comparison bug of strings starting with numbers

---

operations/jsonnet-compiled/StatefulSet-live-store-zone-a.yaml
operations/jsonnet-compiled/StatefulSet-live-store-zone-b.yaml
operations/jsonnet-compiled/util/jsonnetfile.lock.json
operations/jsonnet/microservices/live-store.libsonnet

**What this PR does**: changes service name for each live-store from `live-store` to `live-store-zone-N`, where N is its zone.
This change will require recreating live-store statefulset
**Checklist**

Live-store: correct service name

---

docs/sources/tempo/configuration/manifest.md
modules/generator/overrides_test.go
modules/generator/registry/native_histogram.go
modules/generator/registry/native_histogram_test.go
modules/generator/registry/overrides.go
modules/generator/registry/registry.go
modules/generator/registry/registry_test.go
modules/generator/registry/test.go
modules/overrides/config.go
modules/overrides/config_legacy.go
modules/overrides/config_test.go
modules/overrides/interface.go
modules/overrides/runtime_config_overrides.go
modules/overrides/runtime_config_overrides_test.go

Here we add three new override configurations which allow the tuning of the buckets in the native histograms implementaion in the metrics-generator.  This allows tenants of vartying needs to keep their histograms more relevant to their use cases.
The three new configurations are:
- `native_histogram_bucket_factor` - the minimum required distance between buckets
- `native_histogram_max_bucket_number` - the maximum number of buckets to create
- `native_histogram_min_reset_duration` - the minimum duration before a histogram is reset
The value of these configurations are passed directly to the prometheus client library when creating a new histogram.  More detail on these parameters can be found in the [client documentation](https://github.com/prometheus/client_golang/blo …

Allow per-tenant configuration of native histograms

---

docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md

Add metamonitoring information.

Update helm steps for metamonitoring

---

tools/Dockerfile
tools/go.mod

go1.25.1 (released 2025-09-03) includes security fixes to the net/http package, as well as bug fixes to the go command, and the net, os, os/exec, and testing/synctest packages.
- https://go.dev/doc/devel/release#go1.25.minor
- https://github.com/golang/go/issues?q=milestone%3AGo1.25.1+label%3ACherryPickApproved
**Checklist**

chore: upgrade tempo tools to go 1.25.1

---

CHANGELOG.md
build/tools.mk
go.mod

go1.25.1 (released 2025-09-03) includes security fixes to the net/http package, as well as bug fixes to the go command, and the net, os, os/exec, and testing/synctest packages.
- https://go.dev/doc/devel/release#go1.25.minor
- https://github.com/golang/go/issues?q=milestone%3AGo1.25.1+label%3ACherryPickApproved
**Checklist**

chore: upgrade go version to 1.25.1

---

docs/sources/tempo/configuration/manifest.md
modules/livestore/config.go
modules/livestore/instance.go

Pass buffers to be reused and lower the default size and concurrency. This was found to create more stability. Long term need to see why it diverges from ingest.

Reuse buffers

---

docs/sources/tempo/shared/tempo-in-grafana.md

Removes the public preview statement for Traces Drilldown. 
**Checklist**

[DOC] Remove public-preview for Drilldown

---

docs/sources/tempo/api_docs/_index.md
docs/sources/tempo/metrics-from-traces/metrics-queries/configure-traceql-metrics.md
docs/sources/tempo/metrics-from-traces/metrics-queries/functions.md
docs/sources/tempo/metrics-from-traces/metrics-queries/sampling-guide.md

Creates documentation for TraceQL metrics sampling (#5469) using AI to evaluate the original PR and make documentation recommendations. 
FYI - @mdisibio 
Fixes https://github.com/grafana/tempo-squad/issues/838
Related: https://github.com/grafana/tempo/pull/5469
**Checklist**

[DOC] Create TraceQL metrics sampling docs

---

pkg/util/test/logger.go

Fix race conditions when calling the test log after the test has finished by adding a "done" flag in the test logger.
This can happen in tests with services that are not shut down correctly.
I've seen it in different test in the past months, and recently again in a blockbuilder tests such as: https://github.com/grafana/tempo/actions/runs/18311278340/job/52140208404?pr=5710#step:4:12769
**Checklist**

test: fix test race condition in test logger
